--STAGE_CONDITION_OCCURRENCE_HSP_DISCH_SNO
{#-- {{ config(materialized = 'view', schema = 'OMOP_STAGE') }}#}

SELECT DISTINCT
	PULL_CONDITION_OCCURRENCE_HOSP_DISCH_SNO.PERSON_ID
    ,T_CONDITION_CONCEPT.CONCEPT_ID										AS CONDITION_CONCEPT_ID
	,PULL_CONDITION_OCCURRENCE_HOSP_DISCH_SNO.CONDITION_START_DATE 		AS CONDITION_START_DATE
	,PULL_CONDITION_OCCURRENCE_HOSP_DISCH_SNO.CONDITION_START_DATETIME  AS CONDITION_START_DATETIME
	,PULL_CONDITION_OCCURRENCE_HOSP_DISCH_SNO.CONDITION_END_DATE 		    AS CONDITION_END_DATE
	,PULL_CONDITION_OCCURRENCE_HOSP_DISCH_SNO.CONDITION_END_DATETIME 	    AS CONDITION_END_DATETIME
	,32817 																AS CONDITION_TYPE_CONCEPT_ID
	,STOP_REASON														AS STOP_REASON
	,PROVIDER.PROVIDER_ID 												AS PROVIDER_ID
	,VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID 								AS VISIT_OCCURRENCE_ID
--    ,VISIT_DETAIL.VISIT_DETAIL_ID AS VISIT_DETAIL_ID
    ,NULL 																	AS VISIT_DETAIL_ID
    ,LEFT(COALESCE(PULL_CURRENT_ICD10_LIST,PULL_CURRENT_ICD9_LIST)||': '
        ||T_SNO_SOURCE.CONCEPT_NAME, 50)                                AS CONDITION_SOURCE_VALUE
    ,T_CONDITION_CONCEPT.CONCEPT_ID                                     AS CONDITION_SOURCE_CONCEPT_ID
	,CONDITION_STATUS_SOURCE_VALUE 										AS CONDITION_STATUS_SOURCE_VALUE
    ,CASE WHEN CONDITION_STATUS_SOURCE_VALUE = 'PRIMARY_DISCHARGE_DX'
            THEN '32903'
        WHEN CONDITION_STATUS_SOURCE_VALUE = 'SECONDARY_DISCHARGE_DX'
            THEN '32909'
        ELSE '32896'
    END															        AS CONDITION_STATUS_CONCEPT_ID
	-------- Non-OMOP Fields ------------
	, 'STAGE_CONDITION_OCCURRENCE_HSP_DISCH_SNO' 							AS ETL_MODULE
	, VISIT_OCCURRENCE.phi_PAT_ID                      					AS STAGE_PAT_ID
    , VISIT_OCCURRENCE.phi_MRN_CPI                           			AS STAGE_MRN_CPI
	, VISIT_OCCURRENCE.phi_CSN_ID										AS STAGE_CSN_ID
    , PULL_DX_ID                                                        AS STAGE_DX_ID

FROM {{ref('PULL_CONDITION_OCCURRENCE_HOSP_DISCH_SNO')}} AS PULL_CONDITION_OCCURRENCE_HOSP_DISCH_SNO

	INNER JOIN {{ref('VISIT_OCCURRENCE_RAW')}} AS VISIT_OCCURRENCE
		ON PULL_CONDITION_OCCURRENCE_HOSP_DISCH_SNO.PULL_CSN_ID = VISIT_OCCURRENCE.phi_CSN_ID

	LEFT OUTER JOIN {{ref('PROVIDER_RAW')}} AS PROVIDER
		ON PULL_CONDITION_OCCURRENCE_HOSP_DISCH_SNO.PROVIDER_SOURCE_VALUE = PROVIDER.PROVIDER_SOURCE_VALUE

--------CONCEPT MAPPING--------------------

	LEFT JOIN {{ref('T_SNO_SOURCE')}} AS T_SNO_SOURCE
			ON PULL_CONDITION_OCCURRENCE_HOSP_DISCH_SNO.PULL_SNOMED_CODE = T_SNO_SOURCE.CONCEPT_CODE

	LEFT JOIN {{ref('T_CONDITION_CONCEPT')}} AS T_CONDITION_CONCEPT
		ON T_CONDITION_CONCEPT.SOURCE_CONCEPT_ID = T_SNO_SOURCE.CONCEPT_ID

-------------------------------------------
WHERE  T_CONDITION_CONCEPT.CONCEPT_ID IS NOT NULL

