/*********************************************************
Script Name: QA_VISIT_DETAIL_DUPLICATES_DETAIL
Author: Roger J Carlson - Corewell Health
Date: June 2025
*********************************************************/

WITH TMP_DUPES_DETAIL AS (
    SELECT PERSON_ID
        ,VISIT_DETAIL_CONCEPT_ID
        ,VISIT_DETAIL_START_DATE
        ,VISIT_DETAIL_START_DATETIME
        ,VISIT_DETAIL_END_DATE
        ,VISIT_DETAIL_END_DATETIME
        ,VISIT_DETAIL_TYPE_CONCEPT_ID
        ,PROVIDER_ID
        ,CARE_SITE_ID
        ,VISIT_DETAIL_SOURCE_VALUE
        ,VISIT_DETAIL_SOURCE_CONCEPT_ID
        ,ADMITTED_FROM_CONCEPT_ID
        ,ADMITTED_FROM_SOURCE_VALUE
        ,DISCHARGED_TO_CONCEPT_ID
        ,DISCHARGED_TO_SOURCE_VALUE
        ,PRECEDING_VISIT_DETAIL_ID
        ,VISIT_OCCURRENCE_ID
        ,COUNT(*) AS COUNT
    FROM CARE_RES_OMOP_DEV2_WKSP.OMOP.VISIT_DETAIL_RAW AS T1
    GROUP BY PERSON_ID
        ,VISIT_DETAIL_CONCEPT_ID
        ,VISIT_DETAIL_START_DATE
        ,VISIT_DETAIL_START_DATETIME
        ,VISIT_DETAIL_END_DATE
        ,VISIT_DETAIL_END_DATETIME
        ,VISIT_DETAIL_TYPE_CONCEPT_ID
        ,PROVIDER_ID
        ,CARE_SITE_ID
        ,VISIT_DETAIL_SOURCE_VALUE
        ,VISIT_DETAIL_SOURCE_CONCEPT_ID
        ,ADMITTED_FROM_CONCEPT_ID
        ,ADMITTED_FROM_SOURCE_VALUE
        ,DISCHARGED_TO_CONCEPT_ID
        ,DISCHARGED_TO_SOURCE_VALUE
        ,PRECEDING_VISIT_DETAIL_ID
        ,VISIT_OCCURRENCE_ID
    HAVING COUNT(*) > 1
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
    ,'VISIT_DETAIL' AS STANDARD_DATA_TABLE
    ,'DUPLICATE' AS QA_METRIC
    ,'RECORDS'  AS METRIC_FIELD
    ,'FATAL' AS ERROR_TYPE
    ,VI.VISIT_DETAIL_ID
FROM TMP_DUPES_DETAIL AS D
INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP.VISIT_DETAIL_RAW AS VI 
    ON D.PERSON_ID = VI.PERSON_ID
    AND D.VISIT_DETAIL_CONCEPT_ID = VI.VISIT_DETAIL_CONCEPT_ID
    AND D.VISIT_DETAIL_START_DATE = VI.VISIT_DETAIL_START_DATE
    AND D.VISIT_DETAIL_START_DATETIME = VI.VISIT_DETAIL_START_DATETIME
    AND D.VISIT_DETAIL_END_DATE = VI.VISIT_DETAIL_END_DATE
    AND COALESCE(D.VISIT_DETAIL_END_DATETIME,'1900-01-01') = COALESCE(VI.VISIT_DETAIL_END_DATETIME,'1900-01-01')
    AND COALESCE(D.VISIT_DETAIL_TYPE_CONCEPT_ID, 0) = COALESCE(VI.VISIT_DETAIL_TYPE_CONCEPT_ID, 0)
    AND COALESCE(D.PROVIDER_ID, 0) = COALESCE(VI.PROVIDER_ID, 0)
    AND COALESCE(D.CARE_SITE_ID, 0) = COALESCE(VI.CARE_SITE_ID, 0)
    AND COALESCE(D.VISIT_DETAIL_SOURCE_VALUE, '0') = COALESCE(VI.VISIT_DETAIL_SOURCE_VALUE, '0')
    AND COALESCE(D.VISIT_DETAIL_SOURCE_CONCEPT_ID, 0) = COALESCE(VI.VISIT_DETAIL_SOURCE_CONCEPT_ID, 0)
    AND COALESCE(D.ADMITTED_FROM_CONCEPT_ID, 0) = COALESCE(VI.ADMITTED_FROM_CONCEPT_ID, 0)
    AND COALESCE(D.ADMITTED_FROM_SOURCE_VALUE, '0') = COALESCE(VI.ADMITTED_FROM_SOURCE_VALUE, '0')
    AND COALESCE(D.DISCHARGED_TO_CONCEPT_ID, 0) = COALESCE(VI.DISCHARGED_TO_CONCEPT_ID, 0)
    AND COALESCE(D.DISCHARGED_TO_SOURCE_VALUE, '0') = COALESCE(VI.DISCHARGED_TO_SOURCE_VALUE, '0')
    AND COALESCE(D.PRECEDING_VISIT_DETAIL_ID, 0) = COALESCE(VI.PRECEDING_VISIT_DETAIL_ID, 0)
    AND COALESCE(D.VISIT_OCCURRENCE_ID, 0) = COALESCE(VI.VISIT_OCCURRENCE_ID, 0);

/*********************************************************
COLUMN DESCRIPTIONS:
-----------------
RUN_DATE: Date when the query was executed
STANDARD_DATA_TABLE: Name of the table being analyzed
QA_METRIC: Type of quality check being performed
METRIC_FIELD: Field being evaluated
ERROR_TYPE: Severity of the error
VISIT_DETAIL_ID: Unique identifier for the visit detail

LOGIC:
------
1. Creates a temporary table of duplicate records based on all fields
2. Joins back to original table to get VISIT_DETAIL_IDs
3. Uses COALESCE to handle NULL values in comparison
4. Returns all duplicate records for further investigation

LEGAL DISCLAIMER:
---------------
This code is provided "AS IS" without warranty of any kind.
The entire risk as to the quality and performance of the code is with you.
Use at your own risk.
*********************************************************/