
{#-- {{ config(materialized = 'view', schema = 'OMOP_STAGE') }}#}
----------------------------
--STAGE_VISIT_DETAIL_ALL
----------------------------
SELECT DISTINCT
    VISIT_DETAIL_ID
    , PULL_VISIT_DETAIL_HOSP_ALL.PERSON_ID                                              AS PERSON_ID
    , COALESCE(SOURCE_TO_CONCEPT_MAP_VISIT.TARGET_CONCEPT_ID, 0)                        AS VISIT_DETAIL_CONCEPT_ID
    , PULL_VISIT_DETAIL_HOSP_ALL.VISIT_DETAIL_START_DATE                                AS VISIT_DETAIL_START_DATE
    , PULL_VISIT_DETAIL_HOSP_ALL.VISIT_DETAIL_START_DATETIME                            AS VISIT_DETAIL_START_DATETIME
    , PULL_VISIT_DETAIL_HOSP_ALL.VISIT_DETAIL_END_DATE                                  AS VISIT_DETAIL_END_DATE
    , PULL_VISIT_DETAIL_HOSP_ALL.VISIT_DETAIL_END_DATETIME                              AS VISIT_DETAIL_END_DATETIME
    , 44818518                                                                          AS VISIT_DETAIL_TYPE_CONCEPT_ID
    , PROVIDER.PROVIDER_ID                                                              AS PROVIDER_ID
    , CARE_SITE.CARE_SITE_ID                                                            AS CARE_SITE_ID
    , PULL_VISIT_DETAIL_HOSP_ALL.VISIT_DETAIL_SOURCE_VALUE                              AS VISIT_DETAIL_SOURCE_VALUE
    , NULL                                                                                 AS VISIT_DETAIL_SOURCE_CONCEPT_ID
    , PULL_VISIT_DETAIL_HOSP_ALL.ADMITTED_FROM_SOURCE_VALUE                             AS ADMITTED_FROM_SOURCE_VALUE
    , COALESCE(SOURCE_TO_CONCEPT_MAP_ADMIT.TARGET_CONCEPT_ID, 0)                        AS ADMITTED_FROM_CONCEPT_ID
    , PULL_VISIT_DETAIL_HOSP_ALL.DISCHARGED_TO_SOURCE_VALUE                             AS DISCHARGED_TO_SOURCE_VALUE
    , COALESCE(SOURCE_TO_CONCEPT_MAP_DISCHARGE.TARGET_CONCEPT_ID, 0)                    AS DISCHARGED_TO_CONCEPT_ID
    , PULL_VISIT_DETAIL_HOSP_ALL.VISIT_DETAIL_RANK                                      AS VISIT_DETAIL_RANK
    , CASE
        WHEN VISIT_DETAIL_RANK = 1
            THEN NULL
        ELSE VISIT_DETAIL_ID - 1
        END                                                                             AS PRECEDING_VISIT_DETAIL_ID -- A FOREIGN KEY TO THE VISIT_DETAIL TABLE OF THE VISIT IMMEDIATELY PRECEDING THIS VISIT
    , CASE
        WHEN VISIT_DETAIL_RANK = 1
            THEN VISIT_DETAIL_ID
        ELSE VISIT_DETAIL_ID - VISIT_DETAIL_RANK + 1
        END                                                                             AS PARENT_VISIT_DETAIL_ID
    , VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID                                              AS VISIT_OCCURRENCE_ID

    -------- Non-OMOP Fields ------------
	, 'VISIT_DETAIL_ALL' 										                        AS ETL_MODULE
	, PULL_VISIT_DETAIL_HOSP_ALL.PULL_PAT_ID                      		                AS STAGE_PAT_ID
    , PULL_VISIT_DETAIL_HOSP_ALL.PULL_MRN_CPI                           	            AS STAGE_MRN_CPI
	, PULL_VISIT_DETAIL_HOSP_ALL.PULL_CSN_ID								            AS STAGE_CSN_ID


FROM {{ref('PULL_VISIT_DETAIL_HOSP_ALL')}} AS PULL_VISIT_DETAIL_HOSP_ALL

    LEFT JOIN  {{ref('CARE_SITE_RAW')}} AS CARE_SITE
        ON PULL_VISIT_DETAIL_HOSP_ALL.PULL_VISIT_DETAIL_CARE_SITE_ID = CARE_SITE.CARE_SITE_ID

    INNER JOIN  {{ref('VISIT_OCCURRENCE_RAW')}} AS VISIT_OCCURRENCE
        ON PULL_VISIT_DETAIL_HOSP_ALL.PULL_CSN_ID = VISIT_OCCURRENCE.phi_CSN_ID
        -- ON PULL_VISIT_DETAIL_HOSP_ALL.VISIT_OCCURRENCE_ID = VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID

    LEFT JOIN  {{ref('PROVIDER_RAW')}} AS PROVIDER
        ON PULL_VISIT_DETAIL_HOSP_ALL.PULL_VISIT_DETAIL_PROVIDER_ID = PROVIDER.PROVIDER_SOURCE_VALUE

    LEFT JOIN   {{ ref('SOURCE_TO_CONCEPT_MAP_VISIT')}} AS SOURCE_TO_CONCEPT_MAP_VISIT
        ON PULL_VISIT_DETAIL_HOSP_ALL.VISIT_DETAIL_SOURCE_CONCEPT = SOURCE_TO_CONCEPT_MAP_VISIT.SOURCE_CODE

    LEFT JOIN   {{ ref('SOURCE_TO_CONCEPT_MAP_ADMIT')}} AS SOURCE_TO_CONCEPT_MAP_ADMIT
        ON PULL_VISIT_DETAIL_HOSP_ALL.PULL_ADMIT_SOURCE_CODE = SOURCE_TO_CONCEPT_MAP_ADMIT.SOURCE_CODE

    LEFT JOIN   {{ ref('SOURCE_TO_CONCEPT_MAP_DISCHARGE')}} AS SOURCE_TO_CONCEPT_MAP_DISCHARGE
        ON PULL_VISIT_DETAIL_HOSP_ALL.PULL_DISCH_DISP_CODE = SOURCE_TO_CONCEPT_MAP_DISCHARGE.SOURCE_CODE


