--DRUG_EXPOSURE
{{ config(materialized = 'table', schema = 'OMOP') }}

SELECT DISTINCT
    {{ sequence_get_nextval() }}::NUMBER(28,0)  AS DRUG_EXPOSURE_ID
    , PERSON_ID::NUMBER(28,0)                   AS PERSON_ID
    , DRUG_CONCEPT_ID::NUMBER(28,0)             AS DRUG_CONCEPT_ID
    , DRUG_EXPOSURE_START_DATE::DATE            AS DRUG_EXPOSURE_START_DATE
    , DRUG_EXPOSURE_START_DATETIME::DATETIME    AS DRUG_EXPOSURE_START_DATETIME
    , DRUG_EXPOSURE_END_DATE::DATE              AS DRUG_EXPOSURE_END_DATE
    , DRUG_EXPOSURE_END_DATETIME::DATETIME      AS DRUG_EXPOSURE_END_DATETIME
    , VERBATIM_END_DATE::DATE                   AS VERBATIM_END_DATE
    , DRUG_TYPE_CONCEPT_ID::NUMBER(28,0)        AS DRUG_TYPE_CONCEPT_ID
    , STOP_REASON::VARCHAR(20)                  AS STOP_REASON
    , REFILLS::NUMBER(28,0)                     AS REFILLS
    , QUANTITY::FLOAT                           AS QUANTITY
    , DAYS_SUPPLY::NUMBER(28,0)                 AS DAYS_SUPPLY
    , SIG::VARCHAR                              AS SIG
    , ROUTE_CONCEPT_ID::NUMBER(28,0)            AS ROUTE_CONCEPT_ID
    , LOT_NUMBER::VARCHAR(50)                   AS LOT_NUMBER
    , PROVIDER_ID::NUMBER(28,0)                 AS PROVIDER_ID
    , VISIT_OCCURRENCE_ID::NUMBER(28,0)         AS VISIT_OCCURRENCE_ID
    , VISIT_DETAIL_ID::NUMBER(28,0)             AS VISIT_DETAIL_ID
    , DRUG_SOURCE_VALUE::VARCHAR(250)           AS DRUG_SOURCE_VALUE --Human readable Source Value use src_VALUE_ID below to link
    , DRUG_SOURCE_CONCEPT_ID::NUMBER(28,0)      AS DRUG_SOURCE_CONCEPT_ID
    , ROUTE_SOURCE_VALUE::VARCHAR(50)           AS ROUTE_SOURCE_VALUE
    , DOSE_UNIT_SOURCE_VALUE::VARCHAR(50)       AS DOSE_UNIT_SOURCE_VALUE

 ------Non OMOP fields -----------
    , ETL_MODULE::VARCHAR                       AS etl_MODULE
    , STAGE_PAT_ID::VARCHAR                  	AS phi_PAT_ID
    , STAGE_MRN_CPI::NUMBER(28,0)               AS phi_MRN_CPI
    , STAGE_CSN_ID::NUMBER(28,0)			    AS phi_CSN_ID
----- Link to source
    , SRC_TABLE::VARCHAR                        AS src_TABLE
    , SRC_FIELD::VARCHAR                        AS src_FIELD
    , SRC_VALUE_ID::VARCHAR                     AS src_VALUE_ID

FROM
(
    SELECT PERSON_ID, DRUG_CONCEPT_ID, DRUG_EXPOSURE_START_DATE, DRUG_EXPOSURE_START_DATETIME, DRUG_EXPOSURE_END_DATE
	, DRUG_EXPOSURE_END_DATETIME, VERBATIM_END_DATE, DRUG_TYPE_CONCEPT_ID, STOP_REASON, REFILLS, QUANTITY, DAYS_SUPPLY, SIG
	, ROUTE_CONCEPT_ID, LOT_NUMBER, PROVIDER_ID, VISIT_OCCURRENCE_ID, VISIT_DETAIL_ID, DRUG_SOURCE_VALUE, DRUG_SOURCE_CONCEPT_ID
	, ROUTE_SOURCE_VALUE, DOSE_UNIT_SOURCE_VALUE
    , ETL_MODULE, STAGE_PAT_ID, STAGE_MRN_CPI, STAGE_CSN_ID
    , 'ORDER_MED' as SRC_TABLE, 'MEDICATION_ID' AS SRC_FIELD, STAGE_MEDICATION_ID::INTEGER AS SRC_VALUE_ID
    FROM {{ref('STAGE_DRUG_EXPOSURE_AMB_RXNORM')}}
    UNION ALL
    SELECT PERSON_ID, DRUG_CONCEPT_ID, DRUG_EXPOSURE_START_DATE, DRUG_EXPOSURE_START_DATETIME, DRUG_EXPOSURE_END_DATE
	, DRUG_EXPOSURE_END_DATETIME, VERBATIM_END_DATE, DRUG_TYPE_CONCEPT_ID, STOP_REASON, REFILLS, QUANTITY, DAYS_SUPPLY, SIG
	, ROUTE_CONCEPT_ID, LOT_NUMBER, PROVIDER_ID, VISIT_OCCURRENCE_ID, VISIT_DETAIL_ID, DRUG_SOURCE_VALUE, DRUG_SOURCE_CONCEPT_ID
	, ROUTE_SOURCE_VALUE, DOSE_UNIT_SOURCE_VALUE
    , ETL_MODULE, STAGE_PAT_ID, STAGE_MRN_CPI, STAGE_CSN_ID
    , 'ORDER_MED' as SRC_TABLE, 'MEDICATION_ID' AS SRC_FIELD, STAGE_MEDICATION_ID::INTEGER AS SRC_VALUE_ID
    FROM {{ref('STAGE_DRUG_EXPOSURE_ANES_RXNORM')}}
    UNION ALL
    SELECT PERSON_ID, DRUG_CONCEPT_ID, DRUG_EXPOSURE_START_DATE, DRUG_EXPOSURE_START_DATETIME, DRUG_EXPOSURE_END_DATE
	, DRUG_EXPOSURE_END_DATETIME, VERBATIM_END_DATE, DRUG_TYPE_CONCEPT_ID, STOP_REASON, REFILLS, QUANTITY, DAYS_SUPPLY, SIG
	, ROUTE_CONCEPT_ID, LOT_NUMBER, PROVIDER_ID, VISIT_OCCURRENCE_ID, VISIT_DETAIL_ID, DRUG_SOURCE_VALUE, DRUG_SOURCE_CONCEPT_ID
	, ROUTE_SOURCE_VALUE, DOSE_UNIT_SOURCE_VALUE, ETL_MODULE, STAGE_PAT_ID, STAGE_MRN_CPI, STAGE_CSN_ID
    , 'ORDER_MED' as SRC_TABLE, 'MEDICATION_ID' AS SRC_FIELD, STAGE_MEDICATION_ID::INTEGER AS SRC_VALUE_ID
    FROM {{ref('STAGE_DRUG_EXPOSURE_HSP_RXNORM')}}
    UNION ALL
    SELECT PERSON_ID, DRUG_CONCEPT_ID, DRUG_EXPOSURE_START_DATE, DRUG_EXPOSURE_START_DATETIME, DRUG_EXPOSURE_END_DATE
	, DRUG_EXPOSURE_END_DATETIME, VERBATIM_END_DATE, DRUG_TYPE_CONCEPT_ID, STOP_REASON, REFILLS, QUANTITY, DAYS_SUPPLY, SIG
	, ROUTE_CONCEPT_ID, LOT_NUMBER, PROVIDER_ID, VISIT_OCCURRENCE_ID, VISIT_DETAIL_ID, DRUG_SOURCE_VALUE, DRUG_SOURCE_CONCEPT_ID
	, ROUTE_SOURCE_VALUE, DOSE_UNIT_SOURCE_VALUE, ETL_MODULE, STAGE_PAT_ID, STAGE_MRN_CPI, STAGE_CSN_ID
    , 'IMMUNE' as SRC_TABLE, 'IMMUNZATN_ID' AS SRC_FIELD, STAGE_MEDICATION_ID::INTEGER AS SRC_VALUE_ID
    FROM {{ref('STAGE_DRUG_EXPOSURE_ALL_IMM')}}
) AS A

