-- PULL_NOTE_ANES_ALL
{#-- {{ config(materialized = 'view', schema = 'OMOP_PULL') }}-- , cluster_by = ['PAT_ENC_CSN_ID']#}

SELECT

-- ***STAGE ATTRIBUTES***
-- OMOP Standard fields used for the Stage
	Z_NOTE_LOOKUP.PERSON_ID 							AS PERSON_ID
	,Z_NOTE_LOOKUP.ENTRY_INSTANT_DTTM::DATE				AS NOTE_DATE
	,Z_NOTE_LOOKUP.ENTRY_INSTANT_DTTM 					AS NOTE_DATETIME
	,Z_NOTE_LOOKUP.ZC_NOTE_TYPE_IP_NAME 				AS NOTE_TITLE
	-- ******************************************
	  ,'NO_TEXT' AS NOTE_TEXT	-- NO ACTUAL TEXT IS BEING WRITTEN AT THIS TIME OVER PHI CONCERNS
	-- ******************************************
	,PULL_VISIT_OCCURRENCE_AMB.PULL_PROVIDER_SOURCE_VALUE 	AS PROVIDER_SOURCE_VALUE
	,Z_NOTE_LOOKUP.IP_NOTE_TYPE_C
		|| ':' || Z_NOTE_LOOKUP.AMB_NOTE_YN
		|| ':' || Z_NOTE_LOOKUP.ZC_NOTE_TYPE_IP_NAME 	AS NOTE_SOURCE_VALUE


-- ***ADDITIONAL ATTRIBUTES***
-- Non_OMOP fields used for the Stage
	,Z_NOTE_LOOKUP.PAT_ENC_CSN_ID 						AS PULL_CSN_ID
	,Z_NOTE_LOOKUP.IP_NOTE_TYPE_C						AS PULL_IP_NOTE_TYPE_C
	,Z_NOTE_LOOKUP.AMB_NOTE_YN							AS PULL_AMB_NOTE_YN
	,Z_NOTE_LOOKUP.NOTE_ID								AS PULL_NOTE_ID
	,Z_NOTE_LOOKUP.CONTACT_DATE_REAL 					AS PULL_CONTACT_DATE_REAL
	,PULL_VISIT_OCCURRENCE_AMB.PULL_ENC_TYPE_C			AS PULL_ENC_TYPE_C

 FROM {{ref('PULL_VISIT_OCCURRENCE_AMB')}}  PULL_VISIT_OCCURRENCE_AMB

-- associates anethesia EVENT to hospital encounter
    INNER JOIN {{ ref('F_AN_RECORD_SUMMARY_stg')}} AS F_AN_RECORD_SUMMARY on PULL_VISIT_OCCURRENCE_AMB.PULL_CSN_ID = F_AN_RECORD_SUMMARY.AN_52_ENC_CSN_ID
    INNER JOIN {{ ref('AN_HSB_LINK_INFO_stg')}} AS AN_HSB_LINK_INFO on F_AN_RECORD_SUMMARY.AN_EPISODE_ID=AN_HSB_LINK_INFO.SUMMARY_BLOCK_ID
    INNER JOIN {{ ref('PAT_ENC_HSP_stg')}} AS PAT_ENC_HSP on AN_HSB_LINK_INFO.AN_BILLING_CSN_ID=PAT_ENC_HSP.PAT_ENC_CSN_ID

    INNER JOIN  {{ref('Z_NOTE_LOOKUP')}} AS Z_NOTE_LOOKUP
            ON  PULL_VISIT_OCCURRENCE_AMB.PULL_CSN_ID= Z_NOTE_LOOKUP.PAT_ENC_CSN_ID

WHERE PULL_VISIT_OCCURRENCE_AMB.PULL_ENC_TYPE_C = 52 -- Anesthesia


