
--BEGIN cte__T_CPT_CODES
-- pulls a list of available proc_id and proc_codes
SELECT DISTINCT EAP.PROC_ID
    ,CASE
        WHEN EAP2.PROC_CODE IS NULL THEN
        EAP.PROC_CODE
        ELSE
        EAP2.PROC_CODE
    END AS PROC_CODE
    ,CASE
        WHEN EAP2.PROC_NAME IS NULL THEN
        EAP.PROC_NAME
        ELSE
        EAP2.PROC_NAME
    END AS PROC_NAME
FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_CLARITY.CLARITY_EAP_stg AS EAP
    LEFT JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP_CLARITY.LINKED_PERFORMABLE_stg AS LINKED_PERFORMABLE
        ON EAP.PROC_ID = LINKED_PERFORMABLE.PROC_ID
    LEFT JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP_CLARITY.CLARITY_EAP_stg AS EAP2
        ON LINKED_PERFORMABLE.LINKED_PERFORM_ID = EAP2.PROC_ID
UNION
SELECT DISTINCT EAP.PROC_ID AS PROC_ID
    ,CASE
        WHEN EAP2.PROC_CODE IS NULL THEN
        EAP.PROC_CODE
        ELSE
        EAP2.PROC_CODE
    END AS PROC_CODE
    ,CASE
        WHEN EAP2.PROC_NAME IS NULL THEN
        EAP.PROC_NAME
        ELSE
        EAP2.PROC_NAME
    END AS PROC_NAME
FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_CLARITY.CLARITY_EAP_stg AS EAP
    LEFT JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP_CLARITY.LINKED_CHARGEABLES_stg AS LINKED_CHARGEABLES
        ON EAP.PROC_ID = LINKED_CHARGEABLES.PROC_ID
    LEFT JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP_CLARITY.CLARITY_EAP_stg AS EAP2
        ON LINKED_CHARGEABLES.LINKED_CHRG_ID = EAP2.PROC_ID
-- END cte__T_CPT_CODES
--