--QA_LOCATION_DUPLICATES_COUNT
---------------------------------------------------------------------
WITH TMP_DUPES AS (
SELECT LOCATION_ID
      ,ADDRESS_1
      ,ADDRESS_2
      ,CITY
      ,STATE
      ,ZIP
      ,COUNTY
      ,LOCATION_SOURCE_VALUE
	,COUNT(*) AS CNT

FROM {{ref('LOCATION_RAW')}} AS T1
GROUP BY  LOCATION_ID
      ,ADDRESS_1
      ,ADDRESS_2
      ,CITY
      ,STATE
      ,ZIP
      ,COUNTY
      ,LOCATION_SOURCE_VALUE
HAVING COUNT(*) > 1
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	, 'LOCATION' AS STANDARD_DATA_TABLE
	, 'DUPLICATE' AS QA_METRIC
	, 'RECORDS'  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) IS NOT NULL THEN 'FATAL' ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('LOCATION_RAW')}}) AS TOTAL_RECORDS
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('LOCATION')}}) AS TOTAL_RECORDS_CLEAN
FROM TMP_DUPES

