----QA_MEASUREMENT_NONSTANDARD_DETAIL
-------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH NONSTANDARD_DETAIL
AS (
	SELECT 'MEASUREMENT_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, MEASUREMENT_ID AS CDT_ID
	FROM {{ref('MEASUREMENT_RAW')}} AS M
	LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C
		ON M.MEASUREMENT_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'MEASUREMENT' AND upper(C.VOCABULARY_ID) IN  ('LOINC', 'SNOMED', 'CPT4')
	WHERE MEASUREMENT_CONCEPT_ID <> 0 AND MEASUREMENT_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)

	UNION ALL

	SELECT 'MEASUREMENT_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, MEASUREMENT_ID AS CDT_ID
	FROM {{ref('MEASUREMENT_RAW')}} AS M
	LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C
		ON M.MEASUREMENT_TYPE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'TYPE CONCEPT' AND upper(C.VOCABULARY_ID) IN  ('TYPE CONCEPT')
	WHERE MEASUREMENT_TYPE_CONCEPT_ID <> 0 AND MEASUREMENT_TYPE_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)

	UNION ALL

	SELECT 'OPERATOR_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, MEASUREMENT_ID AS CDT_ID
	FROM {{ref('MEASUREMENT_RAW')}} AS M
	LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C
		ON M.OPERATOR_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'MEAS VALUE OPERATOR'
	WHERE OPERATOR_CONCEPT_ID <> 0 AND OPERATOR_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)

	UNION ALL

	SELECT 'VALUE_AS_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, MEASUREMENT_ID AS CDT_ID
	FROM {{ref('MEASUREMENT_RAW')}} AS M
	LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C
		ON M.VALUE_AS_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) IN ('MEAS VALUE', 'OBSERVATION') AND upper(C.VOCABULARY_ID) IN  ('LOINC', 'SNOMED')
	WHERE VALUE_AS_CONCEPT_ID <> 0 AND VALUE_AS_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)

	UNION ALL

	-- COVID_MAPPING
	SELECT 'VALUE_AS_CONCEPT_ID' AS METRIC_FIELD, 'COVID_MAPPING' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
            , MEASUREMENT_ID AS CDT_ID
    FROM {{ref('MEASUREMENT_RAW')}} AS M
      JOIN {{ source('OMOP','CONCEPT_ANCESTOR')}} AS CA ON M.MEASUREMENT_CONCEPT_ID = CA.DESCENDANT_CONCEPT_ID
	WHERE CA.ANCESTOR_CONCEPT_ID = 756055
     AND (M.VALUE_AS_CONCEPT_ID IS NULL OR M.VALUE_AS_CONCEPT_ID =0)

	UNION ALL

	SELECT 'UNIT_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, MEASUREMENT_ID AS CDT_ID
	FROM {{ref('MEASUREMENT_RAW')}} AS M
	LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C
		ON M.UNIT_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'UNIT'
	WHERE UNIT_CONCEPT_ID <> 0 AND UNIT_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)

	UNION ALL

	SELECT 'MEASUREMENT_SOURCE_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, MEASUREMENT_ID AS CDT_ID
	FROM {{ref('MEASUREMENT_RAW')}} AS M
	LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C
		ON M.MEASUREMENT_SOURCE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'MEASUREMENT' AND upper(C.VOCABULARY_ID) IN  ('LOINC', 'SNOMED')
	WHERE MEASUREMENT_SOURCE_CONCEPT_ID <> 0 AND C.CONCEPT_ID IS NULL
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'MEASUREMENT' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NONSTANDARD_DETAIL
  WHERE ERROR_TYPE <>'EXPECTED'

