--QA_MEASUREMENT_DUPLICATES_DETAIL_PROVIDER
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH TMP_DUPES AS (
SELECT PERSON_ID
	,MEASUREMENT_CONCEPT_ID
	-- ,MEASUREMENT_DATE
	,MEASUREMENT_DATETIME
	-- ,MEASUREMENT_TYPE_CONCEPT_ID
	-- ,OPERATOR_CONCEPT_ID
	,VALUE_AS_NUMBER
	,VALUE_AS_CONCEPT_ID
	,UNIT_CONCEPT_ID
	,RANGE_LOW
	,RANGE_HIGH
	-- ,PROVIDER_ID
	,VISIT_OCCURRENCE_ID
	,MEASUREMENT_SOURCE_VALUE
	-- ,MEASUREMENT_SOURCE_CONCEPT_ID
	-- ,UNIT_SOURCE_VALUE
	,VALUE_SOURCE_VALUE
	,COUNT(*) AS CNT
FROM {{ref('MEASUREMENT_RAW')}}  AS T1
WHERE T1.MEASUREMENT_CONCEPT_ID <> 0
	AND T1.MEASUREMENT_CONCEPT_ID IS NOT NULL
	AND T1.PERSON_ID <> 0
	AND T1.PERSON_ID IS NOT NULL
GROUP BY PERSON_ID
	,MEASUREMENT_CONCEPT_ID
	-- ,MEASUREMENT_DATE
	,MEASUREMENT_DATETIME
	-- ,MEASUREMENT_TYPE_CONCEPT_ID
	-- ,OPERATOR_CONCEPT_ID
	,VALUE_AS_NUMBER
	,VALUE_AS_CONCEPT_ID
	,UNIT_CONCEPT_ID
	,RANGE_LOW
	,RANGE_HIGH
	-- ,PROVIDER_ID
	,VISIT_OCCURRENCE_ID
	,MEASUREMENT_SOURCE_VALUE
	-- ,MEASUREMENT_SOURCE_CONCEPT_ID
	-- ,UNIT_SOURCE_VALUE
	,VALUE_SOURCE_VALUE
HAVING COUNT(*) > 1
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'MEASUREMENT' AS STANDARD_DATA_TABLE
	,'POSSIBLE_DUPLICATE' AS QA_METRIC
	,'PROVIDER_ID'  AS METRIC_FIELD
	,'FOLLOW_UP' AS ERROR_TYPE
	,ME.MEASUREMENT_ID

FROM TMP_DUPES AS D
INNER JOIN {{ref('MEASUREMENT_RAW')}} AS ME ON D.PERSON_ID = ME.PERSON_ID
	AND D.MEASUREMENT_CONCEPT_ID = ME.MEASUREMENT_CONCEPT_ID
	-- AND D.MEASUREMENT_DATE = ME.MEASUREMENT_DATE
	AND COALESCE(D.MEASUREMENT_DATETIME,'1900-01-01') = COALESCE(ME.MEASUREMENT_DATETIME,'1900-01-01')
	-- AND D.MEASUREMENT_TYPE_CONCEPT_ID = ME.MEASUREMENT_TYPE_CONCEPT_ID
	-- AND COALESCE(D.OPERATOR_CONCEPT_ID, 0) = COALESCE(ME.OPERATOR_CONCEPT_ID, 0)
	AND COALESCE(D.VALUE_AS_NUMBER, 0) = COALESCE(ME.VALUE_AS_NUMBER, 0)
	AND COALESCE(D.VALUE_AS_CONCEPT_ID, 0) = COALESCE(ME.VALUE_AS_CONCEPT_ID, 0)
	AND COALESCE(D.UNIT_CONCEPT_ID, 0) = COALESCE(ME.UNIT_CONCEPT_ID, 0)
	AND COALESCE(D.RANGE_LOW, 0) = COALESCE(ME.RANGE_LOW, 0)
	AND COALESCE(D.RANGE_HIGH, 0) = COALESCE(ME.RANGE_HIGH, 0)
	-- AND COALESCE(D.PROVIDER_ID, 0) = COALESCE(ME.PROVIDER_ID, 0)
	AND COALESCE(D.VISIT_OCCURRENCE_ID, 0) = COALESCE(ME.VISIT_OCCURRENCE_ID, 0)
	AND COALESCE(D.MEASUREMENT_SOURCE_VALUE, '0') = COALESCE(ME.MEASUREMENT_SOURCE_VALUE, '0')
	-- AND COALESCE(D.MEASUREMENT_SOURCE_CONCEPT_ID, 0) = COALESCE(ME.MEASUREMENT_SOURCE_CONCEPT_ID, 0)
	-- AND COALESCE(D.UNIT_SOURCE_VALUE, '0') = COALESCE(ME.UNIT_SOURCE_VALUE, '0')
	AND COALESCE(D.VALUE_SOURCE_VALUE, '0') = COALESCE(ME.VALUE_SOURCE_VALUE, '0')
