------ QA_MEASUREMENT_NULLCONCEPT_COUNT
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH NULLCONCEPT_COUNT
AS (
	SELECT 'MEASUREMENT_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM {{ref('MEASUREMENT_RAW')}} AS MEASUREMENT
	WHERE (MEASUREMENT_CONCEPT_ID IS NULL)

	UNION ALL

	SELECT 'OPERATOR_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM {{ref('MEASUREMENT_RAW')}} AS MEASUREMENT
	WHERE (OPERATOR_CONCEPT_ID IS NULL)

	-- UNION ALL

	-- SELECT 'VALUE_AS_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	-- FROM {{ref('MEASUREMENT_RAW')}} AS MEASUREMENT
	-- WHERE (VALUE_AS_CONCEPT_ID IS NULL)

	-- UNION ALL

	-- SELECT 'UNIT_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	-- FROM {{ref('MEASUREMENT_RAW')}} AS MEASUREMENT
	-- WHERE (UNIT_CONCEPT_ID IS NULL)

	-- UNION ALL

	-- SELECT 'MEASUREMENT_SOURCE_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	-- FROM {{ref('MEASUREMENT_RAW')}} AS MEASUREMENT
	-- WHERE (MEASUREMENT_SOURCE_CONCEPT_ID IS NULL)
)

SELECT CAST( GETDATE() AS DATE) AS RUN_DATE
	,'MEASUREMENT' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) <> 0 THEN ERROR_TYPE ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('MEASUREMENT_RAW')}} ) AS TOTAL_RECORDS
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('MEASUREMENT')}} ) AS TOTAL_RECORDS_CLEAN
FROM NULLCONCEPT_COUNT
GROUP BY METRIC_FIELD, QA_METRIC, ERROR_TYPE

