--QA_MEASUREMENT_DATEVDATETIME_DETAIL
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH DATEVDATETIME_DETAIL AS (
SELECT 'MEASUREMENT_DATE' AS METRIC_FIELD, 'DATEVDATETIME' AS QA_METRIC, 'WARNING' AS ERROR_TYPE,
	MEASUREMENT_ID AS CDT_ID
FROM {{ref('MEASUREMENT_RAW')}} AS T1
WHERE MEASUREMENT_DATE <> CAST(MEASUREMENT_DATETIME AS DATE)
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'MEASUREMENT' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM DATEVDATETIME_DETAIL

