--PERSON
{{ config(materialized = 'table', schema = 'OMOP') }}

SELECT
      PERSON_ID::NUMBER(28,0)                   AS PERSON_ID
    , GENDER_CONCEPT_ID::NUMBER(28,0)           AS GENDER_CONCEPT_ID
    , YEAR_OF_BIRTH::NUMBER(28,0)               AS YEAR_OF_BIRTH
    , MONTH_OF_BIRTH::NUMBER(28,0)              AS MONTH_OF_BIRTH
    , DAY_OF_BIRTH::NUMBER(28,0)                AS DAY_OF_BIRTH
    , BIRTH_DATETIME::DATETIME                  AS BIRTH_DATETIME
    , RACE_CONCEPT_ID::NUMBER(28,0)             AS RACE_CONCEPT_ID
    , ETHNICITY_CONCEPT_ID::NUMBER(28,0)        AS ETHNICITY_CONCEPT_ID
    , LOCATION_ID::NUMBER(28,0)                 AS LOCATION_ID
    , PROVIDER_ID::NUMBER(28,0)                 AS PROVIDER_ID
    , CARE_SITE_ID::NUMBER(28,0)                AS CARE_SITE_ID
    , PERSON_SOURCE_VALUE::VARCHAR              AS PERSON_SOURCE_VALUE
    , GENDER_SOURCE_VALUE::VARCHAR              AS GENDER_SOURCE_VALUE
    , GENDER_SOURCE_CONCEPT_ID::NUMBER(28,0)    AS GENDER_SOURCE_CONCEPT_ID
    , RACE_SOURCE_VALUE::VARCHAR                AS RACE_SOURCE_VALUE
    , RACE_SOURCE_CONCEPT_ID::NUMBER(28,0)      AS RACE_SOURCE_CONCEPT_ID
    , ETHNICITY_SOURCE_VALUE::VARCHAR           AS ETHNICITY_SOURCE_VALUE
    , ETHNICITY_SOURCE_CONCEPT_ID::NUMBER(28,0) AS ETHNICITY_SOURCE_CONCEPT_ID
	-------- Non-OMOP Fields ------------
	, 'STAGE_PERSON_ALL' 		                AS ETL_MODULE
	, STAGE_PAT_ID                      	    AS phi_PAT_ID
    , STAGE_MRN_CPI                             AS phi_MRN_CPI
FROM
 {{ref('STAGE_PERSON_ALL')}} AS T
 	    QUALIFY
        ROW_NUMBER() OVER (
        PARTITION BY PERSON_ID
        ORDER BY PERSON_ID
        )=1
