--PERSON
{{ config(materialized = 'view', schema = 'OMOP') }}

SELECT
      PERSON_ID
    , GENDER_CONCEPT_ID
    , YEAR_OF_BIRTH
    , MONTH_OF_BIRTH
    , DAY_OF_BIRTH
    , BIRTH_DATETIME
    , RACE_CONCEPT_ID
    , ETHNICITY_CONCEPT_ID
    , LOCATION_ID
    , PROVIDER_ID
    , CARE_SITE_ID
    , PERSON_SOURCE_VALUE
    , GENDER_SOURCE_VALUE
    , GENDER_SOURCE_CONCEPT_ID
    , RACE_SOURCE_VALUE
    , RACE_SOURCE_CONCEPT_ID
    , ETHNICITY_SOURCE_VALUE
    , ETHNICITY_SOURCE_CONCEPT_ID
	-------- Non-OMOP Fields ------------
	, ETL_MODULE
	, phi_PAT_ID
    , phi_MRN_CPI
FROM
 {{ref('PERSON_RAW')}} AS PERSON
LEFT JOIN (
    SELECT CDT_ID
    FROM {{ref('QA_ERR_DBT')}} AS QA_ERR_DBT
        WHERE (STANDARD_DATA_TABLE = 'PERSON')
            AND (ERROR_TYPE IN ('FATAL', 'INVALID DATA'))
        ) AS EXCLUSION_RECORDS
        ON PERSON.PERSON_ID = EXCLUSION_RECORDS.CDT_ID
WHERE (EXCLUSION_RECORDS.CDT_ID IS NULL)
