/*
Purpose: This query transforms ambulatory CPT procedure data into the OMOP CDM format
Source Tables: 
    - PULL_PROCEDURE_OCCURRENCE_AMB_CPT
    - VISIT_OCCURRENCE_RAW
    - T_PROCEDURE_SOURCE
    - T_PROCEDURE_CONCEPT
    - PROVIDER_RAW
    - SOURCE_TO_CONCEPT_MAP (for modifiers)
*/

-- CTE to get procedure modifiers
WITH __dbt__cte__SOURCE_TO_CONCEPT_MAP_MODIFIER AS (
    SELECT *
    FROM CARE_RES_OMOP_GEN_WKSP.OMOP.SOURCE_TO_CONCEPT_MAP
    WHERE SOURCE_VOCABULARY_ID = 'SH_MODIFIER'
)

-- Main query to transform procedure data
SELECT DISTINCT
    -- Core OMOP fields
    PULL_PROCEDURE_OCCURRENCE_AMB_CPT.PERSON_ID AS PERSON_ID,
    T_CONCEPT.CONCEPT_ID AS PROCEDURE_CONCEPT_ID,
    PROCEDURE_DATE AS PROCEDURE_DATE,
    PROCEDURE_DATETIME AS PROCEDURE_DATETIME,
    PROCEDURE_END_DATE AS PROCEDURE_END_DATE,
    PROCEDURE_END_DATETIME AS PROCEDURE_END_DATETIME,
    32817 AS PROCEDURE_TYPE_CONCEPT_ID,  -- Standard type concept for ambulatory procedures
    SOURCE_TO_CONCEPT_MAP_MODIFIER.TARGET_CONCEPT_ID AS MODIFIER_CONCEPT_ID,
    QUANTITY AS QUANTITY,
    PROVIDER.PROVIDER_ID AS PROVIDER_ID,
    VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID AS VISIT_OCCURRENCE_ID,
    NULL AS VISIT_DETAIL_ID,
    PROCEDURE_SOURCE_VALUE AS PROCEDURE_SOURCE_VALUE,
    T_SOURCE.CONCEPT_ID AS PROCEDURE_SOURCE_CONCEPT_ID,
    MODIFIER_SOURCE_VALUE AS MODIFIER_SOURCE_VALUE,

    -- Custom non-OMOP fields for tracking
    'PROCEDURE_OCCURRENCE_AMB_CPT' AS ETL_MODULE,
    VISIT_OCCURRENCE.phi_PAT_ID AS STAGE_PAT_ID,
    VISIT_OCCURRENCE.phi_MRN_CPI AS STAGE_MRN_CPI,
    VISIT_OCCURRENCE.phi_CSN_ID AS STAGE_CSN_ID,
    PULL_PROC_ID AS STAGE_PROC_ID

FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.PULL_PROCEDURE_OCCURRENCE_AMB_CPT AS PULL_PROCEDURE_OCCURRENCE_AMB_CPT

    -- Join to get visit information
    INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP.VISIT_OCCURRENCE_RAW AS VISIT_OCCURRENCE
        ON PULL_PROCEDURE_OCCURRENCE_AMB_CPT.PULL_CSN_ID = VISIT_OCCURRENCE.phi_CSN_ID

    -- Join to get source procedure concepts
    INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP_STAGE.T_PROCEDURE_SOURCE AS T_SOURCE
        ON PULL_PROCEDURE_OCCURRENCE_AMB_CPT.PULL_PROC_CODE = T_SOURCE.CONCEPT_CODE

    -- Join to get standard procedure concepts
    INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP_STAGE.T_PROCEDURE_CONCEPT AS T_CONCEPT
        ON T_SOURCE.CONCEPT_ID = T_CONCEPT.CONCEPT_ID

    -- Optional join to get provider information
    LEFT JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP.PROVIDER_RAW AS PROVIDER
        ON PULL_PROCEDURE_OCCURRENCE_AMB_CPT.PROVIDER_SOURCE_VALUE = PROVIDER.PROVIDER_SOURCE_VALUE

    -- Optional join to get procedure modifiers
    LEFT JOIN __dbt__cte__SOURCE_TO_CONCEPT_MAP_MODIFIER AS SOURCE_TO_CONCEPT_MAP_MODIFIER
        ON PULL_PROCEDURE_OCCURRENCE_AMB_CPT.PULL_MODIFIER1_ID = SOURCE_TO_CONCEPT_MAP_MODIFIER.SOURCE_CODE::VARCHAR