
--BEGIN cte__T_CODES_DEVICE_EXPOSURE
    SELECT BLOOD_ADMIN_INFO.ORDER_ID
            ,BLOOD_ADMIN_INFO.BLOOD_ADMIN_UNIT
            ,BLOOD_ADMIN_INFO.BLOOD_ADMIN_PROD
            ,BLOOD_ADMIN_INFO.BLOOD_ADMIN_TYPE
            ,ORDER_PROC.PROC_ID
            -- ,ORDER_PROC.PROC_CODE
            ,ORDER_PROC.ORDERING_DATE
            ,CLARITY_EAP.PROC_NAME
    FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_CLARITY.BLOOD_ADMIN_INFO_stg AS BLOOD_ADMIN_INFO
        INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP_CLARITY.ORDER_PROC_stg AS ORDER_PROC
            ON BLOOD_ADMIN_INFO.ORDER_ID = ORDER_PROC.ORDER_PROC_ID
        INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP_CLARITY.CLARITY_EAP_stg AS CLARITY_EAP
            ON ORDER_PROC.PROC_ID = CLARITY_EAP.PROC_ID
    WHERE (BLOOD_ADMIN_INFO.LINE = 1)
--END cte__T_CODES_DEVICE_EXPOSURE
--