
--OBSERVATION
{{ config(materialized = 'view', schema = 'OMOP') }}

SELECT DISTINCT
      OBSERVATION_ID
    , PERSON_ID
    , OBSERVATION_CONCEPT_ID
    , OBSERVATION_DATE
    , OBSERVATION_DATETIME
    , OBSERVATION_TYPE_CONCEPT_ID
    , VALUE_AS_NUMBER
    , VALUE_AS_STRING
    , VALUE_AS_CONCEPT_ID
    , UNIT_CONCEPT_ID
    , QUALIFIER_CONCEPT_ID
    , PROVIDER_ID
    , VISIT_OCCURRENCE_ID
    , VISIT_DETAIL_ID
    , OBSERVATION_SOURCE_VALUE --Human readable Source Value use src_VALUE_ID below to link
    , OBSERVATION_SOURCE_CONCEPT_ID
    , UNIT_SOURCE_VALUE
    , QUALIFIER_SOURCE_VALUE
    , VALUE_SOURCE_VALUE
    , OBSERVATION_EVENT_ID
    , OBS_EVENT_FIELD_CONCEPT_ID

 ------Non OMOP fields -----------
    , etl_MODULE
    , phi_PAT_ID
    , phi_MRN_CPI
    , phi_CSN_ID
----- Link to source
    , src_TABLE
    , src_FIELD
    , src_VALUE_ID

FROM
     {{ref('OBSERVATION_RAW')}}  AS OBSERVATION

LEFT JOIN (
    SELECT CDT_ID
    FROM {{ref('QA_ERR_DBT')}} AS QA_ERR_DBT
        WHERE (STANDARD_DATA_TABLE = 'OBSERVATION')
            AND (ERROR_TYPE IN ('FATAL', 'INVALID DATA'))
        ) AS EXCLUSION_RECORDS
        ON OBSERVATION.OBSERVATION_ID = EXCLUSION_RECORDS.CDT_ID
WHERE (EXCLUSION_RECORDS.CDT_ID IS NULL)
