
--OBSERVATION_RAW
{{ config(materialized = 'table', schema = 'OMOP') }}

SELECT DISTINCT
    {{ sequence_get_nextval() }}::NUMBER(28,0)    AS OBSERVATION_ID
    , PERSON_ID::NUMBER(28,0)                     AS PERSON_ID
    , OBSERVATION_CONCEPT_ID::NUMBER(28,0)        AS OBSERVATION_CONCEPT_ID
    , OBSERVATION_DATE::DATE                      AS OBSERVATION_DATE
    , OBSERVATION_DATETIME::DATETIME              AS OBSERVATION_DATETIME
    , OBSERVATION_TYPE_CONCEPT_ID::NUMBER(28,0)   AS OBSERVATION_TYPE_CONCEPT_ID
    , VALUE_AS_NUMBER::FLOAT                      AS VALUE_AS_NUMBER
    , VALUE_AS_STRING::VARCHAR(60)                AS VALUE_AS_STRING
    , VALUE_AS_CONCEPT_ID::NUMBER(28,0)           AS VALUE_AS_CONCEPT_ID
    , UNIT_CONCEPT_ID::NUMBER(28,0)               AS UNIT_CONCEPT_ID
    , QUALIFIER_CONCEPT_ID::NUMBER(28,0)          AS QUALIFIER_CONCEPT_ID
    , PROVIDER_ID::NUMBER(28,0)                   AS PROVIDER_ID
    , VISIT_OCCURRENCE_ID::NUMBER(28,0)           AS VISIT_OCCURRENCE_ID
    , VISIT_DETAIL_ID::NUMBER(28,0)               AS VISIT_DETAIL_ID
    , OBSERVATION_SOURCE_VALUE::VARCHAR(50)       AS OBSERVATION_SOURCE_VALUE --Human readable Source Value use src_VALUE_ID below to link
    , OBSERVATION_SOURCE_CONCEPT_ID::NUMBER(28,0) AS OBSERVATION_SOURCE_CONCEPT_ID
    , UNIT_SOURCE_VALUE::VARCHAR(50)              AS UNIT_SOURCE_VALUE
    , QUALIFIER_SOURCE_VALUE::VARCHAR(50)         AS QUALIFIER_SOURCE_VALUE
    , VALUE_SOURCE_VALUE::VARCHAR(50)             AS VALUE_SOURCE_VALUE
    , OBSERVATION_EVENT_ID::NUMBER(28,0)          AS OBSERVATION_EVENT_ID
    , OBS_EVENT_FIELD_CONCEPT_ID::NUMBER(28,0)    AS OBS_EVENT_FIELD_CONCEPT_ID

 ------Non OMOP fields -----------
    , ETL_MODULE::VARCHAR                         AS etl_MODULE
    , STAGE_PAT_ID::VARCHAR                  	  AS phi_PAT_ID
    , STAGE_MRN_CPI::NUMBER(28,0)                 AS phi_MRN_CPI
    , STAGE_CSN_ID::NUMBER(28,0)			      AS phi_CSN_ID
----- Link to source
    , SRC_TABLE::VARCHAR                          AS src_TABLE
    , SRC_FIELD::VARCHAR                          AS src_FIELD
    , SRC_VALUE_ID::VARCHAR                       AS src_VALUE_ID

FROM
(
    SELECT PERSON_ID, OBSERVATION_CONCEPT_ID, OBSERVATION_DATE, OBSERVATION_DATETIME, OBSERVATION_TYPE_CONCEPT_ID,
    VALUE_AS_NUMBER, VALUE_AS_STRING, VALUE_AS_CONCEPT_ID, UNIT_CONCEPT_ID, QUALIFIER_CONCEPT_ID, PROVIDER_ID,
    VISIT_OCCURRENCE_ID, VISIT_DETAIL_ID, OBSERVATION_SOURCE_VALUE, OBSERVATION_SOURCE_CONCEPT_ID, UNIT_SOURCE_VALUE, QUALIFIER_SOURCE_VALUE,
    VALUE_SOURCE_VALUE, OBSERVATION_EVENT_ID, OBS_EVENT_FIELD_CONCEPT_ID,
    ETL_MODULE, STAGE_PAT_ID, STAGE_MRN_CPI, STAGE_CSN_ID,
    'CLARITY_EDG' as SRC_TABLE, 'DX_ID' AS SRC_FIELD, STAGE_DX_ID::INTEGER AS SRC_VALUE_ID
FROM
     {{ref('STAGE_OBSERVATION_AMB_ICD')}}  AS STAGE_OBSERVATION_AMB_ICD
UNION ALL
SELECT PERSON_ID, OBSERVATION_CONCEPT_ID, OBSERVATION_DATE, OBSERVATION_DATETIME, OBSERVATION_TYPE_CONCEPT_ID,
    VALUE_AS_NUMBER, VALUE_AS_STRING, VALUE_AS_CONCEPT_ID, UNIT_CONCEPT_ID, QUALIFIER_CONCEPT_ID, PROVIDER_ID,
    VISIT_OCCURRENCE_ID, VISIT_DETAIL_ID, OBSERVATION_SOURCE_VALUE, OBSERVATION_SOURCE_CONCEPT_ID, UNIT_SOURCE_VALUE, QUALIFIER_SOURCE_VALUE,
    VALUE_SOURCE_VALUE, OBSERVATION_EVENT_ID, OBS_EVENT_FIELD_CONCEPT_ID,
    ETL_MODULE, STAGE_PAT_ID, STAGE_MRN_CPI, STAGE_CSN_ID,
    'CLARITY_EDG' as SRC_TABLE, 'DX_ID' AS SRC_FIELD, STAGE_DX_ID::INTEGER AS SRC_VALUE_ID
FROM
     {{ref('STAGE_OBSERVATION_HSP_ICD')}} AS STAGE_OBSERVATION_HSP_ICD
UNION ALL
SELECT PERSON_ID, OBSERVATION_CONCEPT_ID, OBSERVATION_DATE, OBSERVATION_DATETIME, OBSERVATION_TYPE_CONCEPT_ID,
    VALUE_AS_NUMBER, VALUE_AS_STRING, VALUE_AS_CONCEPT_ID, UNIT_CONCEPT_ID, QUALIFIER_CONCEPT_ID, PROVIDER_ID,
    VISIT_OCCURRENCE_ID, VISIT_DETAIL_ID, OBSERVATION_SOURCE_VALUE, OBSERVATION_SOURCE_CONCEPT_ID, UNIT_SOURCE_VALUE, QUALIFIER_SOURCE_VALUE,
    VALUE_SOURCE_VALUE, OBSERVATION_EVENT_ID, OBS_EVENT_FIELD_CONCEPT_ID,
    ETL_MODULE, STAGE_PAT_ID, STAGE_MRN_CPI, STAGE_CSN_ID,
    'ALLERGY' as SRC_TABLE, 'ALLERGY_ID' AS SRC_FIELD, STAGE_ALLERGY_ID::INTEGER AS SRC_VALUE_ID
FROM
     {{ref('STAGE_OBSERVATION_ALLERGY_ALL')}} AS STAGE_OBSERVATION_ALLERGY_ALL
UNION ALL
SELECT PERSON_ID, OBSERVATION_CONCEPT_ID, OBSERVATION_DATE, OBSERVATION_DATETIME, OBSERVATION_TYPE_CONCEPT_ID,
    VALUE_AS_NUMBER, VALUE_AS_STRING, VALUE_AS_CONCEPT_ID, UNIT_CONCEPT_ID, QUALIFIER_CONCEPT_ID, PROVIDER_ID,
    VISIT_OCCURRENCE_ID, VISIT_DETAIL_ID, OBSERVATION_SOURCE_VALUE, OBSERVATION_SOURCE_CONCEPT_ID, UNIT_SOURCE_VALUE, QUALIFIER_SOURCE_VALUE,
    VALUE_SOURCE_VALUE, OBSERVATION_EVENT_ID, OBS_EVENT_FIELD_CONCEPT_ID,
    ETL_MODULE, STAGE_PAT_ID, STAGE_MRN_CPI, STAGE_CSN_ID,
    'IP_FLO_GP_DATA' as SRC_TABLE, 'FLO_MEAS_ID' AS SRC_FIELD, STAGE_FLO_MEAS_ID::INTEGER AS SRC_VALUE_ID
FROM
     {{ref('STAGE_OBSERVATION_HSP_SDOH_FLOWSHEET')}} AS STAGE_OBSERVATION_HSP_SDOH_FLOWSHEET
UNION ALL
SELECT PERSON_ID, OBSERVATION_CONCEPT_ID, OBSERVATION_DATE, OBSERVATION_DATETIME, OBSERVATION_TYPE_CONCEPT_ID,
    VALUE_AS_NUMBER, VALUE_AS_STRING, VALUE_AS_CONCEPT_ID, UNIT_CONCEPT_ID, QUALIFIER_CONCEPT_ID, PROVIDER_ID,
    VISIT_OCCURRENCE_ID, VISIT_DETAIL_ID, OBSERVATION_SOURCE_VALUE, OBSERVATION_SOURCE_CONCEPT_ID, UNIT_SOURCE_VALUE, QUALIFIER_SOURCE_VALUE,
    VALUE_SOURCE_VALUE, OBSERVATION_EVENT_ID, OBS_EVENT_FIELD_CONCEPT_ID,
    ETL_MODULE, STAGE_PAT_ID, STAGE_MRN_CPI, STAGE_CSN_ID,
    'IP_FLO_GP_DATA' as SRC_TABLE, 'FLO_MEAS_ID' AS SRC_FIELD, STAGE_FLO_MEAS_ID::INTEGER AS SRC_VALUE_ID
FROM
     {{ref('STAGE_OBSERVATION_AMB_SDOH_FLOWSHEET')}} AS STAGE_OBSERVATION_AMB_SDOH_FLOWSHEET
) AS A

