  {{ config(materialized='ephemeral') }}
	SELECT DISTINCT 
	  CLARITY_POS.POS_ID,
      CLARITY_POS.POS_NAME,
      CLARITY_POS.ADDRESS_LINE_1,
      CLARITY_POS.ADDRESS_LINE_2,
      CLARITY_POS.CITY,
      CLARITY_POS.STATE_C,
      ZC_STATE_ABBR as STATE_ABBR, 
      CLARITY_POS.COUNTY_C,
      ZC_COUNTY_NAME as COUNTY,
      CLARITY_POS.ZIP,
      CLARITY_POS.POS_TYPE
      --CLARITY_POS.POS_TYPE_C
		--, ZC_POS_TYPE.NAME AS POS_TYPE_NAME
    ------------------------------------------

    FROM  {{ ref('PAT_ENC_stg')}} as PAT_ENC
    	LEFT JOIN {{ ref('CLARITY_DEP_stg')}} as CLARITY_DEP
    		ON PAT_ENC.DEPARTMENT_ID = CLARITY_DEP.DEPARTMENT_ID
    	LEFT JOIN {{ ref('CLARITY_POS_stg')}} as CLARITY_POS
    		ON CLARITY_DEP.REV_LOC_ID = CLARITY_POS.POS_ID
		LEFT JOIN {{ ref('ZC_STATE_stg')}} AS ZC_STATE
			ON CLARITY_POS.STATE_C = ZC_STATE.STATE_C
		LEFT JOIN {{ ref('ZC_COUNTY_stg')}} as ZC_COUNTY
			ON CLARITY_POS.COUNTY_C = ZC_COUNTY.COUNTY_C
--        LEFT JOIN {{ source('CLARITY','ZC_POS_TYPE')}}	  as ZC_POS_TYPE
--			ON CLARITY_POS.POS_TYPE_C = ZC_POS_TYPE.POS_TYPE_C --  (use when ZC_POS_TYPE is added to snowflake)
    -- AOU list of participants
        INNER JOIN {{ref('PATIENT_DRIVER')}} AS PATIENT_DRIVER
            ON PAT_ENC.PAT_ID = PATIENT_DRIVER.EHR_PATIENT_ID
---END cte__ENC_PHYSICIAN_POINTOFSERVICE
--
