  {{ config(materialized='ephemeral') }}
--BEGIN cte__T_DEATH_DIAGNOSIS
SELECT DISTINCT
      PATIENT_3.PAT_ID
      ,CLARITY_EDG.DX_ID
      ,CLARITY_EDG.DX_NAME
      ,replace(SNOMED_CONCEPT.CONCEPT_ID, 'SNOMED#', '') AS SNOMED_CODE
      ,SNOMED_CONCEPT.FULLY_SPECIFIED_NM

FROM   {{ ref('PATIENT_3_stg')}} AS PATIENT_3

      INNER JOIN {{ ref('CLARITY_EDG_stg')}} AS CLARITY_EDG
            ON PATIENT_3.PCOD_CAUSE_DX_ID = CLARITY_EDG.DX_ID

      LEFT JOIN {{ ref('EXTERNAL_CNCPT_MAP_stg')}} AS EXTERNAL_CNCPT_MAP
            ON CLARITY_EDG.DX_ID = EXTERNAL_CNCPT_MAP.ENTITY_VALUE_NUM

      LEFT JOIN {{ ref('CONCEPT_MAPPED_stg')}} AS CONCEPT_MAPPED
            ON EXTERNAL_CNCPT_MAP.MAPPING_ID = CONCEPT_MAPPED.MAPPING_ID

      LEFT JOIN {{ ref('SNOMED_CONCEPT_stg')}} AS SNOMED_CONCEPT
            ON CONCEPT_MAPPED.CONCEPT_ID = SNOMED_CONCEPT.CONCEPT_ID

WHERE PATIENT_3.PCOD_CAUSE_DX_ID IS NOT NULL
      AND EXTERNAL_CNCPT_MAP.ENTITY_INI = 'EDG'
      AND EXTERNAL_CNCPT_MAP.ENTITY_ITEM = 0.1
--END cte__T_DEATH_DIAGNOSIS
--
