--VISIT_DETAIL
{{ config(materialized = 'view', schema = 'OMOP') }}

SELECT DISTINCT
     VISIT_DETAIL_ID
    , PERSON_ID
    , VISIT_DETAIL_CONCEPT_ID
    , VISIT_DETAIL_START_DATE
    , VISIT_DETAIL_START_DATETIME
    , VISIT_DETAIL_END_DATE
    , VISIT_DETAIL_END_DATETIME
    , VISIT_DETAIL_TYPE_CONCEPT_ID
    , PROVIDER_ID
    , CARE_SITE_ID
    , VISIT_DETAIL_SOURCE_VALUE
    , VISIT_DETAIL_SOURCE_CONCEPT_ID
    , ADMITTED_FROM_SOURCE_VALUE
    , ADMITTED_FROM_CONCEPT_ID
    , DISCHARGED_TO_SOURCE_VALUE
    , DISCHARGED_TO_CONCEPT_ID
    , PRECEDING_VISIT_DETAIL_ID
    , PARENT_VISIT_DETAIL_ID
    , VISIT_OCCURRENCE_ID
 ------Non OMOP fields -----------
    , ETL_MODULE
    , phi_PAT_ID
    , phi_MRN_CPI
    , phi_CSN_ID

FROM
     {{ref('VISIT_DETAIL_RAW')}} AS VISIT_DETAIL

LEFT JOIN (
    SELECT CDT_ID
    FROM {{ref('QA_ERR_DBT')}} AS QA_ERR_DBT
        WHERE (STANDARD_DATA_TABLE = 'VISIT_DETAIL')
            AND (ERROR_TYPE IN ('FATAL', 'INVALID DATA'))
        ) AS EXCLUSION_RECORDS
        ON VISIT_DETAIL.VISIT_DETAIL_ID = EXCLUSION_RECORDS.CDT_ID
WHERE (EXCLUSION_RECORDS.CDT_ID IS NULL)

