{{ config(materialized='ephemeral') }}
--BEGIN cte__T_AMB_TEMP_SOURCE
    SELECT PERSON_ID
        ,PULL_CSN_ID
        ,MEASUREMENT_DATETIME
        ,VALUE_SOURCE_VALUE

    FROM {{ref('PULL_MEASUREMENT_AMB_FLOWSHEET')}} AS PULL_MEASUREMENT_AMB_FLOWSHEET
    WHERE PULL_FLO_MEAS_ID IN ('7')
--END cte__T_AMB_TEMP_SOURCE
--
