{{ config(materialized='ephemeral') }}
--BEGIN cte__T_AMB_TEMPERATURE_MERGE
    SELECT T_TEMPERATURE.PERSON_ID                                  AS PERSON_ID
        ,T_TEMPERATURE.PULL_CSN_ID                           AS PULL_CSN_ID
        ,SOURCE_TO_CONCEPT_MAP_FLOWSHEET_TEMP_SRC.TARGET_CONCEPT_ID AS TARGET_CONCEPT_ID 
        ,T_TEMPERATURE.MEASUREMENT_DATE                             AS MEASUREMENT_DATE
        ,T_TEMPERATURE.MEASUREMENT_DATETIME                         AS MEASUREMENT_DATETIME
        ,T_TEMPERATURE.VALUE_SOURCE_VALUE                           AS VALUE_SOURCE_VALUE
        ,T_TEMPERATURE.OPERATOR_CONCEPT_ID                          AS OPERATOR_CONCEPT_ID
        ,T_TEMPERATURE.VALUE_AS_NUMBER                              AS VALUE_AS_NUMBER
        ,T_TEMPERATURE.RANGE_LOW                                    AS RANGE_LOW
        ,T_TEMPERATURE.RANGE_HIGH                                   AS RANGE_HIGH
        ,SOURCE_TO_CONCEPT_MAP_FLOWSHEET_TEMP_SRC.SOURCE_CODE_DESCRIPTION   AS SOURCE_CODE_DESCRIPTION
        ,T_TEMPERATURE.PULL_FLO_MEAS_NAME                           AS PULL_FLO_MEAS_NAME
        ,T_TEMPERATURE.PULL_FLO_MEAS_ID                             AS PULL_FLO_MEAS_ID
        ,T_TEMPERATURE.PROVIDER_SOURCE_VALUE                        AS PROVIDER_SOURCE_VALUE
        ,T_TEMPERATURE.PULL_ENC_TYPE_C                              AS PULL_ENC_TYPE_C
        ,T_TEMPERATURE.UNIT_SOURCE_VALUE                            AS UNIT_SOURCE_VALUE

    FROM {{ref('T_AMB_TEMPERATURE')}} AS T_TEMPERATURE
    LEFT JOIN {{ref('T_AMB_TEMP_SOURCE')}} AS T_TEMP_SOURCE
        ON T_TEMPERATURE.PULL_CSN_ID = T_TEMP_SOURCE.PULL_CSN_ID
            AND T_TEMPERATURE.MEASUREMENT_DATETIME = T_TEMP_SOURCE.MEASUREMENT_DATETIME
    LEFT JOIN {{ ref('SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_TEMP_SRC')}} AS SOURCE_TO_CONCEPT_MAP_FLOWSHEET_TEMP_SRC
        ON COALESCE(T_TEMP_SOURCE.VALUE_SOURCE_VALUE,'99999') = SOURCE_TO_CONCEPT_MAP_FLOWSHEET_TEMP_SRC.SOURCE_CODE
--END cte__T_AMB_TEMPERATURE_MERGE
--
