--  CDM_SOURCE.sql (derived)


SELECT
    'EPIC' AS CDM_SOURCE_NAME,
    'EPIC' AS CDM_SOURCE_ABBREVIATION,
    'COREWELL HEALTH' AS CDM_HOLDER,
    'EPIC' AS SOURCE_DESCRIPTION,
    'HTTPS://DATAHANDBOOK.EPIC.COM/CLARITYDICTIONARY' AS SOURCE_DOCUMENTATION_REFERENCE,  -- E.G. LINK TO SOURCE DATA DICTIONARY
    '<YOUR_ETL_REFERENCE>' AS CDM_ETL_REFERENCE,  -- E.G. LINK TO ETL DOCUMENTATION
    DATEADD(DAY,-1,GETDATE())  AS SOURCE_RELEASE_DATE,  -- WHEN THE SOURCE DATA WAS PULLED
    GETDATE() AS CDM_RELEASE_DATE,  -- OR THE DATE OF ETL RUN
    'V5.4' AS CDM_VERSION,
    VOCABULARY.VOCABULARY_VERSION AS VOCABULARY_VERSION,
    756265 AS VOCABULARY_VERSION_CONCEPT_ID -- 'OMOP CDM VERSION 5.4.0'
FROM CARE_RES_OMOP_GEN_WKSP.OMOP.VOCABULARY AS VOCABULARY 
WHERE UPPER(VOCABULARY_ID) = 'NONE'