
    --BEGIN cte__ SOURCE_TO_CONCEPT_MAP_NOTE_CLASS
    SELECT *
    FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_CLARITY.SOURCE_TO_CONCEPT_MAP_stg
    WHERE SOURCE_VOCABULARY_ID = 'SH_NOTE_CLASS'
--END cte__ SOURCE_TO_CONCEPT_MAP_NOTE_CLASS
--