
--BEGIN cte__T_MAX_NOTE_DATE_AMB
    SELECT PULL_NOTE_ID
           -- ,PULL_NOTE_LINE
            ,MAX(PULL_CONTACT_DATE_REAL) AS MAX_CONTACT_DATE_REAL

    FROM  CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.PULL_NOTE_AMB_ALL AS  PULL_NOTE_AMB_ALL
    GROUP BY PULL_NOTE_ID--, PULL_NOTE_LINE
--END cte__T_MAX_NOTE_DATE_AMB
--