SELECT
      COUNT(SPEC_DB_MAIN.SPECIMEN_ID) AS SOURCE_FREQUENCY
      , SPEC_DB_MAIN.SPEC_SOURCE_C AS SOURCE_CODE
      , ZC_SPEC_SOURCE.NAME AS SOURCE_NAME
FROM
      SH_LAND_EPIC_CLARITY_PROD.DBO.SPEC_DB_MAIN AS SPEC_DB_MAIN
INNER JOIN SH_LAND_EPIC_CLARITY_PROD.DBO.ZC_SPEC_SOURCE AS ZC_SPEC_SOURCE 
                         ON
      SPEC_DB_MAIN.SPEC_SOURCE_C = ZC_SPEC_SOURCE.SPEC_SOURCE_C
GROUP BY
      SPEC_DB_MAIN.SPEC_SOURCE_C
      , ZC_SPEC_SOURCE.NAME
ORDER BY SOURCE_FREQUENCY DESC
/*
SELECT        COUNT(EpicClarity.dbo.SPEC_DB_MAIN.SPECIMEN_ID) AS Count, EpicClarity.dbo.SPEC_DB_MAIN.SPEC_SOURCE_C as code, 
                         EpicClarity.dbo.ZC_SPEC_SOURCE.NAME as description
FROM            EpicClarity.dbo.SPEC_DB_MAIN INNER JOIN
                         EpicClarity.dbo.ZC_SPEC_SOURCE ON EpicClarity.dbo.SPEC_DB_MAIN.SPEC_SOURCE_C = EpicClarity.dbo.ZC_SPEC_SOURCE.SPEC_SOURCE_C
GROUP BY EpicClarity.dbo.SPEC_DB_MAIN.SPEC_SOURCE_C, EpicClarity.dbo.ZC_SPEC_SOURCE.NAME */