--  sh_allergy_source.sql
--> export file name pattern: sh_allergy_source

with __dbt__cte__T_ALLERGY_CODES_OBSERVATION as 
(
	SELECT ALLERGEN_ID, ALLERGEN_NAME
	FROM SH_LAND_EPIC_CLARITY_PROD.DBO.CL_ELG  
)

SELECT 
	T_ALLERGY_CODES.ALLERGEN_ID AS SOURCE_CODE
	, T_ALLERGY_CODES.ALLERGEN_NAME as SOURCE_NAME
	, COUNT(*) AS SOURCE_FREQUENCY
	, 'Allergy to ' ||T_ALLERGY_CODES.ALLERGEN_NAME as ADDITIONAL_INFO

FROM SH_LAND_EPIC_CLARITY_PROD.DBO.PAT_ALLERGIES  AS PAT_ALLERGIES 

--      INNER JOIN OMOP.AoU_Driver  
--            ON (AoU_Driver.Epic_Pat_id = PAT_ALLERGIES.PAT_ID)
            
	INNER JOIN SH_LAND_EPIC_CLARITY_PROD.DBO.ALLERGY  AS ALLERGY  
		ON (PAT_ALLERGIES.ALLERGY_RECORD_ID = ALLERGY.ALLERGY_ID)

	LEFT JOIN __dbt__cte__T_ALLERGY_CODES_OBSERVATION AS T_ALLERGY_CODES
		ON (T_ALLERGY_CODES.ALLERGEN_ID = ALLERGY.ALLERGEN_ID)

	INNER JOIN SH_LAND_EPIC_CLARITY_PROD.DBO.PAT_ENC AS PAT_ENC  
		ON ALLERGY.ALLERGY_PAT_CSN = PAT_ENC.PAT_ENC_CSN_ID
		
GROUP BY 
      T_ALLERGY_CODES.ALLERGEN_ID 
      , T_ALLERGY_CODES.ALLERGEN_NAME 

--HAVING SOURCE_FREQUENCY > 10