SELECT
      COUNT(*) AS SOURCE_FREQUENCY
      , TO_NUMERIC(PAT_ENC.ENC_TYPE_C) AS SOURCE_CODE
      , ZC_DISP_ENC_TYPE.NAME AS SOURCE_NAME
FROM
      SH_LAND_EPIC_CLARITY_PROD.DBO.PAT_ENC AS PAT_ENC
INNER JOIN SH_LAND_EPIC_CLARITY_PROD.DBO.ZC_DISP_ENC_TYPE AS ZC_DISP_ENC_TYPE
	ON
      PAT_ENC.ENC_TYPE_C = ZC_DISP_ENC_TYPE.DISP_ENC_TYPE_C
GROUP BY
      PAT_ENC.ENC_TYPE_C
      , ZC_DISP_ENC_TYPE.NAME
ORDER BY
      COUNT(PAT_ENC.PAT_ENC_CSN_ID) DESC