/****** Script for SelectTopNRows command from SSMS  ******/
--SELECT  count([ORDER_ID]) as count
--
--	  ,order_proc.PROC_ID
--	  ,order_proc.PROC_CODE
--
--	  ,CLARITY_EAP.PROC_NAME
--
--
--  FROM [EpicClarity].[dbo].[BLOOD_ADMIN_INFO]
--  inner join ORDER_PROC on [BLOOD_ADMIN_INFO].ORDER_ID = ORDER_PROC.ORDER_PROC_ID
--              LEFT OUTER JOIN
--                EpicClarity.dbo.CLARITY_EAP                 ON
--                    ORDER_PROC.PROC_ID = CLARITY_EAP.PROC_ID
--where line = 1
--
--group by 	  order_proc.PROC_ID
--	  ,order_proc.PROC_CODE
--
--	  ,CLARITY_EAP.PROC_NAME
	  
-- Snowflake	  
SELECT ORDER_PROC.PROC_ID AS SOURCE_CODE
, CLARITY_EAP.PROC_NAME AS SOURCE_NAME
, COUNT([ORDER_ID]) AS SOURCE_FREQUENCY
FROM
    SH_LAND_EPIC_CLARITY_PROD.DBO.BLOOD_ADMIN_INFO
INNER JOIN SH_LAND_EPIC_CLARITY_PROD.DBO.ORDER_PROC ON
    BLOOD_ADMIN_INFO.ORDER_ID = ORDER_PROC.ORDER_PROC_ID
LEFT OUTER JOIN SH_LAND_EPIC_CLARITY_PROD.DBO.CLARITY_EAP ON
    ORDER_PROC.PROC_ID = CLARITY_EAP.PROC_ID
WHERE
    LINE = 1
GROUP BY
    ORDER_PROC.PROC_ID
    , ORDER_PROC.PROC_CODE
    , CLARITY_EAP.PROC_NAME  