--SELECT DISTINCT count(lda.PAT_ENC_CSN_ID) AS lda_count
--	,lda.FLO_MEAS_ID
--	,d.DISP_NAME AS FLO_MEAS_DISP_NAME
--FROM EpicClarity.dbo.IP_LDA_NOADDSINGLE(NOLOCK) AS lda
--INNER JOIN EpicClarity.dbo.IP_FLO_GP_DATA(NOLOCK) AS d
--	ON lda.FLO_MEAS_ID = d.FLO_MEAS_ID
----WHERE FLO_MEAS_NAME LIKE 'LDA%'
--GROUP BY lda.FLO_MEAS_ID
--	,d.DISP_NAME
--order by lda_count DESC

--Snowflake
SELECT DISTINCT 
    LDA.FLO_MEAS_ID AS SOURCE_CODE
    ,D.DISP_NAME AS SOURCE_NAME
    ,COUNT(LDA.PAT_ENC_CSN_ID) AS SOURCE_FREQUENCY
    ,FLO_MEAS_NAME AS ADDITIONAL_INFO
    
FROM SH_LAND_EPIC_CLARITY_PROD.DBO.IP_LDA_NOADDSINGLE AS LDA
INNER JOIN SH_LAND_EPIC_CLARITY_PROD.DBO.IP_FLO_GP_DATA AS D
    ON LDA.FLO_MEAS_ID = D.FLO_MEAS_ID
--WHERE FLO_MEAS_NAME LIKE 'LDA%'
GROUP BY LDA.FLO_MEAS_ID
    ,D.DISP_NAME
      ,FLO_MEAS_NAME