--  sh_flowsheet_unit_source.sql
--> export file name pattern: sh_flowsheet_unit_source

SELECT '[degF]'AS SOURCE_CODE, 'degree Fahrenheit' AS SOURCE_NAME, 999999999 AS SOURCE_FREQUENCY, '9289' AS ADDITIONAL_INFORMATION --temperature
UNION
SELECT '[oz_av]'AS SOURCE_CODE, 'ounce (avoirdupois)' AS SOURCE_NAME, 999999999 AS SOURCE_FREQUENCY, '9373' AS ADDITIONAL_INFORMATION --weight
UNION
SELECT '[in_us]'AS SOURCE_CODE, 'inch (US)' AS SOURCE_NAME, 999999999 AS SOURCE_FREQUENCY, '9330' AS ADDITIONAL_INFORMATION --height
UNION
SELECT 'kg/m2'AS SOURCE_CODE, 'kilogram per square meter' AS SOURCE_NAME, 999999999 AS SOURCE_FREQUENCY, '9531' AS ADDITIONAL_INFORMATION  --bmi
UNION
SELECT 'mm[Hg]'AS SOURCE_CODE, 'millimeter mercury column' AS SOURCE_NAME, 999999999 AS SOURCE_FREQUENCY, '8876' AS ADDITIONAL_INFORMATION  -- bpd,bps,bpm
UNION
SELECT '{counts}/min'AS SOURCE_CODE, 'counts per minute' AS SOURCE_NAME, 999999999 AS SOURCE_FREQUENCY, '8483' AS ADDITIONAL_INFORMATION  --heart rate, pulse, respiration
UNION
SELECT 'm2'AS SOURCE_CODE, 'square meter' AS SOURCE_NAME, 999999999 AS SOURCE_FREQUENCY, '8617' AS ADDITIONAL_INFORMATION  --BSA
UNION
--SELECT '[xxxx]'AS SOURCE_CODE, 'xxxxxxxxxxx' AS SOURCE_NAME, 999999999 AS SOURCE_FREQUENCY, 'xxxx' AS ADDITIONAL_INFORMATION  --t
--UNION
--SELECT '[xxxx]'AS SOURCE_CODE, 'xxxxxxxxxxx' AS SOURCE_NAME, 999999999 AS SOURCE_FREQUENCY, 'xxxx' AS ADDITIONAL_INFORMATION  --t
--UNION


SELECT
      IP_FLO_GP_DATA.UNITS AS SOURCE_CODE
      ,IP_FLO_GP_DATA.UNITS AS SOURCE_NAME
      , COUNT(IP_FLWSHT_MEAS.FLO_MEAS_ID) AS SOURCE_FREQUENCY
      ,NULL AS ADDITIONAL_INFORMATION

FROM
      SH_LAND_EPIC_CLARITY_PROD.DBO.IP_FLWSHT_MEAS
INNER JOIN SH_LAND_EPIC_CLARITY_PROD.DBO.IP_FLO_GP_DATA ON
      IP_FLWSHT_MEAS.FLO_MEAS_ID = IP_FLO_GP_DATA.FLO_MEAS_ID
WHERE IP_FLO_GP_DATA.UNITS IS NOT NULL
      GROUP BY IP_FLO_GP_DATA.UNITS
ORDER BY
      SOURCE_FREQUENCY DESC