--  sh_flwsht_meas_bp.sql
--> export file name pattern: sh_flwsht_meas_bps_source
--> export file name pattern: sh_flwsht_meas_bpd_source

SELECT DISTINCT 
    FS.FLO_MEAS_ID          AS  SOURCE_CODE
    ,FS.FLO_MEAS_NAME       AS  SOURCE_NAME
    ,FS.DISP_NAME           AS  DISPLAY_NAME
    ,COUNT(FSM.MEAS_VALUE)  AS  SOURCE_FREQUENCY

FROM SH_LAND_EPIC_CLARITY_PROD.DBO.IP_FLO_GP_DATA FS
    INNER JOIN SH_LAND_EPIC_CLARITY_PROD.DBO.IP_FLWSHT_MEAS FSM ON FSM.FLO_MEAS_ID = FS.FLO_MEAS_ID

WHERE --DATEDIFF(YEAR,FSM.RECORDED_TIME,GETDATE()) <= 1      AND 
      (FS.FLO_MEAS_NAME  LIKE ('%BLOOD PRESSURE%') AND FS.FLO_MEAS_NAME NOT LIKE ('%MEAN%'))
            OR 
      (FS.FLO_MEAS_NAME  LIKE ('%BP%') AND FS.FLO_MEAS_NAME NOT LIKE ('%MEAN%'))
   
GROUP BY FS.FLO_MEAS_ID
    ,FS.FLO_MEAS_NAME
    ,FS.DISP_NAME

ORDER BY SOURCE_FREQUENCY DESC;