/*SELECT
      COUNT(ORDER_MED.ORDER_MED_ID) AS count
      , ORDER_MED.MED_ROUTE_C
      , route.NAME
FROM
      epicclarity.dbo.ORDER_MED
LEFT OUTER JOIN
                         epicclarity.dbo.ZC_ADMIN_ROUTE AS route ON
      ORDER_MED.MED_ROUTE_C = route.MED_ROUTE_C
GROUP BY
      ORDER_MED.MED_ROUTE_C
      , route.NAME
*/

SELECT
      ORDER_MED.MED_ROUTE_C AS SOURCE_CODE
      , ROUTE.NAME AS SOURCE_NAME
      , COUNT(ORDER_MED.ORDER_MED_ID) AS SOURCE_FREQUENCY
FROM
      SH_LAND_EPIC_CLARITY_PROD.DBO.ORDER_MED
LEFT OUTER JOIN
     SH_LAND_EPIC_CLARITY_PROD.DBO.ZC_ADMIN_ROUTE AS ROUTE ON
      ORDER_MED.MED_ROUTE_C = ROUTE.MED_ROUTE_C
GROUP BY
      ORDER_MED.MED_ROUTE_C
      , ROUTE.NAME
ORDER BY 
      SOURCE_FREQUENCY DESC
