/*SELECT        COUNT(EpicClarity.dbo.HSC_SPEC_INFO.SPECIMEN_ID) AS Count, EpicClarity.dbo.HSC_SPEC_INFO.SPECIMEN_TYPE_C as code, 
                         EpicClarity.dbo.ZC_SPECIMEN_TYPE.NAME as description
FROM            EpicClarity.dbo.HSC_SPEC_INFO INNER JOIN
                         EpicClarity.dbo.ZC_SPECIMEN_TYPE ON EpicClarity.dbo.HSC_SPEC_INFO.SPECIMEN_TYPE_C = EpicClarity.dbo.ZC_SPECIMEN_TYPE.SPECIMEN_TYPE_C
GROUP BY EpicClarity.dbo.HSC_SPEC_INFO.SPECIMEN_TYPE_C, EpicClarity.dbo.ZC_SPECIMEN_TYPE.NAME */
-- Convert to Snowflake:
SELECT
      COUNT(HSC_SPEC_INFO.SPECIMEN_ID) AS SOURCE_FREQUENCY
      , HSC_SPEC_INFO.SPECIMEN_TYPE_C AS SOURCE_CODE
      , ZC_SPECIMEN_TYPE.NAME AS SOURCE_NAME
FROM
      SH_LAND_EPIC_CLARITY_PROD.DBO.HSC_SPEC_INFO
INNER JOIN
                         SH_LAND_EPIC_CLARITY_PROD.DBO.ZC_SPECIMEN_TYPE ON
     HSC_SPEC_INFO.SPECIMEN_TYPE_C = ZC_SPECIMEN_TYPE.SPECIMEN_TYPE_C
GROUP BY
      HSC_SPEC_INFO.SPECIMEN_TYPE_C
      ,ZC_SPECIMEN_TYPE.NAME
ORDER BY SOURCE_FREQUENCY DESC
