----  sh_xrf_inferred_unit_source.sql
--> export file name pattern: sh_xrf_inferred_unit_source

SELECT distinct
      TARGET_CONCEPT_ID
      ,CONCEPT_NAME
      ,count(MEASUREMENT_ID) AS counts
      ,UNIT_CONCEPT_ID
FROM
      SH_OMOP_DB_PROD.OMOP.SOURCE_TO_CONCEPT_MAP
      INNER JOIN
           SH_OMOP_DB_PROD.OMOP.MEASUREMENT ON SOURCE_TO_CONCEPT_MAP.TARGET_CONCEPT_ID = MEASUREMENT.MEASUREMENT_CONCEPT_ID
      INNER JOIN 
            SH_OMOP_DB_PROD.CDM.CONCEPT ON SOURCE_TO_CONCEPT_MAP.TARGET_CONCEPT_ID = CONCEPT.CONCEPT_ID
WHERE SOURCE_VOCABULARY_ID IN  (
      'SH_FLWSHT_VITALS'
      ,'SH_FLWSHT_MEAS_MISC'
      ,'SH_FLWSHT_MEAS_TEMP'
      ,'SH_FLWSHT_MEAS_BMI'
      ,'SH_FLWSHT_MEAS_BPD'
      ,'SH_FLWSHT_MEAS_BPM'
      ,'SH_FLWSHT_MEAS_BPS'
      ) --AND UNIT_SOURCE_VALUE IS NULL 
GROUP BY 
      TARGET_CONCEPT_ID
      ,CONCEPT_NAME
      ,UNIT_CONCEPT_ID
ORDER BY counts desc