/*******************************************************************************
* Query: SPECIMEN_CLARITY_ALL
* Description: Retrieves specimen information from Clarity database
* 
* Tables Used:
* - CARE_BRONZE_CLARITY_PROD.DBO.PATIENT
* - CARE_BRONZE_CLARITY_PROD.DBO.SPEC_DB_MAIN
* - CARE_BRONZE_CLARITY_PROD.DBO.ZC_SPEC_SOURCE
* - CARE_BRONZE_CLARITY_PROD.DBO.HSC_SPEC_INFO
* - CARE_BRONZE_CLARITY_PROD.DBO.ZC_SPECIMEN_TYPE
* - CARE_BRONZE_CLARITY_PROD.DBO.ZC_SPECIMEN_UNIT
* - CARE_RES_OMOP_DEV2_WKSP.OMOP.PATIENT_DRIVER
*******************************************************************************/

SELECT DISTINCT
    -- Stage Attributes
    PATIENT_DRIVER.PERSON_ID,
    COALESCE(SPEC_DTM_COLLECTED, SPEC_DTM_RECEIVED)::DATE     AS SPECIMEN_DATE,
    COALESCE(SPEC_DTM_COLLECTED, SPEC_DTM_RECEIVED)::DATETIME AS SPECIMEN_DATETIME,
    SPEC_DB_MAIN.SPECIMEN_ID                                  AS SPECIMEN_SOURCE_ID,
    HSC_SPEC_INFO.SPECIMEN_TYPE_C || ':' || 
        ZC_SPECIMEN_TYPE.NAME                                 AS SPECIMEN_SOURCE_VALUE,
    SPEC_DB_MAIN.SPEC_SOURCE_C || ':' || 
        ZC_SPEC_SOURCE.NAME                                   AS ANATOMIC_SITE_SOURCE_VALUE,
    HSC_SPEC_INFO.SPECIMEN_SIZE                              AS QUANTITY, -- Missing from HSC_SPEC_INFO

    -- Pull Attributes
    PATIENT_DRIVER.EHR_PATIENT_ID                            AS PULL_PAT_ID,
    PATIENT_DRIVER.MRN_CPI                                   AS PULL_MRN_CPI,
    HSC_SPEC_INFO.SPECIMEN_TYPE_C::VARCHAR                   AS PULL_SPECIMEN_TYPE_SOURCE_CODE,
    SPEC_DB_MAIN.SPEC_SOURCE_C::VARCHAR                      AS PULL_SPECIMEN_ANATOMIC_SITE_SOURCE_CODE

FROM CARE_BRONZE_CLARITY_PROD.DBO.PATIENT AS PATIENT

    -- Join with specimen main table
    INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.SPEC_DB_MAIN AS SPEC_DB_MAIN
        ON SPEC_DB_MAIN.SPEC_EPT_PAT_ID = PATIENT.PAT_ID

    -- Join with specimen source lookup table
    INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_SPEC_SOURCE AS ZC_SPEC_SOURCE
        ON SPEC_DB_MAIN.SPEC_SOURCE_C = ZC_SPEC_SOURCE.SPEC_SOURCE_C

    -- Join with specimen info table
    INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.HSC_SPEC_INFO AS HSC_SPEC_INFO
        ON SPEC_DB_MAIN.SPECIMEN_COL_ID = HSC_SPEC_INFO.RECORD_ID

    -- Join with specimen type lookup table
    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_SPECIMEN_TYPE AS ZC_SPECIMEN_TYPE
        ON HSC_SPEC_INFO.SPECIMEN_TYPE_C = ZC_SPECIMEN_TYPE.SPECIMEN_TYPE_C

    -- Join with specimen unit lookup table
    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_SPECIMEN_UNIT AS ZC_SPECIMEN_UNIT
        ON HSC_SPEC_INFO.SPECIMEN_UNIT_C = ZC_SPECIMEN_UNIT.SPECIMEN_UNIT_C

    -- Join with patient driver table
    INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP.PATIENT_DRIVER AS PATIENT_DRIVER
        ON PATIENT_DRIVER.EHR_PATIENT_ID = PATIENT.PAT_ID

-- Filter for records with collection or received datetime
WHERE COALESCE(SPEC_DB_MAIN.SPEC_DTM_COLLECTED, SPEC_DB_MAIN.SPEC_DTM_RECEIVED) IS NOT NULL;