--CONDITION_OCCURRENCE
{{ config(materialized = 'view', schema = 'OMOP') }}

SELECT DISTINCT
    CONDITION_OCCURRENCE_ID
    , PERSON_ID
    , CONDITION_CONCEPT_ID
    , CONDITION_START_DATE
    , CONDITION_START_DATETIME
    , CONDITION_END_DATE
    , CONDITION_END_DATETIME
    , CONDITION_TYPE_CONCEPT_ID
    , CONDITION_STATUS_CONCEPT_ID
    , STOP_REASON
    , PROVIDER_ID
    , VISIT_OCCURRENCE_ID
    , VISIT_DETAIL_ID
    , CONDITION_SOURCE_VALUE --Human readable Source Value use src_VALUE_ID below to link
    , CONDITION_SOURCE_CONCEPT_ID
    , CONDITION_STATUS_SOURCE_VALUE

 ------Non OMOP fields -----------
    , etl_MODULE
    , phi_PAT_ID
    , phi_MRN_CPI
    , phi_CSN_ID
----- Link to source
    , src_TABLE
    , src_FIELD
    , src_VALUE_ID
FROM

     {{ref('CONDITION_OCCURRENCE_RAW')}} AS CONDITION_OCCURRENCE

LEFT JOIN (
    SELECT CDT_ID
    FROM {{ref('QA_ERR_DBT')}} AS QA_ERR_DBT
        WHERE (STANDARD_DATA_TABLE = 'CONDITION_OCCURRENCE')
            AND (ERROR_TYPE IN ('FATAL', 'INVALID DATA'))
        ) AS EXCLUSION_RECORDS
        ON CONDITION_OCCURRENCE.CONDITION_OCCURRENCE_ID = EXCLUSION_RECORDS.CDT_ID
WHERE (EXCLUSION_RECORDS.CDT_ID IS NULL)

