
-- STAGE_NOTE_HSP
/*
Purpose: Extract and transform hospital notes data into OMOP CDM format
Source Tables: 
- PULL_NOTE_HOSP_ALL
- T_NOTE_DATE_HSP_MAX
- SOURCE_TO_CONCEPT_MAP
- VISIT_OCCURRENCE_RAW
- PROVIDER_RAW
*/

-- CTE to get note class mappings
WITH __dbt__cte__SOURCE_TO_CONCEPT_MAP_NOTE_CLASS AS (
    SELECT *
    FROM CARE_RES_OMOP_GEN_WKSP.OMOP.SOURCE_TO_CONCEPT_MAP
    WHERE SOURCE_VOCABULARY_ID = 'SH_NOTE_CLASS'
)

-- Main query to transform hospital notes
SELECT DISTINCT
    -- Core OMOP CDM fields
    PULL_NOTE_HOSP_ALL.PERSON_ID AS PERSON_ID,
    NOTE_DATE AS NOTE_DATE,
    NOTE_DATETIME AS NOTE_DATETIME,
    32817 AS NOTE_TYPE_CONCEPT_ID, -- Standard note type
    COALESCE(SOURCE_TO_CONCEPT_MAP_NOTE_CLASS.TARGET_CONCEPT_ID, 0) AS NOTE_CLASS_CONCEPT_ID,
    NOTE_TITLE AS NOTE_TITLE,
    
    -- Note text placeholder for PHI compliance
    'NO_TEXT' AS NOTE_TEXT, -- Actual note text excluded due to PHI concerns
    
    32678 AS ENCODING_CONCEPT_ID, -- UTF-8 encoding
    4180186 AS LANGUAGE_CONCEPT_ID, -- Language concept
    PROVIDER.PROVIDER_ID AS PROVIDER_ID,
    VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID AS VISIT_OCCURRENCE_ID,
    NULL AS VISIT_DETAIL_ID,
    NOTE_SOURCE_VALUE AS NOTE_SOURCE_VALUE,
    NULL AS NOTE_EVENT_ID,
    NULL AS NOTE_EVENT_FIELD_CONCEPT_ID,
    
    -- Custom fields for tracking and debugging
    'NOTE_HSP' AS ETL_MODULE,
    PULL_NOTE_HOSP_ALL.PULL_IP_NOTE_TYPE_C AS STAGE_IP_NOTE_TYPE_C,
    PULL_NOTE_HOSP_ALL.PULL_NOTE_ID AS STAGE_NOTE_ID,
    VISIT_OCCURRENCE.phi_PAT_ID AS STAGE_PAT_ID,
    VISIT_OCCURRENCE.phi_MRN_CPI AS STAGE_MRN_CPI,
    VISIT_OCCURRENCE.phi_CSN_ID AS STAGE_CSN_ID

FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.PULL_NOTE_HOSP_ALL AS PULL_NOTE_HOSP_ALL

    -- Join to get maximum note dates
    INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP_STAGE.T_NOTE_DATE_HSP_MAX AS T_MAX_NOTE_DATE
        ON PULL_NOTE_HOSP_ALL.PULL_NOTE_ID = T_MAX_NOTE_DATE.PULL_NOTE_ID

    -- Join to get note class mappings
    LEFT JOIN __dbt__cte__SOURCE_TO_CONCEPT_MAP_NOTE_CLASS AS SOURCE_TO_CONCEPT_MAP_NOTE_CLASS
        ON PULL_IP_NOTE_TYPE_C || PULL_AMB_NOTE_YN = SOURCE_TO_CONCEPT_MAP_NOTE_CLASS.SOURCE_CODE

    -- Join to get visit information
    INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP.VISIT_OCCURRENCE_RAW AS VISIT_OCCURRENCE
        ON PULL_NOTE_HOSP_ALL.PULL_CSN_ID = VISIT_OCCURRENCE.phi_CSN_ID

    -- Join to get provider information
    LEFT JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP.PROVIDER_RAW AS PROVIDER
        ON PULL_NOTE_HOSP_ALL.PROVIDER_SOURCE_VALUE = PROVIDER.PROVIDER_SOURCE_VALUE

WHERE PULL_NOTE_HOSP_ALL.NOTE_DATE IS NOT NULL;