/*
Purpose: Extract and transform blood pressure diastolic measurements from hospital flowsheets
Source: PULL_MEASUREMENT_HOSP_FLOWSHEET
Target: MEASUREMENT table (OMOP CDM)
*/

-- CTE for Blood Pressure Diastolic measurement concepts
WITH __dbt__cte__SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_BPD AS (
    SELECT *
    FROM CARE_RES_OMOP_GEN_WKSP.OMOP.SOURCE_TO_CONCEPT_MAP
    WHERE SOURCE_VOCABULARY_ID = 'SH_FLWSHT_MEAS_BPD'
),

-- CTE for measurement units
__dbt__cte__SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_UNITS AS (
    SELECT *
    FROM CARE_RES_OMOP_GEN_WKSP.OMOP.SOURCE_TO_CONCEPT_MAP
    WHERE SOURCE_VOCABULARY_ID = 'SH_FLOWSHT_MEAS_UNIT'
)

-- Main query to transform flowsheet measurements
SELECT DISTINCT
    -- Standard OMOP CDM fields
    PULL_MEASUREMENT_HOSP_FLOWSHEET.PERSON_ID AS PERSON_ID,
    COALESCE(SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS.TARGET_CONCEPT_ID, 0) AS MEASUREMENT_CONCEPT_ID,
    PULL_MEASUREMENT_HOSP_FLOWSHEET.MEASUREMENT_DATE AS MEASUREMENT_DATE,
    PULL_MEASUREMENT_HOSP_FLOWSHEET.MEASUREMENT_DATETIME AS MEASUREMENT_DATETIME,
    32817 AS MEASUREMENT_TYPE_CONCEPT_ID, -- EHR
    PULL_MEASUREMENT_HOSP_FLOWSHEET.OPERATOR_CONCEPT_ID AS OPERATOR_CONCEPT_ID,
    SUBSTRING(VALUE_AS_NUMBER, CHARINDEX('/', VALUE_AS_NUMBER) + 1, 2)::FLOAT AS VALUE_AS_NUMBER, -- DIASTOLIC
    NULL AS VALUE_AS_CONCEPT_ID,
    COALESCE(SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_UNITS.TARGET_CONCEPT_ID, 8876) AS UNIT_CONCEPT_ID, -- mm[Hg]
    PULL_MEASUREMENT_HOSP_FLOWSHEET.RANGE_LOW AS RANGE_LOW,
    PULL_MEASUREMENT_HOSP_FLOWSHEET.RANGE_HIGH AS RANGE_HIGH,
    PROVIDER.PROVIDER_ID AS PROVIDER_ID,
    VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID AS VISIT_OCCURRENCE_ID,
    NULL AS VISIT_DETAIL_ID,
    PULL_FLO_MEAS_ID::VARCHAR ||':'|| PULL_FLO_MEAS_NAME AS MEASUREMENT_SOURCE_VALUE,
    NULL AS MEASUREMENT_SOURCE_CONCEPT_ID,
    COALESCE(SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_UNITS.SOURCE_CODE_DESCRIPTION, 'mm[Hg]') AS UNIT_SOURCE_VALUE,
    NULL AS UNIT_SOURCE_CONCEPT_ID,
    PULL_MEASUREMENT_HOSP_FLOWSHEET.VALUE_SOURCE_VALUE AS VALUE_SOURCE_VALUE,
    NULL AS MEASUREMENT_EVENT_ID,
    NULL AS MEAS_EVENT_FIELD_CONCEPT_ID,

    -- Custom non-OMOP fields for tracking
    'MEASUREMENT_HOSP_FLOWSHEET_BPD' AS ETL_MODULE,
    VISIT_OCCURRENCE.phi_PAT_ID AS STAGE_PAT_ID,
    VISIT_OCCURRENCE.phi_MRN_CPI AS STAGE_MRN_CPI,
    VISIT_OCCURRENCE.phi_CSN_ID AS STAGE_CSN_ID,
    PULL_FLO_MEAS_ID AS STAGE_FLO_MEAS_ID,
    PULL_FLO_MEAS_NAME AS STAGE_FLO_MEAS_NAME

FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.PULL_MEASUREMENT_HOSP_FLOWSHEET AS PULL_MEASUREMENT_HOSP_FLOWSHEET

    -- Join to get measurement concepts
    INNER JOIN __dbt__cte__SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_BPD AS SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS
        ON PULL_MEASUREMENT_HOSP_FLOWSHEET.PULL_FLO_MEAS_ID = SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS.SOURCE_CODE

    -- Join to get unit concepts
    LEFT JOIN __dbt__cte__SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_UNITS AS SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_UNITS
        ON PULL_MEASUREMENT_HOSP_FLOWSHEET.UNIT_SOURCE_VALUE = SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_UNITS.SOURCE_CODE

    -- Join to get visit information
    INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP.VISIT_OCCURRENCE_RAW AS VISIT_OCCURRENCE
        ON PULL_MEASUREMENT_HOSP_FLOWSHEET.PULL_CSN_ID = VISIT_OCCURRENCE.phi_CSN_ID

    -- Join to get provider information
    LEFT JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP.PROVIDER_RAW AS PROVIDER
        ON PULL_MEASUREMENT_HOSP_FLOWSHEET.PROVIDER_SOURCE_VALUE = PROVIDER.PROVIDER_SOURCE_VALUE;