{#-- {{ config(materialized = 'view', schema = 'OMOP_STAGE') }}#}
--
--STAGE_VISIT_OCCURRENCE_AMB
SELECT DISTINCT
	PULL_VISIT_OCCURRENCE_AMB.PERSON_ID ,
	COALESCE(SOURCE_TO_CONCEPT_MAP_AMB_VISIT.TARGET_CONCEPT_ID,	0) 		AS VISIT_CONCEPT_ID ,
	PULL_VISIT_OCCURRENCE_AMB.VISIT_START_DATE 							AS VISIT_START_DATE ,
	PULL_VISIT_OCCURRENCE_AMB.VISIT_START_DATETIME						AS VISIT_START_DATETIME ,
	PULL_VISIT_OCCURRENCE_AMB.VISIT_END_DATE							AS VISIT_END_DATE ,
	PULL_VISIT_OCCURRENCE_AMB.VISIT_END_DATETIME 						AS VISIT_END_DATETIME ,
	32817 																AS VISIT_TYPE_CONCEPT_ID,
	PROVIDER.PROVIDER_ID 												AS PROVIDER_ID ,
	COALESCE(CARE_SITE.CARE_SITE_ID,1) 									AS CARE_SITE_ID ,
	PULL_VISIT_OCCURRENCE_AMB.VISIT_SOURCE_VALUE						AS VISIT_SOURCE_VALUE , --NOTE- in current query, this is VISTI_SOURCE_CSN (and in final query)
	NULL 																	AS VISIT_SOURCE_CONCEPT_ID ,
	NULL 																	AS ADMITTED_FROM_CONCEPT_ID ,
	NULL 																AS ADMITTED_FROM_SOURCE_VALUE ,
	NULL 																	AS DISCHARGED_TO_CONCEPT_ID,
	NULL 																AS DISCHARGED_TO_SOURCE_VALUE ,
	NULL 																AS PRECEDING_VISIT_OCCURRENCE_ID ,
	-------- Non-OMOP Fields ------------
	 'STAGE_VISIT_OCCURRENCE_AMB' 										AS ETL_MODULE,
	 PULL_VISIT_OCCURRENCE_AMB.PULL_PAT_ID                      		AS STAGE_PAT_ID,
     PULL_VISIT_OCCURRENCE_AMB.PULL_MRN_CPI                           	AS STAGE_MRN_CPI,
	 PULL_VISIT_OCCURRENCE_AMB.PULL_CSN_ID								AS STAGE_CSN_ID

FROM
	 {{ref('PULL_VISIT_OCCURRENCE_AMB')}} AS PULL_VISIT_OCCURRENCE_AMB

LEFT JOIN  {{ref('CARE_SITE_RAW')}} AS CARE_SITE ON
	PULL_VISIT_OCCURRENCE_AMB.PULL_CARE_SITE_ID = CARE_SITE.CARE_SITE_ID
LEFT JOIN  {{ref('PROVIDER_RAW')}} AS PROVIDER ON
	PULL_VISIT_OCCURRENCE_AMB.PULL_PROVIDER_SOURCE_VALUE = PROVIDER.PROVIDER_SOURCE_VALUE
--VISIT DATE CANNOT BE >30 DAYS AFTER DEATH_DATE
LEFT JOIN {{ref('DEATH_RAW')}} AS DEATH ON
	PULL_VISIT_OCCURRENCE_AMB.PERSON_ID = DEATH.PERSON_ID
INNER JOIN  {{ ref('SOURCE_TO_CONCEPT_MAP_AMB_VISIT')}} AS SOURCE_TO_CONCEPT_MAP_AMB_VISIT ON
	 PULL_VISIT_OCCURRENCE_AMB.PULL_ENC_TYPE_C = SOURCE_TO_CONCEPT_MAP_AMB_VISIT.SOURCE_CODE

-- FUTURE VISITS REMOVED
WHERE PULL_VISIT_OCCURRENCE_AMB.VISIT_START_DATE < COALESCE(DATEADD(DAY, 30, DEATH.DEATH_DATE), GETDATE())
