
--PULL_PROVIDER_ALL
{#{#-- {{ config(materialized = 'view', schema = 'OMOP_PULL') }}#}
SELECT DISTINCT
-- ***STAGE ATTRIBUTES***
-- fields used for the Stage
    CLARITY_SER.PROV_ID                                 AS PROVIDER_ID
    ,CLARITY_SER.PROV_NAME                              AS PROVIDER_NAME
    ,CLARITY_SER_2.NPI                                  AS NPI
    ,CLARITY_SER.DEA_NUMBER                             AS DEA
    ,YEAR(CLARITY_SER.BIRTH_DATE)                       AS YEAR_OF_BIRTH
    ,CAST(SEX_C AS VARCHAR(1)) || ':' || ZC_SEX_NAME    AS GENDER_SOURCE_VALUE
    ,COALESCE(ZC_SPECIALTY_NAME, CLARITY_SER.PROV_TYPE) AS SPECIALTY_SOURCE_VALUE

-- ***PULL attributes***
-- field names pulled from the source for verification purposes. May be duplicated above.
    , TRY_TO_NUMBER (CLARITY_SER.PROV_ID, '9999999999' ,38,0) AS TRYTONUMBER
    , ZC_SPECIALTY.SPECIALTY_C
    , ZC_SPECIALTY_NAME
    , COALESCE(CLARITY_DEP_SER_2.REV_LOC_ID, CLARITY_DEP_EMP.REV_LOC_ID) AS REV_LOC_ID
    , CLARITY_SER.BIRTH_DATE
    , CLARITY_SER.PROV_TYPE
    , CLARITY_SER.SEX_C
    , ZC_SEX_NAME                                       AS ZC_SEX_NAME

FROM {{ ref('CLARITY_SER_stg')}} AS CLARITY_SER

    LEFT JOIN {{ ref('ZC_SEX_stg')}} AS ZC_SEX
        ON ZC_SEX.RCPT_MEM_SEX_C = CLARITY_SER.SEX_C

    LEFT JOIN {{ ref('CLARITY_SER_2_stg')}} AS CLARITY_SER_2
        ON CLARITY_SER.PROV_ID = CLARITY_SER_2.PROV_ID

    LEFT JOIN {{ ref('CLARITY_DEP_stg')}} AS CLARITY_DEP_SER_2
        ON CLARITY_SER_2.PRIMARY_DEPT_ID = CLARITY_DEP_SER_2.DEPARTMENT_ID

    LEFT OUTER JOIN {{ ref('D_PROV_PRIMARY_HIERARCHY_stg')}} AS D_PROV_PRIMARY_HIERARCHY
        ON CLARITY_SER.PROV_ID = D_PROV_PRIMARY_HIERARCHY.PROV_ID

    LEFT OUTER JOIN {{ ref('ZC_SPECIALTY_stg')}} AS ZC_SPECIALTY
            ON D_PROV_PRIMARY_HIERARCHY.SPECIALTY_C = ZC_SPECIALTY.SPECIALTY_C

    LEFT JOIN {{ ref('CLARITY_EMP_stg')}} AS CLARITY_EMP
        ON CLARITY_SER.PROV_ID = CLARITY_EMP.PROV_ID

    LEFT JOIN {{ ref('CLARITY_DEP_stg')}} AS CLARITY_DEP_EMP
        ON CLARITY_EMP.LGIN_DEPARTMENT_ID = CLARITY_DEP_EMP.DEPARTMENT_ID

WHERE CLARITY_SER.PROV_TYPE not in ('RESOURCE','LABORATORY')
    AND TRY_TO_NUMBER(CLARITY_SER.PROV_ID, '9999999999',38,0) IS NOT NULL
    AND LEFT(CLARITY_SER.PROV_ID, 1) <> '0' --GETS RID OF DUPLICATE CAUSED BY LEADING 0 IN THE PROV_ID OF ONE PROVIDER

QUALIFY 1 = ROW_NUMBER() OVER (
    PARTITION BY CLARITY_SER.PROV_ID
    ORDER BY CLARITY_SER.PROV_NAME)
