/*
Description: This query creates a staged specimen dataset by combining specimen information 
with mapped concept IDs for specimen types and anatomic sites.

CTEs:
1. SOURCE_TO_CONCEPT_MAP_SPECIMEN - Filters specimen-related concept mappings
2. SOURCE_TO_CONCEPT_MAP_ANATOMIC_SITE - Filters anatomic site-related concept mappings
*/

-- CTE for specimen concept mappings
WITH __dbt__cte__SOURCE_TO_CONCEPT_MAP_SPECIMEN AS (
    SELECT *
    FROM CARE_RES_OMOP_GEN_WKSP.OMOP.SOURCE_TO_CONCEPT_MAP
    WHERE SOURCE_VOCABULARY_ID = 'SH_SPECIMEN'
),

-- CTE for anatomic site concept mappings
__dbt__cte__SOURCE_TO_CONCEPT_MAP_ANATOMIC_SITE AS (
    SELECT *
    FROM CARE_RES_OMOP_GEN_WKSP.OMOP.SOURCE_TO_CONCEPT_MAP
    WHERE SOURCE_VOCABULARY_ID = 'SH_ANATOMIC_SITE'
)

-- Main query to create staged specimen data
SELECT DISTINCT
    -- OMOP Standard Fields
    PULL_SPECIMEN_ALL.PERSON_ID AS PERSON_ID,
    COALESCE(SOURCE_TO_CONCEPT_MAP_SPECIMEN.TARGET_CONCEPT_ID, 0) AS SPECIMEN_CONCEPT_ID,
    0 AS SPECIMEN_TYPE_CONCEPT_ID,
    PULL_SPECIMEN_ALL.SPECIMEN_DATE AS SPECIMEN_DATE,
    PULL_SPECIMEN_ALL.SPECIMEN_DATETIME AS SPECIMEN_DATETIME,
    PULL_SPECIMEN_ALL.QUANTITY AS QUANTITY,                        -- Missing from HSC_SPEC_INFO
    NULL AS UNIT_CONCEPT_ID,                                      -- Missing from HSC_SPEC_INFO
    COALESCE(SOURCE_TO_CONCEPT_MAP_ANATOMIC_SITE.TARGET_CONCEPT_ID, 0) AS ANATOMIC_SITE_CONCEPT_ID,
    NULL AS DISEASE_STATUS_CONCEPT_ID,                            -- Unknown
    PULL_SPECIMEN_ALL.SPECIMEN_SOURCE_ID AS SPECIMEN_SOURCE_ID,
    PULL_SPECIMEN_ALL.SPECIMEN_SOURCE_VALUE AS SPECIMEN_SOURCE_VALUE,
    NULL AS UNIT_SOURCE_VALUE,                                    -- Missing from HSC_SPEC_INFO
    PULL_SPECIMEN_ALL.ANATOMIC_SITE_SOURCE_VALUE AS ANATOMIC_SITE_SOURCE_VALUE,
    NULL AS DISEASE_STATUS_SOURCE_VALUE,                          -- Unknown

    -- Non-OMOP Fields
    'SPECIMEN_ALL' AS STAGE_ETL_MODULE,
    PULL_PAT_ID AS STAGE_PAT_ID,
    PULL_MRN_CPI AS STAGE_MRN_CPI,
    PULL_SPECIMEN_TYPE_SOURCE_CODE AS STAGE_SPECIMEN_TYPE_SOURCE_CODE,
    PULL_SPECIMEN_ANATOMIC_SITE_SOURCE_CODE AS STAGE_SPECIMEN_ANATOMIC_SITE_SOURCE_CODE

FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.PULL_SPECIMEN_ALL AS PULL_SPECIMEN_ALL

-- Join with concept mappings
LEFT JOIN __dbt__cte__SOURCE_TO_CONCEPT_MAP_SPECIMEN AS SOURCE_TO_CONCEPT_MAP_SPECIMEN
    ON PULL_SPECIMEN_ALL.PULL_SPECIMEN_TYPE_SOURCE_CODE = SOURCE_TO_CONCEPT_MAP_SPECIMEN.SOURCE_CODE

LEFT JOIN __dbt__cte__SOURCE_TO_CONCEPT_MAP_ANATOMIC_SITE AS SOURCE_TO_CONCEPT_MAP_ANATOMIC_SITE
    ON PULL_SPECIMEN_ALL.PULL_SPECIMEN_ANATOMIC_SITE_SOURCE_CODE::VARCHAR = SOURCE_TO_CONCEPT_MAP_ANATOMIC_SITE.SOURCE_CODE;