------ QA_OBSERVATION_NULLCONCEPT_DETAIL
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH NULLCONCEPT_DETAIL
AS (
	SELECT 'OBSERVATION_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, OBSERVATION_ID AS CDT_ID
	FROM {{ref('OBSERVATION_RAW')}} AS OBSERVATION
	WHERE (OBSERVATION_CONCEPT_ID IS NULL)

	UNION ALL

	SELECT 'OBSERVATION_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, OBSERVATION_ID AS CDT_ID
	FROM {{ref('OBSERVATION_RAW')}} AS OBSERVATION
	WHERE (OBSERVATION_TYPE_CONCEPT_ID IS NULL)

	-- UNION ALL

	-- SELECT 'VALUE_AS_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
	-- 	, OBSERVATION_ID AS CDT_ID
	-- FROM {{ref('OBSERVATION_RAW')}} AS OBSERVATION
	-- WHERE (VALUE_AS_CONCEPT_ID IS NULL)

	-- UNION ALL

	-- SELECT 'QUALIFIER_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
	-- 	, OBSERVATION_ID AS CDT_ID
	-- FROM {{ref('OBSERVATION_RAW')}} AS OBSERVATION
	-- WHERE (QUALIFIER_CONCEPT_ID IS NULL)

	-- UNION ALL

	-- SELECT 'UNIT_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
	-- 	, OBSERVATION_ID AS CDT_ID
	-- FROM {{ref('OBSERVATION_RAW')}} AS OBSERVATION
	-- WHERE (UNIT_CONCEPT_ID IS NULL)

	-- UNION ALL

	-- SELECT 'OBSERVATION_SOURCE_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
	-- 	, OBSERVATION_ID AS CDT_ID
	-- FROM {{ref('OBSERVATION_RAW')}} AS OBSERVATION
	-- WHERE (OBSERVATION_SOURCE_CONCEPT_ID IS NULL)
)

SELECT CAST( GETDATE() AS DATE) AS RUN_DATE
	,'OBSERVATION' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NULLCONCEPT_DETAIL
  WHERE ERROR_TYPE <>'EXPECTED'

