--QA_OBSERVATION_POS_DUP_PROVIDER_ID_COUNT
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH TMP_DUPES AS (
SELECT PERSON_ID
	,OBSERVATION_CONCEPT_ID
	-- ,OBSERVATION_DATE
	,OBSERVATION_DATETIME
	-- ,OBSERVATION_TYPE_CONCEPT_ID
	,VALUE_AS_NUMBER
	,VALUE_AS_STRING
	,VALUE_AS_CONCEPT_ID
	,QUALIFIER_CONCEPT_ID
	,UNIT_CONCEPT_ID
	-- ,PROVIDER_ID
	,VISIT_OCCURRENCE_ID
	,OBSERVATION_SOURCE_VALUE
	,OBSERVATION_SOURCE_CONCEPT_ID
	,UNIT_SOURCE_VALUE
	,QUALIFIER_SOURCE_VALUE
	,COUNT(*) AS CNT

FROM {{ref('OBSERVATION_RAW')}} AS T1
WHERE T1.OBSERVATION_CONCEPT_ID <> 0
	AND T1.OBSERVATION_CONCEPT_ID IS NOT NULL
	AND T1.PERSON_ID <> 0
	AND T1.PERSON_ID IS NOT NULL
GROUP BY PERSON_ID
	,OBSERVATION_CONCEPT_ID
	-- ,OBSERVATION_DATE
	,OBSERVATION_DATETIME
	-- ,OBSERVATION_TYPE_CONCEPT_ID
	,VALUE_AS_NUMBER
	,VALUE_AS_STRING
	,VALUE_AS_CONCEPT_ID
	,QUALIFIER_CONCEPT_ID
	,UNIT_CONCEPT_ID
	-- ,PROVIDER_ID
	,VISIT_OCCURRENCE_ID
	,OBSERVATION_SOURCE_VALUE
	,OBSERVATION_SOURCE_CONCEPT_ID
	,UNIT_SOURCE_VALUE
	,QUALIFIER_SOURCE_VALUE
HAVING COUNT(*) > 1
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	, 'OBSERVATION' AS STANDARD_DATA_TABLE
	, 'POSSIBLE_DUPLICATE' AS QA_METRIC
	, 'PROVIDER_ID'  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) IS NOT NULL THEN 'FOLLOW_UP' ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('OBSERVATION_RAW')}}) AS TOTAL_RECORDS
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('OBSERVATION')}}) AS TOTAL_RECORDS_CLEAN
FROM TMP_DUPES
