--PULL_CONDITION_OCCURRENCE_HOSP_DISCH_SNO
{#-- {{ config(materialized = 'view', schema = 'OMOP_PULL') }}#}


SELECT DISTINCT
-- ***STAGE ATTRIBUTES***
-- fields used for the Stage
    PULL_VISIT_OCCURRENCE_HSP.PERSON_ID                         AS PERSON_ID
	,PULL_VISIT_OCCURRENCE_HSP.VISIT_START_DATE 		        AS CONDITION_START_DATE
	,PULL_VISIT_OCCURRENCE_HSP.VISIT_START_DATETIME 			AS CONDITION_START_DATETIME
	,PULL_VISIT_OCCURRENCE_HSP.VISIT_END_DATE  		            AS CONDITION_END_DATE
	,PULL_VISIT_OCCURRENCE_HSP.VISIT_END_DATETIME 				AS CONDITION_END_DATETIME
	,CASE WHEN PULL_DISCHARGE_SOURCE_CODE = 20
		    THEN 'EXPIRED'
		ELSE 'DISCHARGED'
		END 												    AS STOP_REASON
    ,CASE WHEN HSP_ACCT_DX_LIST.LINE = 1
            THEN 'PRIMARY_DISCHARGE_DX'
        WHEN HSP_ACCT_DX_LIST.FINAL_DX_SOI_C IN (3, 4)
            THEN 'SECONDARY_DISCHARGE_DX'
        ELSE 'DISCHARGE_DX'
        END						                                AS CONDITION_STATUS_SOURCE_VALUE
    ,PULL_PROVIDER_SOURCE_VALUE                                 AS PROVIDER_SOURCE_VALUE

-- ***ADDITIONAL ATTRIBUTES***
-- Non-OMOP fields used for the Stage
    ,PULL_VISIT_OCCURRENCE_HSP.PULL_CSN_ID                       AS PULL_CSN_ID
    ,PULL_VISIT_OCCURRENCE_HSP.VISIT_START_DATE                  AS PULL_VISIT_DATE
    ,T_SNO_CODE.DX_ID                                            AS PULL_DX_ID
    ,T_SNO_CODE.DX_NAME                                          AS PULL_DX_NAME
    ,T_SNO_CODE.CURRENT_ICD9_LIST                                AS PULL_CURRENT_ICD9_LIST
    ,T_SNO_CODE.CURRENT_ICD10_LIST                               AS PULL_CURRENT_ICD10_LIST
    ,T_SNO_CODE.SNOMED_CODE                                      AS PULL_SNOMED_CODE

FROM  {{ ref('HSP_ACCT_DX_LIST_stg')}} AS HSP_ACCT_DX_LIST

    INNER JOIN   {{ ref('PULL_VISIT_OCCURRENCE_HSP')}} AS PULL_VISIT_OCCURRENCE_HSP
        ON HSP_ACCT_DX_LIST.HSP_ACCOUNT_ID = PULL_VISIT_OCCURRENCE_HSP.PULL_HSP_ACCOUNT_ID

    LEFT JOIN   {{ ref('HSP_ATND_PROV_stg')}} AS HSP_ATND_PROV
        ON PULL_VISIT_OCCURRENCE_HSP.PULL_CSN_ID = HSP_ATND_PROV.PAT_ENC_CSN_ID
            AND VISIT_START_DATETIME BETWEEN ATTEND_FROM_DATE
                AND COALESCE(ATTEND_TO_DATE, GETDATE())

    LEFT JOIN  {{ref('T_SNO_CODE')}} AS T_SNO_CODE
        ON HSP_ACCT_DX_LIST.DX_ID = T_SNO_CODE.DX_ID

