--PULL_CONDITION_OCCURRENCE_HOSP_FIN_SNO
{#-- {{ config(materialized = 'view', schema = 'OMOP_PULL') }}#}


SELECT DISTINCT
-- ***STAGE ATTRIBUTES***
-- fields used for the Stage
    PULL_VISIT_OCCURRENCE_HSP.PERSON_ID                         AS PERSON_ID
	,PULL_VISIT_OCCURRENCE_HSP.VISIT_START_DATE 		        AS CONDITION_START_DATE
	,PULL_VISIT_OCCURRENCE_HSP.VISIT_START_DATETIME 			AS CONDITION_START_DATETIME
	,PULL_VISIT_OCCURRENCE_HSP.VISIT_END_DATE  		            AS CONDITION_END_DATE
	,PULL_VISIT_OCCURRENCE_HSP.VISIT_END_DATETIME 				AS CONDITION_END_DATETIME
	,CASE WHEN PULL_DISCHARGE_SOURCE_CODE = 20
			THEN 'EXPIRED'
		    ELSE 'DISCHARGED'
		    END 												AS STOP_REASON
	,'FINAL DIAGNOSIS' 											AS CONDITION_STATUS_SOURCE_VALUE
    ,PULL_PROVIDER_SOURCE_VALUE                                 AS PROVIDER_SOURCE_VALUE

-- ***ADDITIONAL ATTRIBUTES***
-- Non-OMOP fields used for the Stage
    ,PULL_VISIT_OCCURRENCE_HSP.PULL_CSN_ID                       AS PULL_CSN_ID
    ,PULL_VISIT_OCCURRENCE_HSP.VISIT_START_DATE                  AS PULL_VISIT_DATE
    ,T_SNO_CODE.DX_ID                                            AS PULL_DX_ID
    ,T_SNO_CODE.DX_NAME                                          AS PULL_DX_NAME
    ,T_SNO_CODE.CURRENT_ICD9_LIST                                AS PULL_CURRENT_ICD9_LIST
    ,T_SNO_CODE.CURRENT_ICD10_LIST                               AS PULL_CURRENT_ICD10_LIST
    ,T_SNO_CODE.SNOMED_CODE                                      AS PULL_SNOMED_CODE

-- ***PULL attributes***
-- field names pulled from the source for verification purposes. May be duplicated above.
-- 	,PULL_VISIT_OCCURRENCE_HSP.EHR_PATIENT_ID
--     ,PULL_VISIT_OCCURRENCE_HSP.PAT_ID
--     ,PAT_ENC_DX.CONTACT_DATE
--     ,PULL_VISIT_OCCURRENCE_HSP.PAT_ENC_CSN_ID
--     ,PULL_VISIT_OCCURRENCE_HSP.HOSP_ADMSN_TIME
--     ,PULL_VISIT_OCCURRENCE_HSP.HOSP_DISCH_TIME
-- --    ,HSP_ATND_PROV.ATTEND_FROM_DATE
-- --    ,HSP_ATND_PROV.ATTEND_TO_DATE
--     ,PAT_ENC_DX.PRIMARY_DX_YN
--     ,PULL_VISIT_OCCURRENCE_HSP.DISCH_DISP_C
-- --    ,HSP_ATND_PROV.PROV_ID
-- --    ,PULL_VISIT_OCCURRENCE_HSP.ATTENDING_PROV_ID
--     ,COALESCE(PULL_VISIT_OCCURRENCE_HSP.ATTENDING_PROV_ID,HSP_ATND_PROV.PROV_ID) AS  CALC_ATTEND_PROV_ID

FROM  {{ ref('PAT_ENC_DX_stg')}} AS PAT_ENC_DX

    INNER JOIN   {{ ref('PULL_VISIT_OCCURRENCE_HSP')}} AS PULL_VISIT_OCCURRENCE_HSP
        ON PAT_ENC_DX.PAT_ENC_CSN_ID = PULL_VISIT_OCCURRENCE_HSP.PULL_CSN_ID

    LEFT JOIN   {{ ref('HSP_ATND_PROV_stg')}} AS HSP_ATND_PROV
        ON PULL_VISIT_OCCURRENCE_HSP.PULL_CSN_ID = HSP_ATND_PROV.PAT_ENC_CSN_ID
            AND VISIT_START_DATETIME BETWEEN ATTEND_FROM_DATE
                AND COALESCE(ATTEND_TO_DATE, GETDATE())

    LEFT JOIN  {{ref('T_SNO_CODE')}} AS T_SNO_CODE
        ON PAT_ENC_DX.DX_ID = T_SNO_CODE.DX_ID

