/*******************************************************************************
* Script Name: PULL_OBSERVATION_ALL_ALLERGY
* Description: Retrieves allergy observations for patients, excluding 'No Known Allergies'
* 
* Tables Used:
*   - CARE_BRONZE_CLARITY_PROD.DBO.PAT_ALLERGIES
*   - CARE_BRONZE_CLARITY_PROD.DBO.ALLERGY
*   - CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.T_ALLERGY_CODES_OBSERVATION
*   - CARE_BRONZE_CLARITY_PROD.DBO.PAT_ENC
*   - CARE_BRONZE_CLARITY_PROD.DBO.PAT_ENC_HSP
*   - CARE_RES_OMOP_DEV2_WKSP.OMOP.PATIENT_DRIVER
*******************************************************************************/

SELECT
    -- OMOP Standard Stage Fields
    PATIENT_DRIVER.PERSON_ID                         AS PERSON_ID,
    ALLERGY.ALRGY_ENTERED_DTTM::DATE                AS OBSERVATION_DATE,
    ALLERGY.ALRGY_ENTERED_DTTM::DATETIME            AS OBSERVATION_DATETIME,
    NULL                                            AS VALUE_AS_NUMBER,
    T_ALLERGY_CODES_OBSERVATION.ALLERGEN_NAME        AS VALUE_AS_STRING,
    COALESCE(
        PAT_ENC.VISIT_PROV_ID,
        PAT_ENC_HSP.BILL_ATTEND_PROV_ID
    )                                               AS PROVIDER_SOURCE_VALUE,
    T_ALLERGY_CODES_OBSERVATION.ALLERGEN_NAME        AS OBSERVATION_SOURCE_VALUE,
    NULL                                            AS UNIT_SOURCE_VALUE,
    NULL                                            AS QUALIFIER_SOURCE_VALUE,
    NULL::VARCHAR(50)                               AS VALUE_SOURCE_VALUE,

    -- Additional Stage Fields
    PAT_ENC.PAT_ENC_CSN_ID                         AS PULL_CSN_ID,
    T_ALLERGY_CODES_OBSERVATION.CONCEPT_NAME         AS PULL_CONCEPT_NAME,
    ALLERGY.ALLERGY_ID                              AS PULL_ALLERGY_ID

FROM CARE_BRONZE_CLARITY_PROD.DBO.PAT_ALLERGIES AS PAT_ALLERGIES

    INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.ALLERGY AS ALLERGY
        ON PAT_ALLERGIES.ALLERGY_RECORD_ID = ALLERGY.ALLERGY_ID

    LEFT JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.T_ALLERGY_CODES_OBSERVATION AS T_ALLERGY_CODES_OBSERVATION
        ON T_ALLERGY_CODES_OBSERVATION.ALLERGEN_ID = ALLERGY.ALLERGEN_ID

    INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.PAT_ENC AS PAT_ENC
        ON ALLERGY.ALLERGY_PAT_CSN = PAT_ENC.PAT_ENC_CSN_ID

    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.PAT_ENC_HSP AS PAT_ENC_HSP
        ON ALLERGY.ALLERGY_PAT_CSN = PAT_ENC_HSP.PAT_ENC_CSN_ID

    INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP.PATIENT_DRIVER AS PATIENT_DRIVER
        ON PATIENT_DRIVER.EHR_PATIENT_ID = PAT_ALLERGIES.PAT_ID

WHERE UPPER(ALLERGY.DESCRIPTION) != 'NO KNOWN ALLERGIES';