  {{ config(materialized='ephemeral') }}
--BEGIN cte__T_DIAGNOSIS
SELECT DISTINCT
    CLARITY_EDG.DX_ID
    ,CLARITY_EDG.DX_NAME
    ,EDG_CURRENT_ICD10.CODE AS ICD10_CODE
    ,EDG_CURRENT_ICD9.CODE AS ICD9_CODE
FROM  {{ ref('CLARITY_EDG_stg')}} AS CLARITY_EDG
    LEFT JOIN  {{ ref('EDG_CURRENT_ICD10_stg')}} AS EDG_CURRENT_ICD10
        ON CLARITY_EDG.DX_ID = EDG_CURRENT_ICD10.DX_ID
    LEFT JOIN  {{ ref('EDG_CURRENT_ICD9_stg')}} AS EDG_CURRENT_ICD9
        ON CLARITY_EDG.DX_ID = EDG_CURRENT_ICD9.DX_ID
--END cte__T_DIAGNOSIS
--
