  {{ config(materialized='ephemeral') }}
--BEGIN cte__T_SNO_CODE

	SELECT DISTINCT CLARITY_EDG.DX_ID
		,CLARITY_EDG.DX_NAME
		,replace(SNOMED_CONCEPT.CONCEPT_ID, 'SNOMED#', '') AS SNOMED_code
		,SNOMED_CONCEPT.FULLY_SPECIFIED_NM
		,CLARITY_EDG.CURRENT_ICD9_LIST
		,CLARITY_EDG.CURRENT_ICD10_LIST
	FROM {{ ref('CLARITY_EDG_stg')}} AS CLARITY_EDG

		LEFT JOIN {{ ref('EXTERNAL_CNCPT_MAP_stg')}} AS EXTERNAL_CNCPT_MAP
			ON CLARITY_EDG.DX_ID = EXTERNAL_CNCPT_MAP.ENTITY_VALUE_NUM

		LEFT JOIN {{ ref('CONCEPT_MAPPED_stg')}} AS CONCEPT_MAPPED
			ON EXTERNAL_CNCPT_MAP.MAPPING_ID = CONCEPT_MAPPED.MAPPING_ID

		LEFT JOIN {{ ref('SNOMED_CONCEPT_stg')}} AS SNOMED_CONCEPT
			ON CONCEPT_MAPPED.CONCEPT_ID = SNOMED_CONCEPT.CONCEPT_ID

	WHERE (
			EXTERNAL_CNCPT_MAP.ENTITY_INI = 'EDG'
			AND EXTERNAL_CNCPT_MAP.ENTITY_ITEM = 0.1
			)and snomed_code is not null

--END cte__T_SNO_CODE
--
