 {{ config(materialized='ephemeral') }}
--BEGIN cte__T_TDL_DX

SELECT DISTINCT
    T_UNION_CLARITY_TDL_TRAN.DX_ID,
	MAX(T_UNION_CLARITY_TDL_TRAN.P_DX) AS P_DX,
    MIN(ORIG_SERVICE_DATE) AS START_DATE,
	MAX(ORIG_SERVICE_DATE) AS END_DATE,
    MIN(TYPE) AS TYPE,
    INT_PAT_ID,
    PAT_ENC_CSN_ID,
	MIN(TDL_ID) AS TDL_ID,
	MAX(MATCH_PROV_ID) AS MATCH_PROV_ID
FROM (
    SELECT DX_ONE_ID AS DX_ID, 'Y' AS P_DX, ORIG_SERVICE_DATE, TYPE, INT_PAT_ID, PAT_ENC_CSN_ID, TDL_ID, MATCH_PROV_ID
    FROM {{ ref('CLARITY_TDL_TRAN_stg')}} AS   cd
    UNION
    SELECT DX_TWO_ID AS DX_ID, 'N' AS P_DX, ORIG_SERVICE_DATE, TYPE, INT_PAT_ID, PAT_ENC_CSN_ID, TDL_ID, MATCH_PROV_ID
    FROM {{ ref('CLARITY_TDL_TRAN_stg')}} AS   cd
    UNION
    SELECT DX_THREE_ID AS DX_ID, 'N' AS P_DX, ORIG_SERVICE_DATE, TYPE, INT_PAT_ID, PAT_ENC_CSN_ID, TDL_ID, MATCH_PROV_ID
    FROM {{ ref('CLARITY_TDL_TRAN_stg')}} AS   cd
    UNION
    SELECT DX_FOUR_ID AS DX_ID, 'N' AS P_DX, ORIG_SERVICE_DATE, TYPE, INT_PAT_ID, PAT_ENC_CSN_ID, TDL_ID, MATCH_PROV_ID
    FROM {{ ref('CLARITY_TDL_TRAN_stg')}} AS   cd
    UNION
    SELECT DX_FIVE_ID AS DX_ID, 'N' AS P_DX, ORIG_SERVICE_DATE, TYPE, INT_PAT_ID, PAT_ENC_CSN_ID, TDL_ID, MATCH_PROV_ID
    FROM {{ ref('CLARITY_TDL_TRAN_stg')}} AS   cd
    UNION
    SELECT DX_SIX_ID AS DX_ID, 'N' AS P_DX, ORIG_SERVICE_DATE, TYPE, INT_PAT_ID, PAT_ENC_CSN_ID, TDL_ID, MATCH_PROV_ID
    FROM {{ ref('CLARITY_TDL_TRAN_stg')}} AS   cd
) T_UNION_CLARITY_TDL_TRAN
WHERE  DX_ID IS NOT NULL --AND TYPE = 1
GROUP BY T_UNION_CLARITY_TDL_TRAN.DX_ID, INT_PAT_ID, PAT_ENC_CSN_ID

--END cte__T_TDL_DX
--
