------ QA_SPECIMEN_NULLCONCEPT_COUNT
---------------------------------------------------------------------
WITH NULLCONCEPT_COUNT
AS (
	SELECT 'SPECIMEN_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM {{ref('SPECIMEN_RAW')}} AS SPECIMEN
	WHERE (SPECIMEN_CONCEPT_ID IS NULL)

	-- UNION ALL

	-- SELECT 'SPECIMEN_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	-- FROM {{ref('SPECIMEN_RAW')}} AS SPECIMEN
	-- WHERE (SPECIMEN_TYPE_CONCEPT_ID IS NULL)

	-- UNION ALL

	-- SELECT 'UNIT_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	-- FROM {{ref('SPECIMEN_RAW')}} AS SPECIMEN
	-- WHERE (UNIT_CONCEPT_ID IS NULL)

	UNION ALL

	SELECT 'ANATOMIC_SITE_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM {{ref('SPECIMEN_RAW')}} AS SPECIMEN
	WHERE (ANATOMIC_SITE_CONCEPT_ID IS NULL)

	-- UNION ALL

	-- SELECT 'DISEASE_STATUS_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	-- FROM {{ref('SPECIMEN_RAW')}} AS SPECIMEN
	-- WHERE (DISEASE_STATUS_CONCEPT_ID IS NULL)
	)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'SPECIMEN' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) <> 0 THEN ERROR_TYPE ELSE NULL END AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('SPECIMEN_RAW')}}) AS TOTAL_RECORDS
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('SPECIMEN')}}) AS TOTAL_RECORDS_CLEAN
FROM NULLCONCEPT_COUNT
GROUP BY METRIC_FIELD, QA_METRIC, ERROR_TYPE

