--QA_SPECIMEN_DATEVDATETIME_DETAIL
---------------------------------------------------------------------
WITH DATEVDATETIME_DETAIL AS (
SELECT 'SPECIMEN_DATE' AS METRIC_FIELD, 'DATEVDATETIME' AS QA_METRIC, 'WARNING' AS ERROR_TYPE,
	SPECIMEN_ID AS CDT_ID
FROM  {{ref('SPECIMEN_RAW')}} AS T1
WHERE SPECIMEN_DATE <> CAST(SPECIMEN_DATETIME AS DATE)
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'SPECIMEN' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM DATEVDATETIME_DETAIL

