--QA_SPECIMEN_DUPLICATES_DETAIL
---------------------------------------------------------------------
WITH TMP_DUPES AS (
SELECT    PERSON_ID
        , SPECIMEN_CONCEPT_ID
        , SPECIMEN_TYPE_CONCEPT_ID
        , SPECIMEN_DATE
        , SPECIMEN_DATETIME
        , QUANTITY
        , UNIT_CONCEPT_ID
        , ANATOMIC_SITE_CONCEPT_ID
        , DISEASE_STATUS_CONCEPT_ID
        , SPECIMEN_SOURCE_ID
        , SPECIMEN_SOURCE_VALUE
        , UNIT_SOURCE_VALUE
        , ANATOMIC_SITE_SOURCE_VALUE
        , DISEASE_STATUS_SOURCE_VALUE
        ,COUNT(*) AS CNT

FROM {{ref('SPECIMEN_RAW')}} AS T1
GROUP BY  PERSON_ID
        , SPECIMEN_CONCEPT_ID
        , SPECIMEN_TYPE_CONCEPT_ID
        , SPECIMEN_DATE
        , SPECIMEN_DATETIME
        , QUANTITY
        , UNIT_CONCEPT_ID
        , ANATOMIC_SITE_CONCEPT_ID
        , DISEASE_STATUS_CONCEPT_ID
        , SPECIMEN_SOURCE_ID
        , SPECIMEN_SOURCE_VALUE
        , UNIT_SOURCE_VALUE
        , ANATOMIC_SITE_SOURCE_VALUE
        , DISEASE_STATUS_SOURCE_VALUE
HAVING COUNT(*) > 1
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'SPECIMEN' AS STANDARD_DATA_TABLE
	,'DUPLICATE' AS QA_METRIC
	,'RECORDS'  AS METRIC_FIELD
	,'FATAL' AS ERROR_TYPE
	,SP.SPECIMEN_ID
FROM TMP_DUPES AS D
INNER JOIN {{ref('SPECIMEN_RAW')}} AS SP ON D.PERSON_ID = SP.PERSON_ID
	AND D.SPECIMEN_CONCEPT_ID =SP.SPECIMEN_CONCEPT_ID
	AND COALESCE(D.SPECIMEN_TYPE_CONCEPT_ID, 0) = COALESCE(SP.SPECIMEN_TYPE_CONCEPT_ID, 0)
	AND D.SPECIMEN_DATE = SP.SPECIMEN_DATE
	AND COALESCE(D.SPECIMEN_DATETIME,'1900-01-01') = COALESCE(SP.SPECIMEN_DATETIME,'1900-01-01')
	AND COALESCE(D.QUANTITY, 0) = COALESCE(SP.QUANTITY, 0)
	AND COALESCE(D.UNIT_CONCEPT_ID, 0) = COALESCE(SP.UNIT_CONCEPT_ID, 0)
	AND COALESCE(D.ANATOMIC_SITE_CONCEPT_ID, 0) = COALESCE(SP.ANATOMIC_SITE_CONCEPT_ID, 0)
	AND COALESCE(D.DISEASE_STATUS_CONCEPT_ID, 0) = COALESCE(SP.DISEASE_STATUS_CONCEPT_ID, '0')
	AND COALESCE(D.SPECIMEN_SOURCE_ID, '0') = COALESCE(SP.SPECIMEN_SOURCE_ID, 0)
	AND COALESCE(D.SPECIMEN_SOURCE_VALUE, '0') = COALESCE(SP.SPECIMEN_SOURCE_VALUE, '0')
	AND COALESCE(D.UNIT_SOURCE_VALUE, '0') = COALESCE(SP.UNIT_SOURCE_VALUE, '0')
	AND COALESCE(D.ANATOMIC_SITE_SOURCE_VALUE, '0') = COALESCE(SP.ANATOMIC_SITE_SOURCE_VALUE, '0')
	AND COALESCE(D.DISEASE_STATUS_SOURCE_VALUE, '0') = COALESCE(SP.DISEASE_STATUS_SOURCE_VALUE, '0')

