--QA_SPECIMEN_DUPLICATES_COUNT
---------------------------------------------------------------------
WITH TMP_DUPES AS (
SELECT    PERSON_ID
        , SPECIMEN_CONCEPT_ID
        , SPECIMEN_TYPE_CONCEPT_ID
        , SPECIMEN_DATE
        , SPECIMEN_DATETIME
        , QUANTITY
        , UNIT_CONCEPT_ID
        , ANATOMIC_SITE_CONCEPT_ID
        , DISEASE_STATUS_CONCEPT_ID
        , SPECIMEN_SOURCE_ID
        , SPECIMEN_SOURCE_VALUE
        , UNIT_SOURCE_VALUE
        , ANATOMIC_SITE_SOURCE_VALUE
        , DISEASE_STATUS_SOURCE_VALUE
        ,COUNT(*) AS CNT

FROM {{ref('SPECIMEN_RAW')}} AS T1
GROUP BY  PERSON_ID
        , SPECIMEN_CONCEPT_ID
        , SPECIMEN_TYPE_CONCEPT_ID
        , SPECIMEN_DATE
        , SPECIMEN_DATETIME
        , QUANTITY
        , UNIT_CONCEPT_ID
        , ANATOMIC_SITE_CONCEPT_ID
        , DISEASE_STATUS_CONCEPT_ID
        , SPECIMEN_SOURCE_ID
        , SPECIMEN_SOURCE_VALUE
        , UNIT_SOURCE_VALUE
        , ANATOMIC_SITE_SOURCE_VALUE
        , DISEASE_STATUS_SOURCE_VALUE
HAVING COUNT(*) > 1
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	, 'SPECIMEN' AS STANDARD_DATA_TABLE
	, 'DUPLICATE' AS QA_METRIC
	, 'RECORDS'  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) IS NOT NULL THEN 'FATAL' ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('SPECIMEN_RAW')}}) AS TOTAL_RECORDS
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('SPECIMEN')}}) AS TOTAL_RECORDS_CLEAN
FROM TMP_DUPES

