--PULL_MEASUREMENT_AMB_LOINC

{{ config(materialized = 'table', schema = 'OMOP_PULL') }}

SELECT DISTINCT

-- ***STAGE ATTRIBUTES***
-- fields used for the Stage

	PULL_VISIT_OCCURRENCE_AMB.PERSON_ID
	,CAST ( ORDER_PROC_2.SPECIMN_TAKEN_TIME AS DATE) AS MEASUREMENT_DATE
	,ORDER_PROC_2.SPECIMN_TAKEN_TIME AS MEASUREMENT_DATETIME
	,CASE
		WHEN ORDER_RESULTS.ORD_VALUE LIKE '>=%'
			THEN 4171755
		WHEN ORDER_RESULTS.ORD_VALUE LIKE '<=%'
			THEN 4171754
		WHEN ORDER_RESULTS.ORD_VALUE LIKE '<%'
			THEN 4171756
		WHEN ORDER_RESULTS.ORD_VALUE LIKE '>%'
			THEN 4172704
		ELSE 4172703
		END AS OPERATOR_CONCEPT_ID
	,CASE
		WHEN TRY_TO_NUMERIC(REPLACE(REPLACE(REPLACE(REPLACE(ORDER_RESULTS.ORD_VALUE, '=', ''), '<', ''), '>', ''), ',', '')) IS NULL
			THEN NULL
		ELSE REPLACE(REPLACE(REPLACE(REPLACE(ORDER_RESULTS.ORD_VALUE, '=', ''), '<', ''), '>', ''), ',', '')
		END AS VALUE_AS_NUMBER

	,CASE
		WHEN TRY_TO_NUMERIC(REPLACE(REPLACE(REPLACE(REPLACE(ORDER_RESULTS.REFERENCE_LOW, '=', ''), '<', ''), '>', ''), ',', '')) IS NULL
			THEN NULL
		ELSE CAST( REPLACE(REPLACE(REPLACE(REPLACE(ORDER_RESULTS.REFERENCE_LOW, '=', '' ), '<', ''), '>', ''), ',', '')AS FLOAT)
		END AS RANGE_LOW
	,CASE
		WHEN TRY_TO_NUMERIC(REPLACE(REPLACE(REPLACE(REPLACE(ORDER_RESULTS.REFERENCE_HIGH, '=', ''), '<', ''), '>', ''), ',', '')) IS NULL
			THEN NULL
		ELSE CAST( REPLACE(REPLACE(REPLACE(REPLACE(ORDER_RESULTS.REFERENCE_HIGH, '=', '' ), '<', ''), '>', ''), ',', '')AS FLOAT)
		END AS RANGE_HIGH
--  ,VISIT_DETAIL.VISIT_DETAIL_ID AS VISIT_DETAIL_ID
    ,0 AS VISIT_DETAIL_ID

	,LNC_DB_MAIN.LNC_CODE || ':' || LNC_DB_MAIN.LNC_COMPON AS MEASUREMENT_SOURCE_VALUE
 	,ORDER_RESULTS.REFERENCE_UNIT AS UNIT_SOURCE_VALUE
	,ORDER_RESULTS.ORD_VALUE AS VALUE_SOURCE_VALUE
	,AUTH_PROVIDER.PROV_ID									AS PROVIDER_SOURCE_VALUE
--    , COALESCE(AUTHRZING_PROV_ID, VISIT_PROV_ID, PCP_PROV_ID) AS PROVIDER_ID

-- ***ADDITIONAL ATTRIBUTES***
-- Non_OMOP fields used for the Stage
	,PULL_VISIT_OCCURRENCE_AMB.PULL_CSN_ID 		            AS PULL_CSN_ID
 	,LNC_DB_MAIN.LNC_CODE									AS PULL_LNC_CODE
    ,LNC_DB_MAIN.RECORD_ID                                  AS PULL_RECORD_ID
-- ***PULL attributes***
-- field names pulled from the source for verification purposes. May be duplicated above.

    -- ,PULL_VISIT_OCCURRENCE_AMB.EHR_PATIENT_ID
    -- ,PULL_VISIT_OCCURRENCE_AMB.PAT_ID
    -- ,PULL_VISIT_OCCURRENCE_AMB.PAT_ENC_CSN_ID
    -- ,PULL_VISIT_OCCURRENCE_AMB.HSP_ACCOUNT_ID
    -- ,PULL_VISIT_OCCURRENCE_AMB.ENC_TYPE_C
    -- ,PULL_VISIT_OCCURRENCE_AMB.IP_DOC_CONTACT_CSN
    -- ,PULL_VISIT_OCCURRENCE_AMB.ZC_DISP_ENC_TYPE_NAME
    -- ,PULL_VISIT_OCCURRENCE_AMB.PAT_OR_ADM_LINK_CSN AS PAT_OR_ADM_LINK_PAT_ENC_CSN_ID
    -- ,ORDER_PROC_2.SPECIMN_TAKEN_TIME
    -- ,ORDER_PROC.ORDER_TIME
    -- ,ORDER_RESULTS.ORD_VALUE
    -- ,ORDER_RESULTS.REFERENCE_LOW
    -- ,ORDER_RESULTS.REFERENCE_HIGH
    -- ,LNC_DB_MAIN.LNC_CODE
    -- ,LNC_DB_MAIN.LNC_COMPON
    -- ,LNC_DB_MAIN.RECORD_ID
    -- ,ORDER_RESULTS.REFERENCE_UNIT
    -- ,ORDER_PROC.AUTHRZING_PROV_ID
    -- ,AUTH_PROVIDER.PROV_NAME AS AUTH_PROVIDER_NAME
    -- ,AUTH_PROVIDER.PROV_TYPE AS AUTH_PROVIDER_TYPE
    -- ,PULL_VISIT_OCCURRENCE_AMB.VISIT_PROV_ID
    -- ,VISIT_PROVIDER_NAME
    -- ,VISIT_PROVIDER_TYPE
    -- ,PULL_VISIT_OCCURRENCE_AMB.PCP_PROV_ID
    -- ,PCP_PROVIDER_NAME
    -- ,PCP_PROVIDER_TYPE
    -- ,ORDER_PROC.ORDER_PROC_ID
    -- ,ORDER_RESULTS.COMPON_LNC_ID
    -- ,ORDER_RESULTS.RESULT_FLAG_C
    -- ,ZC_RESULT_FLAG_NAME
    -- ,ORDER_RESULTS.RESULT_STATUS_C
    -- ,ZC_RESULT_STATUS_NAME
    -- ,ORDER_PROC.ORDER_STATUS_C
    -- ,ZC_ORDER_STATUS_NAME AS ZC_ORDER_STATUS_NAME
    -- ,'PULL_MEASUREMENT--CLARITYAMB--LOINC' AS ETL_MODULE

FROM   {{ref('PULL_VISIT_OCCURRENCE_AMB')}} AS PULL_VISIT_OCCURRENCE_AMB

    INNER JOIN {{ ref('ORDER_PROC_stg')}} AS ORDER_PROC
        ON  PULL_VISIT_OCCURRENCE_AMB.PULL_CSN_ID  = ORDER_PROC.PAT_ENC_CSN_ID

    INNER JOIN {{ ref('ORDER_PROC_2_stg')}} AS ORDER_PROC_2
        ON ORDER_PROC.ORDER_PROC_ID = ORDER_PROC_2.ORDER_PROC_ID

    INNER JOIN {{ ref('ORDER_RESULTS_stg')}} AS ORDER_RESULTS
        ON ORDER_PROC.ORDER_PROC_ID = ORDER_RESULTS.ORDER_PROC_ID

    LEFT JOIN {{ ref('CLARITY_SER_stg')}} AS AUTH_PROVIDER
        ON ORDER_PROC.AUTHRZING_PROV_ID = AUTH_PROVIDER.PROV_ID

    INNER JOIN {{ ref('LNC_DB_MAIN_stg')}} AS LNC_DB_MAIN
        ON ORDER_RESULTS.COMPON_LNC_ID = LNC_DB_MAIN.RECORD_ID

    LEFT JOIN {{ ref('ZC_RESULT_FLAG_stg')}} AS ZC_RESULT_FLAG
        ON ORDER_RESULTS.RESULT_FLAG_C = ZC_RESULT_FLAG.RESULT_FLAG_C

    LEFT JOIN {{ ref('ZC_RESULT_STATUS_stg')}} AS ZC_RESULT_STATUS
        ON ORDER_RESULTS.RESULT_STATUS_C = ZC_RESULT_STATUS.RESULT_STATUS_C

    LEFT JOIN {{ ref('ZC_ORDER_STATUS_stg')}} AS ZC_ORDER_STATUS
        ON ORDER_PROC.ORDER_STATUS_C = ZC_ORDER_STATUS.ORDER_STATUS_C

WHERE  PULL_VISIT_OCCURRENCE_AMB.PULL_ENC_TYPE_C <> 3
        AND ZC_ORDER_STATUS_NAME <> 'Canceled'
        AND ORDER_PROC_2.SPECIMN_TAKEN_TIME IS NOT NULL

