{{ config(materialized = 'table', schema = 'OMOP_PULL') }}
--------------------------------
--PULL_MEASUREMENT_AMB_FLOWSHEET  
--------------------------------
SELECT 
-- ***STAGE ATTRIBUTES***
-- OMOP Standard fields used for the Stage
	 PULL_VISIT_OCCURRENCE_AMB.PERSON_ID                    AS PERSON_ID
	,IP_FLWSHT_MEAS.RECORDED_TIME::DATE                     AS MEASUREMENT_DATE
	,IP_FLWSHT_MEAS.RECORDED_TIME                           AS MEASUREMENT_DATETIME
	,CASE
		WHEN IP_FLWSHT_MEAS.MEAS_VALUE LIKE '>=%'
			THEN 4171755
		WHEN IP_FLWSHT_MEAS.MEAS_VALUE LIKE '<=%'
			THEN 4171754
		WHEN IP_FLWSHT_MEAS.MEAS_VALUE LIKE '<%'
			THEN 4171756
		WHEN IP_FLWSHT_MEAS.MEAS_VALUE LIKE '>%'
			THEN 4172704
		ELSE 4172703
		END                                                  AS OPERATOR_CONCEPT_ID
	,REPLACE(REPLACE(REPLACE(IP_FLWSHT_MEAS.MEAS_VALUE, '=', ''), '<', ''), '>', '') AS VALUE_AS_NUMBER
	,IP_FLO_GP_DATA.MINVALUE                                AS RANGE_LOW
	,IP_FLO_GP_DATA.MAX_VAL                                 AS RANGE_HIGH
    ,IP_FLO_GP_DATA.UNITS                                   AS UNIT_SOURCE_VALUE
	,IP_FLWSHT_MEAS.MEAS_VALUE                              AS VALUE_SOURCE_VALUE
    ,PULL_PROVIDER_SOURCE_VALUE                             AS PROVIDER_SOURCE_VALUE

-- ***ADDITIONAL ATTRIBUTES***
-- Non_OMOP fields used for the Stage
	,PULL_VISIT_OCCURRENCE_AMB.PULL_CSN_ID 	                AS PULL_CSN_ID
    ,IP_FLO_GP_DATA.FLO_MEAS_ID                             AS PULL_FLO_MEAS_ID
	,IP_FLO_GP_DATA.FLO_MEAS_NAME                           AS PULL_FLO_MEAS_NAME
    ,PULL_VISIT_OCCURRENCE_AMB.PULL_ENC_TYPE_C              AS PULL_ENC_TYPE_C   

     
-- ***SOURCE ATTRIBUTES***
-- field names pulled from the source for verification purposes. May be duplicated above.

    -- ,PULL_VISIT_OCCURRENCE_AMB.EHR_PATIENT_ID
    -- ,PULL_VISIT_OCCURRENCE_AMB.PAT_ENC_CSN_ID
    -- ,PULL_VISIT_OCCURRENCE_AMB.HSP_ACCOUNT_ID
    -- ,PULL_VISIT_OCCURRENCE_AMB.IP_DOC_CONTACT_CSN
    -- ,PULL_VISIT_OCCURRENCE_AMB.ENC_TYPE_C
    -- ,PULL_VISIT_OCCURRENCE_AMB.ZC_DISP_ENC_TYPE_NAME
    -- ,PULL_VISIT_OCCURRENCE_AMB.PAT_OR_ADM_LINK_CSN AS PAT_OR_ADM_LINK_PAT_ENC_CSN_ID
    -- ,IP_FLWSHT_MEAS.RECORDED_TIME
    -- ,IP_FLWSHT_MEAS.MEAS_VALUE
    -- ,IP_FLO_GP_DATA.MINVALUE
    -- ,IP_FLO_GP_DATA.MAX_VAL
    -- ,IP_FLO_GP_DATA.FLO_MEAS_ID
    -- ,IP_FLO_GP_DATA.FLO_MEAS_NAME
    -- ,ZC_VAL_TYPE.ZC_VAL_TYPE_NAME
    -- ,IP_FLO_GP_DATA.UNITS
    -- ,IP_FLO_GP_DATA.DISP_NAME
    -- ,IP_DATA_STORE.EPT_CSN
    -- ,IP_DATA_STORE.INPATIENT_DATA_ID
    -- ,IP_FLWSHT_REC.FSD_ID
    -- ,PULL_VISIT_OCCURRENCE_AMB.VISIT_PROV_ID
    -- ,VISIT_PROVIDER_NAME
    -- ,VISIT_PROVIDER_TYPE
    -- ,PULL_VISIT_OCCURRENCE_AMB.PCP_PROV_ID
    -- ,PCP_PROVIDER_NAME
    -- ,PCP_PROVIDER_TYPE

FROM {{ref('PULL_VISIT_OCCURRENCE_AMB')}}     AS PULL_VISIT_OCCURRENCE_AMB

LEFT JOIN {{ ref('IP_DATA_STORE_stg')}}              AS IP_DATA_STORE
    ON  PULL_VISIT_OCCURRENCE_AMB.PULL_CSN_ID = IP_DATA_STORE.EPT_CSN

LEFT JOIN {{ ref('IP_FLWSHT_REC_stg')}}              AS IP_FLWSHT_REC
    ON IP_DATA_STORE.INPATIENT_DATA_ID = IP_FLWSHT_REC.INPATIENT_DATA_ID

LEFT JOIN {{ ref('IP_FLWSHT_MEAS_stg')}}             AS IP_FLWSHT_MEAS
    ON IP_FLWSHT_REC.FSD_ID = IP_FLWSHT_MEAS.FSD_ID

INNER JOIN {{ ref('IP_FLO_GP_DATA_stg')}}            AS IP_FLO_GP_DATA
    ON IP_FLWSHT_MEAS.FLO_MEAS_ID = IP_FLO_GP_DATA.FLO_MEAS_ID

INNER JOIN {{ref('ZC_VAL_TYPE_stg')}}                AS ZC_VAL_TYPE
    ON IP_FLO_GP_DATA.VAL_TYPE_C = ZC_VAL_TYPE.VAL_TYPE_C

-- WHERE PULL_VISIT_OCCURRENCE_AMB.ENC_TYPE_C <> 3