{{ config(materialized='ephemeral') }}--, cluster_by = ['PAT_ENC_CSN_ID']
--BEGIN cte__Z_NOTE_LOOKUP
-- pulls a list of available notes
    SELECT PATIENT_DRIVER.PERSON_ID
        ,HNO_INFO.PAT_ID
        ,HNO_INFO.PAT_ENC_CSN_ID
        ,NOTE_ENC_INFO.ENTRY_INSTANT_DTTM
        ,ZC_NOTE_TYPE_IP_NAME AS ZC_NOTE_TYPE_IP_NAME
        ,HNO_INFO.IP_NOTE_TYPE_C
        ,HNO_INFO.AMB_NOTE_YN
        ,NOTE_ENC_INFO.NOTE_ID
        ,NOTE_ENC_INFO.CONTACT_DATE_REAL
        ,NOTE_ENC_INFO.CONTACT_SERIAL_NUM
    --     ,HNO_NOTE_TEXT.LINE
    --     ,HNO_NOTE_TEXT.NOTE_CSN_ID
    --     ,HNO_NOTE_TEXT.CONTACT_DATE
    --    --,HNO_NOTE_TEXT.CM_CT_OWNER_ID
    --    --,HNO_NOTE_TEXT.CHRON_ITEM_NUM
    --     ,HNO_NOTE_TEXT.NOTE_TEXT
    --     --,HNO_NOTE_TEXT.IS_ARCHIVED_YN
    FROM
    {{ ref('HNO_INFO_stg')}} AS HNO_INFO
    INNER JOIN {{ ref('ZC_NOTE_TYPE_IP_stg')}} AS ZC_NOTE_TYPE_IP
        ON HNO_INFO.IP_NOTE_TYPE_C = ZC_NOTE_TYPE_IP.TYPE_IP_C
    INNER JOIN {{ ref('NOTE_ENC_INFO_stg')}} AS NOTE_ENC_INFO
        ON HNO_INFO.NOTE_ID = NOTE_ENC_INFO.NOTE_ID
    -- INNER JOIN {{ ref('HNO_NOTE_TEXT_stg')}} AS HNO_NOTE_TEXT
    --     ON NOTE_ENC_INFO.NOTE_ID = HNO_NOTE_TEXT.NOTE_ID
    --         AND NOTE_ENC_INFO.CONTACT_DATE_REAL = HNO_NOTE_TEXT.CONTACT_DATE_REAL
    INNER JOIN {{ ref('PATIENT_DRIVER')}} AS PATIENT_DRIVER
        ON HNO_INFO.PAT_ID = PATIENT_DRIVER.EHR_PATIENT_ID

    -- WHERE HNO_INFO.PAT_ID IN (SELECT EHR_PATIENT_ID from {{ref('PATIENT_DRIVER')}})
--END cte__Z_NOTE_LOOKUP
