-- OMOP_CS.COUNT_OBSERVATION
  {{ config(materialized='ephemeral') }}
SELECT
    OBSERVATION.VISIT_OCCURRENCE_ID
    , COUNT(OBSERVATION.PERSON_ID) AS COUNTOFOBSERVATION
    , OBSERVATION.PERSON_ID

FROM
    {{ref('OBSERVATION')}} AS OBSERVATION
GROUP BY
    OBSERVATION.VISIT_OCCURRENCE_ID
    , OBSERVATION.PERSON_ID
