--OMOP_CS.COUNT_MEASUREMENT
  {{ config(materialized='ephemeral') }}
  
SELECT MEASUREMENT.VISIT_OCCURRENCE_ID
    , COUNT(MEASUREMENT.PERSON_ID) AS COUNTOFMEASUREMENT
    , MEASUREMENT.PERSON_ID

FROM {{ref('MEASUREMENT')}} AS MEASUREMENT

GROUP BY MEASUREMENT.VISIT_OCCURRENCE_ID
    , MEASUREMENT.PERSON_ID
