--OMOP_CS.COUNT_CONDITIONS
  {{ config(materialized='ephemeral') }}
  
SELECT CONDITION_OCCURRENCE.VISIT_OCCURRENCE_ID
    , COUNT(CONDITION_OCCURRENCE.PERSON_ID) AS COUNTOFCONDITION
    , CONDITION_OCCURRENCE.PERSON_ID

FROM {{ref('CONDITION_OCCURRENCE')}} AS  CONDITION_OCCURRENCE

GROUP BY CONDITION_OCCURRENCE.VISIT_OCCURRENCE_ID
    , CONDITION_OCCURRENCE.PERSON_ID
