--OMOP_CS.COUNT_NOTE
  {{ config(materialized='ephemeral') }}

  SELECT NOTE.VISIT_OCCURRENCE_ID
    , COUNT(NOTE.PERSON_ID) AS COUNTOFNOTE
    , NOTE.PERSON_ID

FROM {{ref('NOTE')}} AS NOTE

GROUP BY NOTE.VISIT_OCCURRENCE_ID
    , NOTE.PERSON_ID
