-- OMOP_CS.COUNT_VISIT_DETAIL
  {{ config(materialized='ephemeral') }}
  
SELECT
    VISIT_DETAIL.VISIT_OCCURRENCE_ID
    , COUNT(VISIT_DETAIL.PERSON_ID) AS COUNTOFVISITDETAIL
    , VISIT_DETAIL.PERSON_ID

FROM
    {{ref('VISIT_DETAIL')}} AS VISIT_DETAIL
GROUP BY
    VISIT_DETAIL.VISIT_OCCURRENCE_ID
    , VISIT_DETAIL.PERSON_ID
