# Use this command to create an isolated conda env:
# conda env create -f environment.yml --force
# Use this command to then switch to the env:
# conda activate dbt

# If you receive SSL errors due to your network firewall, try installing pip_system_certs by itself
# pip install -U pip_system_certs

### You may want to update your conda utility first:
# conda update -n base conda

# If your anaconda base is incredibly old, you may want to:
# conda install -n base anaconda=2023.03
# or update all packages to the current version:
# conda update -n base --all

### Use this command to create an isolated conda env:
# conda env create -f environment.yml

### Use this command to then switch to the env:
# conda activate dbt

### You may want to update your conda utility first:
# conda update -n base conda

### Conda has removed the --force parameter so you either update or remove an existing env
# conda env update -f environment.yml
# conda env remove -n dbt -y && conda env create -n dbt -f environment.yml

### If you receive SSL errors due to a network firewall, try installing pip and pip_system_certs without SSL verification
# python -m pip install -U --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org pip
# python -m pip install -U --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org pip_system_certs

### If your base packages are incredibly old, you may want to update all packages to the current version:
# conda update -n base --all

name: dbt
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - conda-forge
dependencies:
  - python=3.12.*
  - pip-system-certs
  - pip
  - pip:
    - pip
    - pip-system-certs
    # 1.6.3
    - dbt-core
    - dbt-snowflake
    # - snowflake-connector-python[secure-local-storage,pandas]
    # - snowflake-snowpark-python[pandas]
    # - snowflake-ml-python
