/*******************************************************
 * STAGE_OBSERVATION_AMB_ICD
 * 
 * Purpose: Retrieves and transforms ambulatory ICD diagnosis codes into OMOP observation format
 * Source: PULL_OBSERVATION_AMB_ICD
 * Target: OMOP Observation table
 *******************************************************/

SELECT DISTINCT
    -- Core Fields
    PULL_OBSERVATION_AMB_ICD.PERSON_ID AS PERSON_ID,
    CASE
        WHEN PULL_OBSERVATION_AMB_ICD.OBSERVATION_DATE >= '2015-10-01' THEN T_ICD10_CONCEPT.CONCEPT_ID
        ELSE T_ICD9_CONCEPT.CONCEPT_ID
    END AS OBSERVATION_CONCEPT_ID,
    OBSERVATION_DATE AS OBSERVATION_DATE,
    OBSERVATION_DATETIME AS OBSERVATION_DATETIME,
    32817 AS OBSERVATION_TYPE_CONCEPT_ID,  -- EHR
    
    -- Value Fields
    NULL AS VALUE_AS_NUMBER,
    NULL AS VALUE_AS_STRING,
    CASE
        WHEN PULL_OBSERVATION_AMB_ICD.OBSERVATION_DATE >= '2015-10-01' THEN T_ICD10_CONCEPT_VALUE.CONCEPT_ID
        ELSE T_ICD9_CONCEPT_VALUE.CONCEPT_ID
    END AS VALUE_AS_CONCEPT_ID,
    
    -- Additional Details
    0 AS UNIT_CONCEPT_ID,
    0 AS QUALIFIER_CONCEPT_ID,
    PROVIDER.PROVIDER_ID AS PROVIDER_ID,
    VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID AS VISIT_OCCURRENCE_ID,
    0 AS VISIT_DETAIL_ID,
    
    -- Source Values
    CASE
        WHEN PULL_OBSERVATION_AMB_ICD.OBSERVATION_DATE >= '2015-10-01'
            THEN LEFT(T_ICD10_SOURCE.CONCEPT_CODE || ':' || T_ICD10_SOURCE.CONCEPT_NAME, 50)
        ELSE LEFT(T_ICD9_SOURCE.CONCEPT_CODE || ':' || T_ICD9_SOURCE.CONCEPT_NAME, 50)
    END AS OBSERVATION_SOURCE_VALUE,
    CASE
        WHEN PULL_OBSERVATION_AMB_ICD.OBSERVATION_DATE >= '2015-10-01' THEN T_ICD10_SOURCE.CONCEPT_ID
        ELSE T_ICD9_SOURCE.CONCEPT_ID
    END AS OBSERVATION_SOURCE_CONCEPT_ID,
    UNIT_SOURCE_VALUE AS UNIT_SOURCE_VALUE,
    QUALIFIER_SOURCE_VALUE AS QUALIFIER_SOURCE_VALUE,
    
    -- Event Fields
    NULL::NUMBER(28,0) AS OBSERVATION_EVENT_ID,
    0::NUMBER(28,0) AS OBS_EVENT_FIELD_CONCEPT_ID,
    VALUE_SOURCE_VALUE AS VALUE_SOURCE_VALUE,
    
    -- Custom Fields for Tracking
    'OBSERVATION_AMB_ICD' AS ETL_MODULE,
    VISIT_OCCURRENCE.phi_PAT_ID AS STAGE_PAT_ID,
    VISIT_OCCURRENCE.phi_MRN_CPI AS STAGE_MRN_CPI,
    VISIT_OCCURRENCE.phi_CSN_ID AS STAGE_CSN_ID,
    PULL_DX_ID AS STAGE_DX_ID

FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.PULL_OBSERVATION_AMB_ICD AS PULL_OBSERVATION_AMB_ICD

    -- Join to get visit information
    INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP.VISIT_OCCURRENCE_RAW AS VISIT_OCCURRENCE
        ON PULL_OBSERVATION_AMB_ICD.PULL_CSN_ID = VISIT_OCCURRENCE.phi_CSN_ID

    -- Join to get provider information
    LEFT JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP.PROVIDER_RAW AS PROVIDER
        ON PULL_OBSERVATION_AMB_ICD.PROVIDER_SOURCE_VALUE = PROVIDER.PROVIDER_SOURCE_VALUE

    -- Join to get ICD source concepts
    LEFT JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP_STAGE.T_ICD_SOURCE_OBSERVATION AS T_ICD9_SOURCE
        ON PULL_OBSERVATION_AMB_ICD.PULL_ICD9_CODE = T_ICD9_SOURCE.CONCEPT_CODE

    LEFT JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP_STAGE.T_ICD_SOURCE_OBSERVATION AS T_ICD10_SOURCE
        ON PULL_OBSERVATION_AMB_ICD.PULL_ICD10_CODE = T_ICD10_SOURCE.CONCEPT_CODE

    -- Join to get standard concepts
    LEFT JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP_STAGE.T_CONCEPT_OBSERVATION AS T_ICD9_CONCEPT
        ON T_ICD9_CONCEPT.SOURCE_CONCEPT_ID = T_ICD9_SOURCE.CONCEPT_ID

    LEFT JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP_STAGE.T_CONCEPT_OBSERVATION AS T_ICD10_CONCEPT
        ON T_ICD10_CONCEPT.SOURCE_CONCEPT_ID = T_ICD10_SOURCE.CONCEPT_ID

    -- Join to get value concepts
    LEFT JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP_STAGE.T_CONCEPT_OBSERVATION_VALUE AS T_ICD9_CONCEPT_VALUE
        ON T_ICD9_CONCEPT_VALUE.SOURCE_CONCEPT_ID = T_ICD9_SOURCE.CONCEPT_ID

    LEFT JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP_STAGE.T_CONCEPT_OBSERVATION_VALUE AS T_ICD10_CONCEPT_VALUE
        ON T_ICD10_CONCEPT_VALUE.SOURCE_CONCEPT_ID = T_ICD10_SOURCE.CONCEPT_ID

WHERE
    -- Filter for valid ICD10 codes after cutoff date or valid ICD9 codes before cutoff date
    (PULL_OBSERVATION_AMB_ICD.OBSERVATION_DATE >= '2015-10-01' AND T_ICD10_CONCEPT.CONCEPT_ID IS NOT NULL)
    OR
    (PULL_OBSERVATION_AMB_ICD.OBSERVATION_DATE < '2015-10-01' AND T_ICD9_CONCEPT.CONCEPT_ID IS NOT NULL)