--PULL_FACT_RELATIONSHIP_MOM_AND_BABY
--   {{ config(materialized = 'view', schema = 'OMOP_PULL') }}

SELECT DISTINCT
    BABY.PERSON_ID 		            AS PULL_BABY_PERSON_ID
    ,BABY.EHR_PATIENT_ID       	    AS PULL_BABY_ID
    ,MOM.PERSON_ID 		            AS PULL_MOM_PERSON_ID
    ,MOM.EHR_PATIENT_ID         	AS PULL_MOM_ID

FROM {{ref('V_OB_DEL_RECORDS_stg')}} V_OB_DEL_RECORDS
JOIN {{ref('PATIENT_DRIVER')}} AS BABY ON (BABY.EHR_PATIENT_ID = V_OB_DEL_RECORDS.BABYID)
JOIN {{ref('PATIENT_DRIVER')}} AS MOM ON (MOM.EHR_PATIENT_ID = V_OB_DEL_RECORDS.MOMID)

