--STAGE_PROCEDURE_OCCURRENCE_AMB_CPT
{#-- {{ config(materialized = 'view', schema = 'OMOP_STAGE') }}#}
--
SELECT DISTINCT
--	CDM.SEQ_PROCEDURE_OCCURRENCE.NEXTVAL AS PROCEDURE_OCCURRENCE_ID
	PULL_PROCEDURE_OCCURRENCE_AMB_CPT.PERSON_ID						AS PERSON_ID
	,T_CONCEPT.CONCEPT_ID 											AS PROCEDURE_CONCEPT_ID
	,PROCEDURE_DATE 												AS PROCEDURE_DATE
	,PROCEDURE_DATETIME 											AS PROCEDURE_DATETIME
    ,PROCEDURE_END_DATE 											AS PROCEDURE_END_DATE
    ,PROCEDURE_END_DATETIME 										AS PROCEDURE_END_DATETIME
	,32817 															AS PROCEDURE_TYPE_CONCEPT_ID
	,SOURCE_TO_CONCEPT_MAP_MODIFIER.TARGET_CONCEPT_ID            	AS MODIFIER_CONCEPT_ID
	,QUANTITY 														AS QUANTITY
	,PROVIDER.PROVIDER_ID 											AS PROVIDER_ID
	,VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID 							AS VISIT_OCCURRENCE_ID
--    ,VISIT_DETAIL.VISIT_DETAIL_ID AS VISIT_DETAIL_ID
    ,NULL 																AS VISIT_DETAIL_ID
	,PROCEDURE_SOURCE_VALUE											AS PROCEDURE_SOURCE_VALUE
	,T_SOURCE.CONCEPT_ID 											AS PROCEDURE_SOURCE_CONCEPT_ID
	,MODIFIER_SOURCE_VALUE 											AS MODIFIER_SOURCE_VALUE

	-------- Non-OMOP Fields ------------
	,'PROCEDURE_OCCURRENCE_AMB_CPT' 							    AS ETL_MODULE
	-- , PULL_PROC_CODE											    AS STAGE_PROC_CODE
	, VISIT_OCCURRENCE.phi_PAT_ID                      				AS STAGE_PAT_ID
    , VISIT_OCCURRENCE.phi_MRN_CPI                           		AS STAGE_MRN_CPI
	, VISIT_OCCURRENCE.phi_CSN_ID									AS STAGE_CSN_ID
	, PULL_PROC_ID													AS STAGE_PROC_ID

FROM {{ref('PULL_PROCEDURE_OCCURRENCE_AMB_CPT')}} AS  PULL_PROCEDURE_OCCURRENCE_AMB_CPT

	INNER JOIN {{ref('VISIT_OCCURRENCE_RAW')}} AS VISIT_OCCURRENCE
		ON PULL_PROCEDURE_OCCURRENCE_AMB_CPT.PULL_CSN_ID = VISIT_OCCURRENCE.phi_CSN_ID

	INNER JOIN {{ref('T_PROCEDURE_SOURCE')}} AS T_SOURCE
		ON PULL_PROCEDURE_OCCURRENCE_AMB_CPT.PULL_PROC_CODE = T_SOURCE.CONCEPT_CODE

	INNER JOIN {{ref('T_PROCEDURE_CONCEPT')}} AS T_CONCEPT
		ON T_SOURCE.CONCEPT_ID = T_CONCEPT.CONCEPT_ID

	LEFT JOIN {{ref('PROVIDER_RAW')}} AS PROVIDER
		ON PULL_PROCEDURE_OCCURRENCE_AMB_CPT.PROVIDER_SOURCE_VALUE = PROVIDER.PROVIDER_SOURCE_VALUE

	LEFT JOIN {{ ref('SOURCE_TO_CONCEPT_MAP_MODIFIER')}} AS SOURCE_TO_CONCEPT_MAP_MODIFIER
		ON PULL_PROCEDURE_OCCURRENCE_AMB_CPT.PULL_MODIFIER1_ID = SOURCE_TO_CONCEPT_MAP_MODIFIER.SOURCE_CODE::VARCHAR

