
--VISIT_OCCURRENCE
{{ config(materialized='table', schema = 'OMOP',
        cluster_by = ['VISIT_OCCURRENCE_ID']) }}

SELECT DISTINCT
     {{ sequence_get_nextval() }}::NUMBER(28,0)   AS VISIT_OCCURRENCE_ID
    , PERSON_ID::NUMBER(28,0)                     AS PERSON_ID
    , VISIT_CONCEPT_ID::NUMBER(28,0)              AS VISIT_CONCEPT_ID
    , VISIT_START_DATE::DATE                      AS VISIT_START_DATE
    , VISIT_START_DATETIME::DATETIME              AS VISIT_START_DATETIME
    , VISIT_END_DATE::DATE                        AS VISIT_END_DATE
    , VISIT_END_DATETIME::DATETIME                AS VISIT_END_DATETIME
    , VISIT_TYPE_CONCEPT_ID::NUMBER(28,0)         AS VISIT_TYPE_CONCEPT_ID
    , PROVIDER_ID::NUMBER(28,0)                   AS PROVIDER_ID
    , CARE_SITE_ID::NUMBER(28,0)                  AS CARE_SITE_ID
    , VISIT_SOURCE_VALUE::VARCHAR                 AS VISIT_SOURCE_VALUE
    , VISIT_SOURCE_CONCEPT_ID::NUMBER(28,0)       AS VISIT_SOURCE_CONCEPT_ID
    , ADMITTED_FROM_CONCEPT_ID::NUMBER(28,0)      AS ADMITTED_FROM_CONCEPT_ID
    , ADMITTED_FROM_SOURCE_VALUE::VARCHAR         AS ADMITTED_FROM_SOURCE_VALUE
    , DISCHARGED_TO_CONCEPT_ID::NUMBER(28,0)      AS DISCHARGED_TO_CONCEPT_ID
    , DISCHARGED_TO_SOURCE_VALUE::VARCHAR         AS DISCHARGED_TO_SOURCE_VALUE
    , PRECEDING_VISIT_OCCURRENCE_ID::NUMBER(28,0) AS PRECEDING_VISIT_OCCURRENCE_ID
 ------Non OMOP fields -----------
    , ETL_MODULE::VARCHAR                         AS ETL_MODULE
    , STAGE_PAT_ID::VARCHAR                  	  AS phi_PAT_ID
    , STAGE_MRN_CPI::NUMBER(28,0)                 AS phi_MRN_CPI
    , STAGE_CSN_ID::NUMBER(28,0)			      AS phi_CSN_ID
FROM
(SELECT *
FROM
     {{ref('STAGE_VISIT_OCCURRENCE_AMB')}} AS STAGE_VISIT_OCCURRENCE_AMB
UNION ALL
SELECT *
FROM
     {{ref('STAGE_VISIT_OCCURRENCE_HSP')}} AS VISIT_OCCURRENCE_HSP ) A

