
--VISIT_OCCURRENCE
{{ config(materialized='view', schema = 'OMOP') }}

SELECT DISTINCT
     VISIT_OCCURRENCE_ID
    , PERSON_ID
    , VISIT_CONCEPT_ID
    , VISIT_START_DATE
    , VISIT_START_DATETIME
    , VISIT_END_DATE
    , VISIT_END_DATETIME
    , VISIT_TYPE_CONCEPT_ID
    , PROVIDER_ID
    , CARE_SITE_ID
    , VISIT_SOURCE_VALUE
    , VISIT_SOURCE_CONCEPT_ID
    , ADMITTED_FROM_CONCEPT_ID
    , ADMITTED_FROM_SOURCE_VALUE
    , DISCHARGED_TO_CONCEPT_ID
    , DISCHARGED_TO_SOURCE_VALUE
    , PRECEDING_VISIT_OCCURRENCE_ID
 ------Non OMOP fields -----------
    , ETL_MODULE
    , phi_PAT_ID
    , phi_MRN_CPI
    , phi_CSN_ID

FROM {{ref('VISIT_OCCURRENCE_RAW')}} AS VISIT_OCCURRENCE

LEFT JOIN (
    SELECT CDT_ID
    FROM {{ref('QA_ERR_DBT')}} AS QA_ERR_DBT
        WHERE (STANDARD_DATA_TABLE = 'VISIT_OCCURRENCE')
            AND (ERROR_TYPE IN ('FATAL', 'INVALID DATA'))
        ) AS EXCLUSION_RECORDS
        ON VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID = EXCLUSION_RECORDS.CDT_ID
WHERE (EXCLUSION_RECORDS.CDT_ID IS NULL)

