--STAGE_MEASUREMENT_HOSP_LOINC
{#-- {{ config(materialized = 'view', schema = 'OMOP_STAGE') }}#}
--
SELECT DISTINCT
	PULL_MEASUREMENT_HOSP_LOINC.PERSON_ID                       AS PERSON_ID
	,T_CONCEPT.CONCEPT_ID 										AS MEASUREMENT_CONCEPT_ID
	,PULL_MEASUREMENT_HOSP_LOINC.MEASUREMENT_DATE               AS MEASUREMENT_DATE
	,PULL_MEASUREMENT_HOSP_LOINC.MEASUREMENT_DATETIME           AS MEASUREMENT_DATETIME
	,32817 														AS MEASUREMENT_TYPE_CONCEPT_ID  --EHR
	,PULL_MEASUREMENT_HOSP_LOINC.OPERATOR_CONCEPT_ID            AS OPERATOR_CONCEPT_ID
	,PULL_MEASUREMENT_HOSP_LOINC.VALUE_AS_NUMBER                AS VALUE_AS_NUMBER
	,COALESCE(SOURCE_TO_CONCEPT_MAP_VALUE.TARGET_CONCEPT_ID, 0) AS VALUE_AS_CONCEPT_ID
	,COALESCE(SOURCE_TO_CONCEPT_MAP_UNIT.TARGET_CONCEPT_ID, 0) 	AS UNIT_CONCEPT_ID
	,PULL_MEASUREMENT_HOSP_LOINC.RANGE_LOW                      AS RANGE_LOW
	,PULL_MEASUREMENT_HOSP_LOINC.RANGE_HIGH                     AS RANGE_HIGH
	,PROVIDER.PROVIDER_ID 										AS PROVIDER_ID
	,VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID 						AS VISIT_OCCURRENCE_ID
--    ,VISIT_DETAIL.VISIT_DETAIL_ID AS VISIT_DETAIL_ID
    ,NULL															AS VISIT_DETAIL_ID
	,PULL_MEASUREMENT_HOSP_LOINC.MEASUREMENT_SOURCE_VALUE       AS MEASUREMENT_SOURCE_VALUE
	,T_SOURCE.CONCEPT_ID 										AS MEASUREMENT_SOURCE_CONCEPT_ID
	,PULL_MEASUREMENT_HOSP_LOINC.UNIT_SOURCE_VALUE              AS UNIT_SOURCE_VALUE
	,PULL_MEASUREMENT_HOSP_LOINC.VALUE_SOURCE_VALUE             AS VALUE_SOURCE_VALUE
    ,NULL 															AS UNIT_SOURCE_CONCEPT_ID
    ,NULL 														AS MEASUREMENT_EVENT_ID
    ,NULL 															AS MEAS_EVENT_FIELD_CONCEPT_ID

	-------- Non-OMOP Fields ------------
	, 'MEASUREMENT_HOSP_LOINC' 									AS ETL_MODULE
	, VISIT_OCCURRENCE.phi_PAT_ID                      			AS STAGE_PAT_ID
    , VISIT_OCCURRENCE.phi_MRN_CPI                           	AS STAGE_MRN_CPI
	, VISIT_OCCURRENCE.phi_CSN_ID								AS STAGE_CSN_ID
 	, PULL_LNC_CODE     									    AS STAGE_LNC_CODE
    , PULL_RECORD_ID                                            AS STAGE_RECORD_ID

FROM {{ref('PULL_MEASUREMENT_HOSP_LOINC')}} AS PULL_MEASUREMENT_HOSP_LOINC

    INNER  JOIN {{ref('VISIT_OCCURRENCE_RAW')}} AS VISIT_OCCURRENCE
        ON PULL_MEASUREMENT_HOSP_LOINC.PULL_CSN_ID = VISIT_OCCURRENCE.phi_CSN_ID

    INNER JOIN {{ref('T_LOINC_SOURCE')}} AS T_SOURCE
        ON PULL_MEASUREMENT_HOSP_LOINC.PULL_LNC_CODE = T_SOURCE.CONCEPT_CODE

    INNER JOIN {{ref('T_LOINC_CONCEPT')}} AS T_CONCEPT
        ON T_CONCEPT.SOURCE_CONCEPT_ID = T_SOURCE.CONCEPT_ID

    LEFT JOIN {{ref('PROVIDER_RAW')}} AS PROVIDER
        ON PULL_MEASUREMENT_HOSP_LOINC.PROVIDER_SOURCE_VALUE = PROVIDER.PROVIDER_SOURCE_VALUE

    LEFT JOIN {{ ref('SOURCE_TO_CONCEPT_MAP_UNITS')}} AS  SOURCE_TO_CONCEPT_MAP_UNIT
        ON PULL_MEASUREMENT_HOSP_LOINC.UNIT_SOURCE_VALUE = SOURCE_TO_CONCEPT_MAP_UNIT.SOURCE_CODE

    LEFT JOIN {{ ref('SOURCE_TO_CONCEPT_MAP_VALUE')}} AS  SOURCE_TO_CONCEPT_MAP_VALUE
        ON PULL_MEASUREMENT_HOSP_LOINC.VALUE_SOURCE_VALUE = SOURCE_TO_CONCEPT_MAP_VALUE.SOURCE_CODE

-- WHERE (PULL_MEASUREMENT_HOSP_LOINC.ZC_ORDER_STATUS_NAME <> 'Canceled')

