--QA_DEVICE_EXPOSURE_DATEVDATETIME_DETAIL
---------------------------------------------------------------------
WITH DATEVDATETIME_DETAIL AS (
SELECT 'DEVICE_EXPOSURE_START_DATE' AS METRIC_FIELD, 'DATEVDATETIME' AS QA_METRIC, 'WARNING' AS ERROR_TYPE,
	DEVICE_EXPOSURE_ID AS CDT_ID
FROM {{ref('DEVICE_EXPOSURE_RAW')}}  AS T1
WHERE DEVICE_EXPOSURE_START_DATE <> CAST(DEVICE_EXPOSURE_START_DATETIME AS DATE)

UNION ALL

SELECT 'DEVICE_EXPOSURE_END_DATE' AS METRIC_FIELD, 'DATEVDATETIME' AS QA_METRIC, 'WARNING' AS ERROR_TYPE,
	 DEVICE_EXPOSURE_ID AS CDT_ID
FROM {{ref('DEVICE_EXPOSURE_RAW')}}  AS T1
WHERE DEVICE_EXPOSURE_END_DATE <> CAST(DEVICE_EXPOSURE_END_DATETIME AS DATE)
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'DEVICE_EXPOSURE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM DATEVDATETIME_DETAIL
