------QA_PROVIDER_NONSTANDARD_DETAIL
---------------------------------------------------------------------
WITH NON_STANDARD_DETAIL AS (
	SELECT 'SPECIALTY_CONCEPT_ID' AS METRIC_FIELD,'NON-STANDARD' AS QA_METRIC,'INVALID DATA' AS ERROR_TYPE
		,PROVIDER_ID AS CDT_ID
	FROM {{ref('PROVIDER_RAW')}} AS P
		LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C ON P.SPECIALTY_CONCEPT_ID = C.CONCEPT_ID
			AND upper(C.DOMAIN_ID) =  'PROVIDER'
			AND upper(C.CONCEPT_CLASS_ID) IN ('PHYSICIAN SPECIALTY','PROVIDER')
	WHERE SPECIALTY_CONCEPT_ID <> 0
		AND SPECIALTY_CONCEPT_ID IS NOT NULL
		AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
UNION ALL
	SELECT 'GENDER_CONCEPT_ID' AS METRIC_FIELD,'NON-STANDARD' AS QA_METRIC,'INVALID DATA' AS ERROR_TYPE
		,PROVIDER_ID AS CDT_ID
	FROM {{ref('PROVIDER_RAW')}} AS P
		LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C ON P.GENDER_CONCEPT_ID = C.CONCEPT_ID
			AND upper(C.DOMAIN_ID) =  'GENDER'
	WHERE GENDER_CONCEPT_ID <> 0
		AND GENDER_CONCEPT_ID IS NOT NULL
		AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
UNION ALL
	SELECT 'SPECIALTY_SOURCE_CONCEPT_ID' AS METRIC_FIELD,'NON-STANDARD' AS QA_METRIC,'INVALID DATA' AS ERROR_TYPE
		,PROVIDER_ID AS CDT_ID
	FROM {{ref('PROVIDER_RAW')}} AS P
		LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C ON P.SPECIALTY_SOURCE_CONCEPT_ID = C.CONCEPT_ID
			AND upper(C.DOMAIN_ID) =  'PROVIDER'
			AND upper(C.CONCEPT_CLASS_ID) =  'PHYSICIAN SPECIALTY'
	WHERE SPECIALTY_SOURCE_CONCEPT_ID <> 0
		AND SPECIALTY_SOURCE_CONCEPT_ID IS NOT NULL
		AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
UNION ALL
	SELECT 'GENDER_SOURCE_CONCEPT_ID' AS METRIC_FIELD,'NON-STANDARD' AS QA_METRIC,'INVALID DATA' AS ERROR_TYPE
		,PROVIDER_ID AS CDT_ID
	FROM {{ref('PROVIDER_RAW')}} AS P
		LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C ON P.GENDER_SOURCE_CONCEPT_ID = C.CONCEPT_ID
			AND upper(C.DOMAIN_ID) =  'GENDER'
	WHERE GENDER_SOURCE_CONCEPT_ID <> 0
		AND GENDER_SOURCE_CONCEPT_ID IS NOT NULL
		AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'PROVIDER' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NON_STANDARD_DETAIL
  WHERE ERROR_TYPE <>'EXPECTED'

