------QA_PROVIDER_NONSTANDARD_COUNT
---------------------------------------------------------------------
WITH NON_STANDARD_COUNT AS (
	SELECT 'SPECIALTY_CONCEPT_ID' AS METRIC_FIELD,'NON-STANDARD' AS QA_METRIC,'INVALID DATA' AS ERROR_TYPE
		,COUNT(*) AS CNT
	FROM {{ref('PROVIDER_RAW')}} AS P
		LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C ON P.SPECIALTY_CONCEPT_ID = C.CONCEPT_ID
			AND upper(C.DOMAIN_ID) =  'PROVIDER'
			AND upper(C.CONCEPT_CLASS_ID) IN ('PHYSICIAN SPECIALTY','PROVIDER')
	WHERE SPECIALTY_CONCEPT_ID <> 0
		AND SPECIALTY_CONCEPT_ID IS NOT NULL
		AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
	UNION ALL
	SELECT 'GENDER_CONCEPT_ID' AS METRIC_FIELD,'NON-STANDARD' AS QA_METRIC,'INVALID DATA' AS ERROR_TYPE
		,COUNT(*) AS CNT
	FROM {{ref('PROVIDER_RAW')}} AS P
		LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C ON P.GENDER_CONCEPT_ID = C.CONCEPT_ID
			AND upper(C.DOMAIN_ID) =  'GENDER'
	WHERE GENDER_CONCEPT_ID <> 0
		AND GENDER_CONCEPT_ID IS NOT NULL
		AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
	UNION ALL
	SELECT 'SPECIALTY_SOURCE_CONCEPT_ID' AS METRIC_FIELD,'NON-STANDARD' AS QA_METRIC,'INVALID DATA' AS ERROR_TYPE
		,COUNT(*) AS CNT
	FROM {{ref('PROVIDER_RAW')}} AS P
		LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C ON P.SPECIALTY_SOURCE_CONCEPT_ID = C.CONCEPT_ID
			AND upper(C.DOMAIN_ID) =  'PROVIDER'
			AND upper(C.CONCEPT_CLASS_ID) =  'PHYSICIAN SPECIALTY'
	WHERE SPECIALTY_SOURCE_CONCEPT_ID <> 0
		AND SPECIALTY_SOURCE_CONCEPT_ID IS NOT NULL
		AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
	UNION ALL
	SELECT 'GENDER_SOURCE_CONCEPT_ID' AS METRIC_FIELD,'NON-STANDARD' AS QA_METRIC,'INVALID DATA' AS ERROR_TYPE
		,COUNT(*) AS CNT
	FROM {{ref('PROVIDER_RAW')}} AS P
		LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C ON P.GENDER_SOURCE_CONCEPT_ID = C.CONCEPT_ID
			AND upper(C.DOMAIN_ID) =  'GENDER'
	WHERE GENDER_SOURCE_CONCEPT_ID <> 0
		AND GENDER_SOURCE_CONCEPT_ID IS NOT NULL
		AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'PROVIDER' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) <> 0 THEN ERROR_TYPE ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('PROVIDER_RAW')}}) AS TOTAL_RECORDS
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('PROVIDER')}}) AS TOTAL_RECORDS_CLEAN
	FROM NON_STANDARD_COUNT
	GROUP BY   METRIC_FIELD, QA_METRIC, ERROR_TYPE

