/*******************************************************************************
* Script Name: PULL_DEVICE_EXPOSURE_ANES_LDA
* Description: Retrieves device exposure data related to anesthesia LDA (Line, 
*              Drain, Airway) information
* 
* Tables Used:
*    - CARE_BRONZE_CLARITY_PROD.DBO.PAT_ENC
*    - CARE_BRONZE_CLARITY_PROD.DBO.F_AN_RECORD_SUMMARY
*    - CARE_BRONZE_CLARITY_PROD.DBO.AN_HSB_LINK_INFO
*    - CARE_BRONZE_CLARITY_PROD.DBO.PAT_ENC_HSP
*    - CARE_BRONZE_CLARITY_PROD.DBO.IP_LDA_NOADDSINGLE
*    - CARE_BRONZE_CLARITY_PROD.DBO.IP_FLO_GP_DATA
*    - CARE_RES_OMOP_DEV2_WKSP.OMOP.PATIENT_DRIVER
*******************************************************************************/

SELECT
    -- OMOP Standard Fields
    PATIENT_DRIVER.PERSON_ID                             AS PERSON_ID,
    IP_LDA_NOADDSINGLE.PLACEMENT_INSTANT::DATE          AS DEVICE_EXPOSURE_START_DATE,
    IP_LDA_NOADDSINGLE.PLACEMENT_INSTANT                AS DEVICE_EXPOSURE_START_DATETIME,
    IP_LDA_NOADDSINGLE.REMOVAL_INSTANT::DATE            AS DEVICE_EXPOSURE_END_DATE,
    IP_LDA_NOADDSINGLE.REMOVAL_INSTANT                  AS DEVICE_EXPOSURE_END_DATETIME,
    NULL                                                AS UNIQUE_DEVICE_ID,
    NULL                                                AS PRODUCTION_ID,        -- NEW 5.4
    NULL                                                AS QUANTITY,
    BILL_ATTEND_PROV_ID                                AS PROVIDER_SOURCE_VALUE,
    0                                                   AS VISIT_DETAIL_ID,
    IP_LDA_NOADDSINGLE.FLO_MEAS_ID::VARCHAR 
        || ':' || IP_FLO_GP_DATA.FLO_MEAS_NAME         AS DEVICE_SOURCE_VALUE,
    NULL                                                AS UNIT_SOURCE_VALUE,    -- NEW 5.4

    -- Additional Fields for Stage
    PAT_ENC.PAT_ENC_CSN_ID                             AS PULL_CSN_ID,
    IP_LDA_NOADDSINGLE.FLO_MEAS_ID::VARCHAR            AS PULL_FLO_MEAS_ID,
    IP_FLO_GP_DATA.FLO_MEAS_NAME                       AS PULL_FLO_MEAS_NAME

FROM CARE_BRONZE_CLARITY_PROD.DBO.PAT_ENC AS PAT_ENC

    -- Join to associate anesthesia event to hospital encounter
    INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.F_AN_RECORD_SUMMARY AS F_AN_RECORD_SUMMARY
        ON PAT_ENC.PAT_ENC_CSN_ID = F_AN_RECORD_SUMMARY.AN_52_ENC_CSN_ID

    INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.AN_HSB_LINK_INFO AS AN_HSB_LINK_INFO
        ON F_AN_RECORD_SUMMARY.AN_EPISODE_ID = AN_HSB_LINK_INFO.SUMMARY_BLOCK_ID

    INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.PAT_ENC_HSP AS PAT_ENC_HSP
        ON AN_HSB_LINK_INFO.AN_BILLING_CSN_ID = PAT_ENC_HSP.PAT_ENC_CSN_ID

    -- Join LDA related tables
    INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.IP_LDA_NOADDSINGLE AS IP_LDA_NOADDSINGLE
        ON PAT_ENC.PAT_ENC_CSN_ID = IP_LDA_NOADDSINGLE.PAT_ENC_CSN_ID

    INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.IP_FLO_GP_DATA AS IP_FLO_GP_DATA
        ON IP_LDA_NOADDSINGLE.FLO_MEAS_ID = IP_FLO_GP_DATA.FLO_MEAS_ID

    INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP.PATIENT_DRIVER AS PATIENT_DRIVER
        ON PATIENT_DRIVER.EHR_PATIENT_ID = PAT_ENC.PAT_ID

WHERE PLACEMENT_INSTANT IS NOT NULL;