/*******************************************************************************
* Script Name: PULL_VISIT_OCCURRENCE_AMB
* Description: Retrieves ambulatory visit occurrence data for OMOP CDM
* 
* Tables Used:
*   - CARE_BRONZE_CLARITY_PROD.DBO.PAT_ENC
*   - CARE_BRONZE_CLARITY_PROD.DBO.PAT_ENC_2
*   - CARE_BRONZE_CLARITY_PROD.DBO.PAT_OR_ADM_LINK
*   - CARE_BRONZE_CLARITY_PROD.DBO.CLARITY_LOC
*   - CARE_BRONZE_CLARITY_PROD.DBO.CLARITY_SER
*   - CARE_BRONZE_CLARITY_PROD.DBO.ZC_DISP_ENC_TYPE
*   - CARE_BRONZE_CLARITY_PROD.DBO.ZC_CALCULATED_ENC_STAT
*   - CARE_BRONZE_CLARITY_PROD.DBO.ZC_APPT_STATUS
*   - CARE_RES_OMOP_DEV2_WKSP.OMOP.PATIENT_DRIVER
*******************************************************************************/

SELECT DISTINCT
    -- Stage Attributes
    PATIENT_DRIVER.PERSON_ID::NUMBER(28,0)          AS PERSON_ID,
    CAST(COALESCE(PAT_ENC.CHECKIN_TIME,
        PAT_ENC.APPT_TIME,
        PAT_ENC.CONTACT_DATE) AS DATE)              AS VISIT_START_DATE,
    COALESCE(PAT_ENC.CHECKIN_TIME,
        PAT_ENC.APPT_TIME,
        PAT_ENC.CONTACT_DATE)                       AS VISIT_START_DATETIME,
    
    -- Visit End Date Logic
    CASE
        WHEN COALESCE(CHECKOUT_TIME,
                COALESCE(PAT_ENC.CHECKIN_TIME,
                        PAT_ENC.APPT_TIME,
                        PAT_ENC.CONTACT_DATE)) > 
             COALESCE(PAT_ENC.CHECKIN_TIME,
                    PAT_ENC.APPT_TIME,
                    PAT_ENC.CONTACT_DATE)
        THEN CAST(COALESCE(CHECKOUT_TIME,
                COALESCE(PAT_ENC.CHECKIN_TIME,
                        PAT_ENC.APPT_TIME,
                        PAT_ENC.CONTACT_DATE)) AS DATE)
        ELSE CAST(COALESCE(PAT_ENC.CHECKIN_TIME,
                        PAT_ENC.APPT_TIME,
                        PAT_ENC.CONTACT_DATE) AS DATE)
    END                                             AS VISIT_END_DATE,
    
    -- Visit End Datetime Logic
    CASE
        WHEN COALESCE(CHECKOUT_TIME,
                COALESCE(PAT_ENC.CHECKIN_TIME,
                        PAT_ENC.APPT_TIME,
                        PAT_ENC.CONTACT_DATE)) > 
             COALESCE(PAT_ENC.CHECKIN_TIME,
                    PAT_ENC.APPT_TIME,
                    PAT_ENC.CONTACT_DATE)
        THEN COALESCE(CHECKOUT_TIME,
                COALESCE(PAT_ENC.CHECKIN_TIME,
                        PAT_ENC.APPT_TIME,
                        PAT_ENC.CONTACT_DATE))
        ELSE COALESCE(PAT_ENC.CHECKIN_TIME,
                    PAT_ENC.APPT_TIME,
                    PAT_ENC.CONTACT_DATE)
    END                                             AS VISIT_END_DATETIME,
    ZC_DISP_ENC_TYPE.NAME                          AS VISIT_SOURCE_VALUE,

    -- Additional Attributes
    PATIENT_DRIVER.EHR_PATIENT_ID                  AS PULL_PAT_ID,
    PATIENT_DRIVER.MRN_CPI                         AS PULL_MRN_CPI,
    PAT_ENC.PAT_ENC_CSN_ID                        AS PULL_CSN_ID,
    PAT_ENC.PRIMARY_LOC_ID                        AS PULL_CARE_SITE_ID,
    COALESCE(VISIT_PROVIDER.PROV_ID, 
            PCP_PROVIDER.PROV_ID)                  AS PULL_PROVIDER_SOURCE_VALUE,
    PAT_ENC.ENC_TYPE_C                            AS PULL_ENC_TYPE_C

FROM CARE_BRONZE_CLARITY_PROD.DBO.PAT_ENC AS PAT_ENC
    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.PAT_ENC_2 AS PAT_ENC_2
        ON PAT_ENC.PAT_ENC_CSN_ID = PAT_ENC_2.IP_DOC_CONTACT_CSN
    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.PAT_OR_ADM_LINK AS PAT_OR_ADM_LINK
        ON PAT_ENC.PAT_ENC_CSN_ID = PAT_OR_ADM_LINK.PAT_ENC_CSN_ID
    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.CLARITY_LOC AS CLARITY_LOC
        ON PAT_ENC.PRIMARY_LOC_ID = CLARITY_LOC.LOC_ID
    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.CLARITY_SER AS VISIT_PROVIDER
        ON PAT_ENC.VISIT_PROV_ID = VISIT_PROVIDER.PROV_ID
    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.CLARITY_SER AS PCP_PROVIDER
        ON PAT_ENC.PCP_PROV_ID = PCP_PROVIDER.PROV_ID
    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_DISP_ENC_TYPE AS ZC_DISP_ENC_TYPE
        ON PAT_ENC.ENC_TYPE_C = ZC_DISP_ENC_TYPE.DISP_ENC_TYPE_C
    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_CALCULATED_ENC_STAT AS ZC_CALCULATED_ENC_STAT
        ON PAT_ENC.CALCULATED_ENC_STAT_C = ZC_CALCULATED_ENC_STAT.CALCULATED_ENC_STAT_C
    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_APPT_STATUS AS ZC_APPT_STATUS
        ON PAT_ENC.APPT_STATUS_C = ZC_APPT_STATUS.APPT_STATUS_C
    INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP.PATIENT_DRIVER AS PATIENT_DRIVER
        ON PAT_ENC.PAT_ID = PATIENT_DRIVER.EHR_PATIENT_ID

WHERE PAT_ENC.ENC_TYPE_C <> 3
    AND (PAT_ENC.CALCULATED_ENC_STAT_C = 2
        OR PAT_ENC.CALCULATED_ENC_STAT_C IS NULL)
    AND (PAT_ENC.APPT_STATUS_C = 2
        OR PAT_ENC.APPT_STATUS_C IS NULL);