--STAGE_CARE_SITE_ALL
{#-- {{ config(materialized = 'view', schema = 'OMOP_STAGE') }}#}
SELECT DISTINCT
    PULL_CARE_SITE_ALL.CARE_SITE_ID                                        AS CARE_SITE_ID
    , PULL_CARE_SITE_ALL.CARE_SITE_NAME                                    AS CARE_SITE_NAME
    , COALESCE(SOURCE_TO_CONCEPT_MAP_POS.TARGET_CONCEPT_ID, 0)             AS PLACE_OF_SERVICE_CONCEPT_ID
    , LOCATION.LOCATION_ID                                                 AS LOCATION_ID
    , LEFT(CAST(CARE_SITE_ID AS VARCHAR) || ':' || CARE_SITE_NAME, 50)     AS CARE_SITE_SOURCE_VALUE
    , LEFT(CARE_SITE_ID,50)                                                AS PLACE_OF_SERVICE_SOURCE_VALUE

FROM {{ ref('PULL_CARE_SITE_ALL')}} AS PULL_CARE_SITE_ALL
	LEFT JOIN {{ ref('LOCATION_RAW')}}	 as LOCATION --SH_OMOP_DB_PROD.CDM.location
		ON LOCATION.LOCATION_SOURCE_VALUE = PULL_CARE_SITE_ALL.CARE_SITE_LOCATION_SOURCE_VALUE
  LEFT JOIN {{ ref('SOURCE_TO_CONCEPT_MAP_POS')}}	AS SOURCE_TO_CONCEPT_MAP_POS
      ON SOURCE_TO_CONCEPT_MAP_POS.SOURCE_CODE = PULL_CARE_SITE_ALL.POS_TYPE



