/*******************************************************************************
* Script Name: PULL_DRUG_EXPOSURE_ALL_IMM
* Description: Retrieves drug exposure data related to immunizations
* 
* Tables Used:
*   - CARE_BRONZE_CLARITY_PROD.DBO.IMMUNE
*   - CARE_BRONZE_CLARITY_PROD.DBO.CLARITY_IMMUNZATN
*   - CARE_BRONZE_CLARITY_PROD.DBO.PAT_ENC
*   - CARE_BRONZE_CLARITY_PROD.DBO.PAT_ENC_HSP
*   - CARE_BRONZE_CLARITY_PROD.DBO.ZC_MED_UNIT
*   - CARE_BRONZE_CLARITY_PROD.DBO.RX_NDC
*   - CARE_BRONZE_CLARITY_PROD.DBO.ORDER_MED
*   - CARE_BRONZE_CLARITY_PROD.DBO.ZC_ROUTE
*   - CARE_RES_OMOP_DEV2_WKSP.OMOP.PATIENT_DRIVER
*******************************************************************************/

SELECT
    -- OMOP Standard Fields
    PATIENT_DRIVER.PERSON_ID                          	AS PERSON_ID,
    IMMUNE.IMMUNE_DATE::DATE                          	AS DRUG_EXPOSURE_START_DATE,
    COALESCE(IMMUNE.IMMUNIZATION_TIME,
             IMMUNE.IMMUNE_DATE)::DATETIME            	AS DRUG_EXPOSURE_START_DATETIME,
    ZC_MED_UNIT.NAME                         			AS DOSE_UNIT_SOURCE_VALUE,
    LTRIM(RTRIM(LOT))                                	AS LOT_NUMBER,
    ORDER_MED.AUTHRZING_PROV_ID                      	AS PROVIDER_SOURCE_VALUE,

    -- Additional Attributes
    PAT_ENC.PAT_ENC_CSN_ID                              AS PULL_CSN_ID,
    IMMUNE.IMMUNE_ID                               		AS PULL_IMMUNE_ID,
    IMMUNE.IMMUNZATN_ID                                 AS PULL_IMMUNZATN_ID,
    CLARITY_IMMUNZATN.NAME                 				AS PULL_CLARITY_IMMUNZATN_NAME,
    COALESCE(IMMUNE.ROUTE_C, 
             CLARITY_IMMUNZATN.ROUTE_C)                 AS PULL_ROUTE_C,
    ZC_ROUTE.NAME                             			AS PULL_ZC_ROUTE_NAME,
    CLARITY_IMMUNZATN.CVX_CODE                         	AS PULL_CLARITY_CVX_CODE,
    RX_NDC.RAW_11_DIGIT_NDC                           	AS PULL_RX_NDC_RAW_11_DIGIT_NDC

FROM CARE_BRONZE_CLARITY_PROD.DBO.IMMUNE AS IMMUNE
    INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.CLARITY_IMMUNZATN AS CLARITY_IMMUNZATN
        ON IMMUNE.IMMUNZATN_ID = CLARITY_IMMUNZATN.IMMUNZATN_ID
    INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.PAT_ENC AS PAT_ENC
        ON PAT_ENC.PAT_ENC_CSN_ID = IMMUNE.IMM_CSN
    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.PAT_ENC_HSP AS PAT_ENC_HSP
        ON PAT_ENC_HSP.PAT_ENC_CSN_ID = IMMUNE.IMM_CSN
    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_MED_UNIT AS ZC_MED_UNIT
        ON IMMUNE.IMMNZTN_DOSE_UNIT_C = ZC_MED_UNIT.DISP_QTYUNIT_C
    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.RX_NDC AS RX_NDC
        ON IMMUNE.NDC_NUM_ID = RX_NDC.NDC_ID
    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ORDER_MED AS ORDER_MED
        ON IMMUNE.ORDER_ID = ORDER_MED.ORDER_MED_ID
    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_ROUTE AS ZC_ROUTE
        ON COALESCE(IMMUNE.ROUTE_C, CLARITY_IMMUNZATN.ROUTE_C) = ZC_ROUTE.ROUTE_C
    INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP.PATIENT_DRIVER AS PATIENT_DRIVER
        ON (PATIENT_DRIVER.EHR_PATIENT_ID = IMMUNE.PAT_ID)

WHERE IMMUNE.IMMNZTN_STATUS_C = 1 
    AND ORDER_MED.ORDER_MED_ID IS NULL;