/*******************************************************************************
* Script Name: PULL_DRUG_EXPOSURE_HOSP_RXNORM
* Description: Retrieves drug exposure data for hospital visits with RxNorm codes
* 
* Tables Used:
*   - PULL_VISIT_OCCURRENCE_HSP
*   - ORDER_MED
*   - CLARITY_MEDICATION
*   - MAR_ADMIN_INFO
*   - RXNORM_CODES
*   - ZC_MED_UNIT
*   - ZC_RSN_FOR_DISCON
*   - ZC_ADMIN_ROUTE
*   - ZC_RXNORM_TERM_TYPE
*******************************************************************************/

SELECT DISTINCT
    -- OMOP Standard Fields
    PULL_VISIT_OCCURRENCE_HSP.PERSON_ID                     AS PERSON_ID,
    MAR_ADMIN_INFO.TAKEN_TIME::DATE                        AS DRUG_EXPOSURE_START_DATE,
    MAR_ADMIN_INFO.TAKEN_TIME                              AS DRUG_EXPOSURE_START_DATETIME,
    CAST(
        CASE
            WHEN (COALESCE(ORDER_END_TIME, TAKEN_TIME)::DATE = TAKEN_TIME::DATE)
                AND (COALESCE(ORDER_END_TIME, TAKEN_TIME) < TAKEN_TIME)
                THEN TAKEN_TIME
            ELSE COALESCE(ORDER_END_TIME, TAKEN_TIME)
        END AS DATE
    )                                                       AS DRUG_EXPOSURE_END_DATE,
    CASE
        WHEN (COALESCE(ORDER_END_TIME, TAKEN_TIME)::DATE = TAKEN_TIME::DATE)
            AND (COALESCE(ORDER_END_TIME, TAKEN_TIME) < TAKEN_TIME)
            THEN TAKEN_TIME
        ELSE COALESCE(ORDER_END_TIME, TAKEN_TIME)
    END                                                     AS DRUG_EXPOSURE_END_DATETIME,
    ORDER_MED.END_DATE                                     AS VERBATIM_END_DATE,
    LEFT(ZC_RSN_FOR_DISCON.NAME, 20)                       AS STOP_REASON,
    CASE
        WHEN TRY_CAST(ORDER_MED.REFILLS AS NUMERIC) IS NULL
            THEN NULL
        ELSE ORDER_MED.REFILLS
    END                                                     AS REFILLS,
    CASE
        WHEN TRY_TO_NUMERIC(
            LEFT(QUANTITY, CHARINDEX(' ', QUANTITY))) IS NULL
            OR UPPER(ZC_MED_UNIT.NAME) = 'APPLICATION'
            THEN 1
        ELSE LEFT(QUANTITY, CHARINDEX(' ', QUANTITY))::FLOAT
    END                                                     AS QUANTITY,
    NULL                                                    AS DAYS_SUPPLY,
    MAR_ADMIN_INFO.SIG                                     AS SIG,
    NULL                                                    AS LOT_NUMBER,
    ORDER_MED.AUTHRZING_PROV_ID                           AS PROVIDER_SOURCE_VALUE,
    ZC_MED_UNIT.NAME                                       AS DOSE_UNIT_SOURCE_VALUE,

    -- Additional Attributes
    PULL_VISIT_OCCURRENCE_HSP.PULL_CSN_ID                  AS PULL_CSN_ID,
    CLARITY_MEDICATION.MEDICATION_ID                       AS PULL_MEDICATION_ID,
    CLARITY_MEDICATION.NAME                                AS PULL_MEDICATION_NAME,
    ORDER_MED.MED_ROUTE_C                                 AS PULL_MED_ROUTE_C,
    ZC_ADMIN_ROUTE.NAME                                    AS PULL_ZC_ADMIN_ROUTE_NAME,
    RXNORM_CODES.RXNORM_CODE                              AS PULL_RXNORM_CODE,
    RXNORM_CODES.LINE                                      AS PULL_RXNORM_CODES_LINE

FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.PULL_VISIT_OCCURRENCE_HSP AS PULL_VISIT_OCCURRENCE_HSP

INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.ORDER_MED AS ORDER_MED
    ON ORDER_MED.PAT_ENC_CSN_ID = PULL_VISIT_OCCURRENCE_HSP.PULL_CSN_ID

INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.CLARITY_MEDICATION AS CLARITY_MEDICATION
    ON ORDER_MED.MEDICATION_ID = CLARITY_MEDICATION.MEDICATION_ID

INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.MAR_ADMIN_INFO AS MAR_ADMIN_INFO
    ON ORDER_MED.ORDER_MED_ID = MAR_ADMIN_INFO.ORDER_MED_ID

INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.RXNORM_CODES AS RXNORM_CODES
    ON ORDER_MED.MEDICATION_ID = RXNORM_CODES.MEDICATION_ID

INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_MED_UNIT AS ZC_MED_UNIT
    ON ORDER_MED.HV_DOSE_UNIT_C = ZC_MED_UNIT.DISP_QTYUNIT_C

LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_RSN_FOR_DISCON AS ZC_RSN_FOR_DISCON
    ON ORDER_MED.RSN_FOR_DISCON_C = ZC_RSN_FOR_DISCON.RSN_FOR_DISCON_C

LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_ADMIN_ROUTE AS ZC_ADMIN_ROUTE
    ON ORDER_MED.MED_ROUTE_C = ZC_ADMIN_ROUTE.MED_ROUTE_C

INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_RXNORM_TERM_TYPE AS ZC_RXNORM_TERM_TYPE
    ON RXNORM_CODES.RXNORM_TERM_TYPE_C = ZC_RXNORM_TERM_TYPE.RXNORM_TERM_TYPE_C

WHERE TAKEN_TIME IS NOT NULL
    AND ORDER_STATUS_C NOT IN (
        4,  -- CANCELED
        6,  -- HOLDING
        7,  -- DENIED
        8,  -- SUSPEND
        9   -- DISCONTINUED
    )
    AND MAR_ACTION_C NOT IN (
        2,  -- Missed
        4,  -- Canceled Entry
        8,  -- Stopped
        15  -- See Alternative
    )
    AND RXNORM_CODES.RXNORM_TERM_TYPE_C <> 2  -- PRECISE INGREDIENT