--  OBSERVATION_PERIOD (derived)
--https://ohdsi.github.io/CommonDataModel/cdm54.html#observation_period
{{ config(materialized = 'table', schema = 'OMOP') }}

WITH MIN_AND_MAX_VISITS as (
    SELECT PERSON_ID        AS PERSON_ID
	, min(VISIT_START_DATE) AS OBSERVATION_PERIOD_START_DATE
	, max(VISIT_END_DATE)   AS OBSERVATION_PERIOD_END_DATE
    , 32817                 AS PERIOD_TYPE_CONCEPT_ID
    FROM
	    {{ref('VISIT_OCCURRENCE_RAW')}} AS VISIT_OCCURRENCE
    GROUP BY ALL)

SELECT
     {{ sequence_get_nextval() }}::NUMBER(28,0) AS OBSERVATION_PERIOD_ID
    , PERSON_ID::NUMBER(28,0)                   AS PERSON_ID
	, OBSERVATION_PERIOD_START_DATE::DATE       AS OBSERVATION_PERIOD_START_DATE
	, OBSERVATION_PERIOD_END_DATE::DATE         AS OBSERVATION_PERIOD_END_DATE
    , PERIOD_TYPE_CONCEPT_ID::NUMBER(28,0)      AS PERIOD_TYPE_CONCEPT_ID
FROM MIN_AND_MAX_VISITS

