
--BEGIN cte__T_DRUG_CONCEPT
    SELECT C2.CONCEPT_ID AS DRUG_CONCEPT_ID
        ,C1.CONCEPT_ID AS DRUG_CONCEPT_SOURCE_CONCEPT_ID

    FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_CLARITY.CONCEPT_stg AS C1
    INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP_CLARITY.CONCEPT_RELATIONSHIP_stg AS CR
        ON C1.CONCEPT_ID = CR.CONCEPT_ID_1
            AND UPPER(CR.RELATIONSHIP_ID) = 'MAPS TO'
    INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP_CLARITY.CONCEPT_stg AS C2
        ON C2.CONCEPT_ID = CR.CONCEPT_ID_2
    WHERE C2.STANDARD_CONCEPT = 'S'
        AND (
            C2.INVALID_REASON IS NULL
            OR C2.INVALID_REASON = ''
            )
        AND UPPER(C2.DOMAIN_ID) = 'DRUG'
--END cte__T_DRUG_CONCEPT
--