-- PULL_NOTE_HOSP_ALL


SELECT DISTINCT
-- ***STAGE ATTRIBUTES***
-- OMOP Standard fields used for the Stage
	Z_NOTE_LOOKUP.PERSON_ID 							AS PERSON_ID
	,Z_NOTE_LOOKUP.ENTRY_INSTANT_DTTM::DATE				AS NOTE_DATE
	,Z_NOTE_LOOKUP.ENTRY_INSTANT_DTTM 					AS NOTE_DATETIME
	,Z_NOTE_LOOKUP.ZC_NOTE_TYPE_IP_NAME 				AS NOTE_TITLE
	-- ******************************************
	--   ,'NO_TEXT' AS NOTE_TEXT	-- NO ACTUAL TEXT IS BEING WRITTEN AT THIS TIME OVER PHI CONCERNS
	-- ******************************************
	,PULL_VISIT_OCCURRENCE_HSP.PULL_PROVIDER_SOURCE_VALUE 	AS PROVIDER_SOURCE_VALUE
	,Z_NOTE_LOOKUP.IP_NOTE_TYPE_C
		|| ':' || Z_NOTE_LOOKUP.AMB_NOTE_YN
		|| ':' || Z_NOTE_LOOKUP.ZC_NOTE_TYPE_IP_NAME 	AS NOTE_SOURCE_VALUE

-- ***ADDITIONAL ATTRIBUTES***
-- Non_OMOP fields used for the Stage
	,PULL_VISIT_OCCURRENCE_HSP.PULL_CSN_ID 			AS PULL_CSN_ID
	,Z_NOTE_LOOKUP.IP_NOTE_TYPE_C					AS PULL_IP_NOTE_TYPE_C
	,Z_NOTE_LOOKUP.AMB_NOTE_YN						AS PULL_AMB_NOTE_YN
	,Z_NOTE_LOOKUP.NOTE_ID							AS PULL_NOTE_ID
--	,Z_NOTE_LOOKUP.LINE								AS PULL_NOTE_LINE
	,Z_NOTE_LOOKUP.CONTACT_DATE_REAL 				AS PULL_CONTACT_DATE_REAL

FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.PULL_VISIT_OCCURRENCE_HSP AS PULL_VISIT_OCCURRENCE_HSP

	INNER JOIN  CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.Z_NOTE_LOOKUP AS Z_NOTE_LOOKUP
           ON  PULL_VISIT_OCCURRENCE_HSP.PULL_CSN_ID= Z_NOTE_LOOKUP.PAT_ENC_CSN_ID

    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.HSP_ATND_PROV AS HSP_ATND_PROV
            ON PULL_VISIT_OCCURRENCE_HSP.PULL_CSN_ID = HSP_ATND_PROV.PAT_ENC_CSN_ID
                AND PULL_VISIT_OCCURRENCE_HSP.VISIT_END_DATE BETWEEN ATTEND_FROM_DATE
                    AND COALESCE(ATTEND_TO_DATE, GETDATE())

    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.HSP_ACCOUNT AS HSP_ACCOUNT
            ON PULL_VISIT_OCCURRENCE_HSP.PULL_HSP_ACCOUNT_ID = HSP_ACCOUNT.HSP_ACCOUNT_ID

WHERE Z_NOTE_LOOKUP.ENTRY_INSTANT_DTTM IS NOT NULL