
--SPECIMEN_CLARITY_ALL
{#-- {{ config(materialized = 'view', schema = 'OMOP_PULL') }}#}

SELECT DISTINCT
-- ***STAGE ATTRIBUTES***
-- fields used for the Stage
    PATIENT_DRIVER.PERSON_ID
    , COALESCE(SPEC_DTM_COLLECTED, SPEC_DTM_RECEIVED)::DATE     AS SPECIMEN_DATE
    , COALESCE(SPEC_DTM_COLLECTED, SPEC_DTM_RECEIVED)::DATETIME AS SPECIMEN_DATETIME
    , SPEC_DB_MAIN.SPECIMEN_ID                                  AS SPECIMEN_SOURCE_ID
    , HSC_SPEC_INFO.SPECIMEN_TYPE_C||':'||ZC_SPECIMEN_TYPE_NAME AS SPECIMEN_SOURCE_VALUE
    , SPEC_DB_MAIN.SPEC_SOURCE_C||':'||ZC_SPEC_SOURCE_NAME      AS ANATOMIC_SITE_SOURCE_VALUE
    , HSC_SPEC_INFO.SPECIMEN_SIZE                               AS QUANTITY -- MISSING FROM HSC_SPEC_INFO

-- ***PULL attributes***
    , PATIENT_DRIVER.EHR_PATIENT_ID                             AS PULL_PAT_ID
    , PATIENT_DRIVER.MRN_CPI                                    AS PULL_MRN_CPI
    , HSC_SPEC_INFO.SPECIMEN_TYPE_C::VARCHAR                    AS PULL_SPECIMEN_TYPE_SOURCE_CODE
    , SPEC_DB_MAIN.SPEC_SOURCE_C::VARCHAR                       AS PULL_SPECIMEN_ANATOMIC_SITE_SOURCE_CODE

FROM   {{ ref('PATIENT_stg')}} AS PATIENT

	INNER JOIN   {{ ref('SPEC_DB_MAIN_stg')}} AS SPEC_DB_MAIN
		ON SPEC_DB_MAIN.SPEC_EPT_PAT_ID = PATIENT.PAT_ID

	INNER JOIN  {{ ref('ZC_SPEC_SOURCE_stg')}} AS ZC_SPEC_SOURCE
		ON SPEC_DB_MAIN.SPEC_SOURCE_C = ZC_SPEC_SOURCE.SPEC_SOURCE_C

	INNER JOIN   {{ ref('HSC_SPEC_INFO_stg')}} AS HSC_SPEC_INFO
		ON SPEC_DB_MAIN.SPECIMEN_COL_ID = HSC_SPEC_INFO.RECORD_ID

	LEFT JOIN   {{ ref('ZC_SPECIMEN_TYPE_stg')}} AS ZC_SPECIMEN_TYPE
		ON HSC_SPEC_INFO.SPECIMEN_TYPE_C = ZC_SPECIMEN_TYPE.SPECIMEN_TYPE_C

	LEFT JOIN   {{ref('ZC_SPECIMEN_UNIT_stg')}} AS ZC_SPECIMEN_UNIT
		ON HSC_SPEC_INFO.SPECIMEN_UNIT_C = ZC_SPECIMEN_UNIT.SPECIMEN_UNIT_C

    INNER JOIN {{ref('PATIENT_DRIVER')}} AS PATIENT_DRIVER
        ON PATIENT_DRIVER.EHR_PATIENT_ID = PATIENT.PAT_ID

WHERE COALESCE(SPEC_DB_MAIN.SPEC_DTM_COLLECTED, SPEC_DB_MAIN.SPEC_DTM_RECEIVED) IS NOT NULL
