--QA_PERSON_WO_VISIT_COUNT
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH TMP_WO_VISIT AS (
SELECT
    PERSON_RAW.PERSON_ID AS CDT_ID
FROM {{ref('PERSON_RAW')}} AS PERSON_RAW
    LEFT JOIN {{ref('VISIT_OCCURRENCE_RAW')}} AS VISIT_OCCURRENCE_RAW
        		ON PERSON_RAW.person_ID = VISIT_OCCURRENCE_RAW.PERSON_ID
WHERE VISIT_OCCURRENCE_RAW.PERSON_ID IS null
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	, 'PERSON'   AS STANDARD_DATA_TABLE
	, 'WO_VISIT' AS QA_METRIC
	, 'RECORDS'  AS METRIC_FIELD
	, 'FATAL'    AS ERROR_TYPE
	, CDT_ID
FROM TMP_WO_VISIT
