--QA_PERSON_WO_VISIT_COUNT
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH TMP_WO_VISIT AS (
SELECT COUNT(*) AS CNT
FROM {{ref('PERSON_RAW')}} AS PERSON_RAW
    LEFT JOIN {{ref('VISIT_OCCURRENCE_RAW')}} AS VISIT_OCCURRENCE_RAW
        		ON PERSON_RAW.person_ID = VISIT_OCCURRENCE_RAW.PERSON_ID
WHERE VISIT_OCCURRENCE_RAW.PERSON_ID IS null
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'PERSON' AS STANDARD_DATA_TABLE
	, 'WO_VISIT' AS QA_METRIC
	, 'RECORDS'  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) IS NOT NULL THEN 'FATAL' ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('PERSON_RAW')}}) AS TOTAL_RECORDS
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('PERSON')}}) AS TOTAL_RECORDS_CLEAN
FROM TMP_WO_VISIT
