-- QA_PERSON_ZEROCONCEPT_DETAIL
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH ZEROCONCEPT_DETAIL AS (

	SELECT 'GENDER_CONCEPT_ID' AS METRIC_FIELD,'ZERO CONCEPT' AS QA_METRIC,'WARNING' AS ERROR_TYPE
		,PERSON_ID AS CDT_ID
	FROM {{ref('PERSON_RAW')}} AS T1
	WHERE (GENDER_CONCEPT_ID = 0 )
UNION ALL
	SELECT 'RACE_CONCEPT_ID' AS METRIC_FIELD,'ZERO CONCEPT' AS QA_METRIC,'WARNING' AS ERROR_TYPE
		,PERSON_ID AS CDT_ID
	FROM {{ref('PERSON_RAW')}} AS T1
	WHERE (RACE_CONCEPT_ID = 0 )
UNION ALL
	SELECT 'ETHNICITY_CONCEPT_ID' AS METRIC_FIELD,'ZERO CONCEPT' AS QA_METRIC,'WARNING' AS ERROR_TYPE
		,PERSON_ID AS CDT_ID
	FROM {{ref('PERSON_RAW')}} AS T1
	WHERE (ETHNICITY_CONCEPT_ID = 0 )
UNION ALL
	SELECT 'GENDER_SOURCE_CONCEPT_ID' AS METRIC_FIELD,'ZERO CONCEPT' AS QA_METRIC,'EXPECTED' AS ERROR_TYPE
		,PERSON_ID AS CDT_ID
	FROM {{ref('PERSON_RAW')}} AS T1
	WHERE (GENDER_SOURCE_CONCEPT_ID = 0 )
UNION ALL
	SELECT 'RACE_SOURCE_CONCEPT_ID' AS METRIC_FIELD,'ZERO CONCEPT' AS QA_METRIC,'EXPECTED' AS ERROR_TYPE
		,PERSON_ID AS CDT_ID
	FROM {{ref('PERSON_RAW')}} AS T1
	WHERE (RACE_SOURCE_CONCEPT_ID = 0 )
UNION ALL
	SELECT 'ETHNICITY_SOURCE_CONCEPT_ID' AS METRIC_FIELD,'ZERO CONCEPT' AS QA_METRIC,'EXPECTED' AS ERROR_TYPE
		,PERSON_ID AS CDT_ID
	FROM {{ref('PERSON_RAW')}} AS T1
	WHERE (ETHNICITY_SOURCE_CONCEPT_ID = 0 )
	)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'PERSON' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM ZEROCONCEPT_DETAIL
  WHERE ERROR_TYPE <>'EXPECTED'
