--QA_PERSON_AGE_ERR_COUNT
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH AGE_ERR_COUNT AS (
	SELECT
        'UNDER18' AS AGE,
        SUM(CASE WHEN (DATEDIFF(YEAR,  BIRTH_DATETIME, GETDATE())<18) THEN 1 ELSE 0 END) AS CNT
    FROM
       {{ref('PERSON_RAW')}} AS T1
UNION ALL
    SELECT
        'OVER120' AS AGE,
        SUM(CASE WHEN (DATEDIFF(YEAR,  BIRTH_DATETIME, GETDATE())>120) THEN 1 ELSE 0 END) AS CNT
    FROM
       {{ref('PERSON_RAW')}} AS T1
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'PERSON' AS STANDARD_DATA_TABLE
	, 'WRONG AGE:'|| AGE AS QA_METRIC
	, 'BIRTH_DATETIME'  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) <>0 THEN 'WARNING' ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('PERSON_RAW')}}) AS TOTAL_RECORDS
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('PERSON')}}) AS TOTAL_RECORDS_CLEAN
FROM AGE_ERR_COUNT
GROUP BY AGE

