
--BEGIN cte__SOURCE_TO_CONCEPT_MAP_XRF_INFERRED_UNIT
    SELECT *
    FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_CLARITY.SOURCE_TO_CONCEPT_MAP_stg
    WHERE SOURCE_VOCABULARY_ID = 'SH_XRF_INFERRED_UNIT'
--END cte__SOURCE_TO_CONCEPT_MAP_XRF_INFERRED_UNIT
--