
--BEGIN cte__T_LOINC_SOURCE
SELECT CONCEPT_ID
    ,CONCEPT_CODE

FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_CLARITY.CONCEPT_stg AS C
WHERE (
        C.INVALID_REASON IS NULL
        OR C.INVALID_REASON = ''
        )
    AND UPPER(C.DOMAIN_ID) = 'MEASUREMENT'
    AND UPPER(VOCABULARY_ID) = 'LOINC'
    AND UPPER(CONCEPT_CLASS_ID) = 'LAB TEST'
--END cte__T_LOINC_SOURCE
--