
with __dbt__cte__SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_TEMP as (

--BEGIN cte__SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_TEMP
    SELECT *
    FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_CLARITY.SOURCE_TO_CONCEPT_MAP_stg
    WHERE SOURCE_VOCABULARY_ID = 'SH_FLWSHT_MEAS_TEMP'
--END cte__SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_TEMP
--
) --BEGIN cte__T_TEMPERATURE_AMB
    SELECT DISTINCT PERSON_ID
        ,PAT_ENC_CSN_ID
        ,RECORDED_TIME
        ,MEAS_VALUE
        ,MINVALUE
        ,MAX_VAL
        ,FLO_MEAS_NAME
        ,FLO_MEAS_ID
        ,FSD_ID
        ,VISIT_PROV_ID
        ,PCP_PROV_ID
        ,ENC_TYPE_C
        ,UNITS

    FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.PULL_MEASUREMENT_AMB_FLOWSHEET AS PULL_MEASUREMENT_AMB_FLOWSHEET
        INNER JOIN __dbt__cte__SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_TEMP AS SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS
            ON FLO_MEAS_ID::VARCHAR = SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS.SOURCE_CODE
--END cte__T_TEMPERATURE_AMB
--