-- T_TEMP_SOURCE_AMB


--BEGIN cte__T_TEMP_SOURCE_AMB
    SELECT DISTINCT PERSON_ID
        ,PAT_ENC_CSN_ID
        ,RECORDED_TIME
        ,MEAS_VALUE AS MEAS_VALUE

    FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.PULL_MEASUREMENT_AMB_FLOWSHEET AS PULL_MEASUREMENT_AMB_FLOWSHEET
    WHERE FLO_MEAS_ID IN ('7')
--END cte__T_TEMP_SOURCE_AMB
--