/***************************************************************
 * DRUG_EXPOSURE Table Population Script
 * 
 * This script populates the DRUG_EXPOSURE table by combining data
 * from multiple staging tables including ambulatory, anesthesia,
 * hospital, and immunization drug exposures.
 * 
 * The script uses UNION ALL to combine records from different
 * source tables while maintaining consistent field structure.
 ***************************************************************/

SELECT DISTINCT
    -- Primary and Foreign Keys
    CARE_RES_OMOP_DEV2_WKSP.OMOP.DRUG_EXPOSURE_RAW_SEQ.nextval::NUMBER(28,0)  AS DRUG_EXPOSURE_ID
    , PERSON_ID::NUMBER(28,0)                   AS PERSON_ID
    , DRUG_CONCEPT_ID::NUMBER(28,0)             AS DRUG_CONCEPT_ID
    
    -- DateTime Fields
    , DRUG_EXPOSURE_START_DATE::DATE            AS DRUG_EXPOSURE_START_DATE
    , DRUG_EXPOSURE_START_DATETIME::DATETIME    AS DRUG_EXPOSURE_START_DATETIME
    , DRUG_EXPOSURE_END_DATE::DATE              AS DRUG_EXPOSURE_END_DATE
    , DRUG_EXPOSURE_END_DATETIME::DATETIME      AS DRUG_EXPOSURE_END_DATETIME
    , VERBATIM_END_DATE::DATE                   AS VERBATIM_END_DATE
    
    -- Drug Details
    , DRUG_TYPE_CONCEPT_ID::NUMBER(28,0)        AS DRUG_TYPE_CONCEPT_ID
    , STOP_REASON::VARCHAR(20)                  AS STOP_REASON
    , REFILLS::NUMBER(28,0)                     AS REFILLS
    , QUANTITY::FLOAT                           AS QUANTITY
    , DAYS_SUPPLY::NUMBER(28,0)                 AS DAYS_SUPPLY
    , SIG::VARCHAR                              AS SIG
    , ROUTE_CONCEPT_ID::NUMBER(28,0)            AS ROUTE_CONCEPT_ID
    , LOT_NUMBER::VARCHAR(50)                   AS LOT_NUMBER
    
    -- Related IDs
    , PROVIDER_ID::NUMBER(28,0)                 AS PROVIDER_ID
    , VISIT_OCCURRENCE_ID::NUMBER(28,0)         AS VISIT_OCCURRENCE_ID
    , VISIT_DETAIL_ID::NUMBER(28,0)             AS VISIT_DETAIL_ID
    
    -- Source Values
    , DRUG_SOURCE_VALUE::VARCHAR(250)           AS DRUG_SOURCE_VALUE    -- Human readable Source Value
    , DRUG_SOURCE_CONCEPT_ID::NUMBER(28,0)      AS DRUG_SOURCE_CONCEPT_ID
    , ROUTE_SOURCE_VALUE::VARCHAR(50)           AS ROUTE_SOURCE_VALUE
    , DOSE_UNIT_SOURCE_VALUE::VARCHAR(50)       AS DOSE_UNIT_SOURCE_VALUE

    -- Non-OMOP Fields
    , ETL_MODULE::VARCHAR                       AS etl_MODULE
    , STAGE_PAT_ID::VARCHAR                     AS phi_PAT_ID
    , STAGE_MRN_CPI::NUMBER(28,0)              AS phi_MRN_CPI
    , STAGE_CSN_ID::NUMBER(28,0)               AS phi_CSN_ID
    
    -- Source Tracking Fields
    , SRC_TABLE::VARCHAR                        AS src_TABLE
    , SRC_FIELD::VARCHAR                        AS src_FIELD
    , SRC_VALUE_ID::VARCHAR                     AS src_VALUE_ID

FROM
(
    -- Ambulatory Drug Exposures
    SELECT PERSON_ID, DRUG_CONCEPT_ID, DRUG_EXPOSURE_START_DATE, DRUG_EXPOSURE_START_DATETIME, DRUG_EXPOSURE_END_DATE
        , DRUG_EXPOSURE_END_DATETIME, VERBATIM_END_DATE, DRUG_TYPE_CONCEPT_ID, STOP_REASON, REFILLS, QUANTITY, DAYS_SUPPLY, SIG
        , ROUTE_CONCEPT_ID, LOT_NUMBER, PROVIDER_ID, VISIT_OCCURRENCE_ID, VISIT_DETAIL_ID, DRUG_SOURCE_VALUE, DRUG_SOURCE_CONCEPT_ID
        , ROUTE_SOURCE_VALUE, DOSE_UNIT_SOURCE_VALUE
        , ETL_MODULE, STAGE_PAT_ID, STAGE_MRN_CPI, STAGE_CSN_ID
        , 'ORDER_MED' as SRC_TABLE, 'MEDICATION_ID' AS SRC_FIELD, STAGE_MEDICATION_ID::INTEGER AS SRC_VALUE_ID
    FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_STAGE.STAGE_DRUG_EXPOSURE_AMB_RXNORM
    
    UNION ALL
    
    -- Anesthesia Drug Exposures
    SELECT PERSON_ID, DRUG_CONCEPT_ID, DRUG_EXPOSURE_START_DATE, DRUG_EXPOSURE_START_DATETIME, DRUG_EXPOSURE_END_DATE
        , DRUG_EXPOSURE_END_DATETIME, VERBATIM_END_DATE, DRUG_TYPE_CONCEPT_ID, STOP_REASON, REFILLS, QUANTITY, DAYS_SUPPLY, SIG
        , ROUTE_CONCEPT_ID, LOT_NUMBER, PROVIDER_ID, VISIT_OCCURRENCE_ID, VISIT_DETAIL_ID, DRUG_SOURCE_VALUE, DRUG_SOURCE_CONCEPT_ID
        , ROUTE_SOURCE_VALUE, DOSE_UNIT_SOURCE_VALUE
        , ETL_MODULE, STAGE_PAT_ID, STAGE_MRN_CPI, STAGE_CSN_ID
        , 'ORDER_MED' as SRC_TABLE, 'MEDICATION_ID' AS SRC_FIELD, STAGE_MEDICATION_ID::INTEGER AS SRC_VALUE_ID
    FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_STAGE.STAGE_DRUG_EXPOSURE_ANES_RXNORM
    
    UNION ALL
    
    -- Hospital Drug Exposures
    SELECT PERSON_ID, DRUG_CONCEPT_ID, DRUG_EXPOSURE_START_DATE, DRUG_EXPOSURE_START_DATETIME, DRUG_EXPOSURE_END_DATE
        , DRUG_EXPOSURE_END_DATETIME, VERBATIM_END_DATE, DRUG_TYPE_CONCEPT_ID, STOP_REASON, REFILLS, QUANTITY, DAYS_SUPPLY, SIG
        , ROUTE_CONCEPT_ID, LOT_NUMBER, PROVIDER_ID, VISIT_OCCURRENCE_ID, VISIT_DETAIL_ID, DRUG_SOURCE_VALUE, DRUG_SOURCE_CONCEPT_ID
        , ROUTE_SOURCE_VALUE, DOSE_UNIT_SOURCE_VALUE, ETL_MODULE, STAGE_PAT_ID, STAGE_MRN_CPI, STAGE_CSN_ID
        , 'ORDER_MED' as SRC_TABLE, 'MEDICATION_ID' AS SRC_FIELD, STAGE_MEDICATION_ID::INTEGER AS SRC_VALUE_ID
    FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_STAGE.STAGE_DRUG_EXPOSURE_HSP_RXNORM
    
    UNION ALL
    
    -- Immunization Drug Exposures
    SELECT PERSON_ID, DRUG_CONCEPT_ID, DRUG_EXPOSURE_START_DATE, DRUG_EXPOSURE_START_DATETIME, DRUG_EXPOSURE_END_DATE
        , DRUG_EXPOSURE_END_DATETIME, VERBATIM_END_DATE, DRUG_TYPE_CONCEPT_ID, STOP_REASON, REFILLS, QUANTITY, DAYS_SUPPLY, SIG
        , ROUTE_CONCEPT_ID, LOT_NUMBER, PROVIDER_ID, VISIT_OCCURRENCE_ID, VISIT_DETAIL_ID, DRUG_SOURCE_VALUE, DRUG_SOURCE_CONCEPT_ID
        , ROUTE_SOURCE_VALUE, DOSE_UNIT_SOURCE_VALUE, ETL_MODULE, STAGE_PAT_ID, STAGE_MRN_CPI, STAGE_CSN_ID
        , 'IMMUNE' as SRC_TABLE, 'IMMUNZATN_ID' AS SRC_FIELD, STAGE_MEDICATION_ID::INTEGER AS SRC_VALUE_ID
    FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_STAGE.STAGE_DRUG_EXPOSURE_ALL_IMM
) AS A