/***************************************************************
 * Query: PULL_MEASUREMENT_ANES_FLOWSHEET
 * Description: Retrieves measurement data from anesthesia flowsheets
 * Tables Used:
 *   - PULL_VISIT_OCCURRENCE_AMB
 *   - F_AN_RECORD_SUMMARY
 *   - AN_HSB_LINK_INFO
 *   - PAT_ENC_HSP
 *   - IP_DATA_STORE
 *   - IP_FLWSHT_REC
 *   - IP_FLWSHT_MEAS
 *   - IP_FLO_GP_DATA
 *   - ZC_VAL_TYPE
 ***************************************************************/

SELECT DISTINCT
    -- OMOP Standard Fields
    PULL_VISIT_OCCURRENCE_AMB.PERSON_ID                       AS PERSON_ID,
    IP_FLWSHT_MEAS.RECORDED_TIME::DATE                       AS MEASUREMENT_DATE,
    IP_FLWSHT_MEAS.RECORDED_TIME                            AS MEASUREMENT_DATETIME,
    CASE
        WHEN IP_FLWSHT_MEAS.MEAS_VALUE LIKE '>=%' THEN 4171755
        WHEN IP_FLWSHT_MEAS.MEAS_VALUE LIKE '<=%' THEN 4171754
        WHEN IP_FLWSHT_MEAS.MEAS_VALUE LIKE '<%'  THEN 4171756
        WHEN IP_FLWSHT_MEAS.MEAS_VALUE LIKE '>%'  THEN 4172704
        ELSE 4172703
    END                                                      AS OPERATOR_CONCEPT_ID,
    REPLACE(REPLACE(REPLACE(IP_FLWSHT_MEAS.MEAS_VALUE, 
        '=', ''), '<', ''), '>', '')                        AS VALUE_AS_NUMBER,
    IP_FLO_GP_DATA.MINVALUE                                 AS RANGE_LOW,
    IP_FLO_GP_DATA.MAX_VAL                                  AS RANGE_HIGH,
    IP_FLO_GP_DATA.UNITS                                    AS UNIT_SOURCE_VALUE,
    IP_FLWSHT_MEAS.MEAS_VALUE                              AS VALUE_SOURCE_VALUE,
    PULL_VISIT_OCCURRENCE_AMB.PULL_PROVIDER_SOURCE_VALUE    AS PROVIDER_SOURCE_VALUE,

    -- Additional Fields
    PAT_ENC_HSP.PAT_ENC_CSN_ID                             AS PULL_CSN_ID,
    IP_FLO_GP_DATA.FLO_MEAS_ID                             AS PULL_FLO_MEAS_ID,
    IP_FLO_GP_DATA.FLO_MEAS_NAME                           AS PULL_FLO_MEAS_NAME,
    PULL_VISIT_OCCURRENCE_AMB.PULL_ENC_TYPE_C              AS PULL_ENC_TYPE_C   

FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.PULL_VISIT_OCCURRENCE_AMB AS PULL_VISIT_OCCURRENCE_AMB

-- Join to associate anesthesia record to hospital encounter
INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.F_AN_RECORD_SUMMARY AS F_AN_RECORD_SUMMARY 
    ON PULL_VISIT_OCCURRENCE_AMB.PULL_CSN_ID = F_AN_RECORD_SUMMARY.AN_52_ENC_CSN_ID

INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.AN_HSB_LINK_INFO AS AN_HSB_LINK_INFO 
    ON F_AN_RECORD_SUMMARY.AN_EPISODE_ID = AN_HSB_LINK_INFO.SUMMARY_BLOCK_ID

INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.PAT_ENC_HSP AS PAT_ENC_HSP 
    ON AN_HSB_LINK_INFO.AN_BILLING_CSN_ID = PAT_ENC_HSP.PAT_ENC_CSN_ID

-- Join to get flowsheet data
LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.IP_DATA_STORE AS IP_DATA_STORE
    ON PULL_VISIT_OCCURRENCE_AMB.PULL_CSN_ID = IP_DATA_STORE.EPT_CSN

LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.IP_FLWSHT_REC AS IP_FLWSHT_REC
    ON IP_DATA_STORE.INPATIENT_DATA_ID = IP_FLWSHT_REC.INPATIENT_DATA_ID

LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.IP_FLWSHT_MEAS AS IP_FLWSHT_MEAS
    ON IP_FLWSHT_REC.FSD_ID = IP_FLWSHT_MEAS.FSD_ID

INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.IP_FLO_GP_DATA AS IP_FLO_GP_DATA
    ON IP_FLWSHT_MEAS.FLO_MEAS_ID = IP_FLO_GP_DATA.FLO_MEAS_ID

INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_VAL_TYPE AS ZC_VAL_TYPE
    ON IP_FLO_GP_DATA.VAL_TYPE_C = ZC_VAL_TYPE.VAL_TYPE_C

WHERE PULL_VISIT_OCCURRENCE_AMB.PULL_ENC_TYPE_C = 52  -- Filter for Anesthesia encounters only