/******************************************************************************
* Script Name: PULL_MEASUREMENT_HOSP_LOINC
* Description: Retrieves measurement data from hospital LOINC codes
* 
* Tables Used:
*     - PULL_VISIT_OCCURRENCE_HSP
*     - ORDER_PROC
*     - ORDER_PROC_2
*     - ORDER_RESULTS
*     - CLARITY_SER
*     - LNC_DB_MAIN
*     - ZC_RESULT_FLAG
*     - ZC_RESULT_STATUS
*     - ZC_ORDER_STATUS
******************************************************************************/

SELECT DISTINCT
    -- Stage Attributes
    PULL_VISIT_OCCURRENCE_HSP.PERSON_ID                     AS PERSON_ID,
    CAST(COALESCE(ORDER_PROC_2.SPECIMN_TAKEN_TIME,
                  ORDER_PROC.ORDER_TIME) AS DATE)           AS MEASUREMENT_DATE,
    COALESCE(ORDER_PROC_2.SPECIMN_TAKEN_TIME,
             ORDER_PROC.ORDER_TIME)                         AS MEASUREMENT_DATETIME,

    -- Operator Concept ID determination
    CASE
        WHEN ORDER_RESULTS.ORD_VALUE LIKE '>=%' THEN 4171755
        WHEN ORDER_RESULTS.ORD_VALUE LIKE '<=%' THEN 4171754
        WHEN ORDER_RESULTS.ORD_VALUE LIKE '<%'  THEN 4171756
        WHEN ORDER_RESULTS.ORD_VALUE LIKE '>%'  THEN 4172704
        ELSE 4172703
    END                                                     AS OPERATOR_CONCEPT_ID,

    -- Value processing
    CASE
        WHEN TRY_TO_NUMERIC(REPLACE(REPLACE(REPLACE(REPLACE(ORD_VALUE,
             '=', ''), '<', ''), '>', ''), ',', '')) IS NULL THEN NULL
        ELSE REPLACE(REPLACE(REPLACE(REPLACE(ORD_VALUE,
             '=', ''), '<', ''), '>', ''), ',', '')
    END                                                     AS VALUE_AS_NUMBER,

    -- Reference range processing
    CASE
        WHEN TRY_TO_NUMERIC(REPLACE(REPLACE(REPLACE(REPLACE(ORDER_RESULTS.REFERENCE_LOW,
             '=', ''), '<', ''), '>', ''), ',', '')) IS NULL THEN NULL
        ELSE CAST(REPLACE(REPLACE(REPLACE(REPLACE(ORDER_RESULTS.REFERENCE_LOW,
             '=', ''), '<', ''), '>', ''), ',', '') AS FLOAT)
    END                                                     AS RANGE_LOW,

    CASE
        WHEN TRY_TO_NUMERIC(REPLACE(REPLACE(REPLACE(REPLACE(ORDER_RESULTS.REFERENCE_HIGH,
             '=', ''), '<', ''), '>', ''), ',', '')) IS NULL THEN NULL
        ELSE CAST(REPLACE(REPLACE(REPLACE(REPLACE(ORDER_RESULTS.REFERENCE_HIGH,
             '=', ''), '<', ''), '>', ''), ',', '') AS FLOAT)
    END                                                     AS RANGE_HIGH,

    -- Source values
    LNC_DB_MAIN.LNC_CODE || ':' || LNC_DB_MAIN.LNC_COMPON AS MEASUREMENT_SOURCE_VALUE,
    ORDER_RESULTS.REFERENCE_UNIT                          AS UNIT_SOURCE_VALUE,
    ORDER_RESULTS.ORD_VALUE                               AS VALUE_SOURCE_VALUE,
    AUTH_PROVIDER.PROV_ID                                 AS PROVIDER_SOURCE_VALUE,

    -- Additional attributes
    PULL_VISIT_OCCURRENCE_HSP.PULL_CSN_ID                AS PULL_CSN_ID,
    LNC_DB_MAIN.LNC_CODE                                 AS PULL_LNC_CODE,
    LNC_DB_MAIN.RECORD_ID                                AS PULL_RECORD_ID

FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.PULL_VISIT_OCCURRENCE_HSP AS PULL_VISIT_OCCURRENCE_HSP

    INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.ORDER_PROC AS ORDER_PROC
        ON PULL_VISIT_OCCURRENCE_HSP.PULL_CSN_ID = ORDER_PROC.PAT_ENC_CSN_ID

    INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.ORDER_PROC_2 AS ORDER_PROC_2
        ON ORDER_PROC.ORDER_PROC_ID = ORDER_PROC_2.ORDER_PROC_ID

    INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.ORDER_RESULTS AS ORDER_RESULTS
        ON ORDER_PROC.ORDER_PROC_ID = ORDER_RESULTS.ORDER_PROC_ID

    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.CLARITY_SER AS AUTH_PROVIDER
        ON ORDER_PROC.AUTHRZING_PROV_ID = AUTH_PROVIDER.PROV_ID

    INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.LNC_DB_MAIN AS LNC_DB_MAIN
        ON ORDER_RESULTS.COMPON_LNC_ID = LNC_DB_MAIN.RECORD_ID

    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_RESULT_FLAG AS ZC_RESULT_FLAG
        ON ORDER_RESULTS.RESULT_FLAG_C = ZC_RESULT_FLAG.RESULT_FLAG_C

    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_RESULT_STATUS AS ZC_RESULT_STATUS
        ON ORDER_RESULTS.RESULT_STATUS_C = ZC_RESULT_STATUS.RESULT_STATUS_C

    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_ORDER_STATUS AS ZC_ORDER_STATUS
        ON ORDER_PROC.ORDER_STATUS_C = ZC_ORDER_STATUS.ORDER_STATUS_C

WHERE (ZC_ORDER_STATUS.NAME <> 'Canceled');