
--QA_CARE_SITE_DUPLICATES_DETAIL
---------------------------------------------------------------------
{# --{{ config(materialized = 'view') }} #}

WITH TMP_DUPES AS (
SELECT  PLACE_OF_SERVICE_CONCEPT_ID, LOCATION_ID, PLACE_OF_SERVICE_SOURCE_VALUE,
        CARE_SITE_NAME, CARE_SITE_SOURCE_VALUE,
        COUNT(*) AS CNT
FROM {{ref('CARE_SITE_RAW')}} AS T1
GROUP BY  PLACE_OF_SERVICE_CONCEPT_ID, LOCATION_ID, PLACE_OF_SERVICE_SOURCE_VALUE,
        CARE_SITE_NAME, CARE_SITE_SOURCE_VALUE
HAVING COUNT(*) > 1
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	, 'CARE_SITE' AS STANDARD_DATA_TABLE
	, 'DUPLICATE ' AS QA_METRIC
	, 'RECORDS'  AS METRIC_FIELD
	, 'FATAL' AS ERROR_TYPE
	, CS.CARE_SITE_ID
FROM TMP_DUPES AS D
INNER JOIN {{ref('CARE_SITE_RAW')}} AS CS ON
	 COALESCE(D.CARE_SITE_NAME, '0') = COALESCE(CS.CARE_SITE_NAME, '0')
        AND COALESCE(D.PLACE_OF_SERVICE_CONCEPT_ID, 0) = COALESCE(CS.PLACE_OF_SERVICE_CONCEPT_ID, 0)
        AND COALESCE(D.LOCATION_ID, 0) = COALESCE(CS.LOCATION_ID, 0)
        AND COALESCE(D.CARE_SITE_SOURCE_VALUE, '0') = COALESCE(CS.CARE_SITE_SOURCE_VALUE, '0')
        AND COALESCE(D.PLACE_OF_SERVICE_SOURCE_VALUE, '0') = COALESCE(CS.PLACE_OF_SERVICE_SOURCE_VALUE, '0')
