--QA_CARE_SITE_ZERO_CONCEPT_DETAIL
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH CTE_ZERO_CONCEPT_COUNT AS (
	SELECT 'CARE_SITE' AS STANDARD_DATA_TABLE
		,'PLACE_OF_SERVICE_CONCEPT_ID' AS METRIC_FIELD
		,'ZERO CONCEPT' AS QA_METRIC
		,'WARNING' AS ERROR_TYPE
		,COUNT(*) AS CNT
	FROM {{ref('CARE_SITE_RAW')}} AS CARE_SITE
	WHERE (PLACE_OF_SERVICE_CONCEPT_ID = 0 )
)

SELECT CAST( GETDATE() AS DATE) AS RUN_DATE
	, STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) <> 0 THEN ERROR_TYPE ELSE NULL END   AS ERROR_TYPE
	,(SELECT COUNT(*) AS NUM_ROWS FROM {{ref('CARE_SITE_RAW')}}) AS TOTAL_RECORDS
	,(SELECT COUNT(*) AS NUM_ROWS FROM {{ref('CARE_SITE')}}) AS TOTAL_RECORDS_CLEAN
FROM CTE_ZERO_CONCEPT_COUNT
GROUP BY STANDARD_DATA_TABLE, METRIC_FIELD, QA_METRIC, ERROR_TYPE
