--QA_CARE_SITE_ZERO_CONCEPT_DETAIL
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH CTE_ZERO_CONCEPT_DETAIL AS (
	SELECT 'CARE_SITE' AS STANDARD_DATA_TABLE
		,'PLACE_OF_SERVICE_CONCEPT_ID' AS METRIC_FIELD
		,'ZERO CONCEPT' AS QA_METRIC
		,'WARNING' AS ERROR_TYPE
		, CARE_SITE_ID AS CDT_ID
	FROM {{ref('CARE_SITE_RAW')}} AS CARE_SITE
	WHERE (PLACE_OF_SERVICE_CONCEPT_ID = 0 )
)

SELECT CAST( GETDATE() AS DATE) AS RUN_DATE
	, STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM CTE_ZERO_CONCEPT_DETAIL
  WHERE ERROR_TYPE <>'EXPECTED'
