
--QA_CARE_SITE_DUPLICATES_COUNT
---------------------------------------------------------------------
{# --{{ config(materialized = 'view') }} #}

WITH TMP_DUPES AS (
SELECT  PLACE_OF_SERVICE_CONCEPT_ID, LOCATION_ID, PLACE_OF_SERVICE_SOURCE_VALUE,
        CARE_SITE_NAME, CARE_SITE_SOURCE_VALUE,
        COUNT(*) AS CNT
FROM {{ref('CARE_SITE_RAW')}} AS T1
GROUP BY  PLACE_OF_SERVICE_CONCEPT_ID, LOCATION_ID, PLACE_OF_SERVICE_SOURCE_VALUE,
        CARE_SITE_NAME, CARE_SITE_SOURCE_VALUE
HAVING COUNT(*) > 1
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	, 'CARE_SITE' AS STANDARD_DATA_TABLE
	, 'DUPLICATE' AS QA_METRIC
	, 'RECORDS'  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) IS NOT NULL THEN 'FATAL' ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('CARE_SITE_RAW')}}) AS TOTAL_RECORDS
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('CARE_SITE')}}) AS TOTAL_RECORDS_CLEAN
FROM TMP_DUPES
