--QA_CARE_SITE_NON_STANDARD_DETAIL
---------------------------------------------------------------------
{# --{{ config(materialized = 'view') }} #}

WITH CTE_NON_STANDARD_DETAIL AS
(
	SELECT CAST(  GETDATE()AS DATE) AS RUN_DATE
		,'CARE_SITE' AS  STANDARD_DATA_TABLE
		,'NON-STANDARD' AS  QA_METRIC
		,'PLACE_OF_SERVICE_CONCEPT_ID'   AS METRIC_FIELD
		,'INVALID DATA' AS ERROR_TYPE
		,CARE_SITE_ID AS CDT_ID
	FROM
       {{ref('CARE_SITE_RAW')}} AS P
	LEFT JOIN
       {{ source('OMOP','CONCEPT')}} AS  C
		ON
			P. PLACE_OF_SERVICE_CONCEPT_ID =C.CONCEPT_ID AND upper(C.DOMAIN_ID) =  'PLACE OF SERVICE'
	WHERE  PLACE_OF_SERVICE_CONCEPT_ID  <> 0 AND STANDARD_CONCEPT <>'S'
)

--INSERT INTO OMOP_QA.QA_ERR (RUN_DATE ,STANDARD_DATA_TABLE ,QA_METRIC , METRIC_FIELD ,ERROR_TYPE ,CDT_ID)
	SELECT  RUN_DATE, STANDARD_DATA_TABLE, QA_METRIC,  METRIC_FIELD,ERROR_TYPE, CDT_ID
	FROM CTE_NON_STANDARD_DETAIL
  WHERE ERROR_TYPE <>'EXPECTED'
