
with __dbt__cte__SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_TEMP as (

--BEGIN cte__SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_TEMP
    SELECT *
    FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_CLARITY.SOURCE_TO_CONCEPT_MAP_stg
    WHERE SOURCE_VOCABULARY_ID = 'SH_FLWSHT_MEAS_TEMP'
--END cte__SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_TEMP
--
) --BEGIN cte__T_ANES_TEMPERATURE
    SELECT DISTINCT PERSON_ID
           ,PULL_CSN_ID
            ,MEASUREMENT_DATE
            ,MEASUREMENT_DATETIME
            ,VALUE_SOURCE_VALUE
            ,VALUE_AS_NUMBER
            ,RANGE_LOW
            ,RANGE_HIGH
            ,PULL_FLO_MEAS_ID
            ,PULL_FLO_MEAS_NAME
            ,PROVIDER_SOURCE_VALUE
            ,UNIT_SOURCE_VALUE
        FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.PULL_MEASUREMENT_ANES_FLOWSHEET AS PULL_MEASUREMENT_ANES_FLOWSHEET
        INNER JOIN __dbt__cte__SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_TEMP AS SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS
            ON PULL_FLO_MEAS_ID::VARCHAR = SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS.SOURCE_CODE
--END cte__T_ANES_TEMPERATURE
--