
------ QA_DEATH_NULL_CONCEPT_COUNT
---------------------------------------------------------------------
WITH NULLCONCEPT_COUNT AS (
	SELECT 'DEATH_TYPE_CONCEPT_ID' AS METRIC_FIELD,'NULL CONCEPT' AS QA_METRIC,'FATAL' AS ERROR_TYPE
		,COUNT(*) AS CNT
	FROM {{ref('DEATH_RAW')}} AS T1
	WHERE (DEATH_TYPE_CONCEPT_ID IS NULL)
-- UNION ALL
-- 	SELECT 'CAUSE_SOURCE_CONCEPT_ID' AS METRIC_FIELD,'NULL CONCEPT' AS QA_METRIC,'EXPECTED' AS ERROR_TYPE
-- 		,COUNT(*) AS CNT
-- 	FROM {{ref('DEATH_RAW')}} AS T1
-- 	WHERE (CAUSE_SOURCE_CONCEPT_ID IS NULL)
)

SELECT CAST( GETDATE() AS DATE) AS RUN_DATE
	,'DEATH' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) <> 0 THEN ERROR_TYPE ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('DEATH_RAW')}}) AS TOTAL_RECORDS
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('DEATH')}}) AS TOTAL_RECORDS_CLEAN
FROM NULLCONCEPT_COUNT
GROUP BY METRIC_FIELD, QA_METRIC, ERROR_TYPE
