
------ QA_DEATH_NULL_DEATHDATE_COUNT
---------------------------------------------------------------------
WITH NULLDEATHDATE_COUNT AS (
	SELECT 'DEATH_DATE' AS METRIC_FIELD,'NULL DATE' AS QA_METRIC,'FATAL' AS ERROR_TYPE
		,COUNT(*) AS CNT
	FROM {{ref('DEATH_RAW')}} AS T1
	WHERE (DEATH_DATE IS NULL)
-- UNION ALL
-- 	SELECT 'DEATH_DATETIME' AS METRIC_FIELD,'NULL DATE' AS QA_METRIC,'FATAL' AS ERROR_TYPE
-- 		,COUNT(*) AS CNT
-- 	FROM {{ref('DEATH_RAW')}}  AS T1
-- 	WHERE (DEATH_DATETIME IS NULL)
)

SELECT CAST( GETDATE() AS DATE) AS RUN_DATE
	,'DEATH' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) <> 0 THEN ERROR_TYPE ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('DEATH_RAW')}}) AS TOTAL_RECORDS
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('DEATH')}}) AS TOTAL_RECORDS_CLEAN
FROM NULLDEATHDATE_COUNT
GROUP BY METRIC_FIELD, QA_METRIC, ERROR_TYPE
