
--QA_DEATH_DUPLICATES_DETAIL
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH TMP_DUPES AS (
SELECT  PERSON_ID
    ,DEATH_DATE
	,DEATH_DATETIME
	,DEATH_TYPE_CONCEPT_ID
	,CAUSE_CONCEPT_ID
	,CAUSE_SOURCE_VALUE
	,CAUSE_SOURCE_CONCEPT_ID
	,COUNT(*) AS CNT
FROM {{ref('DEATH_RAW')}} AS T1
GROUP BY  PERSON_ID
    ,DEATH_DATE
	,DEATH_DATETIME
	,DEATH_TYPE_CONCEPT_ID
	,CAUSE_CONCEPT_ID
	,CAUSE_SOURCE_VALUE
	,CAUSE_SOURCE_CONCEPT_ID
HAVING COUNT(*) > 1
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'DEATH' AS STANDARD_DATA_TABLE
	, 'DUPLICATE' AS QA_METRIC
	, 'RECORDS'  AS METRIC_FIELD
	, 'FATAL' AS ERROR_TYPE
	, DE.PERSON_ID

FROM TMP_DUPES AS D
INNER JOIN {{ref('DEATH_RAW')}} AS DE ON D.DEATH_DATE = DE.DEATH_DATE
	AND COALESCE(D.DEATH_DATETIME,'1900-01-01') = COALESCE(DE.DEATH_DATETIME,'1900-01-01')
	AND COALESCE(D.DEATH_TYPE_CONCEPT_ID, 0) = COALESCE(DE.DEATH_TYPE_CONCEPT_ID, 0)
	AND COALESCE(D.CAUSE_CONCEPT_ID, 0) = COALESCE(DE.CAUSE_CONCEPT_ID, 0)
	AND COALESCE(D.CAUSE_SOURCE_VALUE, '0') = COALESCE(DE.CAUSE_SOURCE_VALUE, '0')
	AND COALESCE(D.CAUSE_SOURCE_CONCEPT_ID, 0) = COALESCE(DE.CAUSE_SOURCE_CONCEPT_ID, 0)

