
------ QA_DEATH_NULL_DEATHDATE_DETAIL
---------------------------------------------------------------------
WITH NULLDEATHDATE_DETAIL AS (
	SELECT 'DEATH_DATE' AS METRIC_FIELD,'NULL DATE' AS QA_METRIC,'FATAL' AS ERROR_TYPE
		,PERSON_ID AS CDT_ID
	FROM {{ref('DEATH_RAW')}} AS T1
	WHERE (DEATH_DATE IS NULL)
-- UNION ALL
-- 	SELECT 'DEATH_DATETIME' AS METRIC_FIELD,'NULL DATE' AS QA_METRIC,'FATAL' AS ERROR_TYPE
-- 		,PERSON_ID AS CDT_ID
-- 	FROM {{ref('DEATH_RAW')}}  AS T1
-- 	WHERE (DEATH_DATETIME IS NULL)
)

SELECT CAST( GETDATE() AS DATE) AS RUN_DATE
	,'DEATH' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NULLDEATHDATE_DETAIL
  WHERE ERROR_TYPE <>'EXPECTED'
