
------ QA_DEATH_NULL_CONCEPT_DETAIL
---------------------------------------------------------------------
WITH NULLCONCEPT_DETAIL AS (
	SELECT 'DEATH_TYPE_CONCEPT_ID' AS METRIC_FIELD,'NULL CONCEPT' AS QA_METRIC,'FATAL' AS ERROR_TYPE
		,PERSON_ID AS CDT_ID
	FROM {{ref('DEATH_RAW')}} AS T1
	WHERE (DEATH_TYPE_CONCEPT_ID IS NULL)
-- UNION ALL
-- 	SELECT 'CAUSE_SOURCE_CONCEPT_ID' AS METRIC_FIELD,'NULL CONCEPT' AS QA_METRIC,'EXPECTED' AS ERROR_TYPE
-- 		,PERSON_ID AS CDT_ID
-- 	FROM {{ref('DEATH_RAW')}}  AS T1
-- 	WHERE (CAUSE_SOURCE_CONCEPT_ID IS NULL)
)

SELECT CAST( GETDATE() AS DATE) AS RUN_DATE
	,'DEATH' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NULLCONCEPT_DETAIL
  WHERE ERROR_TYPE <>'EXPECTED'
