
-- QA_DEATH_ZERO_CONCEPT_DETAIL
---------------------------------------------------------------------
WITH ZEROCONCEPT_DETAIL AS (
	SELECT 'DEATH_TYPE_CONCEPT_ID' AS METRIC_FIELD,'ZERO CONCEPT' AS QA_METRIC,'WARNING' AS ERROR_TYPE
		,PERSON_ID AS CDT_ID
	FROM {{ref('DEATH_RAW')}}  AS T1
	WHERE (DEATH_TYPE_CONCEPT_ID = 0 )
-- UNION ALL
-- 	SELECT 'CAUSE_SOURCE_CONCEPT_ID' AS METRIC_FIELD,'ZERO CONCEPT' AS QA_METRIC,'EXPECTED' AS ERROR_TYPE
-- 		,PERSON_ID AS CDT_ID
-- 	FROM {{ref('DEATH_RAW')}}  AS T1
-- 	WHERE (CAUSE_SOURCE_CONCEPT_ID = 0 )
)

SELECT CAST( GETDATE() AS DATE) AS RUN_DATE
	,'DEATH' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM ZEROCONCEPT_DETAIL
  WHERE ERROR_TYPE <>'EXPECTED'
