-- SQRY_SNOWFLAKE_DBT_COUNTS

{{ config(materialized = 'table', schema='OMOP_QA') }}

SELECT 'PULL_CARE_SITE_ALL' AS OMOP_CLARITY_TABLE, COUNT(*) AS TABLE_COUNT_DBT FROM {{ref('PULL_CARE_SITE_ALL')}} AS PULL_CARE_SITE_ALL
UNION ALL
SELECT 'PULL_CONDITION_OCCURRENCE_AMB_SNO', COUNT(*) FROM {{ref('PULL_CONDITION_OCCURRENCE_AMB_SNO')}} AS PULL_CONDITION_OCCURRENCE_AMB_SNO
UNION ALL
SELECT 'PULL_CONDITION_OCCURRENCE_HOSP_ADM_SNO', COUNT(*) FROM {{ref('PULL_CONDITION_OCCURRENCE_HOSP_ADM_SNO')}} AS PULL_CONDITION_OCCURRENCE_HOSP_ADM_SNO
UNION ALL
SELECT 'PULL_CONDITION_OCCURRENCE_HOSP_DISCH_SNO', COUNT(*) FROM {{ref('PULL_CONDITION_OCCURRENCE_HOSP_DISCH_SNO')}} AS PULL_CONDITION_OCCURRENCE_HOSP_DISCH_SNO
UNION ALL
SELECT 'PULL_CONDITION_OCCURRENCE_HOSP_FIN_SNO', COUNT(*) FROM {{ref('PULL_CONDITION_OCCURRENCE_HOSP_FIN_SNO')}} AS PULL_CONDITION_OCCURRENCE_HOSP_FIN_SNO
UNION ALL
SELECT 'PULL_CONDITION_OCCURRENCE_HOSP_PROB_SNO', COUNT(*) FROM {{ref('PULL_CONDITION_OCCURRENCE_HOSP_PROB_SNO')}} AS PULL_CONDITION_OCCURRENCE_HOSP_PROB_SNO
UNION ALL
SELECT 'PULL_DEATH_ALL', COUNT(*) FROM {{ref('PULL_DEATH_ALL')}} AS PULL_DEATH_ALL
UNION ALL
SELECT 'PULL_DEVICE_EXPOSURE_ANES_LDA', COUNT(*) FROM {{ref('PULL_DEVICE_EXPOSURE_ANES_LDA')}} AS PULL_DEVICE_EXPOSURE_ANES_LDA
UNION ALL
SELECT 'PULL_DEVICE_EXPOSURE_HOSP_BLOOD', COUNT(*) FROM {{ref('PULL_DEVICE_EXPOSURE_HOSP_BLOOD')}} AS PULL_DEVICE_EXPOSURE_HOSP_BLOOD
UNION ALL
SELECT 'PULL_DEVICE_EXPOSURE_HOSP_LDA', COUNT(*) FROM {{ref('PULL_DEVICE_EXPOSURE_HOSP_LDA')}} AS PULL_DEVICE_EXPOSURE_HOSP_LDA
UNION ALL
SELECT 'PULL_DRUG_EXPOSURE_AMB_RXNORM', COUNT(*) FROM {{ref('PULL_DRUG_EXPOSURE_AMB_RXNORM')}} AS PULL_DRUG_EXPOSURE_AMB_RXNORM
UNION ALL
SELECT 'PULL_DRUG_EXPOSURE_ANES_RXNORM', COUNT(*) FROM {{ref('PULL_DRUG_EXPOSURE_ANES_RXNORM')}} AS PULL_DRUG_EXPOSURE_ANES_RXNORM
UNION ALL
SELECT 'PULL_DRUG_EXPOSURE_HOSP_RXNORM', COUNT(*) FROM {{ref('PULL_DRUG_EXPOSURE_HOSP_RXNORM')}} AS PULL_DRUG_EXPOSURE_HOSP_RXNORM
-- UNION ALL
-- SELECT 'LOCATION_CLARITY_ALL', COUNT(*) FROM REF('V_LOCATION_ALL') AS LOCATION_CLARITY_ALL
UNION ALL
SELECT 'PULL_MEASUREMENT_AMB_FLOWSHEET', COUNT(*) FROM {{ref('PULL_MEASUREMENT_AMB_FLOWSHEET')}} AS PULL_MEASUREMENT_AMB_FLOWSHEET
UNION ALL
SELECT 'PULL_MEASUREMENT_AMB_LOINC', COUNT(*) FROM {{ref('PULL_MEASUREMENT_AMB_LOINC')}} AS PULL_MEASUREMENT_AMB_LOINC
UNION ALL
SELECT 'PULL_MEASUREMENT_ANES_FLOWSHEET', COUNT(*) FROM {{ref('PULL_MEASUREMENT_ANES_FLOWSHEET')}} AS PULL_MEASUREMENT_ANES_FLOWSHEET
UNION ALL
SELECT 'PULL_MEASUREMENT_HOSP_FLOWSHEET', COUNT(*) FROM {{ref('PULL_MEASUREMENT_HOSP_FLOWSHEET')}} AS PULL_MEASUREMENT_HOSP_FLOWSHEET
UNION ALL
SELECT 'PULL_MEASUREMENT_HOSP_LOINC', COUNT(*) FROM {{ref('PULL_MEASUREMENT_HOSP_LOINC')}} AS PULL_MEASUREMENT_HOSP_LOINC
UNION ALL
SELECT 'PULL_NOTE_AMB_ALL', COUNT(*) FROM {{ref('PULL_NOTE_AMB_ALL')}} AS PULL_NOTE_AMB_ALL
UNION ALL
SELECT 'PULL_NOTE_ANES_ALL', COUNT(*) FROM {{ref('PULL_NOTE_ANES_ALL')}} AS PULL_NOTE_ANES_ALL
UNION ALL
SELECT 'PULL_NOTE_HOSP_ALL', COUNT(*) FROM {{ref('PULL_NOTE_HOSP_ALL')}} AS PULL_NOTE_HOSP_ALL
UNION ALL
SELECT 'PULL_OBSERVATION_ALL_ALLERGY', COUNT(*) FROM {{ref('PULL_OBSERVATION_ALL_ALLERGY')}} AS PULL_OBSERVATION_ALL_ALLERGY
UNION ALL
SELECT 'PULL_OBSERVATION_AMB_ICD', COUNT(*) FROM {{ref('PULL_OBSERVATION_AMB_ICD')}} AS PULL_OBSERVATION_AMB_ICD
UNION ALL
SELECT 'PULL_OBSERVATION_HOSP_FLOWSHEET', COUNT(*) FROM {{ref('PULL_OBSERVATION_HOSP_FLOWSHEET')}} AS PULL_OBSERVATION_HOSP_FLOWSHEET
UNION ALL
SELECT 'PULL_OBSERVATION_HOSP_ICD', COUNT(*) FROM {{ref('PULL_OBSERVATION_HOSP_ICD')}} AS PULL_OBSERVATION_HOSP_ICD
UNION ALL
SELECT 'PULL_PERSON_ALL', COUNT(*) FROM {{ref('PULL_PERSON_ALL')}} AS PULL_PERSON_ALL
UNION ALL
SELECT 'PULL_PROCEDURE_OCCURRENCE_AMB_CPT', COUNT(*) FROM {{ref('PULL_PROCEDURE_OCCURRENCE_AMB_CPT')}} AS PULL_PROCEDURE_OCCURRENCE_AMB_CPT
UNION ALL
SELECT 'PULL_PROCEDURE_OCCURRENCE_HSP_CPT', COUNT(*) FROM {{ref('PULL_PROCEDURE_OCCURRENCE_HSP_CPT')}} AS PULL_PROCEDURE_OCCURRENCE_HSP_CPT
UNION ALL
SELECT 'PULL_PROCEDURE_OCCURRENCE_SURG_CPT', COUNT(*) FROM {{ref('PULL_PROCEDURE_OCCURRENCE_SURG_CPT')}} AS PULL_PROCEDURE_OCCURRENCE_SURG_CPT
UNION ALL
SELECT 'PULL_PROVIDER_ALL', COUNT(*) FROM {{ref('PULL_PROVIDER_ALL')}} AS PULL_PROVIDER_ALL
UNION ALL
SELECT 'PULL_SPECIMEN_ALL', COUNT(*) FROM {{ref('PULL_SPECIMEN_ALL')}} AS PULL_SPECIMEN_ALL
UNION ALL
SELECT 'PULL_VISIT_DETAIL_HOSP_ALL', COUNT(*) FROM {{ref('PULL_VISIT_DETAIL_HOSP_ALL')}} AS PULL_VISIT_DETAIL_HOSP_ALL
UNION ALL
SELECT 'PULL_VISIT_OCCURRENCE_AMB', COUNT(*) FROM {{ref('PULL_VISIT_OCCURRENCE_AMB')}} AS PULL_VISIT_OCCURRENCE_AMB
UNION ALL
SELECT 'PULL_VISIT_OCCURRENCE_HSP', COUNT(*) FROM {{ref('PULL_VISIT_OCCURRENCE_HSP')}} AS PULL_VISIT_OCCURRENCE_HSP
