--
--STAGE_MEASUREMENT_AMB_FLOWSHEET_BPS
{#-- {{ config(materialized = 'view', schema = 'OMOP_STAGE') }}#}

SELECT DISTINCT PULL_MEASUREMENT_AMB_FLOWSHEET.PERSON_ID 					AS PERSON_ID
	,COALESCE(SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS.TARGET_CONCEPT_ID, 0) 	AS MEASUREMENT_CONCEPT_ID
	,PULL_MEASUREMENT_AMB_FLOWSHEET.MEASUREMENT_DATE 						AS MEASUREMENT_DATE
	,PULL_MEASUREMENT_AMB_FLOWSHEET.MEASUREMENT_DATETIME 					AS MEASUREMENT_DATETIME
	,32817 																	AS MEASUREMENT_TYPE_CONCEPT_ID --EHR
	,PULL_MEASUREMENT_AMB_FLOWSHEET.OPERATOR_CONCEPT_ID 					AS OPERATOR_CONCEPT_ID
	,LEFT(VALUE_AS_NUMBER, CHARINDEX('/', VALUE_AS_NUMBER) - 1)::FLOAT      AS VALUE_AS_NUMBER --SYSTOLIC
	,NULL 																		AS VALUE_AS_CONCEPT_ID
    ,COALESCE(
		SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_UNITS.TARGET_CONCEPT_ID
			, 8876) 														AS UNIT_CONCEPT_ID --mm[Hg]
	,PULL_MEASUREMENT_AMB_FLOWSHEET.RANGE_LOW 								AS RANGE_LOW
	,PULL_MEASUREMENT_AMB_FLOWSHEET.RANGE_HIGH 								AS RANGE_HIGH
	,PROVIDER.PROVIDER_ID						                        	AS PROVIDER_ID
	,VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID 									AS VISIT_OCCURRENCE_ID

--    ,VISIT_DETAIL.VISIT_DETAIL_ID 										AS VISIT_DETAIL_ID
    ,NULL 																		AS VISIT_DETAIL_ID
	,PULL_FLO_MEAS_ID::VARCHAR ||':'|| PULL_FLO_MEAS_NAME                    AS MEASUREMENT_SOURCE_VALUE
	,NULL 																		AS MEASUREMENT_SOURCE_CONCEPT_ID
    ,COALESCE(
		SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_UNITS.SOURCE_CODE_DESCRIPTION
		, 'mm[Hg]') 														AS UNIT_SOURCE_VALUE
	,PULL_MEASUREMENT_AMB_FLOWSHEET.VALUE_SOURCE_VALUE 						AS VALUE_SOURCE_VALUE
    ,NULL 																		AS UNIT_SOURCE_CONCEPT_ID
    ,NULL 																	AS MEASUREMENT_EVENT_ID
    ,NULL 																		AS MEAS_EVENT_FIELD_CONCEPT_ID

	-------- Non-OMOP Fields ------------
	,'MEASUREMENT_AMB_FLOWSHEET_BPS'                               			AS ETL_MODULE
	,VISIT_OCCURRENCE.phi_PAT_ID                      						AS STAGE_PAT_ID
    ,VISIT_OCCURRENCE.phi_MRN_CPI                           				AS STAGE_MRN_CPI
	,VISIT_OCCURRENCE.phi_CSN_ID											AS STAGE_CSN_ID
	,PULL_FLO_MEAS_ID                          							    AS STAGE_FLO_MEAS_ID
	,PULL_FLO_MEAS_NAME                           							AS STAGE_FLO_MEAS_NAME

FROM {{ref('PULL_MEASUREMENT_AMB_FLOWSHEET')}} AS PULL_MEASUREMENT_AMB_FLOWSHEET

	INNER JOIN {{ ref('SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_BPS')}} AS  SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS
		ON PULL_MEASUREMENT_AMB_FLOWSHEET.PULL_FLO_MEAS_ID = SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS.SOURCE_CODE

	LEFT JOIN {{ ref('SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_UNITS')}} AS  SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_UNITS
		ON 	PULL_MEASUREMENT_AMB_FLOWSHEET.UNIT_SOURCE_VALUE  = SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_UNITS.SOURCE_CODE

    INNER JOIN {{ ref('SOURCE_TO_CONCEPT_MAP_AMB_VISIT')}} AS  SOURCE_TO_CONCEPT_MAP_AMB_VISIT
		ON	PULL_MEASUREMENT_AMB_FLOWSHEET.PULL_ENC_TYPE_C  =  SOURCE_TO_CONCEPT_MAP_AMB_VISIT.SOURCE_CODE

	INNER JOIN {{ref('VISIT_OCCURRENCE_RAW')}} AS VISIT_OCCURRENCE
		ON PULL_MEASUREMENT_AMB_FLOWSHEET.PULL_CSN_ID = VISIT_OCCURRENCE.phi_CSN_ID

    LEFT JOIN   {{ref('PROVIDER_RAW')}}  AS PROVIDER
        ON  PULL_MEASUREMENT_AMB_FLOWSHEET.PROVIDER_SOURCE_VALUE = PROVIDER.PROVIDER_SOURCE_VALUE
