------ QA_PROCEDURE_OCCURRENCE_NULLCONCEPT_DETAIL
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH NULLCONCEPT_DETAIL
AS (
	SELECT 'PROCEDURE_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, PROCEDURE_OCCURRENCE_ID AS CDT_ID
	FROM {{ref('PROCEDURE_OCCURRENCE_RAW')}} AS PROCEDURE_OCCURRENCE
	WHERE (PROCEDURE_CONCEPT_ID IS NULL)

	UNION ALL

	SELECT 'PROCEDURE_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, PROCEDURE_OCCURRENCE_ID AS CDT_ID
	FROM {{ref('PROCEDURE_OCCURRENCE_RAW')}} AS PROCEDURE_OCCURRENCE
	WHERE (PROCEDURE_TYPE_CONCEPT_ID IS NULL)

	-- UNION ALL

	-- SELECT 'MODIFIER_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
	-- 	, PROCEDURE_OCCURRENCE_ID AS CDT_ID
	-- FROM {{ref('PROCEDURE_OCCURRENCE_RAW')}} AS PROCEDURE_OCCURRENCE
	-- WHERE (MODIFIER_CONCEPT_ID IS NULL)

	-- UNION ALL

	-- SELECT 'PROCEDURE_SOURCE_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
	-- 	, PROCEDURE_OCCURRENCE_ID AS CDT_ID
	-- FROM {{ref('PROCEDURE_OCCURRENCE_RAW')}} AS PROCEDURE_OCCURRENCE
	-- WHERE (PROCEDURE_SOURCE_CONCEPT_ID IS NULL)
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'PROCEDURE_OCCURRENCE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NULLCONCEPT_DETAIL
  WHERE ERROR_TYPE <>'EXPECTED'

