------ QA_PROCEDURE_OCCURRENCE_ZEROCONCEPT_DETAIL
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH ZEROCONCEPT_DETAIL
AS (
	SELECT 'PROCEDURE_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE
		, PROCEDURE_OCCURRENCE_ID AS CDT_ID
	FROM {{ref('PROCEDURE_OCCURRENCE_RAW')}} AS PROCEDURE_OCCURRENCE
	WHERE (PROCEDURE_CONCEPT_ID = 0)

	UNION ALL

	SELECT 'PROCEDURE_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE
		, PROCEDURE_OCCURRENCE_ID AS CDT_ID
	FROM {{ref('PROCEDURE_OCCURRENCE_RAW')}} AS PROCEDURE_OCCURRENCE
	WHERE (PROCEDURE_TYPE_CONCEPT_ID = 0)

	UNION ALL

	--MODIFIER_CONCEPT_ID
	--IF THERE IS A VALUE IN 'MODIFIER_SOURCE_VALUE' THERE SHOULD NOT BE A ZERO IN 'MODIFIER_CONCEPT_ID'
	SELECT 'MODIFIER_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE
		, PROCEDURE_OCCURRENCE_ID AS CDT_ID
	FROM {{ref('PROCEDURE_OCCURRENCE_RAW')}} AS PROCEDURE_OCCURRENCE
	WHERE (MODIFIER_CONCEPT_ID = 0 AND MODIFIER_SOURCE_VALUE IS NOT NULL)

	-- UNION ALL

	-- --MODIFIER_CONCEPT_ID
	-- --IF THERE IS NOT A VALUE IN 'MODIFIER_SOURCE_VALUE' THERE SHOULD BE A ZERO IN 'MODIFIER_CONCEPT_ID'
	-- SELECT 'MODIFIER_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'EXPECTED' AS ERROR_TYPE
	-- 	, PROCEDURE_OCCURRENCE_ID AS CDT_ID
	-- FROM {{ref('PROCEDURE_OCCURRENCE_RAW')}} AS PROCEDURE_OCCURRENCE
	-- WHERE (MODIFIER_CONCEPT_ID = 0 AND MODIFIER_SOURCE_VALUE IS NULL)

	-- UNION ALL

	-- SELECT 'PROCEDURE_SOURCE_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE
	-- 	, PROCEDURE_OCCURRENCE_ID AS CDT_ID
	-- FROM {{ref('PROCEDURE_OCCURRENCE_RAW')}} AS PROCEDURE_OCCURRENCE
	-- WHERE (PROCEDURE_SOURCE_CONCEPT_ID = 0)
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'PROCEDURE_OCCURRENCE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM ZEROCONCEPT_DETAIL
  WHERE ERROR_TYPE <>'EXPECTED'

