--QA_PROCEDURE_OCCURRENCE_DATEVDATETIME_DETAIL
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH DATEVDATETIME_DETAIL AS (
SELECT 'PROCEDURE_DATE' AS METRIC_FIELD, 'DATEVDATETIME' AS QA_METRIC, 'WARNING' AS ERROR_TYPE,
	PROCEDURE_OCCURRENCE_ID AS CDT_ID
FROM {{ref('PROCEDURE_OCCURRENCE_RAW')}} AS T1
WHERE PROCEDURE_DATE <> CAST(PROCEDURE_DATETIME AS DATE)
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'PROCEDURE_OCCURRENCE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM DATEVDATETIME_DETAIL

