------ QA_PROCEDURE_OCCURRENCE_NULLCONCEPT_COUNT
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH NULLCONCEPT_COUNT
AS (
	SELECT 'PROCEDURE_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM {{ref('PROCEDURE_OCCURRENCE_RAW')}} AS PROCEDURE_OCCURRENCE
	WHERE (PROCEDURE_CONCEPT_ID IS NULL)

	UNION ALL

	SELECT 'PROCEDURE_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM {{ref('PROCEDURE_OCCURRENCE_RAW')}} AS PROCEDURE_OCCURRENCE
	WHERE (PROCEDURE_TYPE_CONCEPT_ID IS NULL)

	-- UNION ALL

	-- SELECT 'MODIFIER_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	-- FROM {{ref('PROCEDURE_OCCURRENCE_RAW')}} AS PROCEDURE_OCCURRENCE
	-- WHERE (MODIFIER_CONCEPT_ID IS NULL)

	-- UNION ALL

	-- SELECT 'PROCEDURE_SOURCE_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	-- FROM {{ref('PROCEDURE_OCCURRENCE_RAW')}} AS PROCEDURE_OCCURRENCE
	-- WHERE (PROCEDURE_SOURCE_CONCEPT_ID IS NULL)
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'PROCEDURE_OCCURRENCE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) <> 0 THEN ERROR_TYPE ELSE NULL END AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('PROCEDURE_OCCURRENCE_RAW')}}) AS TOTAL_RECORDS
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('PROCEDURE_OCCURRENCE')}}) AS TOTAL_RECORDS_CLEAN
FROM NULLCONCEPT_COUNT
GROUP BY METRIC_FIELD, QA_METRIC, ERROR_TYPE

