----QA_PROCEDURE_OCCURRENCE_NONSTANDARD_DETAIL
-------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH NONSTANDARD_DETAIL
AS (
	SELECT 'PROCEDURE_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, PROCEDURE_OCCURRENCE_ID AS CDT_ID
	FROM {{ref('PROCEDURE_OCCURRENCE_RAW')}} AS P
	LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C
		ON P.PROCEDURE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) =  'PROCEDURE'
	WHERE PROCEDURE_CONCEPT_ID <> 0 AND PROCEDURE_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)

	UNION ALL

	SELECT 'PROCEDURE_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, PROCEDURE_OCCURRENCE_ID AS CDT_ID
	FROM {{ref('PROCEDURE_OCCURRENCE_RAW')}} AS P
	LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C
		ON P.PROCEDURE_TYPE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) =  'TYPE CONCEPT' AND upper(C.VOCABULARY_ID) IN  ('TYPE CONCEPT')
	WHERE PROCEDURE_TYPE_CONCEPT_ID <> 0 AND PROCEDURE_TYPE_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)

	UNION ALL

	SELECT 'MODIFIER_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, PROCEDURE_OCCURRENCE_ID AS CDT_ID
	FROM {{ref('PROCEDURE_OCCURRENCE_RAW')}} AS P
	LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C
		ON P.MODIFIER_CONCEPT_ID = C.CONCEPT_ID AND upper(C.CONCEPT_CLASS_ID) IN ('CPT4 MODIFIER', 'HCPCS MODIFIER')
	WHERE MODIFIER_CONCEPT_ID <> 0 AND MODIFIER_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)

	UNION ALL

	SELECT 'PROCEDURE_SOURCE_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, PROCEDURE_OCCURRENCE_ID AS CDT_ID
	FROM {{ref('PROCEDURE_OCCURRENCE_RAW')}} AS P
	LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C
		ON P.PROCEDURE_SOURCE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) =  'PROCEDURE'
	WHERE PROCEDURE_SOURCE_CONCEPT_ID <> 0 AND C.CONCEPT_ID IS NULL
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'PROCEDURE_OCCURRENCE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NONSTANDARD_DETAIL
  WHERE ERROR_TYPE <>'EXPECTED'

