----QA_PROCEDURE_30AFTERDEATH_DETAIL
-------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH PROCEDURE30AFTERDEATH_DETAIL AS (
SELECT 'PROCEDURE_DATE' AS METRIC_FIELD, '30AFTERDEATH' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE,
	 PROCEDURE_OCCURRENCE_ID AS CDT_ID
FROM {{ref('PROCEDURE_OCCURRENCE_RAW')}} AS T1
INNER JOIN {{ref('DEATH_RAW')}} AS T2
	ON T1.PERSON_ID = T2.PERSON_ID
WHERE DATEDIFF(DAY, DEATH_DATE, PROCEDURE_DATE) > 30
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'PROCEDURE_OCCURRENCE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM PROCEDURE30AFTERDEATH_DETAIL
