{{ config(materialized='ephemeral') }}
--BEGIN cte__T_HOSP_TEMPERATURE
    SELECT DISTINCT PERSON_ID
        ,PULL_CSN_ID
        ,MEASUREMENT_DATE
        ,MEASUREMENT_DATETIME
        ,VALUE_SOURCE_VALUE
        ,VALUE_AS_NUMBER
        ,RANGE_LOW
        ,RANGE_HIGH
        ,PULL_FLO_MEAS_ID
        ,PULL_FLO_MEAS_NAME
        -- ,FSD_ID
        ,PROVIDER_SOURCE_VALUE
        ,UNIT_SOURCE_VALUE

    FROM {{ref('PULL_MEASUREMENT_HOSP_FLOWSHEET')}} AS PULL_MEASUREMENT_HOSP_FLOWSHEET
    --6 TEMPERATURE
    INNER JOIN {{ ref('SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_TEMP')}} AS SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS
        ON PULL_FLO_MEAS_ID = SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS.SOURCE_CODE
--END cte__T_HOSP_TEMPERATURE
--
