{%- set source_relation = source('OMOP', 'CONCEPT') -%}
{{ config(materialized = 'ephemeral')}}
-- BEGIN CONCEPT_stg
SELECT UPPER(C.CONCEPT_ID) AS CONCEPT_ID
        , UPPER(C.CONCEPT_NAME) AS CONCEPT_NAME
        , UPPER(C.DOMAIN_ID) AS DOMAIN_ID
        , UPPER(C.VOCABULARY_ID) AS VOCABULARY_ID
        , UPPER(C.CONCEPT_CLASS_ID) AS CONCEPT_CLASS_ID
        , UPPER(C.STANDARD_CONCEPT) AS STANDARD_CONCEPT
        , UPPER(C.CONCEPT_CODE) AS CONCEPT_CODE
        , C.VALID_START_DATE
        , C.VALID_END_DATE
	, UPPER(C.INVALID_REASON) AS INVALID_REASON
FROM {{ source('OMOP', 'CONCEPT')}} AS C
-- END CONCEPT_stg
