{%- set source_relation = source('OMOP', 'CONCEPT_RELATIONSHIP') -%}
{{ config(materialized = 'ephemeral')}}
-- BEGIN CONCEPT_RELATIONSHIP_stg
SELECT 
	CR.CONCEPT_ID_1 
	,CR.CONCEPT_ID_2 
	,UPPER(CR.RELATIONSHIP_ID) AS RELATIONSHIP_ID
	,CR.VALID_START_DATE 
	,CR.VALID_END_DATE 
	,UPPER(CR.INVALID_REASON) AS INVALID_REASON
FROM {{ source('OMOP', 'CONCEPT_RELATIONSHIP')}} AS CR
-- BEGIN CONCEPT_RELATIONSHIP_stg
