{%- set source_relation = source('OMOP', 'CONCEPT_ANCESTOR') -%}
{{ config(materialized = 'ephemeral')}}
-- BEGIN CONCEPT_ANCESTOR_stg
SELECT C.ANCESTOR_CONCEPT_ID AS ANCESTOR_CONCEPT_ID
        , C.DESCENDANT_CONCEPT_ID AS DESCENDANT_CONCEPT_ID
        , C.MIN_LEVELS_OF_SEPARATION AS MIN_LEVELS_OF_SEPARATION
        , C.MAX_LEVELS_OF_SEPARATION AS MAX_LEVELS_OF_SEPARATION
FROM {{ source('OMOP', 'CONCEPT_ANCESTOR')}} AS C
-- END CONCEPT_ANCESTOR_stg
