{%- set source_relation = source('OMOP', 'SOURCE_TO_CONCEPT_MAP') -%}
{{ config(materialized = "table")}}
--BEGIN SOURCE_TO_CONCEPT_MAP_stg
SELECT UPPER(S.SOURCE_CODE::VARCHAR) AS SOURCE_CODE
        , UPPER(S.SOURCE_CONCEPT_ID) AS SOURCE_CONCEPT_ID
        , UPPER(S.SOURCE_VOCABULARY_ID) AS SOURCE_VOCABULARY_ID
        , UPPER(S.SOURCE_CODE_DESCRIPTION) AS SOURCE_CODE_DESCRIPTION
        , UPPER(S.TARGET_CONCEPT_ID) AS TARGET_CONCEPT_ID
        , UPPER(S.TARGET_VOCABULARY_ID) AS TARGET_VOCABULARY_ID
        , S.VALID_START_DATE
        , S.VALID_END_DATE
        , S.INVALID_REASON
        , S.LAST_MODIFIED
FROM {{ source('OMOP', 'SOURCE_TO_CONCEPT_MAP')}} AS S
--END SOURCE_TO_CONCEPT_MAP_stg
