--PULL_OBSERVATION_HOSP_ICD
--  {{ config(materialized = 'view', schema = 'OMOP_PULL') }}

SELECT DISTINCT
-- ***STAGE ATTRIBUTES***
-- OMOP Standard fields used for the Stage
    PULL_VISIT_OCCURRENCE_HSP.PERSON_ID 					AS PERSON_ID
	,PULL_VISIT_OCCURRENCE_HSP.VISIT_START_DATE 		    AS OBSERVATION_DATE
	,PULL_VISIT_OCCURRENCE_HSP.VISIT_START_DATETIME 		AS OBSERVATION_DATETIME
	,NULL 													AS VALUE_AS_NUMBER
   	,PULL_PROVIDER_SOURCE_VALUE                             AS PROVIDER_SOURCE_VALUE
	,NULL 													AS UNIT_SOURCE_VALUE
	,NULL 													AS QUALIFIER_SOURCE_VALUE
    ,NULL                 									AS VALUE_SOURCE_VALUE

-- ***ADDITIONAL ATTRIBUTES***
-- Non_OMOP fields used for the Stage
    ,PULL_VISIT_OCCURRENCE_HSP.PULL_CSN_ID           		AS PULL_CSN_ID
	,T_DIAGNOSIS_OBSERVATION.ICD10_CODE						AS PULL_ICD10_CODE
	,T_DIAGNOSIS_OBSERVATION.ICD9_CODE						AS PULL_ICD9_CODE
    ,T_DIAGNOSIS_OBSERVATION.DX_ID                          AS PULL_DX_ID

-- ***SOURCE ATTRIBUTES***
	-- ,PAT_ENC_DX.CONTACT_DATE
	-- ,PAT_ENC_DX.PAT_ENC_CSN_ID

	-- ,PAT_ENC_HSP.BILL_ATTEND_PROV_ID


FROM {{ ref('PAT_ENC_DX_stg')}} AS PAT_ENC_DX

    INNER JOIN   {{ ref('PULL_VISIT_OCCURRENCE_HSP')}} AS PULL_VISIT_OCCURRENCE_HSP
        ON PAT_ENC_DX.PAT_ENC_CSN_ID = PULL_VISIT_OCCURRENCE_HSP.PULL_CSN_ID

	LEFT JOIN {{ ref('HSP_ATND_PROV_stg')}} AS HSP_ATND_PROV
		ON PULL_VISIT_OCCURRENCE_HSP.PULL_CSN_ID = HSP_ATND_PROV.PAT_ENC_CSN_ID
			AND VISIT_END_DATETIME BETWEEN ATTEND_FROM_DATE
				AND COALESCE(ATTEND_TO_DATE, GETDATE())

	INNER JOIN {{ref('T_DIAGNOSIS_OBSERVATION')}} AS T_DIAGNOSIS_OBSERVATION
		ON PAT_ENC_DX.DX_ID = T_DIAGNOSIS_OBSERVATION.DX_ID

