--PULL_OBSERVATION_AMB_ICD
{#-- {{ config(materialized = 'view', schema = 'OMOP_PULL') }}#}


SELECT DISTINCT
-- ***STAGE ATTRIBUTES***
-- OMOP Standard fields used for the Stage
    PULL_VISIT_OCCURRENCE_AMB.PERSON_ID 					AS PERSON_ID
	,PULL_VISIT_OCCURRENCE_AMB.VISIT_START_DATE 			AS OBSERVATION_DATE
	,PULL_VISIT_OCCURRENCE_AMB.VISIT_START_DATETIME 		AS OBSERVATION_DATETIME
	,NULL 													AS VALUE_AS_NUMBER
   	,PULL_PROVIDER_SOURCE_VALUE                             AS PROVIDER_SOURCE_VALUE
	,NULL 													AS UNIT_SOURCE_VALUE
	,NULL 													AS QUALIFIER_SOURCE_VALUE
    ,NULL                 									AS VALUE_SOURCE_VALUE

-- ***ADDITIONAL ATTRIBUTES***
-- Non_OMOP fields used for the Stage
    ,PULL_VISIT_OCCURRENCE_AMB.PULL_CSN_ID     				AS PULL_CSN_ID
	,T_DIAGNOSIS_OBSERVATION.ICD10_CODE						AS PULL_ICD10_CODE
	,T_DIAGNOSIS_OBSERVATION.ICD9_CODE						AS PULL_ICD9_CODE
    ,T_DIAGNOSIS_OBSERVATION.DX_ID                          AS PULL_DX_ID


-- ***SOURCE ATTRIBUTES***
    -- ,PATIENT_DRIVER.PERSON_ID AS PERSON_ID
	-- ,PULL_VISIT_OCCURRENCE_AMB.PAT_ID
	-- ,PULL_VISIT_OCCURRENCE_AMB.PAT_ENC_CSN_ID
	-- ,PULL_VISIT_OCCURRENCE_AMB.HSP_ACCOUNT_ID
	-- ,PULL_VISIT_OCCURRENCE_AMB.IP_DOC_CONTACT_CSN
	-- ,PULL_VISIT_OCCURRENCE_AMB.ENC_TYPE_C
	-- ,PULL_VISIT_OCCURRENCE_AMB.ZC_DISP_ENC_TYPE_NAME
    -- ,PAT_ENC_DX.CONTACT_DATE
	-- ,PAT_OR_ADM_LINK_CSN AS PAT_OR_ADM_LINK_PAT_ENC_CSN_ID
	-- ,PULL_VISIT_OCCURRENCE_AMB.VISIT_PROV_ID
	-- ,VISIT_PROVIDER_NAME
	-- ,VISIT_PROVIDER_TYPE
	-- ,PULL_VISIT_OCCURRENCE_AMB.PCP_PROV_ID
	-- ,PCP_PROVIDER_NAME
	-- ,PCP_PROVIDER_TYPE
	-- ,PRIMARY_DX_YN
	-- ,T_DIAGNOSIS.DX_ID
	-- ,T_DIAGNOSIS.DX_NAME
	-- ,T_DIAGNOSIS.ICD10_CODE
	-- ,T_DIAGNOSIS.ICD9_CODE
	-- ,'OBSERVATION--ClarityAMB--SNOMED_ICD' AS ETL_Module

FROM    {{ref('PULL_VISIT_OCCURRENCE_AMB')}} AS PULL_VISIT_OCCURRENCE_AMB

 	INNER JOIN {{ ref('PAT_ENC_DX_stg')}} AS PAT_ENC_DX
		ON  PULL_VISIT_OCCURRENCE_AMB.PULL_CSN_ID = PAT_ENC_DX.PAT_ENC_CSN_ID

	INNER JOIN {{ref('T_DIAGNOSIS_OBSERVATION')}} AS T_DIAGNOSIS_OBSERVATION
		ON PAT_ENC_DX.DX_ID = T_DIAGNOSIS_OBSERVATION.DX_ID

    -- INNER JOIN {{ref('PATIENT_DRIVER')}} AS PATIENT_DRIVER
    --     ON PATIENT_DRIVER.EHR_PATIENT_ID = PULL_VISIT_OCCURRENCE_AMB.PAT_ID

-- WHERE PULL_VISIT_OCCURRENCE_AMB.ENC_TYPE_C <> 3
