--PULL_OBSERVATION_AMB_FLOWSHEET
{#-- {{ config(materialized = 'view', schema = 'OMOP_PULL') }}#}

SELECT --DISTINCT
-- ***STAGE ATTRIBUTES***
-- OMOP Standard fields used for the Stage
    PATIENT_DRIVER.PERSON_ID  								AS PERSON_ID
	,IP_FLWSHT_MEAS.RECORDED_TIME::VARCHAR  				AS OBSERVATION_DATE
	,IP_FLWSHT_MEAS.RECORDED_TIME 							AS OBSERVATION_DATETIME
	,NULL 													AS VALUE_AS_NUMBER
   	,COALESCE(VISIT_PROV_ID,PCP_PROV_ID)               		AS PROVIDER_SOURCE_VALUE
	,NULL 													AS UNIT_SOURCE_VALUE
	,NULL 													AS QUALIFIER_SOURCE_VALUE
    ,NULL                 									AS VALUE_SOURCE_VALUE

-- ***ADDITIONAL ATTRIBUTES***
-- Non_OMOP fields used for the Stage
    ,PAT_ENC.PAT_ENC_CSN_ID     							AS PULL_CSN_ID
	,IP_FLO_GP_DATA.FLO_MEAS_ID								AS PULL_FLO_MEAS_ID
	,IP_FLWSHT_MEAS.MEAS_VALUE								AS PULL_MEAS_VALUE
    ,IP_FLO_GP_DATA.CAT_INI									AS PULL_CAT_INI
    ,IP_FLO_GP_DATA.CAT_ITEM								AS PULL_CAT_ITEM
	,IP_FLO_GP_DATA.FLO_MEAS_NAME							AS PULL_FLO_MEAS_NAME

-- ***SOURCE ATTRIBUTES***

    -- PATIENT_DRIVER.PERSON_ID AS PERSON_ID
	-- ,PULL_VISIT_OCCURRENCE_AMB.PAT_ID
	-- ,PULL_VISIT_OCCURRENCE_AMB.PAT_ENC_CSN_ID
	-- ,PULL_VISIT_OCCURRENCE_AMB.HSP_ACCOUNT_ID
	-- ,PULL_VISIT_OCCURRENCE_AMB.IP_DOC_CONTACT_CSN
	-- ,PULL_VISIT_OCCURRENCE_AMB.ENC_TYPE_C
	-- ,PULL_VISIT_OCCURRENCE_AMB.ZC_DISP_ENC_TYPE_NAME
	-- ,PULL_VISIT_OCCURRENCE_AMB.PAT_OR_ADM_LINK_CSN AS PAT_OR_ADM_LINK_PAT_ENC_CSN_ID
	-- ,IP_FLWSHT_MEAS.RECORDED_TIME

	-- ,IP_FLO_GP_DATA.MINVALUE
	-- ,IP_FLO_GP_DATA.MAX_VAL


	-- ,IP_FLO_GP_DATA.VAL_TYPE_C
	-- ,ZC_VAL_TYPE_NAME
	-- ,IP_FLO_GP_DATA.UNITS
	-- ,IP_FLO_GP_DATA.DISP_NAME

	-- ,IP_DATA_STORE.EPT_CSN
	-- ,IP_DATA_STORE.INPATIENT_DATA_ID
	-- ,IP_FLWSHT_REC.FSD_ID
	-- ,PULL_VISIT_OCCURRENCE_AMB.VISIT_PROV_ID
	-- ,VISIT_PROVIDER_NAME
	-- ,VISIT_PROVIDER_TYPE
	-- ,PULL_VISIT_OCCURRENCE_AMB.PCP_PROV_ID
	-- ,PCP_PROVIDER_NAME
	-- ,PCP_PROVIDER_TYPE
	-- ,'PULL_OBSERVATION_CLARITYAMB_FLOWSHEET' AS ETL_Module

FROM  --{{ref('PULL_VISIT_OCCURRENCE_AMB')}} AS PULL_VISIT_OCCURRENCE_AMB
	{{ ref('PAT_ENC_stg')}} AS PAT_ENC
    LEFT JOIN {{ref('IP_DATA_STORE_stg')}} AS IP_DATA_STORE
        ON PAT_ENC.PAT_ENC_CSN_ID = IP_DATA_STORE.EPT_CSN

    LEFT JOIN {{ ref('IP_FLWSHT_REC_stg')}} AS IP_FLWSHT_REC
        ON IP_DATA_STORE.INPATIENT_DATA_ID = IP_FLWSHT_REC.INPATIENT_DATA_ID

    LEFT JOIN {{ ref('IP_FLWSHT_MEAS_stg')}} AS IP_FLWSHT_MEAS
        ON IP_FLWSHT_REC.FSD_ID = IP_FLWSHT_MEAS.FSD_ID

    INNER JOIN {{ ref('IP_FLO_GP_DATA_stg')}} AS IP_FLO_GP_DATA
        ON IP_FLWSHT_MEAS.FLO_MEAS_ID = IP_FLO_GP_DATA.FLO_MEAS_ID

    INNER JOIN {{ref('ZC_VAL_TYPE_stg')}} AS ZC_VAL_TYPE
        ON IP_FLO_GP_DATA.VAL_TYPE_C = ZC_VAL_TYPE.VAL_TYPE_C

    INNER JOIN {{ref('PATIENT_DRIVER')}} AS PATIENT_DRIVER
        ON PATIENT_DRIVER.EHR_PATIENT_ID = PAT_ENC.PAT_ID

WHERE PAT_ENC.ENC_TYPE_C <> 3 AND
		 IP_FLWSHT_MEAS.MEAS_VALUE	 is not null
