--PULL_OBSERVATION_ALL_ALLERGY
{#-- {{ config(materialized = 'view', schema = 'OMOP_PULL') }}#}
--

SELECT
-- ***STAGE ATTRIBUTES***
-- OMOP Standard fields used for the Stage
    PATIENT_DRIVER.PERSON_ID 						AS PERSON_ID
	, ALLERGY.ALRGY_ENTERED_DTTM::DATE 				AS OBSERVATION_DATE
	, ALLERGY.ALRGY_ENTERED_DTTM::DATETIME 			AS OBSERVATION_DATETIME
	, NULL 											AS VALUE_AS_NUMBER
	, T_ALLERGY_CODES_OBSERVATION.ALLERGEN_NAME	 	AS VALUE_AS_STRING
	, COALESCE(
		PAT_ENC.VISIT_PROV_ID
		, PAT_ENC_HSP.BILL_ATTEND_PROV_ID) 			AS PROVIDER_SOURCE_VALUE
	, T_ALLERGY_CODES_OBSERVATION.ALLERGEN_NAME 	AS OBSERVATION_SOURCE_VALUE
	, NULL											AS UNIT_SOURCE_VALUE
	, NULL 											AS QUALIFIER_SOURCE_VALUE
    , NULL::VARCHAR(50)                 			AS VALUE_SOURCE_VALUE

-- ***ADDITIONAL ATTRIBUTES***
-- Non_OMOP fields used for the Stage
	, PAT_ENC.PAT_ENC_CSN_ID 						AS PULL_CSN_ID
	, T_ALLERGY_CODES_OBSERVATION.CONCEPT_NAME 		AS PULL_CONCEPT_NAME
    , ALLERGY.ALLERGY_ID                            AS PULL_ALLERGY_ID

-- ***SOURCE ATTRIBUTES***
--	, PATIENT_DRIVER.EHR_PAT_ID
-- 	, PAT_ENC.PAT_ID
-- 	, PAT_ENC.PAT_ENC_CSN_ID
-- 	, PAT_ENC.ENC_TYPE_C
-- --	, T_ALLERGY_CODES_OBSERVATION.ALLERGEN_ID
-- 	, T_ALLERGY_CODES_OBSERVATION.ALLERGEN_NAME
-- 	, T_ALLERGY_CODES_OBSERVATION.CONCEPT_NAME
-- 	, ALLERGY.ALRGY_ENTERED_DTTM
-- --	, ALLERGY.DATE_NOTED
-- 	, PAT_ENC.CONTACT_DATE
-- 	, ALLERGY.DESCRIPTION AS VALUE_AS_STRING
-- 	, COALESCE(PAT_ENC.VISIT_PROV_ID, PAT_ENC_HSP.BILL_ATTEND_PROV_ID) as PROV_ID

FROM {{ ref('PAT_ALLERGIES_stg')}}  AS PAT_ALLERGIES

	INNER JOIN {{ ref('ALLERGY_stg')}}  AS ALLERGY
		ON (PAT_ALLERGIES.ALLERGY_RECORD_ID = ALLERGY.ALLERGY_ID)

	LEFT JOIN {{ref('T_ALLERGY_CODES_OBSERVATION')}} AS T_ALLERGY_CODES_OBSERVATION
		ON (T_ALLERGY_CODES_OBSERVATION.ALLERGEN_ID = ALLERGY.ALLERGEN_ID)

	INNER JOIN {{ ref('PAT_ENC_stg')}} AS PAT_ENC
		ON ALLERGY.ALLERGY_PAT_CSN = PAT_ENC.PAT_ENC_CSN_ID

	LEFT JOIN {{ ref('PAT_ENC_HSP_stg')}} AS PAT_ENC_HSP
		ON ALLERGY.ALLERGY_PAT_CSN = PAT_ENC_HSP.PAT_ENC_CSN_ID

	INNER JOIN {{ref('PATIENT_DRIVER')}} AS PATIENT_DRIVER
		ON (PATIENT_DRIVER.EHR_PATIENT_ID = PAT_ALLERGIES.PAT_ID)

WHERE UPPER(ALLERGY.DESCRIPTION) != 'NO KNOWN ALLERGIES'
