--PULL_OBSERVATION_HOSP_FLOWSHEET
{#-- {{ config(materialized = 'view', schema = 'OMOP_PULL') }}#}

SELECT DISTINCT
-- ***STAGE ATTRIBUTES***
-- OMOP Standard fields used for the Stage
    PATIENT_DRIVER.PERSON_ID  								AS PERSON_ID
	,IP_FLWSHT_MEAS.RECORDED_TIME::VARCHAR 					AS OBSERVATION_DATE
	,IP_FLWSHT_MEAS.RECORDED_TIME							AS OBSERVATION_DATETIME
	,NULL 													AS VALUE_AS_NUMBER
   	,COALESCE(ATTENDING_PROV_ID,HSP_ATND_PROV.PROV_ID)  	AS PROVIDER_SOURCE_VALUE
 	,NULL 													AS UNIT_SOURCE_VALUE
	,NULL 													AS QUALIFIER_SOURCE_VALUE
    ,NULL                 									AS VALUE_SOURCE_VALUE

-- ***ADDITIONAL ATTRIBUTES***
-- Non_OMOP fields used for the Stage
   	,PAT_ENC_HSP.PAT_ENC_CSN_ID     						AS PULL_CSN_ID
	,IP_FLO_GP_DATA.FLO_MEAS_ID								AS PULL_FLO_MEAS_ID
	,IP_FLWSHT_MEAS.MEAS_VALUE								AS PULL_MEAS_VALUE
    ,IP_FLO_GP_DATA.CAT_INI									AS PULL_CAT_INI
    ,IP_FLO_GP_DATA.CAT_ITEM								AS PULL_CAT_ITEM
	,IP_FLO_GP_DATA.FLO_MEAS_NAME							AS PULL_FLO_MEAS_NAME

-- ***SOURCE ATTRIBUTES***
--    PULL_VISIT_OCCURRENCE_HSP.PERSON_ID AS PERSON_ID
-- 	,IP_FLWSHT_MEAS.RECORDED_TIME
-- 	,IP_FLWSHT_MEAS.MEAS_VALUE
-- 	,IP_FLO_GP_DATA.MINVALUE
-- 	,IP_FLO_GP_DATA.MAX_VAL
-- 	,IP_FLO_GP_DATA.FLO_MEAS_ID
-- 	,IP_FLO_GP_DATA.FLO_MEAS_NAME
-- 	,IP_FLO_GP_DATA.VAL_TYPE_C
-- 	,ZC_VAL_TYPE_NAME
--     ,IP_FLO_GP_DATA.UNITS
--     ,IP_FLO_GP_DATA.DISP_NAME
--     ,IP_FLO_GP_DATA.CAT_INI
--     ,IP_FLO_GP_DATA.CAT_ITEM
-- 	,PULL_VISIT_OCCURRENCE_HSP.PAT_ID
-- 	,PULL_VISIT_OCCURRENCE_HSP.PAT_ENC_CSN_ID
-- 	,IP_DATA_STORE.EPT_CSN
-- 	,IP_DATA_STORE.INPATIENT_DATA_ID
-- 	,IP_FLWSHT_REC.FSD_ID
-- 	,PULL_VISIT_OCCURRENCE_HSP.BILL_ATTEND_PROV_ID
-- 	, HSP_ACCOUNT.ATTENDING_PROV_ID
-- 	, HSP_ACCOUNT.REFERRING_PROV_ID
-- 	, HSP_ACCOUNT.ADM_DATE_TIME
-- 	, HSP_ACCOUNT.DISCH_DATE_TIME
-- 	,ATTEND_FROM_DATE
-- 	,ATTEND_TO_DATE
-- 	,HSP_ATND_PROV.PROV_ID
-- 	,COALESCE(ATTENDING_PROV_ID,HSP_ATND_PROV.PROV_ID) AS  CALC_ATTEND_PROV_ID
-- 	,'PULL_OBSERVATION--CLARITYHOSP--FLOWSHEET_ALL' AS ETL_MODULE

FROM --{{ ref('PULL_VISIT_OCCURRENCE_HSP')}} AS PULL_VISIT_OCCURRENCE_HSP
{{ ref('PAT_ENC_HSP_stg')}} AS PAT_ENC_HSP

	LEFT JOIN {{ref('IP_DATA_STORE_stg')}} AS IP_DATA_STORE
		ON PAT_ENC_HSP.PAT_ENC_CSN_ID = IP_DATA_STORE.EPT_CSN

	LEFT JOIN {{ ref('IP_FLWSHT_REC_stg')}} AS IP_FLWSHT_REC
		ON IP_DATA_STORE.INPATIENT_DATA_ID = IP_FLWSHT_REC.INPATIENT_DATA_ID

	LEFT JOIN {{ ref('IP_FLWSHT_MEAS_stg')}} AS IP_FLWSHT_MEAS
		ON IP_FLWSHT_REC.FSD_ID = IP_FLWSHT_MEAS.FSD_ID

	INNER JOIN {{ ref('IP_FLO_GP_DATA_stg')}} AS IP_FLO_GP_DATA
		ON IP_FLWSHT_MEAS.FLO_MEAS_ID = IP_FLO_GP_DATA.FLO_MEAS_ID

	INNER JOIN {{ref('ZC_VAL_TYPE_stg')}} AS ZC_VAL_TYPE
		ON IP_FLO_GP_DATA.VAL_TYPE_C = ZC_VAL_TYPE.VAL_TYPE_C

	LEFT JOIN {{ ref('HSP_ACCOUNT_stg')}} AS HSP_ACCOUNT
		on PAT_ENC_HSP.HSP_ACCOUNT_ID = HSP_ACCOUNT.HSP_ACCOUNT_ID

	LEFT JOIN {{ ref('HSP_ATND_PROV_stg')}} AS HSP_ATND_PROV
		ON PAT_ENC_HSP.PAT_ENC_CSN_ID = HSP_ATND_PROV.PAT_ENC_CSN_ID
			AND IP_FLWSHT_MEAS.recorded_time BETWEEN ATTEND_FROM_DATE
				AND COALESCE(ATTEND_TO_DATE, GETDATE())

    INNER JOIN {{ref('PATIENT_DRIVER')}} AS PATIENT_DRIVER
        ON PAT_ENC_HSP.PAT_ID = PATIENT_DRIVER.EHR_PATIENT_ID

WHERE MEAS_VALUE IS NOT NULL
