
--BEGIN cte__T_DEATH_DIAGNOSIS
SELECT DISTINCT
      PATIENT_3.PAT_ID
      ,CLARITY_EDG.DX_ID
      ,CLARITY_EDG.DX_NAME
      ,replace(SNOMED_CONCEPT.CONCEPT_ID, 'SNOMED#', '') AS SNOMED_CODE
      ,SNOMED_CONCEPT.FULLY_SPECIFIED_NM

FROM   CARE_BRONZE_CLARITY_PROD.DBO.PATIENT_3 AS PATIENT_3

      INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.CLARITY_EDG AS CLARITY_EDG
            ON PATIENT_3.PCOD_CAUSE_DX_ID = CLARITY_EDG.DX_ID

      LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.EXTERNAL_CNCPT_MAP AS EXTERNAL_CNCPT_MAP
            ON CLARITY_EDG.DX_ID = EXTERNAL_CNCPT_MAP.ENTITY_VALUE_NUM

      LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.CONCEPT_MAPPED AS CONCEPT_MAPPED
            ON EXTERNAL_CNCPT_MAP.MAPPING_ID = CONCEPT_MAPPED.MAPPING_ID

      LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.SNOMED_CONCEPT AS SNOMED_CONCEPT
            ON CONCEPT_MAPPED.CONCEPT_ID = SNOMED_CONCEPT.CONCEPT_ID

WHERE PATIENT_3.PCOD_CAUSE_DX_ID IS NOT NULL
      AND EXTERNAL_CNCPT_MAP.ENTITY_INI = 'EDG'
      AND EXTERNAL_CNCPT_MAP.ENTITY_ITEM = 0.1
--END cte__T_DEATH_DIAGNOSIS
--