
-- PULL_CARE_SITE_LOCATIONS
--  {{ config(materialized='ephemeral') }}
    SELECT DISTINCT CLARITY_POS.ADDRESS_LINE_1 AS ADDRESS_1
        ,CLARITY_POS.ADDRESS_LINE_2 AS ADDRESS_2
        ,CLARITY_POS.CITY AS CITY
        ,LEFT(ZC_STATE_ABBR, 2) AS STATE
        ,LEFT(CLARITY_POS.ZIP, 5) AS ZIP
        ,ZC_COUNTY_NAME AS COUNTY
        ,COALESCE(CLARITY_POS.ADDRESS_LINE_1, '')
            || COALESCE(CLARITY_POS.ADDRESS_LINE_2, '')
            || COALESCE(CLARITY_POS.CITY, '')
            || COALESCE(LEFT(ZC_STATE_ABBR, 2), '')
            || COALESCE(CLARITY_POS.ZIP, '')
            || COALESCE(ZC_COUNTY.COUNTY_C, '')
        AS LOCATION_SOURCE_VALUE

    FROM {{ref('PATIENT_DRIVER')}} AS PATIENT_DRIVER
        INNER JOIN {{ ref('PAT_ENC_stg')}}	 as PAT_ENC 
            ON PAT_ENC.PAT_ID = PATIENT_DRIVER.EHR_PATIENT_ID
        INNER JOIN {{ ref('CLARITY_DEP_stg')}}	 as CLARITY_DEP 
            ON PAT_ENC.DEPARTMENT_ID = CLARITY_DEP.DEPARTMENT_ID
        INNER JOIN {{ ref('CLARITY_POS_stg')}} as CLARITY_POS
            ON CLARITY_DEP.REV_LOC_ID = CLARITY_POS.POS_ID
        INNER JOIN {{ ref('ZC_STATE_stg')}} 	 as ZC_STATE
            ON CLARITY_POS.STATE_C = ZC_STATE.STATE_C
        LEFT OUTER JOIN {{ ref('ZC_COUNTY_stg')}}	 as ZC_COUNTY
          ON CLARITY_POS.COUNTY_C = ZC_COUNTY.COUNTY_C
          