  {{ config(materialized='ephemeral') }}
--BEGIN cte__T_ALLERGY_CODES_OBSERVATION
	SELECT A.ALLERGEN_ID
		, A.ALLERGEN_NAME
		, CONCAT (
			'ALLERGY TO '
			, A.ALLERGEN_NAME
			) 					AS CONCEPT_NAME
	FROM {{ ref('CL_ELG_stg')}}  AS A
	WHERE UPPER(ALLERGEN_NAME) NOT IN ('NO KNOWN ALLERGIES', 'NKA', 'NKDA', 'NONE')
--END cte__T_ALLERGY_CODES_OBSERVATION
--
