
--CONDITION_LOOKUP
SELECT DISTINCT
    T_DIAGNOSIS.DX_ID
    ,T_DIAGNOSIS.DX_NAME
    ,ICD9_CODE
    ,ICD10_CODE
    ,SNOMED_code
	,FULLY_SPECIFIED_NM
	,CURRENT_ICD9_LIST
	,CURRENT_ICD10_LIST
FROM  {{ ref('T_DIAGNOSIS')}} AS T_DIAGNOSIS
INNER JOIN {{ ref('T_SNO_CODE')}} AS T_SNO_CODE ON T_DIAGNOSIS.DX_ID = T_SNO_CODE.DX_ID
