
--QRY_OBSERVATION

WITH observation_data AS (
    SELECT
        OBSERVATION.OBSERVATION_ID,
        OBSERVATION.PERSON_ID,
        LEFT(OBSERVATION.OBSERVATION_CONCEPT_ID || '::' || c1.CONCEPT_NAME, 100) AS OBSERVATION,
        OBSERVATION.OBSERVATION_DATETIME,
        OBSERVATION.OBSERVATION_TYPE_CONCEPT_ID || '::' || c2.CONCEPT_NAME AS OBSERVATION_TYPE,
        OBSERVATION.VALUE_AS_NUMBER,
        OBSERVATION.VALUE_AS_STRING,
        OBSERVATION.VALUE_AS_CONCEPT_ID || '::' || c3.CONCEPT_NAME AS VALUE_AS_CONCEPT,
        OBSERVATION.QUALIFIER_CONCEPT_ID || '::' || c4.CONCEPT_NAME AS QUALIFIER,
        OBSERVATION.UNIT_CONCEPT_ID || '::' || c5.CONCEPT_NAME AS UNIT,
        PROVIDER.PROVIDER_NAME,
        OBSERVATION.VISIT_OCCURRENCE_ID,
        OBSERVATION.OBSERVATION_SOURCE_VALUE,
        OBSERVATION.OBSERVATION_SOURCE_CONCEPT_ID || '::' || c6.CONCEPT_NAME AS OBSERVATION_SOURCE_CONCEPT,
        OBSERVATION.UNIT_SOURCE_VALUE,
        OBSERVATION.QUALIFIER_SOURCE_VALUE,
        'OBSERVATION' AS SDT_TAB,
        VISIT_OCCURRENCE.PERSON_ID || OBSERVATION.OBSERVATION_SOURCE_VALUE || OBSERVATION.OBSERVATION_DATETIME AS NK,
        OBSERVATION.ETL_MODULE,
        OBSERVATION.PHI_PAT_ID,
        OBSERVATION.PHI_MRN_CPI,
        OBSERVATION.PHI_CSN_ID,
        OBSERVATION.SRC_TABLE,
        OBSERVATION.SRC_FIELD,
        OBSERVATION.SRC_VALUE_ID
    FROM {{ ref('OBSERVATION') }} OBSERVATION
    INNER JOIN {{ source('OMOP', 'CONCEPT') }} c1
        ON OBSERVATION.OBSERVATION_CONCEPT_ID = c1.CONCEPT_ID
    INNER JOIN {{ source('OMOP', 'CONCEPT') }} c2
        ON OBSERVATION.OBSERVATION_TYPE_CONCEPT_ID = c2.CONCEPT_ID
    LEFT JOIN {{ source('OMOP', 'CONCEPT') }} c3
        ON OBSERVATION.VALUE_AS_CONCEPT_ID = c3.CONCEPT_ID
    LEFT JOIN {{ source('OMOP', 'CONCEPT') }} c4
        ON OBSERVATION.QUALIFIER_CONCEPT_ID = c4.CONCEPT_ID
    LEFT JOIN {{ source('OMOP', 'CONCEPT') }} c5
        ON OBSERVATION.UNIT_CONCEPT_ID = c5.CONCEPT_ID
    LEFT JOIN {{ source('OMOP', 'CONCEPT') }} c6
        ON OBSERVATION.OBSERVATION_SOURCE_CONCEPT_ID = c6.CONCEPT_ID
    LEFT JOIN {{ ref('PROVIDER') }} PROVIDER
        ON OBSERVATION.PROVIDER_ID = PROVIDER.PROVIDER_ID
    INNER JOIN {{ ref('VISIT_OCCURRENCE') }} VISIT_OCCURRENCE
        ON OBSERVATION.VISIT_OCCURRENCE_ID = VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID
)

SELECT * FROM observation_data
