--QRY_NOTE

WITH note_data AS (
    SELECT
        NOTE.NOTE_ID,
        NOTE.PERSON_ID,
        NOTE.NOTE_DATETIME,
        NOTE.NOTE_TYPE_CONCEPT_ID || '::' || c1.CONCEPT_NAME AS NOTE_TYPE,
        NOTE.NOTE_CLASS_CONCEPT_ID || '::' || c2.CONCEPT_NAME AS NOTE_CLASS,
        NOTE.NOTE_TITLE,
        NOTE.NOTE_TEXT,
        NOTE.ENCODING_CONCEPT_ID || '::' || c3.CONCEPT_NAME AS ENCODING,
        NOTE.LANGUAGE_CONCEPT_ID || '::' || c4.CONCEPT_NAME AS LANGUAGE,
        PROVIDER.PROVIDER_NAME,
        NOTE.VISIT_OCCURRENCE_ID,
        NOTE.NOTE_SOURCE_VALUE,
        'NOTE' AS SDT_TAB,
        VISIT_OCCURRENCE.PERSON_ID || NOTE_SOURCE_VALUE || NOTE_DATETIME AS NK,
        NOTE.ETL_MODULE,
        NOTE.PHI_PAT_ID,
        NOTE.PHI_MRN_CPI,
        NOTE.PHI_CSN_ID,
        NOTE.SRC_TABLE,
        NOTE.SRC_FIELD,
        NOTE.SRC_VALUE_ID
    FROM {{ ref('NOTE') }}
    INNER JOIN {{ source('OMOP', 'CONCEPT') }} c1
        ON NOTE.NOTE_TYPE_CONCEPT_ID = c1.CONCEPT_ID
    INNER JOIN {{ source('OMOP', 'CONCEPT') }} c2
        ON NOTE.NOTE_CLASS_CONCEPT_ID = c2.CONCEPT_ID
    INNER JOIN {{ source('OMOP', 'CONCEPT') }} c3
        ON NOTE.ENCODING_CONCEPT_ID = c3.CONCEPT_ID
    INNER JOIN {{ source('OMOP', 'CONCEPT') }} c4
        ON NOTE.LANGUAGE_CONCEPT_ID = c4.CONCEPT_ID
    LEFT JOIN {{ ref('PROVIDER') }}
        ON NOTE.PROVIDER_ID = PROVIDER.PROVIDER_ID
    INNER JOIN {{ ref('VISIT_OCCURRENCE') }}
        ON NOTE.VISIT_OCCURRENCE_ID = VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID
)

SELECT *
FROM note_data
