-- OMOP_CS.QRY_VISIT_DETAIL


WITH visit_detail_enhanced AS (
    SELECT
        VISIT_DETAIL.VISIT_DETAIL_ID,
        VISIT_DETAIL.PERSON_ID,
        VISIT_DETAIL.VISIT_DETAIL_CONCEPT_ID || '::' || c1.CONCEPT_NAME AS VISIT_DETAIL,
        VISIT_DETAIL.VISIT_DETAIL_START_DATETIME,
        VISIT_DETAIL.VISIT_DETAIL_END_DATETIME,
        VISIT_DETAIL.VISIT_DETAIL_TYPE_CONCEPT_ID || '::' || c2.CONCEPT_NAME AS VISIT_DETAIL_TYPE,
        PROVIDER.PROVIDER_ID || '::' || PROVIDER_NAME AS PROVIDER,
        CARE_SITE.CARE_SITE_ID || '::' || CARE_SITE_NAME AS CARE_SITE,
        VISIT_DETAIL.VISIT_DETAIL_SOURCE_VALUE,
        VISIT_DETAIL.VISIT_DETAIL_SOURCE_CONCEPT_ID || '::' || c3.CONCEPT_NAME AS VISIT_DETAIL_SOURCE,
        VISIT_DETAIL.ADMITTED_FROM_SOURCE_VALUE,
        VISIT_DETAIL.ADMITTED_FROM_CONCEPT_ID || '::' || c4.CONCEPT_NAME AS ADMITTING_SOURCE,
        VISIT_DETAIL.DISCHARGED_TO_SOURCE_VALUE,
        VISIT_DETAIL.DISCHARGED_TO_CONCEPT_ID || '::' || c4.CONCEPT_NAME AS DISCHARGE,
        VISIT_DETAIL.PRECEDING_VISIT_DETAIL_ID,
        VISIT_DETAIL.PARENT_VISIT_DETAIL_ID,
        VISIT_DETAIL.VISIT_OCCURRENCE_ID,
        'VISIT_DETAIL' AS SDT_TAB,
        VISIT_DETAIL.PERSON_ID || VISIT_DETAIL_SOURCE_VALUE || VISIT_DETAIL_START_DATETIME AS NK,
        VISIT_DETAIL.ETL_MODULE,
        VISIT_DETAIL.PHI_PAT_ID,
        VISIT_DETAIL.PHI_MRN_CPI,
        VISIT_DETAIL.PHI_CSN_ID
    FROM {{ ref('VISIT_DETAIL') }}

    INNER JOIN {{ source('OMOP', 'CONCEPT') }} c1
        ON c1.CONCEPT_ID = VISIT_DETAIL.VISIT_DETAIL_CONCEPT_ID

    INNER JOIN {{ source('OMOP', 'CONCEPT') }} c2
        ON c2.CONCEPT_ID = VISIT_DETAIL.VISIT_DETAIL_TYPE_CONCEPT_ID

    LEFT JOIN {{ source('OMOP', 'CONCEPT') }} c3
        ON c3.CONCEPT_ID = VISIT_DETAIL.VISIT_DETAIL_SOURCE_CONCEPT_ID

    INNER JOIN {{ source('OMOP', 'CONCEPT') }} c4
        ON c4.CONCEPT_ID = VISIT_DETAIL.ADMITTED_FROM_CONCEPT_ID

    INNER JOIN {{ source('OMOP', 'CONCEPT') }} c5
        ON c5.CONCEPT_ID = VISIT_DETAIL.DISCHARGED_TO_CONCEPT_ID

    LEFT JOIN {{ ref('CARE_SITE') }}
        ON VISIT_DETAIL.CARE_SITE_ID = CARE_SITE.CARE_SITE_ID

    LEFT JOIN {{ ref('PROVIDER') }}
        ON VISIT_DETAIL.PROVIDER_ID = PROVIDER.PROVIDER_ID
)

SELECT * FROM visit_detail_enhanced
