--QRY_PROCEDURE_OCCURRENCE

WITH procedure_query AS (

SELECT
    PROCEDURE_OCCURRENCE.PROCEDURE_OCCURRENCE_ID,
    PROCEDURE_OCCURRENCE.PERSON_ID,
    LEFT(PROCEDURE_OCCURRENCE.PROCEDURE_CONCEPT_ID || '::' || c1.CONCEPT_NAME, 100) AS PROCEDURE,
    PROCEDURE_OCCURRENCE.PROCEDURE_DATETIME,
    PROCEDURE_OCCURRENCE.PROCEDURE_TYPE_CONCEPT_ID || '::' || c2.CONCEPT_NAME AS "PROCEDURE TYPE",
    PROCEDURE_OCCURRENCE.MODIFIER_CONCEPT_ID || '::' || c3.CONCEPT_NAME AS MODIFIER,
    PROCEDURE_OCCURRENCE.QUANTITY,
    PROVIDER.PROVIDER_NAME,
    PROCEDURE_OCCURRENCE.VISIT_OCCURRENCE_ID,
    PROCEDURE_OCCURRENCE.PROCEDURE_SOURCE_VALUE,
    PROCEDURE_OCCURRENCE.PROCEDURE_SOURCE_CONCEPT_ID || '::' || c4.CONCEPT_NAME AS PROCEDURE_SOURCE,
    PROCEDURE_OCCURRENCE.MODIFIER_SOURCE_VALUE AS QUALIFIER_SOURCE_VALUE,
    'PROCEDURE' AS SDT_TAB,
    PROCEDURE_OCCURRENCE.PERSON_ID || PROCEDURE_SOURCE_VALUE || PROCEDURE_DATETIME AS NK,
    PROCEDURE_OCCURRENCE.ETL_MODULE,
    PROCEDURE_OCCURRENCE.PHI_PAT_ID,
    PROCEDURE_OCCURRENCE.PHI_MRN_CPI,
    PROCEDURE_OCCURRENCE.PHI_CSN_ID,
    PROCEDURE_OCCURRENCE.SRC_TABLE,
    PROCEDURE_OCCURRENCE.SRC_FIELD,
    PROCEDURE_OCCURRENCE.SRC_VALUE_ID

FROM {{ ref('PROCEDURE_OCCURRENCE') }}

INNER JOIN {{ source('OMOP', 'CONCEPT') }} c1
    ON PROCEDURE_OCCURRENCE.PROCEDURE_CONCEPT_ID = c1.CONCEPT_ID

LEFT JOIN {{ source('OMOP', 'CONCEPT') }} c2
    ON PROCEDURE_OCCURRENCE.PROCEDURE_TYPE_CONCEPT_ID = c2.CONCEPT_ID

LEFT JOIN {{ source('OMOP', 'CONCEPT') }} c3
    ON PROCEDURE_OCCURRENCE.MODIFIER_CONCEPT_ID = c3.CONCEPT_ID

LEFT JOIN {{ ref('PROVIDER') }}
    ON PROCEDURE_OCCURRENCE.PROVIDER_ID = PROVIDER.PROVIDER_ID

LEFT JOIN {{ source('OMOP', 'CONCEPT') }} c4
    ON PROCEDURE_OCCURRENCE.PROCEDURE_SOURCE_CONCEPT_ID = c4.CONCEPT_ID

INNER JOIN {{ ref('VISIT_OCCURRENCE') }}
    ON PROCEDURE_OCCURRENCE.VISIT_OCCURRENCE_ID = VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID
)

SELECT * FROM procedure_query
