--QRY_CONDITION_OCCURRENCE

WITH CONDITION_DATA AS (
    SELECT
        CONDITION_OCCURRENCE.CONDITION_OCCURRENCE_ID,
        CONDITION_OCCURRENCE.PERSON_ID,
        LEFT(CONDITION_OCCURRENCE.CONDITION_CONCEPT_ID || '::' || CONCEPT_2.CONCEPT_NAME, 100) AS CONDITION,
        CONDITION_OCCURRENCE.CONDITION_START_DATETIME,
        CONDITION_OCCURRENCE.CONDITION_END_DATETIME,
        CONDITION_OCCURRENCE.CONDITION_TYPE_CONCEPT_ID || '::' || CONCEPT.CONCEPT_NAME AS CONDITION_TYPE,
        CONDITION_OCCURRENCE.STOP_REASON,
        PROVIDER.PROVIDER_NAME,
        CONDITION_OCCURRENCE.VISIT_OCCURRENCE_ID,
        CONDITION_OCCURRENCE.CONDITION_SOURCE_VALUE,
        CONDITION_OCCURRENCE.CONDITION_SOURCE_CONCEPT_ID,
        CONDITION_OCCURRENCE.CONDITION_STATUS_CONCEPT_ID || '::' || CONCEPT_1.CONCEPT_NAME AS CONDITION_STATUS,
        'CONDITION' AS SDT_TAB,
        CONDITION_OCCURRENCE.PERSON_ID || CONDITION_SOURCE_VALUE || CONDITION_START_DATETIME AS NK,
        CONDITION_OCCURRENCE.ETL_MODULE,
        CONDITION_OCCURRENCE.PHI_PAT_ID,
        CONDITION_OCCURRENCE.PHI_MRN_CPI,
        CONDITION_OCCURRENCE.PHI_CSN_ID,
        CONDITION_OCCURRENCE.SRC_TABLE,
        CONDITION_OCCURRENCE.SRC_FIELD,
        CONDITION_OCCURRENCE.SRC_VALUE_ID
    FROM {{ ref('CONDITION_OCCURRENCE') }}
    LEFT JOIN {{ ref('PROVIDER') }}
        ON CONDITION_OCCURRENCE.PROVIDER_ID = PROVIDER.PROVIDER_ID
    LEFT JOIN {{ source('OMOP', 'CONCEPT') }} AS CONCEPT
        ON CONDITION_OCCURRENCE.CONDITION_TYPE_CONCEPT_ID = CONCEPT.CONCEPT_ID
    INNER JOIN {{ source('OMOP', 'CONCEPT') }} AS CONCEPT_1
        ON CONDITION_OCCURRENCE.CONDITION_STATUS_CONCEPT_ID = CONCEPT_1.CONCEPT_ID
    INNER JOIN {{ source('OMOP', 'CONCEPT') }} AS CONCEPT_2
        ON CONDITION_OCCURRENCE.CONDITION_CONCEPT_ID = CONCEPT_2.CONCEPT_ID
    INNER JOIN {{ ref('VISIT_OCCURRENCE') }}
        ON CONDITION_OCCURRENCE.VISIT_OCCURRENCE_ID = VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID
)

SELECT * FROM CONDITION_DATA
