--QRY_SPECIMEN

WITH specimen_detail AS (
    SELECT
        SPECIMEN.SPECIMEN_ID,
        SPECIMEN.PERSON_ID,
        LEFT(SPECIMEN.SPECIMEN_CONCEPT_ID || '::' || c1.CONCEPT_NAME, 100) AS SPECIMENS,
        SPECIMEN.SPECIMEN_DATETIME,
        SPECIMEN.SPECIMEN_TYPE_CONCEPT_ID || '::' || c2.CONCEPT_NAME AS SPECIMEN_TYPE,
        SPECIMEN.QUANTITY,
        SPECIMEN.UNIT_CONCEPT_ID || '::' || c3.CONCEPT_NAME AS UNIT,
        SPECIMEN.ANATOMIC_SITE_CONCEPT_ID || '::' || c4.CONCEPT_NAME AS ANATOMIC_SITE,
        SPECIMEN.DISEASE_STATUS_CONCEPT_ID || '::' || c5.CONCEPT_NAME AS DISEASE_STATUS,
        SPECIMEN.SPECIMEN_SOURCE_ID,
        SPECIMEN.SPECIMEN_SOURCE_VALUE,
        SPECIMEN.UNIT_SOURCE_VALUE,
        SPECIMEN.ANATOMIC_SITE_SOURCE_VALUE,
        SPECIMEN.DISEASE_STATUS_SOURCE_VALUE,
        'SPECIMEN' AS SDT_TAB,
        SPECIMEN.PERSON_ID || SPECIMEN.SPECIMEN_SOURCE_VALUE || SPECIMEN.SPECIMEN_DATETIME AS NK,
        SPECIMEN.ETL_MODULE,
        SPECIMEN.PHI_PAT_ID,
        SPECIMEN.PHI_MRN_CPI,
        SPECIMEN.SRC_TABLE,
        SPECIMEN.SRC_FIELD,
        SPECIMEN.SRC_VALUE_ID
    FROM {{ ref('SPECIMEN') }}
    INNER JOIN {{ source('OMOP', 'CONCEPT') }} c1
        ON SPECIMEN.SPECIMEN_CONCEPT_ID = c1.CONCEPT_ID
    INNER JOIN {{ source('OMOP', 'CONCEPT') }} c2
        ON SPECIMEN.SPECIMEN_TYPE_CONCEPT_ID = c2.CONCEPT_ID
    LEFT JOIN {{ source('OMOP', 'CONCEPT') }} c3
        ON SPECIMEN.UNIT_CONCEPT_ID = c3.CONCEPT_ID
    LEFT JOIN {{ source('OMOP', 'CONCEPT') }} c4
        ON SPECIMEN.ANATOMIC_SITE_CONCEPT_ID = c4.CONCEPT_ID
    LEFT JOIN {{ source('OMOP', 'CONCEPT') }} c5
        ON SPECIMEN.DISEASE_STATUS_CONCEPT_ID = c5.CONCEPT_ID
)

SELECT *
FROM specimen_detail
