-- OMOP_CS.QRY_VISIT_OCCURRENCE


WITH visit_occurrence_details AS (
    SELECT
        VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID,
        VISIT_OCCURRENCE.PERSON_ID,
        VISIT_OCCURRENCE.VISIT_TYPE_CONCEPT_ID || '::' || c1.CONCEPT_NAME AS VISIT_TYPE,
        VISIT_OCCURRENCE.VISIT_START_DATETIME,
        VISIT_OCCURRENCE.VISIT_END_DATETIME,
        PROVIDER.PROVIDER_ID || '::' || PROVIDER_NAME AS PROVIDER,
        CARE_SITE.CARE_SITE_ID || '::' || CARE_SITE_NAME AS CARE_SITE,
        VISIT_OCCURRENCE.VISIT_CONCEPT_ID || '::' || c2.CONCEPT_NAME AS VISIT,
        VISIT_OCCURRENCE.VISIT_SOURCE_CONCEPT_ID,
        VISIT_OCCURRENCE.ADMITTED_FROM_CONCEPT_ID || '::' || c3.CONCEPT_NAME AS ADMITTING_SOURCE,
        VISIT_OCCURRENCE.DISCHARGED_TO_CONCEPT_ID || '::' || c4.CONCEPT_NAME AS DISCHARGE,
        VISIT_OCCURRENCE.ADMITTED_FROM_SOURCE_VALUE,
        VISIT_OCCURRENCE.ADMITTED_FROM_CONCEPT_ID,
        VISIT_OCCURRENCE.DISCHARGED_TO_SOURCE_VALUE,
        VISIT_OCCURRENCE.DISCHARGED_TO_CONCEPT_ID,
        VISIT_OCCURRENCE.PRECEDING_VISIT_OCCURRENCE_ID,
        'VISIT_OCCURRENCE' AS SDT_TAB,
        VISIT_OCCURRENCE.phi_CSN_ID AS NK,
        VISIT_OCCURRENCE.ETL_MODULE,
        VISIT_OCCURRENCE.PHI_PAT_ID,
        VISIT_OCCURRENCE.PHI_MRN_CPI,
        VISIT_OCCURRENCE.PHI_CSN_ID
    FROM {{ ref('VISIT_OCCURRENCE') }}
    LEFT JOIN {{ ref('PROVIDER') }}
        ON VISIT_OCCURRENCE.PROVIDER_ID = PROVIDER.PROVIDER_ID
    INNER JOIN {{ ref('CARE_SITE') }}
        ON VISIT_OCCURRENCE.CARE_SITE_ID = CARE_SITE.CARE_SITE_ID
    INNER JOIN {{ source('OMOP', 'CONCEPT') }} c1
        ON VISIT_OCCURRENCE.VISIT_TYPE_CONCEPT_ID = c1.CONCEPT_ID
    INNER JOIN {{ source('OMOP', 'CONCEPT') }} c2
        ON VISIT_OCCURRENCE.VISIT_CONCEPT_ID = c2.CONCEPT_ID
    INNER JOIN {{ source('OMOP', 'CONCEPT') }} c3
        ON VISIT_OCCURRENCE.ADMITTED_FROM_CONCEPT_ID = c3.CONCEPT_ID
    INNER JOIN {{ source('OMOP', 'CONCEPT') }} c4
        ON VISIT_OCCURRENCE.DISCHARGED_TO_CONCEPT_ID = c4.CONCEPT_ID
)

SELECT * FROM visit_occurrence_details
