/*******************************************************************************
* Procedure Name: PULL_PROCEDURE_OCCURRENCE_AMB_CPT
* Description: Retrieves ambulatory procedure occurrences with CPT codes
* 
* Tables Referenced:
*   - PULL_VISIT_OCCURRENCE_AMB
*   - ORDER_PROC
*   - ORDER_INSTANTIATED
*   - T_CPT_CODES
*   - CLARITY_MOD
*   - Various lookup tables (ZC_*)

*******************************************************************************/

SELECT DISTINCT
    -- OMOP Standard Fields
    PULL_VISIT_OCCURRENCE_AMB.PERSON_ID,

    -- Procedure Dates
    CAST(COALESCE(ORDER_PROC_CHILD.INSTANTIATED_TIME,
                  ORDER_PROC.INSTANTIATED_TIME,
                  ORDER_PROC.PROC_START_TIME,
                  ORDER_PROC.ORDER_TIME) AS DATE) AS PROCEDURE_DATE,
    
    COALESCE(ORDER_PROC_CHILD.INSTANTIATED_TIME,
             ORDER_PROC.INSTANTIATED_TIME,
             ORDER_PROC.PROC_START_TIME,
             ORDER_PROC.ORDER_TIME) AS PROCEDURE_DATETIME,
    
    NULL AS PROCEDURE_END_DATE,
    NULL AS PROCEDURE_END_DATETIME,

    -- Procedure Details
    ORDER_PROC.QUANTITY AS QUANTITY,
    ORDER_PROC.AUTHRZING_PROV_ID AS PROVIDER_SOURCE_VALUE,
    ORDER_PROC.PROC_ID || ':' || T_CPT_CODES.PROC_NAME AS PROCEDURE_SOURCE_VALUE,
    ORDER_PROC.MODIFIER1_ID || ':' || MODIFIER_NAME AS MODIFIER_SOURCE_VALUE,

    -- Additional Fields for Stage
    PULL_VISIT_OCCURRENCE_AMB.PULL_CSN_ID AS PULL_CSN_ID,
    ORDER_PROC.MODIFIER1_ID::VARCHAR AS PULL_MODIFIER1_ID,
    ORDER_PROC.PROC_ID::VARCHAR AS PULL_PROC_ID,
    T_CPT_CODES.PROC_CODE AS PULL_PROC_CODE

FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.PULL_VISIT_OCCURRENCE_AMB AS PULL_VISIT_OCCURRENCE_AMB

    -- Join with Order Processing Tables
    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ORDER_PROC AS ORDER_PROC
        ON PULL_VISIT_OCCURRENCE_AMB.PULL_CSN_ID = ORDER_PROC.PAT_ENC_CSN_ID

    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ORDER_INSTANTIATED AS ORDER_INSTANTIATED
        ON ORDER_PROC.ORDER_PROC_ID = ORDER_INSTANTIATED.ORDER_ID

    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ORDER_PROC AS OP_CHILD
        ON PULL_VISIT_OCCURRENCE_AMB.PULL_CSN_ID = OP_CHILD.PAT_ENC_CSN_ID

    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ORDER_PROC AS ORDER_PROC_CHILD
        ON ORDER_INSTANTIATED.ORDER_ID = ORDER_PROC_CHILD.ORDER_PROC_ID

    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ORDER_DX_PROC AS ORDER_DX_PROC
        ON ORDER_PROC.ORDER_PROC_ID = ORDER_DX_PROC.ORDER_PROC_ID

    -- Join with Reference Tables
    LEFT JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.T_CPT_CODES AS T_CPT_CODES
        ON ORDER_PROC.PROC_ID = T_CPT_CODES.PROC_ID

    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.CLARITY_MOD AS CLARITY_MOD
        ON ORDER_PROC.MODIFIER1_ID = CLARITY_MOD.MODIFIER_ID

    -- Join with Status and Classification Tables
    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_ORDER_STATUS AS ZC_ORDER_STATUS
        ON ORDER_PROC.ORDER_STATUS_C = ZC_ORDER_STATUS.ORDER_STATUS_C

    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_LAB_STATUS AS ZC_LAB_STATUS
        ON ORDER_PROC.LAB_STATUS_C = ZC_LAB_STATUS.LAB_STATUS_C

    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_ORDER_CLASS AS ZC_ORDER_CLASS
        ON ORDER_PROC.ORDER_CLASS_C = ZC_ORDER_CLASS.ORDER_CLASS_C

    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_ORDER_TYPE AS ZC_ORDER_TYPE
        ON ORDER_PROC.ORDER_TYPE_C = ZC_ORDER_TYPE.ORDER_TYPE_C

WHERE
    -- Filter for completed orders only
    ORDER_PROC.ORDER_STATUS_C = 5  -- COMPLETE
    -- Filter for final lab status
    AND ORDER_PROC.LAB_STATUS_C = 3  -- FINAL