/***************************************************************
* Procedure Name: PULL_PROCEDURE_OCCURRENCE_HSP_CPT
* Description: Retrieves procedure occurrences from hospital CPT codes
* 
* Tables Referenced:
* - PULL_VISIT_OCCURRENCE_HSP
* - ORDER_PROC
* - ORDER_DX_PROC
* - T_CPT_CODES
* - ZC_ORDER_STATUS
* - ZC_LAB_STATUS
* - ZC_ORDER_CLASS
* - ZC_ORDER_TYPE
* - CLARITY_MOD
***************************************************************/

SELECT
    -- OMOP Standard Fields
    PULL_VISIT_OCCURRENCE_HSP.PERSON_ID                         AS PERSON_ID,
    ORDER_PROC.PROC_START_TIME::DATE                           AS PROCEDURE_DATE,
    ORDER_PROC.PROC_START_TIME                                 AS PROCEDURE_DATETIME,
    NULL                                                       AS PROCEDURE_END_DATE,
    NULL                                                       AS PROCEDURE_END_DATETIME,
    ORDER_PROC.QUANTITY                                        AS QUANTITY,
    ORDER_PROC.AUTHRZING_PROV_ID                              AS PROVIDER_SOURCE_VALUE,
    ORDER_PROC.PROC_ID || ':' || T_CPT_CODES.PROC_NAME        AS PROCEDURE_SOURCE_VALUE,
    ORDER_PROC.MODIFIER1_ID || ':' || CLARITY_MOD.MODIFIER_NAME AS MODIFIER_SOURCE_VALUE,

    -- Additional Fields for Stage
    PULL_VISIT_OCCURRENCE_HSP.PULL_CSN_ID                     AS PULL_CSN_ID,
    ORDER_PROC.MODIFIER1_ID::VARCHAR                          AS PULL_MODIFIER1_ID,
    ORDER_PROC.PROC_ID::VARCHAR                              AS PULL_PROC_ID,
    T_CPT_CODES.PROC_CODE                                    AS PULL_PROC_CODE

FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.PULL_VISIT_OCCURRENCE_HSP AS PULL_VISIT_OCCURRENCE_HSP

    -- Join with ORDER_PROC table
    INNER JOIN CARE_BRONZE_CLARITY_PROD.DBO.ORDER_PROC AS ORDER_PROC
        ON PULL_VISIT_OCCURRENCE_HSP.PULL_CSN_ID = ORDER_PROC.PAT_ENC_CSN_ID

    -- Join with ORDER_DX_PROC table
    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ORDER_DX_PROC AS ORDER_DX_PROC
        ON ORDER_PROC.ORDER_PROC_ID = ORDER_DX_PROC.ORDER_PROC_ID

    -- Join with T_CPT_CODES table
    INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.T_CPT_CODES AS T_CPT_CODES
        ON ORDER_PROC.PROC_ID = T_CPT_CODES.PROC_ID

    -- Join with ZC_ORDER_STATUS table
    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_ORDER_STATUS AS ZC_ORDER_STATUS
        ON ORDER_PROC.ORDER_STATUS_C = ZC_ORDER_STATUS.ORDER_STATUS_C

    -- Join with ZC_LAB_STATUS table
    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_LAB_STATUS AS ZC_LAB_STATUS
        ON ORDER_PROC.LAB_STATUS_C = ZC_LAB_STATUS.LAB_STATUS_C

    -- Join with ZC_ORDER_CLASS table
    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_ORDER_CLASS AS ZC_ORDER_CLASS
        ON ORDER_PROC.ORDER_CLASS_C = ZC_ORDER_CLASS.ORDER_CLASS_C

    -- Join with ZC_ORDER_TYPE table
    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.ZC_ORDER_TYPE AS ZC_ORDER_TYPE
        ON ORDER_PROC.ORDER_TYPE_C = ZC_ORDER_TYPE.ORDER_TYPE_C

    -- Join with CLARITY_MOD table
    LEFT JOIN CARE_BRONZE_CLARITY_PROD.DBO.CLARITY_MOD AS CLARITY_MOD
        ON ORDER_PROC.MODIFIER1_ID = CLARITY_MOD.MODIFIER_ID

WHERE (ORDER_PROC.ORDER_STATUS_C = 5)  -- Filter for COMPLETED orders
    AND ORDER_PROC.LAB_STATUS_C = 3    -- Filter for FINAL lab status
    AND ORDER_PROC.PROC_START_TIME IS NOT NULL;  -- Ensure procedure start time exists