/*
Description: This query creates a staged provider table by combining provider information
            with specialty and gender mappings from source-to-concept tables.
Tables Used: 
    - PULL_PROVIDER_ALL
    - SOURCE_TO_CONCEPT_MAP_stg
    - CARE_SITE_RAW
Created By: [Author]
Created Date: [Date]
Modified By: [Author]
Modified Date: [Date]
*/

-- CTE for specialty mapping
WITH cte__SOURCE_TO_CONCEPT_MAP_SPECIALTY AS (
    SELECT *
    FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_CLARITY.SOURCE_TO_CONCEPT_MAP_stg
    WHERE SOURCE_VOCABULARY_ID = 'SH_SPECIALTY'
),

-- CTE for gender mapping
cte__SOURCE_TO_CONCEPT_MAP_GENDER AS (
    SELECT *
    FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_CLARITY.SOURCE_TO_CONCEPT_MAP_stg
    WHERE SOURCE_VOCABULARY_ID = 'SH_GENDER'
)

-- Main query to build the staged provider table
SELECT DISTINCT 
    PULL_PROVIDER_ALL.PROVIDER_ID                                    AS PROVIDER_ID,
    PULL_PROVIDER_ALL.PROVIDER_NAME                                 AS PROVIDER_NAME,
    PULL_PROVIDER_ALL.NPI                                          AS NPI,
    PULL_PROVIDER_ALL.DEA                                          AS DEA,
    COALESCE(SOURCE_TO_CONCEPT_MAP_SPECIALTY.TARGET_CONCEPT_ID, 0) AS SPECIALTY_CONCEPT_ID,
    COALESCE(MAX(CARE_SITE.CARE_SITE_ID), 1)                      AS CARE_SITE_ID,
    PULL_PROVIDER_ALL.YEAR_OF_BIRTH                               AS YEAR_OF_BIRTH,
    COALESCE(SOURCE_TO_CONCEPT_MAP_GENDER.TARGET_CONCEPT_ID, 0)    AS GENDER_CONCEPT_ID,
    PULL_PROVIDER_ALL.PROVIDER_ID                                  AS PROVIDER_SOURCE_VALUE,
    PULL_PROVIDER_ALL.SPECIALTY_SOURCE_VALUE                       AS SPECIALTY_SOURCE_VALUE,
    NULL                                                           AS SPECIALTY_SOURCE_CONCEPT_ID,
    GENDER_SOURCE_VALUE                                            AS GENDER_SOURCE_VALUE,
    NULL                                                           AS GENDER_SOURCE_CONCEPT_ID

FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.PULL_PROVIDER_ALL AS PULL_PROVIDER_ALL

    -- Join to get specialty concept mapping
    LEFT OUTER JOIN cte__SOURCE_TO_CONCEPT_MAP_SPECIALTY AS SOURCE_TO_CONCEPT_MAP_SPECIALTY
        ON PULL_PROVIDER_ALL.SPECIALTY_C = SOURCE_TO_CONCEPT_MAP_SPECIALTY.SOURCE_CODE

    -- Join to get care site information
    LEFT JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP.CARE_SITE_RAW AS CARE_SITE
        ON PULL_PROVIDER_ALL.REV_LOC_ID = CARE_SITE.CARE_SITE_ID

    -- Join to get gender concept mapping
    LEFT JOIN cte__SOURCE_TO_CONCEPT_MAP_GENDER AS SOURCE_TO_CONCEPT_MAP_GENDER
        ON PULL_PROVIDER_ALL.SEX_C = SOURCE_TO_CONCEPT_MAP_GENDER.SOURCE_CODE

GROUP BY
    PULL_PROVIDER_ALL.PROVIDER_ID,
    PULL_PROVIDER_ALL.PROVIDER_NAME,
    PULL_PROVIDER_ALL.NPI,
    PULL_PROVIDER_ALL.DEA,
    COALESCE(SOURCE_TO_CONCEPT_MAP_SPECIALTY.TARGET_CONCEPT_ID, 0),
    PULL_PROVIDER_ALL.YEAR_OF_BIRTH,
    COALESCE(SOURCE_TO_CONCEPT_MAP_GENDER.TARGET_CONCEPT_ID, 0),
    PULL_PROVIDER_ALL.PROVIDER_ID,
    LEFT(ZC_SPECIALTY_NAME, 50),
    PULL_PROVIDER_ALL.GENDER_SOURCE_VALUE,
    PULL_PROVIDER_ALL.SPECIALTY_SOURCE_VALUE;