--PROCEDURE_OCCURRENCE_RAW
{{ config(materialized = 'table', schema = 'OMOP') }}

SELECT
    {{ sequence_get_nextval() }}::NUMBER(28,0)      AS PROCEDURE_OCCURRENCE_ID
    ,  PERSON_ID::NUMBER(28,0)                      AS PERSON_ID
    , PROCEDURE_CONCEPT_ID::NUMBER(28,0)            AS PROCEDURE_CONCEPT_ID
    , PROCEDURE_DATE::DATE                          AS PROCEDURE_DATE
    , PROCEDURE_DATETIME::DATETIME                  AS PROCEDURE_DATETIME
    , PROCEDURE_END_DATE::DATE                      AS PROCEDURE_END_DATE
    , PROCEDURE_END_DATETIME::DATETIME              AS PROCEDURE_END_DATETIME
    , PROCEDURE_TYPE_CONCEPT_ID::NUMBER(28,0)       AS PROCEDURE_TYPE_CONCEPT_ID
    , MODIFIER_CONCEPT_ID::NUMBER(28,0)             AS MODIFIER_CONCEPT_ID
    , QUANTITY::NUMBER(28,0)                        AS QUANTITY
    , PROVIDER_ID::NUMBER(28,0)                     AS PROVIDER_ID
    , VISIT_OCCURRENCE_ID::NUMBER(28,0)             AS VISIT_OCCURRENCE_ID
    , VISIT_DETAIL_ID::NUMBER(28,0)                 AS VISIT_DETAIL_ID
    , PROCEDURE_SOURCE_VALUE::VARCHAR(250)          AS PROCEDURE_SOURCE_VALUE --Human readable Source Value use src_VALUE_ID below to link
    , PROCEDURE_SOURCE_CONCEPT_ID::NUMBER(28,0)     AS PROCEDURE_SOURCE_CONCEPT_ID
    , LEFT(MODIFIER_SOURCE_VALUE, 50)::VARCHAR(50)  AS MODIFIER_SOURCE_VALUE

 ------Non OMOP fields -----------
    , ETL_MODULE::VARCHAR                           AS etl_MODULE
    , STAGE_PAT_ID::VARCHAR                  	    AS phi_PAT_ID
    , STAGE_MRN_CPI::NUMBER(28,0)                   AS phi_MRN_CPI
    , STAGE_CSN_ID::NUMBER(28,0)			        AS phi_CSN_ID
    ----- Link to source
    , SRC_TABLE::VARCHAR                            AS src_TABLE
    , SRC_FIELD::VARCHAR                            AS src_FIELD
    , SRC_VALUE_ID::VARCHAR                         AS src_VALUE_ID

FROM
(
    SELECT PERSON_ID, PROCEDURE_CONCEPT_ID, PROCEDURE_DATE, PROCEDURE_DATETIME, PROCEDURE_END_DATE, PROCEDURE_END_DATETIME,
        PROCEDURE_TYPE_CONCEPT_ID, MODIFIER_CONCEPT_ID, QUANTITY, PROVIDER_ID, VISIT_OCCURRENCE_ID, VISIT_DETAIL_ID,
        PROCEDURE_SOURCE_VALUE, PROCEDURE_SOURCE_CONCEPT_ID, MODIFIER_SOURCE_VALUE,
        ETL_MODULE, STAGE_PAT_ID, STAGE_MRN_CPI, STAGE_CSN_ID,
        'CLARITY_EAP' as SRC_TABLE, 'PROC_ID' AS SRC_FIELD, STAGE_PROC_ID::INTEGER AS SRC_VALUE_ID
    FROM {{ref('STAGE_PROCEDURE_OCCURRENCE_AMB_CPT')}}
    UNION ALL
    SELECT PERSON_ID, PROCEDURE_CONCEPT_ID, PROCEDURE_DATE, PROCEDURE_DATETIME, PROCEDURE_END_DATE, PROCEDURE_END_DATETIME,
        PROCEDURE_TYPE_CONCEPT_ID, MODIFIER_CONCEPT_ID, QUANTITY, PROVIDER_ID, VISIT_OCCURRENCE_ID, VISIT_DETAIL_ID,
        PROCEDURE_SOURCE_VALUE, PROCEDURE_SOURCE_CONCEPT_ID, MODIFIER_SOURCE_VALUE,
        ETL_MODULE, STAGE_PAT_ID, STAGE_MRN_CPI, STAGE_CSN_ID,
        'CLARITY_EAP' as SRC_TABLE, 'PROC_ID' AS SRC_FIELD, STAGE_PROC_ID::INTEGER AS SRC_VALUE_ID
    FROM {{ref('STAGE_PROCEDURE_OCCURRENCE_HSP_CPT')}}
    UNION ALL
    SELECT PERSON_ID, PROCEDURE_CONCEPT_ID, PROCEDURE_DATE, PROCEDURE_DATETIME, PROCEDURE_END_DATE, PROCEDURE_END_DATETIME,
        PROCEDURE_TYPE_CONCEPT_ID, MODIFIER_CONCEPT_ID, QUANTITY, PROVIDER_ID, VISIT_OCCURRENCE_ID, VISIT_DETAIL_ID,
        PROCEDURE_SOURCE_VALUE, PROCEDURE_SOURCE_CONCEPT_ID, MODIFIER_SOURCE_VALUE,
        ETL_MODULE, STAGE_PAT_ID, STAGE_MRN_CPI, STAGE_CSN_ID,
        'CLARITY_EAP' as SRC_TABLE, 'PROC_ID' AS SRC_FIELD, STAGE_PROC_ID::INTEGER AS SRC_VALUE_ID
    FROM {{ref('STAGE_PROCEDURE_OCCURRENCE_SURG_CPT')}}
) AS A

