--PROCEDURE_OCCURRENCE
{{ config(materialized = 'view', schema = 'OMOP') }}

SELECT
    PROCEDURE_OCCURRENCE_ID
    , PERSON_ID
    , PROCEDURE_CONCEPT_ID
    , PROCEDURE_DATE
    , PROCEDURE_DATETIME
    , PROCEDURE_END_DATE
    , PROCEDURE_END_DATETIME
    , PROCEDURE_TYPE_CONCEPT_ID
    , MODIFIER_CONCEPT_ID
    , QUANTITY
    , PROVIDER_ID
    , VISIT_OCCURRENCE_ID
    , VISIT_DETAIL_ID
    , PROCEDURE_SOURCE_VALUE --Human readable Source Value use src_VALUE_ID below to link
    , PROCEDURE_SOURCE_CONCEPT_ID
    , MODIFIER_SOURCE_VALUE

 ------Non OMOP fields -----------
    , etl_MODULE
    , phi_PAT_ID
    , phi_MRN_CPI
    , phi_CSN_ID
    ----- Link to source
    , src_TABLE
    , src_FIELD
    , src_VALUE_ID

FROM
{{ref('PROCEDURE_OCCURRENCE_RAW')}} AS PROCEDURE_OCCURRENCE

LEFT JOIN (
    SELECT CDT_ID
    FROM {{ref('QA_ERR_DBT')}} AS QA_ERR_DBT
        WHERE (STANDARD_DATA_TABLE = 'PROCEDURE_OCCURRENCE')
            AND (ERROR_TYPE IN ('FATAL', 'INVALID DATA'))
        ) AS EXCLUSION_RECORDS
        ON PROCEDURE_OCCURRENCE.PROCEDURE_OCCURRENCE_ID = EXCLUSION_RECORDS.CDT_ID
WHERE (EXCLUSION_RECORDS.CDT_ID IS NULL)
