
--DEATH
{{ config(materialized = 'view', schema = 'OMOP') }}

SELECT
     PERSON_ID
    ,DEATH_DATE
    ,DEATH_DATETIME
    ,DEATH_TYPE_CONCEPT_ID
    ,CAUSE_CONCEPT_ID
    ,CAUSE_SOURCE_VALUE
    ,CAUSE_SOURCE_CONCEPT_ID
	-------- Non-OMOP Fields ------------
    ,ETL_MODULE
	,phi_PAT_ID
    ,phi_MRN_CPI
FROM  {{ref('DEATH_RAW')}} AS DEATH
LEFT JOIN (
    SELECT CDT_ID
    FROM {{ref('QA_ERR_DBT')}} AS QA_ERR_DBT
        WHERE (STANDARD_DATA_TABLE = 'DEATH')
            AND (ERROR_TYPE IN ('FATAL', 'INVALID DATA'))
        ) AS EXCLUSION_RECORDS
        ON DEATH.PERSON_ID = EXCLUSION_RECORDS.CDT_ID
WHERE (EXCLUSION_RECORDS.CDT_ID IS NULL)
