-- PULL_PROCEDURE_OCCURRENCE_SURG_CPT
{#-- {{ config(materialized = 'view', schema = 'OMOP_PULL') }}#}

SELECT DISTINCT
-- ***STAGE ATTRIBUTES***
-- OMOP Standard fields used for the Stage
    PULL_VISIT_OCCURRENCE_HSP.PERSON_ID                      AS PERSON_ID
	,COALESCE(
        OR_LOG_VIRTUAL.ACT_START_OTS_DTTM
        , OR_LOG.SCHED_START_TIME)::DATE                            AS PROCEDURE_DATE
	,COALESCE(
        OR_LOG_VIRTUAL.ACT_START_OTS_DTTM
        , OR_LOG.SCHED_START_TIME)                                  AS PROCEDURE_DATETIME
    ,NULL                                                           AS PROCEDURE_END_DATE
    ,NULL                                                           AS PROCEDURE_END_DATETIME
	,1                                                              AS QUANTITY
	,COALESCE(OR_LOG_ALL_SURG.SURG_ID, OR_LOG.PRIMARY_PHYS_ID)      AS PROVIDER_SOURCE_VALUE
	,OR_LOG_ALL_PROC.ALL_PROC_CODE_ID||':'||T_CPT_CODES.PROC_CODE   AS PROCEDURE_SOURCE_VALUE
	,NULL                                                           AS MODIFIER_SOURCE_VALUE

-- ***ADDITIONAL ATTRIBUTES***
-- Non_OMOP fields used for the Stage
	, PULL_VISIT_OCCURRENCE_HSP.PULL_CSN_ID 		                AS PULL_CSN_ID
	,UPPER(OR_LOG_ALL_PROC.ALL_PROC_CODE_ID)						AS PULL_PROC_ID
    ,COALESCE(T_CPT_CODES.PROC_CODE, T_CPT_CODES_2.PROC_CODE)       AS PULL_PROC_CODE
    ,COALESCE(T_CPT_CODES.PROC_NAME, T_CPT_CODES_2.PROC_NAME)       AS PULL_PROC_NAME

-- ***SOURCE ATTRIBUTES***
-- field names pulled from the source for verification purposes.

    -- ,PULL_VISIT_OCCURRENCE_HSP.PAT_ENC_CSN_ID
    -- ,PULL_VISIT_OCCURRENCE_HSP.PAT_ID
    -- ,PULL_VISIT_OCCURRENCE_HSP.HSP_ACCOUNT_ID
    -- ,OR_LOG.INPATIENT_DATA_ID
    -- ,OR_LOG.SURGERY_DATE
    -- ,OR_LOG.SCHED_START_TIME
    -- ,OR_LOG.TOTAL_TIME_NEEDED
    -- ,OR_LOG_VIRTUAL.ACT_START_OTS_DTTM
    -- ,OR_LOG_VIRTUAL.ACT_END_OTS_DTTM
    -- ,COALESCE(OR_LOG_VIRTUAL.ACT_START_OTS_DTTM, OR_LOG.SCHED_START_TIME) AS CALC_START_TIME
    -- ,COALESCE(OR_LOG_VIRTUAL.ACT_END_OTS_DTTM, DATEADD(MINUTE, OR_LOG.TOTAL_TIME_NEEDED::INTEGER, OR_LOG.SCHED_START_TIME)) AS CALC_END_DTTM
    -- ,OR_LOG.PRIMARY_PHYS_ID
    -- ,OR_LOG_ALL_SURG.SURG_ID
    -- ,COALESCE(OR_LOG_ALL_SURG.SURG_ID, OR_LOG.PRIMARY_PHYS_ID) AS CALC_PERFORM_PHYS
    -- ,OR_LOG_ALL_PROC.OR_PROC_ID
    -- ,(COALESCE(OR_LOG_ALL_PROC.ALL_PROC_CODE_ID, OR_OPE_PROC_CODE.PROC_CODE_ID)) AS PROC_CODE_ID
    -- ,OR_LOG_ALL_PROC.LINE
    -- ,OR_LOG_VIRTUAL.PRIMARY_PROC_ID
    -- ,COALESCE(T_CPT_CODES.PROC_CODE, T_CPT_CODES_2.PROC_CODE) AS PROC_CODE
    -- ,COALESCE(T_CPT_CODES.PROC_NAME, T_CPT_CODES_2.PROC_NAME) AS PROC_NAME
    -- ,OR_LOG.STATUS_C
    -- ,ZC_OR_STATUS_NAME

FROM {{ref('PULL_VISIT_OCCURRENCE_HSP')}} AS PULL_VISIT_OCCURRENCE_HSP

    INNER JOIN {{ ref('PAT_OR_ADM_LINK_stg')}} AS PAT_OR_ADM_LINK
        ON  PULL_VISIT_OCCURRENCE_HSP.PULL_CSN_ID = PAT_OR_ADM_LINK.OR_LINK_CSN

    INNER JOIN {{ ref('OR_LOG_stg')}} AS OR_LOG
        ON PAT_OR_ADM_LINK.LOG_ID = OR_LOG.LOG_ID

    INNER JOIN {{ ref('OR_LOG_VIRTUAL_stg')}} AS OR_LOG_VIRTUAL
        ON OR_LOG.LOG_ID = OR_LOG_VIRTUAL.LOG_ID

    INNER JOIN {{ ref('OR_LOG_ALL_PROC_stg')}} AS OR_LOG_ALL_PROC
        ON OR_LOG.LOG_ID = OR_LOG_ALL_PROC.LOG_ID

    LEFT JOIN {{ ref('OR_LOG_ALL_SURG_stg')}} AS OR_LOG_ALL_SURG
        ON OR_LOG.LOG_ID = OR_LOG_ALL_SURG.LOG_ID
            AND OR_LOG_ALL_PROC.LINE = OR_LOG_ALL_SURG.LINE

--ALL_PROC_CODE_ID is only populated for older surgical logs which were created and last modified before upgrading to the Epic 2018 version
    LEFT JOIN {{ref('T_CPT_CODES')}} AS T_CPT_CODES
        ON OR_LOG_ALL_PROC.ALL_PROC_CODE_ID = T_CPT_CODES.PROC_ID
------------------------------------------------------------------------------------------
      --alternative join to T_CPT_CODES (via OR_OPE_PROC_CODE)
      --For newer surgical logs, codes are in OR_OPE_PROC_CODE.PROC_CODE_ID. OR_LOG_ALL_PROC joins to OR_OPE_PROC_CODE on column ALL_PANEL_ADDL_ID.
      LEFT JOIN {{ ref('OR_OPE_PROC_CODE_stg')}} AS OR_OPE_PROC_CODE
          ON OR_LOG_ALL_PROC.ALL_PANEL_ADDL_ID = OR_OPE_PROC_CODE.OPE_ID
      LEFT JOIN {{ref('T_CPT_CODES')}} AS T_CPT_CODES_2
          ON OR_OPE_PROC_CODE.PROC_CODE_ID = T_CPT_CODES_2.PROC_ID
------------------------------------------------------------------------------------------

    LEFT JOIN {{ ref('ZC_OR_STATUS_stg')}} AS ZC_OR_STATUS
        ON OR_LOG.STATUS_C = ZC_OR_STATUS.STATUS_C

WHERE (OR_LOG.STATUS_C = 2)
    AND (COALESCE(OR_LOG_ALL_PROC.ALL_PROC_CODE_ID, OR_OPE_PROC_CODE.PROC_CODE_ID)) IS NOT NULL



