
--PULL_PROCEDURE_OCCURRENCE_AMB_CPT
{#-- {{ config(materialized = 'view', schema = 'OMOP_PULL') }}#}
SELECT DISTINCT
-- ***STAGE ATTRIBUTES***
-- OMOP Standard fields used for the Stage
    PULL_VISIT_OCCURRENCE_AMB.PERSON_ID

	,CAST( COALESCE(ORDER_PROC_CHILD.INSTANTIATED_TIME
				, ORDER_PROC.INSTANTIATED_TIME
				, ORDER_PROC.PROC_START_TIME
				, ORDER_PROC.ORDER_TIME) AS DATE) 			AS PROCEDURE_DATE
	,COALESCE(ORDER_PROC_CHILD.INSTANTIATED_TIME
				, ORDER_PROC.INSTANTIATED_TIME
				, ORDER_PROC.PROC_START_TIME
				, ORDER_PROC.ORDER_TIME) 					AS PROCEDURE_DATETIME
    ,NULL AS PROCEDURE_END_DATE
    ,NULL AS PROCEDURE_END_DATETIME
	,ORDER_PROC.QUANTITY						 			AS QUANTITY
	,ORDER_PROC.AUTHRZING_PROV_ID 							AS PROVIDER_SOURCE_VALUE
	,ORDER_PROC.PROC_ID||':'||T_CPT_CODES.PROC_NAME			AS PROCEDURE_SOURCE_VALUE
	,ORDER_PROC.MODIFIER1_ID|| ':' || MODIFIER_NAME 		AS MODIFIER_SOURCE_VALUE

-- ***ADDITIONAL ATTRIBUTES***
-- Non_OMOP fields used for the Stage
	,PULL_VISIT_OCCURRENCE_AMB.PULL_CSN_ID 					AS PULL_CSN_ID
	,ORDER_PROC.MODIFIER1_ID::VARCHAR						AS PULL_MODIFIER1_ID
	,ORDER_PROC.PROC_ID	::VARCHAR							AS PULL_PROC_ID
	,T_CPT_CODES.PROC_CODE									AS PULL_PROC_CODE

-- ***SOURCE ATTRIBUTES***
-- field names pulled from the source for verification purposes.

	{# ,PULL_VISIT_OCCURRENCE_AMB.PAT_ID
	,PULL_VISIT_OCCURRENCE_AMB.PAT_ENC_CSN_ID
	,PULL_VISIT_OCCURRENCE_AMB.HSP_ACCOUNT_ID
	,PULL_VISIT_OCCURRENCE_AMB.IP_DOC_CONTACT_CSN
	,PULL_VISIT_OCCURRENCE_AMB.ENC_TYPE_C
	,PULL_VISIT_OCCURRENCE_AMB.ZC_DISP_ENC_TYPE_NAME
	,PAT_OR_ADM_LINK_CSN AS PAT_OR_ADM_LINK_PAT_ENC_CSN_ID
	,ORDER_PROC.INSTANTIATED_TIME AS OP_INSTANTIATED_TIME
	,ORDER_PROC.ORDER_TIME AS OP_ORDER_TIME
	,ORDER_PROC.PROC_START_TIME AS OP_PROC_START_TIME
	,ORDER_PROC.PROC_BGN_TIME AS OP_PROC_BGN_TIME
	,ORDER_PROC.PROC_END_TIME AS OP_PROC_END_TIME
	,ORDER_PROC_CHILD.ORDER_TIME AS OP_CHILD_ORDER_TIME
	,ORDER_PROC_CHILD.PROC_START_TIME AS OP_CHILD_START_TIME
	,ORDER_PROC_CHILD.INSTANTIATED_TIME AS OP_CHILD_INSTANTIATED_TIME
	,ORDER_PROC_CHILD.PROC_BGN_TIME AS OP_CHILD_PROC_BGN_TIME
	,ORDER_PROC_CHILD.PROC_END_TIME AS OP_CHILD_PROC_END_TIME
	,ORDER_PROC.MODIFIER1_ID
	,MODIFIER_NAME
	,ORDER_PROC.QUANTITY
	,ORDER_PROC.AUTHRZING_PROV_ID
	,ORDER_PROC.FUTURE_OR_STAND
	, ORDER_PROC.PROC_ID
	,ORDER_DX_PROC.LINE AS ORDER_DX_LINE
	,ORDER_DX_PROC.DX_ID AS ORDER_DX_ID
	,T_CPT_CODES.PROC_CODE
	,T_CPT_CODES.PROC_NAME
	,ORDER_PROC.ORDER_STATUS_C
	,ZC_ORDER_STATUS_NAME AS ZC_ORDER_STATUS_NAME
	, ORDER_PROC.ORDER_PROC_ID
	, ORDER_PROC.ORDER_TYPE_C
	, ZC_ORDER_TYPE_NAME AS ZC_ORDER_TYPE_NAME
	,ORDER_PROC.ORDER_CLASS_C
	,ZC_ORDER_CLASS_NAME AS ZC_ORDER_CLASS_NAME
	,ORDER_PROC.LAB_STATUS_C
	,ZC_LAB_STATUS_NAME AS ZC_LAB_STATUS_NAME #}


FROM {{ ref('PULL_VISIT_OCCURRENCE_AMB')}}  AS PULL_VISIT_OCCURRENCE_AMB

	LEFT JOIN {{ ref('ORDER_PROC_stg')}} AS ORDER_PROC
		ON  PULL_VISIT_OCCURRENCE_AMB.PULL_CSN_ID = ORDER_PROC.PAT_ENC_CSN_ID

	LEFT JOIN {{ ref('ORDER_INSTANTIATED_stg')}} AS ORDER_INSTANTIATED
		ON ORDER_PROC.ORDER_PROC_ID = ORDER_INSTANTIATED.ORDER_ID

	LEFT JOIN {{ ref('ORDER_PROC_stg')}} AS OP_CHILD
		ON  PULL_VISIT_OCCURRENCE_AMB.PULL_CSN_ID = OP_CHILD.PAT_ENC_CSN_ID

	LEFT JOIN {{ ref('ORDER_PROC_stg')}}  AS ORDER_PROC_CHILD
		ON ORDER_INSTANTIATED.ORDER_ID = ORDER_PROC_CHILD.ORDER_PROC_ID

	LEFT JOIN {{ ref('ORDER_DX_PROC_stg')}} AS ORDER_DX_PROC
	   ON ORDER_PROC.ORDER_PROC_ID = ORDER_DX_PROC.ORDER_PROC_ID

	LEFT JOIN {{ref('T_CPT_CODES')}} AS T_CPT_CODES
		ON ORDER_PROC.PROC_ID = T_CPT_CODES.PROC_ID

	LEFT JOIN {{ ref('CLARITY_MOD_stg')}} AS CLARITY_MOD
		ON ORDER_PROC.MODIFIER1_ID = CLARITY_MOD.MODIFIER_ID

	LEFT JOIN {{ ref('ZC_ORDER_STATUS_stg')}} AS ZC_ORDER_STATUS
	   ON ORDER_PROC.ORDER_STATUS_C = ZC_ORDER_STATUS.ORDER_STATUS_C

	LEFT JOIN {{ ref('ZC_LAB_STATUS_stg')}} AS ZC_LAB_STATUS
	   ON ORDER_PROC.LAB_STATUS_C = ZC_LAB_STATUS.LAB_STATUS_C

	LEFT JOIN {{ ref('ZC_ORDER_CLASS_stg')}} AS 	ZC_ORDER_CLASS
	   ON ORDER_PROC.ORDER_CLASS_C = ZC_ORDER_CLASS.ORDER_CLASS_C

	LEFT JOIN {{ ref('ZC_ORDER_TYPE_stg')}} AS 	ZC_ORDER_TYPE
	   ON ORDER_PROC.ORDER_TYPE_C = ZC_ORDER_TYPE.ORDER_TYPE_C

WHERE
-- (
-- 		PULL_VISIT_OCCURRENCE_AMB.CALCULATED_ENC_STAT_C = 2
-- 		OR PULL_VISIT_OCCURRENCE_AMB.CALCULATED_ENC_STAT_C IS NULL
-- 		)
-- 	AND (
-- 		PULL_VISIT_OCCURRENCE_AMB.APPT_STATUS_C = 2
-- 		OR PULL_VISIT_OCCURRENCE_AMB.APPT_STATUS_C IS NULL
-- 		)
-- 	AND
		ORDER_PROC.ORDER_STATUS_C = 5 -- COMPLETE

--ADDED 11/6/2020 TO REMOVE FUTURE OR STANDING ORDERS
	AND
		ORDER_PROC.LAB_STATUS_C = 3 -- FINAL


