{{ config(materialized='ephemeral') }}
--BEGIN cte__SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_BPS
    SELECT *
    FROM {{ref('SOURCE_TO_CONCEPT_MAP_stg')}}
    WHERE SOURCE_VOCABULARY_ID = 'SH_FLWSHT_MEAS_BPS'
--END cte__SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_BPS
--
