{{ config(materialized='ephemeral') }}
--BEGIN cte__SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_BPM
    SELECT *
    FROM {{ref('SOURCE_TO_CONCEPT_MAP_stg')}}
    WHERE SOURCE_VOCABULARY_ID = 'SH_FLWSHT_MEAS_BPM'
--END cte__SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_BPM
--
