{{ config(materialized='ephemeral') }}
--BEGIN cte__SOURCE_TO_CONCEPT_MAP_XRF_INFERRED_UNIT
    SELECT *
    FROM {{ref('SOURCE_TO_CONCEPT_MAP_stg')}}
    WHERE SOURCE_VOCABULARY_ID = 'SH_XRF_INFERRED_UNIT'
--END cte__SOURCE_TO_CONCEPT_MAP_XRF_INFERRED_UNIT
--
