{{ config(materialized = 'ephemeral') }}
--BEGIN cte__T_TEMPERATURE_MERGE
    SELECT T_TEMPERATURE.PERSON_ID
        ,T_TEMPERATURE.PAT_ENC_CSN_ID
        ,SOURCE_TO_CONCEPT_MAP_FLOWSHEET_TEMP_SRC.TARGET_CONCEPT_ID AS TARGET_CONCEPT_ID --TEMPERATURE
        ,T_TEMPERATURE.RECORDED_TIME
        ,T_TEMPERATURE.MEAS_VALUE AS MEAS_VALUE
        ,T_TEMPERATURE.MINVALUE
        ,T_TEMPERATURE.MAX_VAL
        ,T_TEMPERATURE.FLO_MEAS_NAME
        ,SOURCE_TO_CONCEPT_MAP_FLOWSHEET_TEMP_SRC.SOURCE_CODE_DESCRIPTION
        ,T_TEMPERATURE.FLO_MEAS_ID
        ,T_TEMPERATURE.FSD_ID
        ,T_TEMPERATURE.CALC_ATTEND_PROV_ID
        ,T_TEMPERATURE.UNITS

    FROM {{ref('T_TEMPERATURE')}} AS T_TEMPERATURE

    INNER JOIN {{ref('T_TEMP_SOURCE')}} AS T_TEMP_SOURCE
        ON T_TEMPERATURE.PAT_ENC_CSN_ID = T_TEMP_SOURCE.PAT_ENC_CSN_ID
            AND T_TEMPERATURE.RECORDED_TIME = T_TEMP_SOURCE.RECORDED_TIME

    INNER JOIN {{ ref('SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_TEMP_SRC')}} AS SOURCE_TO_CONCEPT_MAP_FLOWSHEET_TEMP_SRC
        ON T_TEMP_SOURCE.MEAS_VALUE = SOURCE_TO_CONCEPT_MAP_FLOWSHEET_TEMP_SRC.SOURCE_CODE
--END cte__T_TEMPERATURE_MERGE
--
