{{ config(materialized='ephemeral') }}
--BEGIN cte__T_TEMPERATURE_ANES
    SELECT DISTINCT PERSON_ID
            ,PAT_ENC_CSN_ID
            ,RECORDED_TIME
            ,MEAS_VALUE
            ,MINVALUE
            ,MAX_VAL
            ,FLO_MEAS_NAME
            ,FLO_MEAS_ID
            ,FSD_ID
            ,VISIT_PROV_ID
            ,UNITS

        FROM {{ref('PULL_MEASUREMENT_ANES_FLOWSHEET')}} AS PULL_MEASUREMENT_ANES_FLOWSHEET
        INNER JOIN {{ ref('SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_TEMP')}} AS SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS
            ON FLO_MEAS_ID::VARCHAR = SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS.SOURCE_CODE
--END cte__T_TEMPERATURE_ANES
--
