-- T_TEMP_SOURCE_AMB

{{ config(materialized='ephemeral') }}
--BEGIN cte__T_TEMP_SOURCE_AMB
    SELECT DISTINCT PERSON_ID
        ,PAT_ENC_CSN_ID
        ,RECORDED_TIME
        ,MEAS_VALUE AS MEAS_VALUE

    FROM {{ref('PULL_MEASUREMENT_AMB_FLOWSHEET')}} AS PULL_MEASUREMENT_AMB_FLOWSHEET
    WHERE FLO_MEAS_ID IN ('7')
--END cte__T_TEMP_SOURCE_AMB
--
