-- STAGE_NOTE_ANES
{#-- {{ config(materialized = 'view', schema = 'OMOP_STAGE') }}#}
--
SELECT  DISTINCT

	PULL_NOTE_ANES_ALL.PERSON_ID 									AS PERSON_ID
	,NOTE_DATE 														AS NOTE_DATE
	,NOTE_DATETIME			 										AS NOTE_DATETIME
	,32817 															AS NOTE_TYPE_CONCEPT_ID
	,COALESCE(SOURCE_TO_CONCEPT_MAP_NOTE_CLASS.TARGET_CONCEPT_ID, 0) AS NOTE_CLASS_CONCEPT_ID
	,NOTE_TITLE														AS NOTE_TITLE
	-- ******************************************
	--   ,'NO_TEXT' AS NOTE_TEXT	-- NO ACTUAL TEXT IS BEING WRITTEN AT THIS TIME OVER PHI CONCERNS
	,PULL_NOTE_ANES_ALL.NOTE_TEXT 									AS NOTE_TEXT
	-- ******************************************
	,32678 															AS ENCODING_CONCEPT_ID --UTF-8
	,4180186 														AS LANGUAGE_CONCEPT_ID
	,PROVIDER.PROVIDER_ID 											AS PROVIDER_ID
	,VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID 							AS VISIT_OCCURRENCE_ID
--    ,VISIT_DETAIL.VISIT_DETAIL_ID AS VISIT_DETAIL_ID
    ,NULL 																AS VISIT_DETAIL_ID
	,NOTE_SOURCE_VALUE 												AS NOTE_SOURCE_VALUE
    ,NULL 																AS NOTE_EVENT_ID
    ,NULL 																AS NOTE_EVENT_FIELD_CONCEPT_ID
	-------- Non-OMOP Fields ------------
	, 'NOTE_ANES' 													AS ETL_MODULE
    ,PULL_NOTE_ANES_ALL.PULL_IP_NOTE_TYPE_C						    AS STAGE_IP_NOTE_TYPE_C
    ,PULL_NOTE_ANES_ALL.PULL_NOTE_ID						            AS STAGE_NOTE_ID
	,VISIT_OCCURRENCE.phi_PAT_ID                      				AS STAGE_PAT_ID
    ,VISIT_OCCURRENCE.phi_MRN_CPI                           		AS STAGE_MRN_CPI
	,VISIT_OCCURRENCE.phi_CSN_ID									AS STAGE_CSN_ID

FROM {{ref('PULL_NOTE_ANES_ALL')}} AS PULL_NOTE_ANES_ALL

    -- INNER JOIN {{ref('T_NOTE_DATE_ANES_MAX')}} AS T_MAX_NOTE_DATE
    --     ON PULL_NOTE_ANES_ALL.PULL_NOTE_ID = T_MAX_NOTE_DATE.PULL_NOTE_ID
       -- AND PULL_NOTE_ANES_ALL.PULL_NOTE_LINE= T_MAX_NOTE_DATE.PULL_NOTE_LINE

    LEFT JOIN {{ ref('SOURCE_TO_CONCEPT_MAP_NOTE_CLASS')}} AS SOURCE_TO_CONCEPT_MAP_NOTE_CLASS
        ON PULL_IP_NOTE_TYPE_C || PULL_AMB_NOTE_YN = SOURCE_TO_CONCEPT_MAP_NOTE_CLASS.SOURCE_CODE

    LEFT JOIN {{ref('VISIT_OCCURRENCE_RAW')}} AS VISIT_OCCURRENCE
        ON PULL_NOTE_ANES_ALL.PULL_CSN_ID = VISIT_OCCURRENCE.phi_CSN_ID

    LEFT JOIN {{ref('PROVIDER_RAW')}} AS PROVIDER
        ON PULL_NOTE_ANES_ALL.PROVIDER_SOURCE_VALUE = PROVIDER.PROVIDER_SOURCE_VALUE

WHERE NOTE_DATE IS NOT NULL
	--AND PULL_NOTE_ANES_ALL.PULL_NOTE_LINE = 1

