------ QA_NOTE_NULLCONCEPT_DETAIL
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH NULLCONCEPT_DETAIL
AS (
	SELECT 'NOTE_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, NOTE_ID AS CDT_ID
	FROM {{ref('NOTE_RAW')}} AS NOTE
	WHERE (NOTE_TYPE_CONCEPT_ID IS NULL)

	UNION ALL

	SELECT 'NOTE_CLASS_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
		, NOTE_ID AS CDT_ID
	FROM {{ref('NOTE_RAW')}} AS NOTE
	WHERE (NOTE_CLASS_CONCEPT_ID IS NULL)

	-- UNION ALL

	-- SELECT 'ENCODING_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
	-- 	, NOTE_ID AS CDT_ID
	-- FROM {{ref('NOTE_RAW')}} AS NOTE
	-- WHERE (ENCODING_CONCEPT_ID IS NULL)

	-- UNION ALL

	-- SELECT 'LANGUAGE_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE
	-- 	, NOTE_ID AS CDT_ID
	-- FROM {{ref('NOTE_RAW')}} AS NOTE
	-- WHERE (LANGUAGE_CONCEPT_ID IS NULL)
)

SELECT CAST( GETDATE() AS DATE) AS RUN_DATE
	,'NOTE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NULLCONCEPT_DETAIL
  WHERE ERROR_TYPE <>'EXPECTED'

