------ QA_NOTE_ZEROCONCEPT_DETAIL
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH ZEROCONCEPT_DETAIL
AS (
	SELECT 'NOTE_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE
		, NOTE_ID AS CDT_ID
	FROM {{ref('NOTE_RAW')}} AS NOTE
	WHERE (NOTE_TYPE_CONCEPT_ID = 0)

	UNION ALL

	SELECT 'NOTE_CLASS_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE
		, NOTE_ID AS CDT_ID
	FROM {{ref('NOTE_RAW')}} AS NOTE
	WHERE (NOTE_CLASS_CONCEPT_ID = 0)

	-- UNION ALL

	-- SELECT 'ENCODING_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE
	-- 	, NOTE_ID AS CDT_ID
	-- FROM {{ref('NOTE_RAW')}} AS NOTE
	-- WHERE (ENCODING_CONCEPT_ID = 0)

	-- UNION ALL

	-- SELECT 'LANGUAGE_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE
	-- 	, NOTE_ID AS CDT_ID
	-- FROM {{ref('NOTE_RAW')}} AS NOTE
	-- WHERE (LANGUAGE_CONCEPT_ID = 0)
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'NOTE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM ZEROCONCEPT_DETAIL
  WHERE ERROR_TYPE <>'EXPECTED'

