--QA_NOTE_DATEVDATETIME_DETAIL
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH DATEVDATETIME_DETAIL AS (
SELECT 'NOTE_DATE' AS METRIC_FIELD, 'DATEVDATETIME' AS QA_METRIC, 'WARNING' AS ERROR_TYPE,
	NOTE_ID AS CDT_ID
FROM {{ref('NOTE_RAW')}} AS T1
WHERE NOTE_DATE <> CAST( NOTE_DATETIME AS DATE)
)

SELECT CAST( GETDATE() AS DATE) AS RUN_DATE
	,'NOTE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM DATEVDATETIME_DETAIL

