---- QA_NOTE_NONSTANDARD_DETAIL
-------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH NONSTANDARD_DETAIL
AS (
	SELECT 'NOTE_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, NOTE_ID AS CDT_ID
	FROM {{ref('NOTE_RAW')}} AS NT
	LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C
		ON NT.NOTE_TYPE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'TYPE CONCEPT' AND upper(C.VOCABULARY_ID) =  ('TYPE CONCEPT')
	WHERE NOTE_TYPE_CONCEPT_ID <> 0 AND NOTE_TYPE_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)

	UNION ALL

	SELECT 'NOTE_CLASS_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, NOTE_ID AS CDT_ID
	FROM {{ref('NOTE_RAW')}} AS NT
	LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C
		ON NT.NOTE_CLASS_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'MEAS VALUE' AND upper(C.VOCABULARY_ID) IN  ('LOINC')
		AND C.CONCEPT_CLASS_ID IN ('DOC KIND', 'DOC SUBJECT MATTER', 'DOC SETTING', 'DOC ROLE', 'DOC TYPE OF SERVICE')
	WHERE NOTE_CLASS_CONCEPT_ID <> 0 AND NOTE_CLASS_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)

	-- UNION ALL

	-- SELECT 'ENCODING_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
	-- 	, NOTE_ID AS CDT_ID
	-- FROM {{ref('NOTE_RAW')}} AS NT
	-- LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C
	-- 	ON NT.ENCODING_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'METADATA' AND upper(C.CONCEPT_CLASS_ID) =  'METADATA'
	-- WHERE ENCODING_CONCEPT_ID <> 0 AND ENCODING_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)

	-- UNION ALL

	-- SELECT 'LANGUAGE_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
	-- 	, NOTE_ID AS CDT_ID
	-- FROM {{ref('NOTE_RAW')}} AS NT
	-- LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C
	-- 	ON NT.LANGUAGE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'LANGUAGE' AND upper(C.VOCABULARY_ID) =  ('SNOMED')
	-- 	AND UPPER(C.CONCEPT_CLASS_ID) = 'QUALIFIER VALUE'
	-- WHERE LANGUAGE_CONCEPT_ID <> 0 AND LANGUAGE_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)
	)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'NOTE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NONSTANDARD_DETAIL
  WHERE ERROR_TYPE <>'EXPECTED'

