
--BEGIN cte__SOURCE_TO_CONCEPT_MAP_DEVICE_LDA
    SELECT *
    FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_CLARITY.SOURCE_TO_CONCEPT_MAP_stg
    WHERE SOURCE_VOCABULARY_ID = 'SH_DEVICE_LDA'
--END cte__SOURCE_TO_CONCEPT_MAP_DEVICE_LDA