
--QA_CONDITION_OCCURRENCE_END_BEFORE_START_COUNT
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH END_BEFORE_START_COUNT AS (
SELECT  'CONDITION_END_DATETIME' AS METRIC_FIELD, 'END_BEFORE_START' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE, COUNT(*) AS CNT
FROM {{ref('CONDITION_OCCURRENCE_RAW')}} AS CO
WHERE CONDITION_END_DATETIME < CONDITION_START_DATETIME
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	, 'CONDITION_OCCURRENCE' AS STANDARD_DATA_TABLE
	, QA_METRIC
	, METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) IS NOT NULL AND SUM(CNT) <> 0 THEN ERROR_TYPE ELSE NULL END   AS ERROR_TYPE
	,(SELECT COUNT(*) AS NUM_ROWS FROM {{ref('CONDITION_OCCURRENCE_RAW')}}) AS TOTAL_RECORDS
	,(SELECT COUNT(*) AS NUM_ROWS FROM {{ref('CONDITION_OCCURRENCE')}}) AS TOTAL_RECORDS_CLEAN
FROM END_BEFORE_START_COUNT
GROUP BY  METRIC_FIELD, QA_METRIC, ERROR_TYPE
