
--QA_CONDITION_OCCURRENCE_END_BEFORE_START_DETAIL
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH END_BEFORE_START_DETAIL AS (
SELECT 'CONDITION_END_DATETIME' AS METRIC_FIELD, 'END_BEFORE_START' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE, CONDITION_OCCURRENCE_ID AS CDT_ID
FROM {{ref('CONDITION_OCCURRENCE_RAW')}} AS CONDITION_OCCURRENCE
WHERE CONDITION_END_DATETIME < CONDITION_START_DATETIME
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'CONDITION_OCCURRENCE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM END_BEFORE_START_DETAIL
