
--QA_CONDITION_OCCURRENCE_DATEVDATETIME_DETAIL
---------------------------------------------------------------------

WITH DATEVDATETIME_DETAIL AS (
SELECT 'CONDITION_START_DATE' AS METRIC_FIELD, 'DATEVDATETIME' AS QA_METRIC, 'WARNING' AS ERROR_TYPE,
	 CONDITION_OCCURRENCE_ID AS CDT_ID
FROM {{ref('CONDITION_OCCURRENCE_RAW')}} AS T1
WHERE CONDITION_START_DATE <> CAST(CONDITION_START_DATETIME AS DATE)

UNION ALL

SELECT 'CONDITION_END_DATE' AS METRIC_FIELD, 'DATEVDATETIME' AS QA_METRIC, 'WARNING' AS ERROR_TYPE,
	 CONDITION_OCCURRENCE_ID AS CDT_ID
FROM {{ref('CONDITION_OCCURRENCE_RAW')}} AS T1
WHERE CONDITION_END_DATE <> CAST(CONDITION_END_DATETIME AS DATE)
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'CONDITION_OCCURRENCE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM DATEVDATETIME_DETAIL
