
--QA_CONDITION_OCCURRENCE_NOVISIT_COUNT
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH NOVISIT_COUNT AS (
SELECT 'VISIT_OCCURRENCE_ID' AS METRIC_FIELD, 'NO VISIT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE, COUNT(*) AS CNT
FROM {{ref('CONDITION_OCCURRENCE_RAW')}} AS CONDITION_OCCURRENCE
LEFT JOIN {{ref('VISIT_OCCURRENCE_RAW')}} AS VISIT_OCCURRENCE
	ON CONDITION_OCCURRENCE.VISIT_OCCURRENCE_ID = VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID
WHERE (VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID IS NULL)
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	, 'CONDITION_OCCURRENCE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) IS NOT NULL AND SUM(CNT) <> 0 THEN ERROR_TYPE ELSE NULL END AS ERROR_TYPE_RAW
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('CONDITION_OCCURRENCE_RAW')}}) AS TOTAL_RECORDS
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('CONDITION_OCCURRENCE')}}) AS TOTAL_RECORDS_CLEAN
FROM NOVISIT_COUNT
GROUP BY   METRIC_FIELD, QA_METRIC, ERROR_TYPE
