
--STAGE_DRUG_EXPOSURE_ALL_IMM
--
{#-- {{ config(materialized = 'view', schema = 'OMOP_STAGE') }}#}

SELECT DISTINCT
	 PULL_DRUG_EXPOSURE_ALL_IMM.PERSON_ID 			            AS PERSON_ID
    ,T_IMM_CONCEPT.DRUG_CONCEPT_ID 							    AS DRUG_CONCEPT_ID
	,DRUG_EXPOSURE_START_DATE 									AS DRUG_EXPOSURE_START_DATE
	,DRUG_EXPOSURE_START_DATETIME 								AS DRUG_EXPOSURE_START_DATETIME
    --End date same as start date
	,DRUG_EXPOSURE_START_DATE								    AS DRUG_EXPOSURE_END_DATE
	,DRUG_EXPOSURE_START_DATETIME							    AS DRUG_EXPOSURE_END_DATETIME
	,NULL            											AS VERBATIM_END_DATE
	,32817 														AS DRUG_TYPE_CONCEPT_ID -- EHR
	,NULL					 							        AS STOP_REASON
    ,NULL 													    AS REFILLS
	,NULL 													    AS QUANTITY
	,NULL 												        AS DAYS_SUPPLY
	,NULL                                                       AS SIG
	,COALESCE(SOURCE_TO_CONCEPT_MAP_IMM_ROUTE.TARGET_CONCEPT_ID, 0) AS ROUTE_CONCEPT_ID
	,LOT_NUMBER 												AS LOT_NUMBER
	,PROVIDER.PROVIDER_ID 										AS PROVIDER_ID
	,VISIT_OCCURRENCE_ID 										AS VISIT_OCCURRENCE_ID
--    ,VISIT_DETAIL.VISIT_DETAIL_ID AS VISIT_DETAIL_ID
    ,0 															AS VISIT_DETAIL_ID
	,PULL_DRUG_EXPOSURE_ALL_IMM.PULL_CLARITY_CVX_CODE::VARCHAR
        ||':'||PULL_CLARITY_IMMUNZATN_NAME		                AS DRUG_SOURCE_VALUE
	,0                      									AS DRUG_SOURCE_CONCEPT_ID
	,PULL_DRUG_EXPOSURE_ALL_IMM.PULL_ROUTE_C::VARCHAR
	    ||':'|| PULL_ZC_ROUTE_NAME					 	        AS ROUTE_SOURCE_VALUE
	,PULL_DRUG_EXPOSURE_ALL_IMM.DOSE_UNIT_SOURCE_VALUE		    AS DOSE_UNIT_SOURCE_VALUE
	-------- Non-OMOP Fields ------------
	, 'STAGE_DRUG_EXPOSURE_ALL_IMM' 							AS ETL_MODULE
	, VISIT_OCCURRENCE.phi_PAT_ID                      			AS STAGE_PAT_ID
    , VISIT_OCCURRENCE.phi_MRN_CPI                           	AS STAGE_MRN_CPI
	, VISIT_OCCURRENCE.phi_CSN_ID								AS STAGE_CSN_ID
	, PULL_DRUG_EXPOSURE_ALL_IMM.PULL_IMMUNZATN_ID			    AS STAGE_MEDICATION_ID

FROM {{ref('PULL_DRUG_EXPOSURE_ALL_IMM')}} AS PULL_DRUG_EXPOSURE_ALL_IMM

    INNER JOIN {{ref('VISIT_OCCURRENCE_RAW')}} AS VISIT_OCCURRENCE
    	ON PULL_DRUG_EXPOSURE_ALL_IMM.PULL_CSN_ID = VISIT_OCCURRENCE.phi_CSN_ID

    LEFT JOIN {{ref('PROVIDER_RAW')}} AS PROVIDER
    	ON PULL_DRUG_EXPOSURE_ALL_IMM.PROVIDER_SOURCE_VALUE = PROVIDER.PROVIDER_SOURCE_VALUE

    INNER JOIN {{ref('T_IMM_SOURCE')}} AS T_IMM_SOURCE
    	ON PULL_DRUG_EXPOSURE_ALL_IMM.PULL_CLARITY_CVX_CODE = T_IMM_SOURCE.CONCEPT_CODE

    INNER JOIN {{ref('T_IMM_CONCEPT')}} AS T_IMM_CONCEPT
    	ON T_IMM_SOURCE.CONCEPT_ID = T_IMM_CONCEPT.DRUG_CONCEPT_SOURCE_CONCEPT_ID

	LEFT JOIN {{ ref('SOURCE_TO_CONCEPT_MAP_IMM_ROUTE')}} AS SOURCE_TO_CONCEPT_MAP_IMM_ROUTE
		ON PULL_DRUG_EXPOSURE_ALL_IMM.PULL_ROUTE_C::VARCHAR =  SOURCE_TO_CONCEPT_MAP_IMM_ROUTE.SOURCE_CODE::VARCHAR

WHERE PULL_DRUG_EXPOSURE_ALL_IMM.DRUG_EXPOSURE_START_DATE IS NOT NULL

