 ------ QA_DRUG_EXPOSURE_ZEROCONCEPT_DETAIL
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH ZEROCONCEPT_DETAIL
AS (
	SELECT 'DRUG_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE
		, DRUG_EXPOSURE_ID AS CDT_ID
	FROM {{ref('DRUG_EXPOSURE_RAW')}} AS DRUG_EXPOSURE
	WHERE (DRUG_CONCEPT_ID = 0)

	UNION ALL

	SELECT 'DRUG_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE
		, DRUG_EXPOSURE_ID AS CDT_ID
	FROM {{ref('DRUG_EXPOSURE_RAW')}} AS DRUG_EXPOSURE
	WHERE (DRUG_TYPE_CONCEPT_ID = 0)

	-- UNION ALL

	-- SELECT 'ROUTE_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE
	-- 	, DRUG_EXPOSURE_ID AS CDT_ID
	-- FROM {{ref('DRUG_EXPOSURE_RAW')}} AS DRUG_EXPOSURE
	-- WHERE (ROUTE_CONCEPT_ID = 0)

	-- UNION ALL

	-- SELECT 'DRUG_SOURCE_CONCEPT_ID' AS METRIC_FIELD, 'ZERO CONCEPT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE
	-- 	, DRUG_EXPOSURE_ID AS CDT_ID
	-- FROM {{ref('DRUG_EXPOSURE_RAW')}} AS DRUG_EXPOSURE
	-- WHERE (DRUG_SOURCE_CONCEPT_ID = 0)
	)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'DRUG_EXPOSURE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM ZEROCONCEPT_DETAIL
  WHERE ERROR_TYPE <>'EXPECTED'

