--QA_DRUG_EXPOSURE_INGREDIENTCLASS_COUNT
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH INGREDIENTCLASS_COUNT AS (
SELECT 'DRUG_CONCEPT_ID' AS METRIC_FIELD, 'INGREDIENT CLASS' AS QA_METRIC, 'WARNING' AS ERROR_TYPE, COUNT(*) AS CNT

FROM {{ref('DRUG_EXPOSURE_RAW')}} AS DRUG_EXPOSURE
LEFT JOIN {{ source('OMOP','CONCEPT')}} AS CONCEPT
	ON DRUG_EXPOSURE.DRUG_CONCEPT_ID = CONCEPT.CONCEPT_ID
WHERE (UPPER(CONCEPT.CONCEPT_CLASS_ID) = 'INGREDIENT')
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'DRUG_EXPOSURE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) IS NOT NULL AND SUM(CNT) <> 0 THEN ERROR_TYPE ELSE NULL END AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('DRUG_EXPOSURE_RAW')}} ) AS TOTAL_RECORDS
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('DRUG_EXPOSURE')}} ) AS TOTAL_RECORDS_CLEAN
FROM INGREDIENTCLASS_COUNT
GROUP BY   METRIC_FIELD, QA_METRIC, ERROR_TYPE
