------ QA_DRUG_EXPOSURE_NULLCONCEPT_COUNT
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH NULLCONCEPT_COUNT
AS (
	SELECT 'DRUG_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM {{ref('DRUG_EXPOSURE_RAW')}} AS DRUG_EXPOSURE
	WHERE (DRUG_CONCEPT_ID IS NULL)

	UNION ALL

	SELECT 'DRUG_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM {{ref('DRUG_EXPOSURE_RAW')}} AS DRUG_EXPOSURE
	WHERE (DRUG_TYPE_CONCEPT_ID IS NULL)

	-- UNION ALL

	-- SELECT 'ROUTE_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	-- FROM {{ref('DRUG_EXPOSURE_RAW')}} AS DRUG_EXPOSURE
	-- WHERE (ROUTE_CONCEPT_ID IS NULL)

	-- UNION ALL

	-- SELECT 'DRUG_SOURCE_CONCEPT_ID' AS METRIC_FIELD, 'NULL CONCEPT' AS QA_METRIC, 'FATAL' AS ERROR_TYPE, COUNT(*) AS CNT
	-- FROM {{ref('DRUG_EXPOSURE_RAW')}} AS DRUG_EXPOSURE
	-- WHERE (DRUG_SOURCE_CONCEPT_ID IS NULL)
	)


SELECT CAST( GETDATE() AS DATE) AS RUN_DATE
	,'DRUG_EXPOSURE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) <> 0 THEN ERROR_TYPE ELSE NULL END AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('DRUG_EXPOSURE_RAW')}}) AS TOTAL_RECORDS
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('DRUG_EXPOSURE')}}) AS TOTAL_RECORDS_CLEAN
FROM NULLCONCEPT_COUNT
GROUP BY METRIC_FIELD, QA_METRIC, ERROR_TYPE

