--DRUG_EXPOSURE_END_BEFORE_START_COUNT
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH END_BEFORE_START_COUNT AS (
SELECT 'DRUG_EXPOSURE_END_DATE' AS METRIC_FIELD, 'END_BEFORE_START' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE, COUNT(*) AS CNT
FROM {{ref('DRUG_EXPOSURE_RAW')}}
WHERE DRUG_EXPOSURE_END_DATE < DRUG_EXPOSURE_START_DATE
	OR
	DRUG_EXPOSURE_END_DATETIME < DRUG_EXPOSURE_START_DATETIME
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	, 'DRUG_EXPOSURE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) IS NOT NULL AND SUM(CNT) <> 0 THEN ERROR_TYPE ELSE NULL END AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('DRUG_EXPOSURE_RAW')}} ) AS TOTAL_RECORDS
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('DRUG_EXPOSURE')}} ) AS TOTAL_RECORDS_CLEAN
FROM END_BEFORE_START_COUNT
GROUP BY METRIC_FIELD, QA_METRIC, ERROR_TYPE

