--QA_DRUG_EXPOSURE_END_BEFORE_START_DETAIL
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH END_BEFORE_START_DETAIL AS (
SELECT 'DRUG_EXPOSURE_END_DATE' AS METRIC_FIELD, 'END_BEFORE_START' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE, DRUG_EXPOSURE_ID AS CDT_ID
FROM {{ref('DRUG_EXPOSURE_RAW')}} AS DRUG_EXPOSURE
WHERE DRUG_EXPOSURE_END_DATE < DRUG_EXPOSURE_START_DATE
	OR
	DRUG_EXPOSURE_END_DATETIME < DRUG_EXPOSURE_START_DATETIME
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'DRUG_EXPOSURE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM END_BEFORE_START_DETAIL

