--QA_DRUG_EXPOSURE_POS_DUP_DRUG_SOURCE_VALUE_DETAIL
---------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH TMP_DUPES AS (
SELECT PERSON_ID
	,DRUG_CONCEPT_ID
	-- ,DRUG_EXPOSURE_START_DATE
	,DRUG_EXPOSURE_START_DATETIME
	-- ,DRUG_EXPOSURE_END_DATE
	,DRUG_EXPOSURE_END_DATETIME
	,VERBATIM_END_DATE
	-- ,DRUG_TYPE_CONCEPT_ID
	,STOP_REASON
	,REFILLS
	,QUANTITY
	,DAYS_SUPPLY
	,SIG
	,ROUTE_CONCEPT_ID
	,LOT_NUMBER
	,PROVIDER_ID
	,VISIT_OCCURRENCE_ID
	-- ,DRUG_SOURCE_VALUE
	-- ,DRUG_SOURCE_CONCEPT_ID
	,ROUTE_SOURCE_VALUE
	-- ,DOSE_UNIT_SOURCE_VALUE
	,COUNT(*) AS CNT
FROM {{ref('DRUG_EXPOSURE_RAW')}} AS T1
WHERE T1.DRUG_CONCEPT_ID != 0
	AND T1.DRUG_CONCEPT_ID IS NOT NULL
	AND T1.PERSON_ID != 0
	AND T1.PERSON_ID IS NOT NULL
GROUP BY PERSON_ID
	,DRUG_CONCEPT_ID
	-- ,DRUG_EXPOSURE_START_DATE
	,DRUG_EXPOSURE_START_DATETIME
	-- ,DRUG_EXPOSURE_END_DATE
	,DRUG_EXPOSURE_END_DATETIME
	,VERBATIM_END_DATE
	-- ,DRUG_TYPE_CONCEPT_ID
	,STOP_REASON
	,REFILLS
	,QUANTITY
	,DAYS_SUPPLY
	,SIG
	,ROUTE_CONCEPT_ID
	,LOT_NUMBER
	,PROVIDER_ID
	,VISIT_OCCURRENCE_ID
	-- ,DRUG_SOURCE_VALUE
	-- ,DRUG_SOURCE_CONCEPT_ID
	,ROUTE_SOURCE_VALUE
	-- ,DOSE_UNIT_SOURCE_VALUE
HAVING COUNT(*) > 1
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'DRUG_EXPOSURE' AS STANDARD_DATA_TABLE
	, 'POSSIBLE_DUPLICATE' AS QA_METRIC
	, 'DRUG_SOURCE_VALUE'  AS METRIC_FIELD
	, 'FOLLOW_UP' AS ERROR_TYPE
	, DE.DRUG_EXPOSURE_ID

FROM TMP_DUPES AS D
INNER JOIN {{ref('DRUG_EXPOSURE_RAW')}} AS DE ON D.PERSON_ID = DE.PERSON_ID
	AND D.DRUG_CONCEPT_ID =DE.DRUG_CONCEPT_ID
	-- AND D.DRUG_EXPOSURE_START_DATE = DE.DRUG_EXPOSURE_START_DATE
	AND D.DRUG_EXPOSURE_START_DATETIME = DE.DRUG_EXPOSURE_START_DATETIME
	-- AND D.DRUG_EXPOSURE_END_DATE = DE.DRUG_EXPOSURE_END_DATE
	AND COALESCE(D.DRUG_EXPOSURE_END_DATETIME,'1900-01-01') = COALESCE(DE.DRUG_EXPOSURE_END_DATETIME,'1900-01-01')
	AND COALESCE(D.VERBATIM_END_DATE,'1900-01-01') = COALESCE(DE.VERBATIM_END_DATE,'1900-01-01')
	-- AND COALESCE(D.DRUG_TYPE_CONCEPT_ID, 0) = COALESCE(DE.DRUG_TYPE_CONCEPT_ID, 0)
	AND COALESCE(D.STOP_REASON, '0') = COALESCE(DE.STOP_REASON, '0')
	AND COALESCE(D.REFILLS, 0) = COALESCE(DE.REFILLS, 0)
	AND COALESCE(D.QUANTITY, 0) = COALESCE(DE.QUANTITY, 0)
	AND COALESCE(D.DAYS_SUPPLY, 0) = COALESCE(DE.DAYS_SUPPLY, 0)
	AND COALESCE(D.SIG, '0') = COALESCE(DE.SIG, '0')
	-- AND COALESCE(D.ROUTE_CONCEPT_ID, 0) = COALESCE(DE.ROUTE_CONCEPT_ID, 0)
	AND COALESCE(D.LOT_NUMBER, '0') = COALESCE(DE.LOT_NUMBER, '0')
	AND COALESCE(D.PROVIDER_ID, 0) = COALESCE(DE.PROVIDER_ID, 0)
	AND COALESCE(D.VISIT_OCCURRENCE_ID, 0) = COALESCE(DE.VISIT_OCCURRENCE_ID, 0)
	-- AND COALESCE(D.DRUG_SOURCE_VALUE, '0') = COALESCE(DE.DRUG_SOURCE_VALUE, '0')
	-- AND COALESCE(D.DRUG_SOURCE_CONCEPT_ID, 0) = COALESCE(DE.DRUG_SOURCE_CONCEPT_ID, 0)
	AND COALESCE(D.ROUTE_SOURCE_VALUE, '0') = COALESCE(DE.ROUTE_SOURCE_VALUE, '0')
	-- AND COALESCE(D.DOSE_UNIT_SOURCE_VALUE, '0') = COALESCE(DE.DOSE_UNIT_SOURCE_VALUE, '0')

