--QA_DRUG_EXPOSURE_NOVISIT_DETAIL
---------------------------------------------------------------------
WITH NOVISIT_DETAIL AS (
SELECT 'VISIT_OCCURRENCE_ID' AS METRIC_FIELD, 'NO VISIT' AS QA_METRIC, 'WARNING' AS ERROR_TYPE, DRUG_EXPOSURE_ID AS CDT_ID

FROM {{ref('DRUG_EXPOSURE_RAW')}} AS DRUG_EXPOSURE
LEFT JOIN {{ref('VISIT_OCCURRENCE_RAW')}} AS VISIT_OCCURRENCE
	ON DRUG_EXPOSURE.VISIT_OCCURRENCE_ID = VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID
WHERE (VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID IS NULL)
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'DRUG_EXPOSURE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NOVISIT_DETAIL
  WHERE ERROR_TYPE <>'EXPECTED'

