----DRUG_EXPOSURE_NONSTANDARD_COUNT
-------------------------------------------------------------------

{# --{{ config(materialized = 'view') }} #}

WITH NONSTANDARD_COUNT
AS (
	SELECT 'DRUG_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM {{ref('DRUG_EXPOSURE_RAW')}}  AS DE
	LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C
		ON DE.DRUG_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'DRUG' AND upper(C.VOCABULARY_ID) IN ('RXNORM', 'CVX')
	WHERE DRUG_CONCEPT_ID <> 0 AND DRUG_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)

	UNION ALL

	SELECT 'DRUG_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM {{ref('DRUG_EXPOSURE_RAW')}}  AS DE
	LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C
		ON DE.DRUG_TYPE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'TYPE CONCEPT' AND upper(C.VOCABULARY_ID) =  'TYPE CONCEPT'
	WHERE DRUG_TYPE_CONCEPT_ID <> 0 AND DRUG_TYPE_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)

	UNION ALL

	SELECT 'ROUTE_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE, COUNT(*) AS CNT
	FROM {{ref('DRUG_EXPOSURE_RAW')}} AS DE
	LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C
		ON DE.ROUTE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'ROUTE' AND upper(C.VOCABULARY_ID) =  'SNOMED'
	WHERE ROUTE_CONCEPT_ID <> 0 AND ROUTE_CONCEPT_ID IS NOT NULL AND (STANDARD_CONCEPT <> 'S' OR STANDARD_CONCEPT IS NULL)

	UNION ALL

	SELECT 'DRUG_SOURCE_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE, --C.CONCEPT_ID, STANDARD_CONCEPT,
		COUNT(*) AS CNT
	FROM {{ref('DRUG_EXPOSURE_RAW')}}  AS DE
	LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C
		ON DE.DRUG_SOURCE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.DOMAIN_ID) = 'DRUG' AND upper(C.VOCABULARY_ID)  IN ('RXNORM', 'CVX')
	WHERE DRUG_SOURCE_CONCEPT_ID <> 0 AND C.CONCEPT_ID IS NULL
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'DRUG_EXPOSURE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, COALESCE (SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) <> 0 THEN ERROR_TYPE ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('DRUG_EXPOSURE_RAW')}} ) AS TOTAL_RECORDS
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('DRUG_EXPOSURE')}} ) AS TOTAL_RECORDS_CLEAN
FROM NONSTANDARD_COUNT
GROUP BY   METRIC_FIELD, QA_METRIC, ERROR_TYPE

