/*
Description: This query transforms ambulatory LOINC measurements data into OMOP CDM format
Source Tables: 
    - PULL_MEASUREMENT_AMB_LOINC
    - SOURCE_TO_CONCEPT_MAP
    - VISIT_OCCURRENCE_RAW
    - T_LOINC_SOURCE
    - T_LOINC_CONCEPT
    - PROVIDER_RAW
*/

-- CTE for unit mappings
WITH __dbt__cte__SOURCE_TO_CONCEPT_MAP_UNITS AS (
    SELECT *
    FROM CARE_RES_OMOP_GEN_WKSP.OMOP.SOURCE_TO_CONCEPT_MAP
    WHERE SOURCE_VOCABULARY_ID = 'SH_UNIT'
),

-- CTE for value mappings
__dbt__cte__SOURCE_TO_CONCEPT_MAP_VALUE AS (
    SELECT *
    FROM CARE_RES_OMOP_GEN_WKSP.OMOP.SOURCE_TO_CONCEPT_MAP
    WHERE SOURCE_VOCABULARY_ID = 'SH_VALUE_AS_CONCEPT'
)

-- Main query for MEASUREMENT table
SELECT DISTINCT
    -- Core OMOP fields
    PULL_MEASUREMENT_AMB_LOINC.PERSON_ID                               AS PERSON_ID,
    T_CONCEPT.CONCEPT_ID                                               AS MEASUREMENT_CONCEPT_ID,
    PULL_MEASUREMENT_AMB_LOINC.MEASUREMENT_DATE                        AS MEASUREMENT_DATE,
    PULL_MEASUREMENT_AMB_LOINC.MEASUREMENT_DATETIME                    AS MEASUREMENT_DATETIME,
    32817                                                              AS MEASUREMENT_TYPE_CONCEPT_ID,
    PULL_MEASUREMENT_AMB_LOINC.OPERATOR_CONCEPT_ID                     AS OPERATOR_CONCEPT_ID,
    PULL_MEASUREMENT_AMB_LOINC.VALUE_AS_NUMBER                         AS VALUE_AS_NUMBER,
    COALESCE(SOURCE_TO_CONCEPT_MAP_VALUE.TARGET_CONCEPT_ID, 0)         AS VALUE_AS_CONCEPT_ID,
    COALESCE(SOURCE_TO_CONCEPT_MAP_UNIT.TARGET_CONCEPT_ID, 0)          AS UNIT_CONCEPT_ID,
    PULL_MEASUREMENT_AMB_LOINC.RANGE_LOW                               AS RANGE_LOW,
    PULL_MEASUREMENT_AMB_LOINC.RANGE_HIGH                              AS RANGE_HIGH,
    PROVIDER.PROVIDER_ID                                               AS PROVIDER_ID,
    VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID                               AS VISIT_OCCURRENCE_ID,
    NULL                                                               AS VISIT_DETAIL_ID,
    PULL_MEASUREMENT_AMB_LOINC.MEASUREMENT_SOURCE_VALUE                AS MEASUREMENT_SOURCE_VALUE,
    T_SOURCE.CONCEPT_ID                                                AS MEASUREMENT_SOURCE_CONCEPT_ID,
    PULL_MEASUREMENT_AMB_LOINC.UNIT_SOURCE_VALUE                       AS UNIT_SOURCE_VALUE,
    PULL_MEASUREMENT_AMB_LOINC.VALUE_SOURCE_VALUE                      AS VALUE_SOURCE_VALUE,
    NULL                                                               AS UNIT_SOURCE_CONCEPT_ID,
    NULL                                                               AS MEASUREMENT_EVENT_ID,
    NULL                                                               AS MEAS_EVENT_FIELD_CONCEPT_ID,

    -- Additional staging fields
    'MEASUREMENT--CLARITYAMB--LOINC'                                   AS ETL_MODULE,
    VISIT_OCCURRENCE.phi_PAT_ID                                        AS STAGE_PAT_ID,
    VISIT_OCCURRENCE.phi_MRN_CPI                                       AS STAGE_MRN_CPI,
    VISIT_OCCURRENCE.phi_CSN_ID                                        AS STAGE_CSN_ID,
    PULL_LNC_CODE                                                      AS STAGE_LNC_CODE,
    PULL_RECORD_ID                                                     AS STAGE_RECORD_ID

FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.PULL_MEASUREMENT_AMB_LOINC AS PULL_MEASUREMENT_AMB_LOINC

-- Join to get visit information
INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP.VISIT_OCCURRENCE_RAW AS VISIT_OCCURRENCE
    ON PULL_MEASUREMENT_AMB_LOINC.PULL_CSN_ID = VISIT_OCCURRENCE.phi_CSN_ID

-- Join to get LOINC source concepts
INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP_STAGE.T_LOINC_SOURCE AS T_SOURCE
    ON PULL_MEASUREMENT_AMB_LOINC.PULL_LNC_CODE = T_SOURCE.CONCEPT_CODE

-- Join to get standard LOINC concepts
INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP_STAGE.T_LOINC_CONCEPT AS T_CONCEPT
    ON T_CONCEPT.SOURCE_CONCEPT_ID = T_SOURCE.CONCEPT_ID

-- Join to get provider information
LEFT JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP.PROVIDER_RAW AS PROVIDER
    ON PULL_MEASUREMENT_AMB_LOINC.PROVIDER_SOURCE_VALUE = PROVIDER.PROVIDER_SOURCE_VALUE

-- Join to get unit mappings
LEFT JOIN __dbt__cte__SOURCE_TO_CONCEPT_MAP_UNITS AS SOURCE_TO_CONCEPT_MAP_UNIT
    ON PULL_MEASUREMENT_AMB_LOINC.UNIT_SOURCE_VALUE = SOURCE_TO_CONCEPT_MAP_UNIT.SOURCE_CODE

-- Join to get value mappings
LEFT JOIN __dbt__cte__SOURCE_TO_CONCEPT_MAP_VALUE AS SOURCE_TO_CONCEPT_MAP_VALUE
    ON PULL_MEASUREMENT_AMB_LOINC.VALUE_SOURCE_VALUE = SOURCE_TO_CONCEPT_MAP_VALUE.SOURCE_CODE;