/*
Purpose: Transform and map ambulatory flowsheet vital measurements to OMOP CDM format
Source: CLARITY ambulatory flowsheet data
Target: OMOP Measurement table
*/

-- CTE for vital signs flowsheet measurements mapping
WITH __dbt__cte__SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_VITALS AS (
    SELECT *
    FROM CARE_RES_OMOP_GEN_WKSP.OMOP.SOURCE_TO_CONCEPT_MAP
    WHERE SOURCE_VOCABULARY_ID = 'SH_FLWSHT_VITALS'
),

-- CTE for measurement units mapping
__dbt__cte__SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_UNITS AS (
    SELECT *
    FROM CARE_RES_OMOP_GEN_WKSP.OMOP.SOURCE_TO_CONCEPT_MAP
    WHERE SOURCE_VOCABULARY_ID = 'SH_FLOWSHT_MEAS_UNIT'
),

-- CTE for inferred unit mapping
__dbt__cte__SOURCE_TO_CONCEPT_MAP_XRF_INFERRED_UNIT AS (
    SELECT *
    FROM CARE_RES_OMOP_GEN_WKSP.OMOP.SOURCE_TO_CONCEPT_MAP
    WHERE SOURCE_VOCABULARY_ID = 'SH_XRF_INFERRED_UNIT'
),

-- CTE for ambulatory visit mapping
__dbt__cte__SOURCE_TO_CONCEPT_MAP_AMB_VISIT AS (
    SELECT *
    FROM CARE_RES_OMOP_GEN_WKSP.OMOP.SOURCE_TO_CONCEPT_MAP
    WHERE SOURCE_VOCABULARY_ID = 'SH_AMB_F2F'
)

-- Main query to transform measurements
SELECT DISTINCT
    -- Standard OMOP fields
    PULL_MEASUREMENT_AMB_FLOWSHEET.PERSON_ID AS PERSON_ID,
    COALESCE(SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS.TARGET_CONCEPT_ID, 0) AS MEASUREMENT_CONCEPT_ID,
    PULL_MEASUREMENT_AMB_FLOWSHEET.MEASUREMENT_DATE AS MEASUREMENT_DATE,
    PULL_MEASUREMENT_AMB_FLOWSHEET.MEASUREMENT_DATETIME AS MEASUREMENT_DATETIME,
    32817 AS MEASUREMENT_TYPE_CONCEPT_ID, -- EHR
    PULL_MEASUREMENT_AMB_FLOWSHEET.OPERATOR_CONCEPT_ID,
    PULL_MEASUREMENT_AMB_FLOWSHEET.VALUE_AS_NUMBER AS VALUE_AS_NUMBER,
    NULL AS VALUE_AS_CONCEPT_ID,
    COALESCE(SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_UNITS.TARGET_CONCEPT_ID,
             SOURCE_TO_CONCEPT_MAP_XRF_INFERRED_UNIT.target_concept_id, 0) AS UNIT_CONCEPT_ID,
    PULL_MEASUREMENT_AMB_FLOWSHEET.RANGE_LOW AS RANGE_LOW,
    PULL_MEASUREMENT_AMB_FLOWSHEET.RANGE_HIGH AS RANGE_HIGH,
    PROVIDER.PROVIDER_ID AS PROVIDER_ID,
    VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID AS VISIT_OCCURRENCE_ID,
    NULL AS VISIT_DETAIL_ID,
    PULL_FLO_MEAS_ID::VARCHAR ||':'|| PULL_FLO_MEAS_NAME AS MEASUREMENT_SOURCE_VALUE,
    NULL AS MEASUREMENT_SOURCE_CONCEPT_ID,
    COALESCE(PULL_MEASUREMENT_AMB_FLOWSHEET.UNIT_SOURCE_VALUE, 
             CONCEPT_NAME ||'(inferred)') AS UNIT_SOURCE_VALUE,
    PULL_MEASUREMENT_AMB_FLOWSHEET.VALUE_SOURCE_VALUE,
    NULL AS UNIT_SOURCE_CONCEPT_ID,
    NULL AS MEASUREMENT_EVENT_ID,
    NULL AS MEAS_EVENT_FIELD_CONCEPT_ID,

    -- Additional tracking fields
    'MEASUREMENT--CLARITYAMB--FLOWSHEET_VITALS' AS ETL_MODULE,
    VISIT_OCCURRENCE.phi_PAT_ID AS STAGE_PAT_ID,
    VISIT_OCCURRENCE.phi_MRN_CPI AS STAGE_MRN_CPI,
    VISIT_OCCURRENCE.phi_CSN_ID AS STAGE_CSN_ID,
    PULL_FLO_MEAS_ID AS STAGE_FLO_MEAS_ID,
    PULL_FLO_MEAS_NAME AS STAGE_FLO_MEAS_NAME

FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.PULL_MEASUREMENT_AMB_FLOWSHEET AS PULL_MEASUREMENT_AMB_FLOWSHEET

-- Join to get measurement concepts
INNER JOIN __dbt__cte__SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_VITALS AS SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS
    ON PULL_MEASUREMENT_AMB_FLOWSHEET.PULL_FLO_MEAS_ID = SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS.SOURCE_CODE

-- Join to get unit concepts for measures with explicit units
LEFT JOIN __dbt__cte__SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_UNITS AS SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_UNITS
    ON PULL_MEASUREMENT_AMB_FLOWSHEET.UNIT_SOURCE_VALUE = SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS_UNITS.SOURCE_CODE

-- Join to get inferred unit concepts where explicit units are missing
LEFT JOIN __dbt__cte__SOURCE_TO_CONCEPT_MAP_XRF_INFERRED_UNIT AS SOURCE_TO_CONCEPT_MAP_XRF_INFERRED_UNIT
    ON UPPER(SOURCE_TO_CONCEPT_MAP_FLOWSHEET_MEAS.TARGET_CONCEPT_ID) = UPPER(SOURCE_TO_CONCEPT_MAP_XRF_INFERRED_UNIT.SOURCE_CODE)

-- Join to get unit concept names
LEFT JOIN CARE_RES_OMOP_GEN_WKSP.OMOP.CONCEPT AS CONCEPT
    ON SOURCE_TO_CONCEPT_MAP_XRF_INFERRED_UNIT.target_concept_id = CONCEPT.CONCEPT_ID

-- Join to get visit type concepts
INNER JOIN __dbt__cte__SOURCE_TO_CONCEPT_MAP_AMB_VISIT AS SOURCE_TO_CONCEPT_MAP_AMB_VISIT
    ON PULL_MEASUREMENT_AMB_FLOWSHEET.PULL_ENC_TYPE_C = SOURCE_TO_CONCEPT_MAP_AMB_VISIT.SOURCE_CODE

-- Join to get visit occurrence information
INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP.VISIT_OCCURRENCE_RAW AS VISIT_OCCURRENCE
    ON PULL_MEASUREMENT_AMB_FLOWSHEET.PULL_CSN_ID = VISIT_OCCURRENCE.phi_CSN_ID

-- Join to get provider information
LEFT JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP.PROVIDER_RAW AS PROVIDER
    ON PULL_MEASUREMENT_AMB_FLOWSHEET.PROVIDER_SOURCE_VALUE = PROVIDER.PROVIDER_SOURCE_VALUE;