 --PROVIDER_RAW
{{ config(materialized = 'table', schema = 'OMOP') }}

SELECT DISTINCT
      PROVIDER_ID::NUMBER(28,0)                 AS PROVIDER_ID
    , PROVIDER_NAME::VARCHAR                    AS PROVIDER_NAME
    , NPI::VARCHAR                              AS NPI
    , DEA::VARCHAR                              AS DEA
    , SPECIALTY_CONCEPT_ID::NUMBER(28,0)        AS SPECIALTY_CONCEPT_ID
    , CARE_SITE_ID::NUMBER(28,0)                AS CARE_SITE_ID
    , YEAR_OF_BIRTH::NUMBER(28,0)               AS YEAR_OF_BIRTH
    , GENDER_CONCEPT_ID::NUMBER(28,0)           AS GENDER_CONCEPT_ID
    , PROVIDER_SOURCE_VALUE::VARCHAR            AS PROVIDER_SOURCE_VALUE
    , SPECIALTY_SOURCE_VALUE::VARCHAR           AS SPECIALTY_SOURCE_VALUE
    , SPECIALTY_SOURCE_CONCEPT_ID::NUMBER(28,0) AS SPECIALTY_SOURCE_CONCEPT_ID
    , GENDER_SOURCE_VALUE::VARCHAR              AS GENDER_SOURCE_VALUE
    , GENDER_SOURCE_CONCEPT_ID::NUMBER(28,0)    AS GENDER_SOURCE_CONCEPT_ID

FROM
 {{ref('STAGE_PROVIDER_ALL')}} AS T
