/*********************************************************
Script Name: QA_LOG_DBT
Author: Roger J Carlson - Corewell Health
Date: June 2025
Description: Comprehensive QA checks across OMOP tables combining multiple quality metrics
**********************************************************/

-- Main Query combining all QA checks
--CARE_SITE
SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_CARE_SITE_DUPLICATES_COUNT AS QA_CARE_SITE_DUPLICATES_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_CARE_SITE_NON_STANDARD_COUNT AS QA_CARE_SITE_NON_STANDARD_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_CARE_SITE_ZERO_CONCEPT_COUNT AS QA_CARE_SITE_ZERO_CONCEPT_COUNT

--CONDITION
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_CONDITION_30AFTERDEATH_COUNT AS QA_CONDITION_30AFTERDEATH_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_CONDITION_OCCURRENCE_DATEVDATETIME_COUNT AS QA_CONDITION_OCCURRENCE_DATEVDATETIME_COUNT
UNION ALL SELECT  * FROM
 CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_CONDITION_OCCURRENCE_DUPLICATES_COUNT AS QA_CONDITION_OCCURRENCE_DUPLICATES_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_CONDITION_OCCURRENCE_END_BEFORE_START_COUNT AS QA_CONDITION_OCCURRENCE_END_BEFORE_START_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_CONDITION_OCCURRENCE_NONSTANDARD_COUNT AS QA_CONDITION_OCCURRENCE_NONSTANDARD_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_CONDITION_OCCURRENCE_NOVISIT_COUNT AS QA_CONDITION_OCCURRENCE_NOVISIT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_CONDITION_OCCURRENCE_NULLCONCEPT_COUNT AS QA_CONDITION_OCCURRENCE_NULLCONCEPT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_CONDITION_OCCURRENCE_NULLFK_COUNT AS QA_CONDITION_OCCURRENCE_NULLFK_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_CONDITION_OCCURRENCE_VISITDATEDISPARITY_COUNT AS QA_CONDITION_OCCURRENCE_VISITDATEDISPARITY_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_CONDITION_OCCURRENCE_ZEROCONCEPT_COUNT AS QA_CONDITION_OCCURRENCE_ZEROCONCEPT_COUNT

--DEATH
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DEATH_DUPLICATES_COUNT AS QA_DEATH_DUPLICATES_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DEATH_NULL_CONCEPT_COUNT AS QA_DEATH_NULL_CONCEPT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DEATH_ZERO_CONCEPT_COUNT AS QA_DEATH_ZERO_CONCEPT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DEATH_NULL_DEATHDATE_COUNT AS QA_DEATH_NULL_DEATHDATE_COUNT

--DEVICE_EXPOSURE
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DEVICE_CONCEPT_DUPLICATES_COUNT AS QA_DEVICE_CONCEPT_DUPLICATES_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DEVICE_EXPOSURE_DATEVDATETIME_COUNT AS QA_DEVICE_EXPOSURE_DATEVDATETIME_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DEVICE_EXPOSURE_END_BEFORE_START_COUNT AS QA_DEVICE_EXPOSURE_END_BEFORE_START_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DEVICE_EXPOSURE_NONSTANDARD_COUNT AS QA_DEVICE_EXPOSURE_NONSTANDARD_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DEVICE_EXPOSURE_NOVISIT_COUNT AS QA_DEVICE_EXPOSURE_NOVISIT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DEVICE_EXPOSURE_NULLFK_COUNT AS QA_DEVICE_EXPOSURE_NULLFK_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DEVICE_EXPOSURE_NULL_CONCEPT_COUNT AS QA_DEVICE_EXPOSURE_NULL_CONCEPT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DEVICE_EXPOSURE_ZERO_CONCEPT_COUNT AS QA_DEVICE_EXPOSURE_ZERO_CONCEPT_COUNT

--DRUG_EXPOSURE
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DRUG_30AFTERDEATH_COUNT AS QA_DRUG_30AFTERDEATH_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DRUG_EXPOSURE_DATEVDATETIME_COUNT AS QA_DRUG_EXPOSURE_DATEVDATETIME_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DRUG_EXPOSURE_DUPLICATES_COUNT AS QA_DRUG_EXPOSURE_DUPLICATES_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DRUG_EXPOSURE_END_BEFORE_START_COUNT AS QA_DRUG_EXPOSURE_END_BEFORE_START_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DRUG_EXPOSURE_NONSTANDARD_COUNT AS QA_DRUG_EXPOSURE_NONSTANDARD_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DRUG_EXPOSURE_NOVISIT_COUNT AS QA_DRUG_EXPOSURE_NOVISIT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DRUG_EXPOSURE_NULLCONCEPT_COUNT AS QA_DRUG_EXPOSURE_NULLCONCEPT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DRUG_EXPOSURE_NULLFK_COUNT AS QA_DRUG_EXPOSURE_NULLFK_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DRUG_EXPOSURE_VISITDATEDISPARITY_COUNT AS QA_DRUG_EXPOSURE_VISITDATEDISPARITY_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DRUG_EXPOSURE_ZEROCONCEPT_COUNT AS QA_DRUG_EXPOSURE_ZEROCONCEPT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DRUG_EXPOSURE_INGREDIENTCLASS_COUNT AS QA_DRUG_EXPOSURE_INGREDIENTCLASS_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DRUG_EXPOSURE_POS_DUP_DRUG_SOURCE_VALUE_COUNT AS QA_DRUG_EXPOSURE_POS_DUP_DRUG_SOURCE_VALUE_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DRUG_EXPOSURE_POS_DUP_PROVIDER_ID_COUNT AS QA_DRUG_EXPOSURE_POS_DUP_PROVIDER_ID_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DRUG_EXPOSURE_POS_DUP_REFILLS_COUNT AS QA_DRUG_EXPOSURE_POS_DUP_REFILLS_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DRUG_EXPOSURE_POS_DUP_STOP_REASON_COUNT AS QA_DRUG_EXPOSURE_POS_DUP_STOP_REASON_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DRUG_EXPOSURE_POS_DUP_VERBATIM_END_DATE_COUNT AS QA_DRUG_EXPOSURE_POS_DUP_VERBATIM_END_DATE_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_DRUG_EXPOSURE_POS_DUP_VISIT_OCCURRENCE_ID_COUNT AS QA_DRUG_EXPOSURE_POS_DUP_VISIT_OCCURRENCE_ID_COUNT

--LOCATION
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_LOCATION_DUPLICATES_COUNT AS QA_LOCATION_DUPLICATES_COUNT

--MEASUREMENT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_MEASUREMENT_30AFTERDEATH_COUNT AS QA_MEASUREMENT_30AFTERDEATH_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_MEASUREMENT_DATEVDATETIME_COUNT AS QA_MEASUREMENT_DATEVDATETIME_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_MEASUREMENT_DUPLICATES_COUNT AS QA_MEASUREMENT_DUPLICATES_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_MEASUREMENT_NONSTANDARD_COUNT AS QA_MEASUREMENT_NONSTANDARD_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_MEASUREMENT_NOVISIT_COUNT AS QA_MEASUREMENT_NOVISIT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_MEASUREMENT_NULLCONCEPT_COUNT AS QA_MEASUREMENT_NULLCONCEPT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_MEASUREMENT_NULLFK_COUNT AS QA_MEASUREMENT_NULLFK_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_MEASUREMENT_VISITDATEDISPARITY_COUNT AS QA_MEASUREMENT_VISITDATEDISPARITY_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_MEASUREMENT_ZEROCONCEPT_COUNT AS QA_MEASUREMENT_ZEROCONCEPT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_MEASUREMENT_POS_DUP_LOW_HIGH_COUNT AS QA_MEASUREMENT_POS_DUP_LOW_HIGH_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_MEASUREMENT_POS_DUP_MEASUREMENT_SOURCE_VALUE_COUNT AS QA_MEASUREMENT_POS_DUP_MEASUREMENT_SOURCE_VALUE_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_MEASUREMENT_POS_DUP_PROVIDER_COUNT AS QA_MEASUREMENT_POS_DUP_PROVIDER_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_MEASUREMENT_POS_DUP_UNIT_CONCEPT_ID_COUNT AS QA_MEASUREMENT_POS_DUP_UNIT_CONCEPT_ID_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_MEASUREMENT_POS_DUP_VALUE_SOURCE_VALUE_COUNT AS QA_MEASUREMENT_POS_DUP_VALUE_SOURCE_VALUE_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_MEASUREMENT_POS_DUP_VISIT_OCCURRENCE_COUNT AS QA_MEASUREMENT_POS_DUP_VISIT_OCCURRENCE_COUNT

--NOTE
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_NOTE_DATEVDATETIME_COUNT AS QA_NOTE_DATEVDATETIME_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_NOTE_DUPLICATES_COUNT AS QA_NOTE_DUPLICATES_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_NOTE_NONSTANDARD_COUNT AS QA_NOTE_NONSTANDARD_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_NOTE_NOVISIT_COUNT AS QA_NOTE_NOVISIT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_NOTE_NULLCONCEPT_COUNT AS QA_NOTE_NULLCONCEPT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_NOTE_NULLFK_COUNT AS QA_NOTE_NULLFK_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_NOTE_ZEROCONCEPT_COUNT AS QA_NOTE_ZEROCONCEPT_COUNT

--OBSERVATION
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_OBSERVATION_30AFTERDEATH_COUNT AS QA_OBSERVATION_30AFTERDEATH_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_OBSERVATION_DATEVDATETIME_COUNT AS QA_OBSERVATION_DATEVDATETIME_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_OBSERVATION_DUPLICATES_COUNT AS QA_OBSERVATION_DUPLICATES_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_OBSERVATION_NONSTANDARD_COUNT AS QA_OBSERVATION_NONSTANDARD_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_OBSERVATION_NOVISIT_COUNT AS QA_OBSERVATION_NOVISIT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_OBSERVATION_NULLCONCEPT_COUNT AS QA_OBSERVATION_NULLCONCEPT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_OBSERVATION_NULLFK_COUNT AS QA_OBSERVATION_NULLFK_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_OBSERVATION_VISITDATEDISPARITY_COUNT AS QA_OBSERVATION_VISITDATEDISPARITY_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_OBSERVATION_ZEROCONCEPT_COUNT AS QA_OBSERVATION_ZEROCONCEPT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_OBSERVATION_POS_DUP_PROVIDER_ID_COUNT AS QA_OBSERVATION_POS_DUP_PROVIDER_ID_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_OBSERVATION_POS_DUP_VISIT_OCCURRENCE_ID_COUNT AS QA_OBSERVATION_POS_DUP_VISIT_OCCURRENCE_ID_COUNT

--PERSON
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PERSON_WO_VISIT_COUNT AS QA_PERSON_WO_VISIT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PERSON_AGE_ERR_COUNT AS QA_PERSON_AGE_ERR_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PERSON_DUPLICATES_COUNT AS QA_PERSON_DUPLICATES_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PERSON_NONSTANDARD_COUNT AS QA_PERSON_NONSTANDARD_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PERSON_NULLCONCEPT_COUNT AS QA_PERSON_NULLCONCEPT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PERSON_ZEROCONCEPT_COUNT AS QA_PERSON_ZEROCONCEPT_COUNT

--PROCEDURE_OCCURRENCE
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PROCEDURE_30AFTERDEATH_COUNT AS QA_PROCEDURE_30AFTERDEATH_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PROCEDURE_OCCURRENCE_DATEVDATETIME_COUNT AS QA_PROCEDURE_OCCURRENCE_DATEVDATETIME_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PROCEDURE_OCCURRENCE_DUPLICATES_COUNT AS QA_PROCEDURE_OCCURRENCE_DUPLICATES_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PROCEDURE_OCCURRENCE_NONSTANDARD_COUNT AS QA_PROCEDURE_OCCURRENCE_NONSTANDARD_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PROCEDURE_OCCURRENCE_NOVISIT_COUNT AS QA_PROCEDURE_OCCURRENCE_NOVISIT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PROCEDURE_OCCURRENCE_NULLCONCEPT_COUNT AS QA_PROCEDURE_OCCURRENCE_NULLCONCEPT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PROCEDURE_OCCURRENCE_NULLFK_COUNT AS QA_PROCEDURE_OCCURRENCE_NULLFK_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PROCEDURE_OCCURRENCE_VISITDATEDISPARITY_COUNT AS QA_PROCEDURE_OCCURRENCE_VISITDATEDISPARITY_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PROCEDURE_OCCURRENCE_ZEROCONCEPT_COUNT AS QA_PROCEDURE_OCCURRENCE_ZEROCONCEPT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PROCEDURE_OCCURRENCE_VISITDATEDISPARITY_COUNT AS QA_PROCEDURE_OCCURRENCE_VISITDATEDISPARITY_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PROCEDURE_OCCURRENCE_ZEROCONCEPT_COUNT AS QA_PROCEDURE_OCCURRENCE_ZEROCONCEPT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PROCEDURE_OCCURRENCE_POS_DUP_PROVIDER_ID_COUNT AS QA_PROCEDURE_OCCURRENCE_POS_DUP_PROVIDER_ID_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PROCEDURE_OCCURRENCE_POS_DUP_VISIT_OCCURRENCE_ID_COUNT AS QA_PROCEDURE_OCCURRENCE_POS_DUP_VISIT_OCCURRENCE_ID_COUNT

--PROVIDER
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PROVIDER_DUPLICATES_COUNT AS QA_PROVIDER_DUPLICATES_COUNT

UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PROVIDER_NONSTANDARD_COUNT AS QA_PROVIDER_NONSTANDARD_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PROVIDER_NULLFK_COUNT AS QA_PROVIDER_NULLFK_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PROVIDER_NULL_CONCEPT_COUNT AS QA_PROVIDER_NULL_CONCEPT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_PROVIDER_ZEROCONCEPT_COUNT AS QA_PROVIDER_ZEROCONCEPT_COUNT

--SPECIMEN
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_SPECIMEN_DATEVDATETIME_COUNT AS QA_SPECIMEN_DATEVDATETIME_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_SPECIMEN_DUPLICATES_COUNT AS QA_SPECIMEN_DUPLICATES_COUNT

UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_SPECIMEN_NONSTANDARD_COUNT AS QA_SPECIMEN_NONSTANDARD_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_SPECIMEN_NULLCONCEPT_COUNT AS QA_SPECIMEN_NULLCONCEPT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_SPECIMEN_ZEROCONCEPT_COUNT AS QA_SPECIMEN_ZEROCONCEPT_COUNT

--VISIT_OCCURRENCE
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_VISIT_30AFTERDEATH_COUNT AS QA_VISIT_30AFTERDEATH_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_VISIT_DATEVDATETIME_COUNT AS QA_VISIT_DATEVDATETIME_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_VISIT_OCCURRENCE_DUPLICATES_COUNT AS QA_VISIT_OCCURRENCE_DUPLICATES_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_VISIT_OCCURRENCE_END_BEFORE_START_COUNT AS QA_VISIT_OCCURRENCE_END_BEFORE_START_COUNT

UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_VISIT_OCCURRENCE_NONSTANDARD_COUNT AS QA_VISIT_OCCURRENCE_NONSTANDARD_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_VISIT_OCCURRENCE_NULLCONCEPT_COUNT AS QA_VISIT_OCCURRENCE_NULLCONCEPT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_VISIT_OCCURRENCE_NULLFK_COUNT AS QA_VISIT_OCCURRENCE_NULLFK_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_VISIT_OCCURRENCE_ZEROCONCEPT_COUNT AS QA_VISIT_OCCURRENCE_ZEROCONCEPT_COUNT


--VISIT_DETAIL
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_VISIT_DETAIL_30AFTERDEATH_COUNT AS QA_VISIT_DETAIL_30AFTERDEATH_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_VISIT_DETAIL_DATEVDATETIME_COUNT AS QA_VISIT_DETAIL_DATEVDATETIME_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_VISIT_DETAIL_DUPLICATES_COUNT AS QA_VISIT_DETAIL_DUPLICATES_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_VISIT_DETAIL_END_BEFORE_START_COUNT AS QA_VISIT_DETAIL_END_BEFORE_START_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_VISIT_DETAIL_NONSTANDARD_COUNT AS QA_VISIT_DETAIL_NONSTANDARD_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_VISIT_DETAIL_NULLCONCEPT_COUNT AS QA_VISIT_DETAIL_NULLCONCEPT_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_VISIT_DETAIL_NULLFK_COUNT AS QA_VISIT_DETAIL_NULLFK_COUNT
UNION ALL SELECT  * FROM
CARE_RES_OMOP_DEV2_WKSP.OMOP_QA.QA_VISIT_DETAIL_ZEROCONCEPT_COUNT AS QA_VISIT_DETAIL_ZEROCONCEPT_COUNT


/*********************************************************
COLUMN DESCRIPTIONS:
- Each QA check returns standardized columns including:
  * ISSUE_TYPE: Type of quality issue identified
  * RECORD_COUNT: Number of records with the issue
  * TABLE_NAME: Affected OMOP table
  * CHECK_NAME: Specific quality check name

LOGIC:
1. Executes individual QA checks on each OMOP table
2. Combines results using UNION ALL
3. Returns consolidated quality metrics

LEGAL DISCLAIMER:
This code is provided "AS IS" without warranty of any kind.
The entire risk arising out of the use or performance of the code 
remains with you. In no event shall the authors be liable for any damages.
**********************************************************/
