------ QA_VISIT_OCCURRENCE_NONSTANDARD_DETAIL
---------------------------------------------------------------------
WITH NONSTANDARD_DETAIL
AS (
	--VISIT_CONCEPT_ID-------------------------------------------
	SELECT 'VISIT_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, VISIT_DETAIL_ID AS CDT_ID
	FROM {{ref('VISIT_DETAIL_RAW')}} AS VD
	LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C
		ON VD.VISIT_DETAIL_CONCEPT_ID = C.CONCEPT_ID AND upper(C.VOCABULARY_ID) =  'VISIT' AND upper(C.DOMAIN_ID) =  'VISIT'
	WHERE VISIT_DETAIL_CONCEPT_ID <> 0 AND STANDARD_CONCEPT <> 'S'

	UNION ALL

	--VISIT_TYPE_CONCEPT_ID-------------------------------------------
	SELECT 'VISIT_TYPE_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, VISIT_DETAIL_ID AS CDT_ID
	FROM {{ref('VISIT_DETAIL_RAW')}} AS VD
	LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C
		ON VD.VISIT_DETAIL_TYPE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.VOCABULARY_ID) =  'VISIT TYPE' AND upper(C.DOMAIN_ID) =  'TYPE CONCEPT'
	WHERE VISIT_DETAIL_TYPE_CONCEPT_ID <> 0 AND STANDARD_CONCEPT <> 'S'

	UNION ALL

	--VISIT_SOURCE_CONCEPT_ID-------------------------------------------
	SELECT 'VISIT_SOURCE_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, VISIT_DETAIL_ID AS CDT_ID
	FROM {{ref('VISIT_DETAIL_RAW')}} AS VD
	LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C
		ON VD.VISIT_DETAIL_SOURCE_CONCEPT_ID = C.CONCEPT_ID AND upper(C.VOCABULARY_ID) =  'VISIT' AND upper(C.DOMAIN_ID) =  'VISIT'
	WHERE VISIT_DETAIL_SOURCE_CONCEPT_ID <> 0 AND STANDARD_CONCEPT <> 'S'

	UNION ALL

	--ADMITTED_FROM_CONCEPT_ID-------------------------------------------
	SELECT 'ADMITTED_FROM_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, VISIT_DETAIL_ID AS CDT_ID
	FROM {{ref('VISIT_DETAIL_RAW')}} AS VD
	LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C
		ON VD.ADMITTED_FROM_CONCEPT_ID= C.CONCEPT_ID AND upper(C.VOCABULARY_ID) =  'CMS PLACE OF SERVICE'
	WHERE ADMITTED_FROM_CONCEPT_ID<> 0 AND STANDARD_CONCEPT <> 'S'

	UNION ALL

	--DISCHARGED_TO_CONCEPT_ID-------------------------------------------
	SELECT 'DISCHARGED_TO_CONCEPT_ID' AS METRIC_FIELD, 'NON-STANDARD' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE
		, VISIT_DETAIL_ID AS CDT_ID
	FROM {{ref('VISIT_DETAIL_RAW')}} AS VD
	LEFT JOIN {{ source('OMOP','CONCEPT')}} AS C
		ON VD.DISCHARGED_TO_CONCEPT_ID= C.CONCEPT_ID AND upper(C.VOCABULARY_ID) =  'CMS PLACE OF SERVICE'
	WHERE DISCHARGED_TO_CONCEPT_ID<> 0 AND STANDARD_CONCEPT <> 'S'
)

SELECT CAST( GETDATE() AS DATE ) AS RUN_DATE
	,'VISIT_DETAIL' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NONSTANDARD_DETAIL
  WHERE ERROR_TYPE <>'EXPECTED'

