--QA_VISIT_DETAIL_DUPLICATES_DETAIL
---------------------------------------------------------------------
WITH TMP_DUPES_DETAIL AS (
SELECT PERSON_ID
	,VISIT_DETAIL_CONCEPT_ID
	,VISIT_DETAIL_START_DATE
	,VISIT_DETAIL_START_DATETIME
	,VISIT_DETAIL_END_DATE
	,VISIT_DETAIL_END_DATETIME
	,VISIT_DETAIL_TYPE_CONCEPT_ID
	,PROVIDER_ID
	,CARE_SITE_ID
	,VISIT_DETAIL_SOURCE_VALUE
	,VISIT_DETAIL_SOURCE_CONCEPT_ID
	,ADMITTED_FROM_CONCEPT_ID
	,ADMITTED_FROM_SOURCE_VALUE
	,DISCHARGED_TO_CONCEPT_ID
	,DISCHARGED_TO_SOURCE_VALUE
	,PRECEDING_VISIT_DETAIL_ID
	,VISIT_OCCURRENCE_ID
	,COUNT(*) AS COUNT

FROM {{ref('VISIT_DETAIL_RAW')}} AS T1
GROUP BY PERSON_ID
	,VISIT_DETAIL_CONCEPT_ID
	,VISIT_DETAIL_START_DATE
	,VISIT_DETAIL_START_DATETIME
	,VISIT_DETAIL_END_DATE
	,VISIT_DETAIL_END_DATETIME
	,VISIT_DETAIL_TYPE_CONCEPT_ID
	,PROVIDER_ID
	,CARE_SITE_ID
	,VISIT_DETAIL_SOURCE_VALUE
	,VISIT_DETAIL_SOURCE_CONCEPT_ID
	,ADMITTED_FROM_CONCEPT_ID
	,ADMITTED_FROM_SOURCE_VALUE
	,DISCHARGED_TO_CONCEPT_ID
	,DISCHARGED_TO_SOURCE_VALUE
	,PRECEDING_VISIT_DETAIL_ID
	,VISIT_OCCURRENCE_ID
HAVING COUNT(*) > 1
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'VISIT_DETAIL' AS STANDARD_DATA_TABLE
	,'DUPLICATE' AS QA_METRIC
	,'RECORDS'  AS METRIC_FIELD
	,'FATAL' AS ERROR_TYPE
	,VI.VISIT_DETAIL_ID

FROM TMP_DUPES_DETAIL AS D
INNER JOIN {{ref('VISIT_DETAIL_RAW')}} AS VI ON D.PERSON_ID = VI.PERSON_ID
	AND D.VISIT_DETAIL_CONCEPT_ID =VI.VISIT_DETAIL_CONCEPT_ID
	AND D.VISIT_DETAIL_START_DATE = VI.VISIT_DETAIL_START_DATE
	AND D.VISIT_DETAIL_START_DATETIME = VI.VISIT_DETAIL_START_DATETIME
	AND D.VISIT_DETAIL_END_DATE = VI.VISIT_DETAIL_END_DATE
	AND COALESCE(D.VISIT_DETAIL_END_DATETIME,'1900-01-01') = COALESCE(VI.VISIT_DETAIL_END_DATETIME,'1900-01-01')
	AND COALESCE(D.VISIT_DETAIL_TYPE_CONCEPT_ID, 0) = COALESCE(VI.VISIT_DETAIL_TYPE_CONCEPT_ID, 0)
	AND COALESCE(D.PROVIDER_ID, 0) = COALESCE(VI.PROVIDER_ID, 0)
	AND COALESCE(D.CARE_SITE_ID, 0) = COALESCE(VI.CARE_SITE_ID, 0)
	AND COALESCE(D.VISIT_DETAIL_SOURCE_VALUE, '0') = COALESCE(VI.VISIT_DETAIL_SOURCE_VALUE, '0')
	AND COALESCE(D.VISIT_DETAIL_SOURCE_CONCEPT_ID, 0) = COALESCE(VI.VISIT_DETAIL_SOURCE_CONCEPT_ID, 0)
	AND COALESCE(D.ADMITTED_FROM_CONCEPT_ID, 0) = COALESCE(VI.ADMITTED_FROM_CONCEPT_ID, 0)
	AND COALESCE(D.ADMITTED_FROM_SOURCE_VALUE, '0') = COALESCE(VI.ADMITTED_FROM_SOURCE_VALUE, '0')
	AND COALESCE(D.DISCHARGED_TO_CONCEPT_ID, 0) = COALESCE(VI.DISCHARGED_TO_CONCEPT_ID, 0)
	AND COALESCE(D.DISCHARGED_TO_SOURCE_VALUE, '0') = COALESCE(VI.DISCHARGED_TO_SOURCE_VALUE, '0')
	AND COALESCE(D.PRECEDING_VISIT_DETAIL_ID, 0) = COALESCE(VI.PRECEDING_VISIT_DETAIL_ID, 0)
	AND COALESCE(D.VISIT_OCCURRENCE_ID, 0) = COALESCE(VI.VISIT_OCCURRENCE_ID, 0)

