--QA_VISIT_DETAIL_DUPLICATES_COUNT
---------------------------------------------------------------------
WITH TMP_DUPES AS (
SELECT PERSON_ID
	,VISIT_DETAIL_CONCEPT_ID
	,VISIT_DETAIL_START_DATE
	,VISIT_DETAIL_START_DATETIME
	,VISIT_DETAIL_END_DATE
	,VISIT_DETAIL_END_DATETIME
	,VISIT_DETAIL_TYPE_CONCEPT_ID
	,PROVIDER_ID
	,CARE_SITE_ID
	,VISIT_DETAIL_SOURCE_VALUE
	,VISIT_DETAIL_SOURCE_CONCEPT_ID
	,ADMITTED_FROM_CONCEPT_ID
	,ADMITTED_FROM_SOURCE_VALUE
	,DISCHARGED_TO_CONCEPT_ID
	,DISCHARGED_TO_SOURCE_VALUE
	,PRECEDING_VISIT_DETAIL_ID
	,VISIT_OCCURRENCE_ID
	,COUNT(*) AS COUNT
FROM {{ref('VISIT_DETAIL_RAW')}} AS T1
GROUP BY PERSON_ID
	,VISIT_DETAIL_CONCEPT_ID
	,VISIT_DETAIL_START_DATE
	,VISIT_DETAIL_START_DATETIME
	,VISIT_DETAIL_END_DATE
	,VISIT_DETAIL_END_DATETIME
	,VISIT_DETAIL_TYPE_CONCEPT_ID
	,PROVIDER_ID
	,CARE_SITE_ID
	,VISIT_DETAIL_SOURCE_VALUE
	,VISIT_DETAIL_SOURCE_CONCEPT_ID
	,ADMITTED_FROM_CONCEPT_ID
	,ADMITTED_FROM_SOURCE_VALUE
	,DISCHARGED_TO_CONCEPT_ID
	,DISCHARGED_TO_SOURCE_VALUE
	,PRECEDING_VISIT_DETAIL_ID
	,VISIT_OCCURRENCE_ID
HAVING COUNT(*) > 1
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	, 'VISIT_DETAIL' AS STANDARD_DATA_TABLE
	, 'DUPLICATE' AS QA_METRIC
	, 'RECORDS'  AS METRIC_FIELD
	, COALESCE(SUM(COUNT),0) AS QA_ERRORS
	, CASE WHEN SUM(COUNT) IS NOT NULL THEN 'FATAL' ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('VISIT_DETAIL_RAW')}}) AS TOTAL_RECORDS
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('VISIT_DETAIL')}}) AS TOTAL_RECORDS_CLEAN
FROM TMP_DUPES

