----QA_VISIT_DETAIL_30AFTERDEATH_DETAIL
-------------------------------------------------------------------
WITH VISIT30AFTERDEATH_DETAIL AS (
SELECT 'VISIT_DETAIL_START_DATE' AS METRIC_FIELD, '30AFTERDEATH' AS QA_METRIC, 'INVALID DATA' AS ERROR_TYPE,
	 VISIT_DETAIL_ID AS CDT_ID
FROM {{ref('VISIT_DETAIL_RAW')}} AS T1
INNER JOIN {{ref('DEATH_RAW')}} AS T2
	ON T1.PERSON_ID = T2.PERSON_ID
WHERE DATEDIFF(DAY, DEATH_DATE, VISIT_DETAIL_START_DATE) > 30
)

SELECT CAST(GETDATE()AS DATE) AS RUN_DATE
	,'VISIT_DETAIL' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM VISIT30AFTERDEATH_DETAIL

