--  SPECIMEN
{#-- {{ config(materialized = 'table', schema = 'OMOP') }}#}

SELECT DISTINCT
     SPECIMEN_ID
    , PERSON_ID
    , SPECIMEN_CONCEPT_ID
    , SPECIMEN_TYPE_CONCEPT_ID
    , SPECIMEN_DATE
    , SPECIMEN_DATETIME
    , QUANTITY
    , UNIT_CONCEPT_ID
    , ANATOMIC_SITE_CONCEPT_ID
    , DISEASE_STATUS_CONCEPT_ID
    , SPECIMEN_SOURCE_ID
    , SPECIMEN_SOURCE_VALUE
    , UNIT_SOURCE_VALUE
    , ANATOMIC_SITE_SOURCE_VALUE
    , DISEASE_STATUS_SOURCE_VALUE
 ------Non OMOP fields -----------
    , etl_MODULE
    , phi_PAT_ID
    , phi_MRN_CPI
----- Link to source
    , src_TABLE
    , src_FIELD
    , src_VALUE_ID
FROM
 {{ref('SPECIMEN_RAW')}} AS SPECIMEN

LEFT JOIN (
    SELECT CDT_ID
    FROM {{ref('QA_ERR_DBT')}} AS QA_ERR_DBT
        WHERE (STANDARD_DATA_TABLE = 'SPECIMEN')
            AND (ERROR_TYPE IN ('FATAL', 'INVALID DATA'))
        ) AS EXCLUSION_RECORDS
        ON SPECIMEN.SPECIMEN_ID = EXCLUSION_RECORDS.CDT_ID
WHERE (EXCLUSION_RECORDS.CDT_ID IS NULL)
