{{ config(materialized='ephemeral') }}
--BEGIN cte__SOURCE_TO_CONCEPT_MAP_ANATOMIC_SITE
    SELECT *
    FROM {{ref('SOURCE_TO_CONCEPT_MAP_stg')}}
    WHERE SOURCE_VOCABULARY_ID = 'SH_ANATOMIC_SITE'
--END cte__SOURCE_TO_CONCEPT_MAP_ANATOMIC_SITE
--
