--STAGE_PROVIDER_ALL
{#-- {{ config(materialized = 'view', schema = 'OMOP_STAGE') }}#}
SELECT DISTINCT PULL_PROVIDER_ALL.PROVIDER_ID                       AS PROVIDER_ID
    ,PULL_PROVIDER_ALL.PROVIDER_NAME                                AS PROVIDER_NAME
    ,PULL_PROVIDER_ALL.NPI                                          AS NPI
    ,PULL_PROVIDER_ALL.DEA                                          AS DEA
    ,COALESCE(SOURCE_TO_CONCEPT_MAP_SPECIALTY.TARGET_CONCEPT_ID, 0) AS SPECIALTY_CONCEPT_ID
    ,COALESCE(MAX(CARE_SITE.CARE_SITE_ID),1)                        AS CARE_SITE_ID
    ,PULL_PROVIDER_ALL.YEAR_OF_BIRTH                                AS YEAR_OF_BIRTH
    ,COALESCE(SOURCE_TO_CONCEPT_MAP_GENDER.TARGET_CONCEPT_ID, 0)    AS GENDER_CONCEPT_ID
    ,PULL_PROVIDER_ALL.PROVIDER_ID                                  AS PROVIDER_SOURCE_VALUE
    ,PULL_PROVIDER_ALL.SPECIALTY_SOURCE_VALUE                       AS SPECIALTY_SOURCE_VALUE
    ,NULL                                                           AS SPECIALTY_SOURCE_CONCEPT_ID
    ,GENDER_SOURCE_VALUE                                            AS GENDER_SOURCE_VALUE
    ,NULL                                                           AS GENDER_SOURCE_CONCEPT_ID

FROM  {{ ref('PULL_PROVIDER_ALL')}} AS  PULL_PROVIDER_ALL

    LEFT OUTER JOIN  {{ ref('SOURCE_TO_CONCEPT_MAP_SPECIALTY')}} AS SOURCE_TO_CONCEPT_MAP_SPECIALTY
        ON PULL_PROVIDER_ALL.SPECIALTY_C = SOURCE_TO_CONCEPT_MAP_SPECIALTY.SOURCE_CODE

    LEFT JOIN  {{ ref('CARE_SITE_RAW')}} AS CARE_SITE
        ON PULL_PROVIDER_ALL.REV_LOC_ID = CARE_SITE.CARE_SITE_ID

    LEFT JOIN {{ ref('SOURCE_TO_CONCEPT_MAP_GENDER')}}  AS SOURCE_TO_CONCEPT_MAP_GENDER
        ON PULL_PROVIDER_ALL.SEX_C = SOURCE_TO_CONCEPT_MAP_GENDER.SOURCE_CODE

GROUP BY
    PULL_PROVIDER_ALL.PROVIDER_ID
    ,PULL_PROVIDER_ALL.PROVIDER_NAME
    ,PULL_PROVIDER_ALL.NPI
    ,PULL_PROVIDER_ALL.DEA
    ,COALESCE(SOURCE_TO_CONCEPT_MAP_SPECIALTY.TARGET_CONCEPT_ID, 0)
    ,PULL_PROVIDER_ALL.YEAR_OF_BIRTH
    ,COALESCE(SOURCE_TO_CONCEPT_MAP_GENDER.TARGET_CONCEPT_ID, 0)
    ,PULL_PROVIDER_ALL.PROVIDER_ID
    ,LEFT(ZC_SPECIALTY_NAME, 50)
    ,PULL_PROVIDER_ALL.GENDER_SOURCE_VALUE
    ,PULL_PROVIDER_ALL.SPECIALTY_SOURCE_VALUE

