/*
Purpose: Create DEVICE_EXPOSURE_RAW table by combining device exposure data from multiple sources
Tables Used: 
- STAGE_DEVICE_EXPOSURE_HSP_BLOOD
- STAGE_DEVICE_EXPOSURE_HSP_LDA
- STAGE_DEVICE_EXPOSURE_ANES_LDA
*/

SELECT DISTINCT
    -- OMOP Standard Fields
    CARE_RES_OMOP_DEV2_WKSP.OMOP.DEVICE_EXPOSURE_RAW_SEQ.nextval::NUMBER(28,0)   AS DEVICE_EXPOSURE_ID,
    PERSON_ID::NUMBER(28,0)                     AS PERSON_ID,
    DEVICE_CONCEPT_ID::NUMBER(28,0)             AS DEVICE_CONCEPT_ID,
    DEVICE_EXPOSURE_START_DATE::DATE            AS DEVICE_EXPOSURE_START_DATE,
    DEVICE_EXPOSURE_START_DATETIME::DATETIME    AS DEVICE_EXPOSURE_START_DATETIME,
    DEVICE_EXPOSURE_END_DATE::DATE              AS DEVICE_EXPOSURE_END_DATE,
    DEVICE_EXPOSURE_END_DATETIME::DATETIME      AS DEVICE_EXPOSURE_END_DATETIME,
    DEVICE_TYPE_CONCEPT_ID::NUMBER(28,0)        AS DEVICE_TYPE_CONCEPT_ID,
    UNIQUE_DEVICE_ID::VARCHAR(255)              AS UNIQUE_DEVICE_ID,
    PRODUCTION_ID::VARCHAR(255)                 AS PRODUCTION_ID,          -- NEW 5.4
    QUANTITY::NUMBER(28,0)                      AS QUANTITY,
    PROVIDER_ID::NUMBER(28,0)                   AS PROVIDER_ID,
    VISIT_OCCURRENCE_ID::NUMBER(28,0)           AS VISIT_OCCURRENCE_ID,
    VISIT_DETAIL_ID::NUMBER(28,0)               AS VISIT_DETAIL_ID,
    DEVICE_SOURCE_VALUE::VARCHAR(250)           AS DEVICE_SOURCE_VALUE,    -- Human readable Source Value
    DEVICE_SOURCE_CONCEPT_ID::NUMBER(28,0)      AS DEVICE_SOURCE_CONCEPT_ID,
    UNIT_CONCEPT_ID::NUMBER(28,0)               AS UNIT_CONCEPT_ID,       -- NEW 5.4
    UNIT_SOURCE_VALUE::VARCHAR(50)              AS UNIT_SOURCE_VALUE,     -- NEW 5.4
    UNIT_SOURCE_CONCEPT_ID::NUMBER(28,0)        AS UNIT_SOURCE_CONCEPT_ID,-- NEW 5.4

    -- Non-OMOP Fields
    ETL_MODULE::VARCHAR                         AS ETL_MODULE,
    STAGE_PAT_ID::VARCHAR                       AS phi_PAT_ID,
    STAGE_MRN_CPI::NUMBER(28,0)                 AS phi_MRN_CPI,
    STAGE_CSN_ID::NUMBER(28,0)                  AS phi_CSN_ID,

    -- Source Link Fields
    SRC_TABLE::VARCHAR                          AS src_TABLE,
    SRC_FIELD::VARCHAR                          AS src_FIELD,
    SRC_VALUE_ID::VARCHAR                       AS src_VALUE_ID

FROM (
    -- Blood Device Exposures
    SELECT 
        PERSON_ID, DEVICE_CONCEPT_ID, DEVICE_EXPOSURE_START_DATE,
        DEVICE_EXPOSURE_START_DATETIME, DEVICE_EXPOSURE_END_DATE, DEVICE_EXPOSURE_END_DATETIME,
        DEVICE_TYPE_CONCEPT_ID, UNIQUE_DEVICE_ID, PRODUCTION_ID, QUANTITY, PROVIDER_ID, VISIT_OCCURRENCE_ID,
        VISIT_DETAIL_ID, DEVICE_SOURCE_VALUE, DEVICE_SOURCE_CONCEPT_ID, UNIT_CONCEPT_ID, UNIT_SOURCE_VALUE, UNIT_SOURCE_CONCEPT_ID,
        ETL_MODULE, STAGE_PAT_ID, STAGE_MRN_CPI, STAGE_CSN_ID,
        'ORDER_PROC' as SRC_TABLE, 
        'PROC_ID' AS SRC_FIELD, 
        STAGE_PROC_ID::INTEGER AS SRC_VALUE_ID
    FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_STAGE.STAGE_DEVICE_EXPOSURE_HSP_BLOOD

    UNION ALL

    -- Hospital LDA Device Exposures
    SELECT 
        PERSON_ID, DEVICE_CONCEPT_ID, DEVICE_EXPOSURE_START_DATE,
        DEVICE_EXPOSURE_START_DATETIME, DEVICE_EXPOSURE_END_DATE, DEVICE_EXPOSURE_END_DATETIME,
        DEVICE_TYPE_CONCEPT_ID, UNIQUE_DEVICE_ID, PRODUCTION_ID, QUANTITY, PROVIDER_ID, VISIT_OCCURRENCE_ID,
        VISIT_DETAIL_ID, DEVICE_SOURCE_VALUE, DEVICE_SOURCE_CONCEPT_ID, UNIT_CONCEPT_ID, UNIT_SOURCE_VALUE, UNIT_SOURCE_CONCEPT_ID,
        ETL_MODULE, STAGE_PAT_ID, STAGE_MRN_CPI, STAGE_CSN_ID,
        'IP_FLO_GP_DATA' as SRC_TABLE, 
        'FLO_MEAS_ID' AS SRC_FIELD, 
        STAGE_FLO_MEAS_ID::INTEGER AS SRC_VALUE_ID
    FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_STAGE.STAGE_DEVICE_EXPOSURE_HSP_LDA

    UNION ALL

    -- Anesthesia LDA Device Exposures
    SELECT 
        PERSON_ID, DEVICE_CONCEPT_ID, DEVICE_EXPOSURE_START_DATE,
        DEVICE_EXPOSURE_START_DATETIME, DEVICE_EXPOSURE_END_DATE, DEVICE_EXPOSURE_END_DATETIME,
        DEVICE_TYPE_CONCEPT_ID, UNIQUE_DEVICE_ID, PRODUCTION_ID, QUANTITY, PROVIDER_ID, VISIT_OCCURRENCE_ID,
        VISIT_DETAIL_ID, DEVICE_SOURCE_VALUE, DEVICE_SOURCE_CONCEPT_ID, UNIT_CONCEPT_ID, UNIT_SOURCE_VALUE, UNIT_SOURCE_CONCEPT_ID,
        ETL_MODULE, STAGE_PAT_ID, STAGE_MRN_CPI, STAGE_CSN_ID,
        'IP_FLO_GP_DATA' as SRC_TABLE, 
        'FLO_MEAS_ID' AS SRC_FIELD, 
        STAGE_FLO_MEAS_ID::INTEGER AS SRC_VALUE_ID
    FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_STAGE.STAGE_DEVICE_EXPOSURE_ANES_LDA
) A;