--OMOP.AOU_PII

{{ config(materialized = 'view') }}

--This JOINS AOU_DRIVER_PROD to CLARITY.PATIENT to identify AOU data to Epic data for validation


SELECT distinct UPPER(CPI) AS CPI
      ,UPPER(AOU_DRIVER_PROD.EPIC_PAT_ID) AS EPIC_PAT_ID
      ,UPPER(AOU_ID) AS AOU_ID

	,SUBSTRING(AOU_DRIVER_PROD.AOU_ID, 2, LEN(AOU_DRIVER_PROD.AOU_ID)) AS PID

	,CASE
		WHEN REPLACE(UPPER(PAT_FIRST_NAME), ' ', '') LIKE REPLACE(UPPER(FIRST_NAME), ' ', '') || '%'
			OR REPLACE(UPPER(FIRST_NAME), ' ', '') LIKE REPLACE(UPPER(PAT_FIRST_NAME), ' ', '') || '%'
			THEN 1
		ELSE 0
		END AS FIRSTNAME
	,UPPER(PAT_FIRST_NAME) AS EPIC_FIRST_NAME
	,UPPER(FIRST_NAME) AS AOU_FIRST_NAME
	,CASE
		WHEN REPLACE(REPLACE(REPLACE(UPPER(PAT_LAST_NAME), ' ', ''), '-', ''), '''', '')
			LIKE REPLACE(REPLACE(REPLACE(UPPER(AOU_DRIVER_PROD.LAST_NAME), ' ', ''), '-', ''), '''', '') || '%'
			OR REPLACE(REPLACE(REPLACE(UPPER(AOU_DRIVER_PROD.LAST_NAME), ' ', ''), '-', ''), '''', '')
			LIKE REPLACE(REPLACE(REPLACE(UPPER(PAT_LAST_NAME), ' ', ''), '-', ''), '''', '') || '%'
			THEN 1
		ELSE 0
		END AS LASTNAME
	,UPPER(PATIENT.PAT_LAST_NAME) AS EPIC_LAST_NAME
	,UPPER(AOU_DRIVER_PROD.LAST_NAME) AS AOU_LAST_NAME
	,CASE
--        WHEN CAST( BIRTH_DATE AS DATE) = CAST(DATE_OF_BIRTH AS DATE)
        WHEN BIRTH_DATE::DATE = DATE_OF_BIRTH::DATE
			THEN 1
		ELSE 0
		END AS DOB
	,UPPER(BIRTH_DATE) AS EPIC_BIRTH_DATE
	,UPPER(DATE_OF_BIRTH) AS AOU_BIRTH_DATE
	,CASE
		WHEN UPPER(ZC_SEX.NAME) = UPPER(AOU_DRIVER_PROD.SEX)
			THEN 1
		ELSE 0
		END AS SEX
	,UPPER(ZC_SEX.NAME) AS EPIC_SEX
	,UPPER(AOU_DRIVER_PROD.SEX) AS AOU_SEX
	,CASE
		WHEN (REPLACE(REPLACE(REPLACE(UPPER(ADD_LINE_1), ' ', ''), '.', ''), ',', '') <> NULL) AND
            (REPLACE(REPLACE(REPLACE(UPPER(ADD_LINE_1), ' ', ''), '.', ''), ',', '')
			LIKE REPLACE(REPLACE(REPLACE(UPPER(STREET_ADDRESS), ' ', ''), '.', ''), ',', '') || '%'
			OR REPLACE(REPLACE(REPLACE(UPPER(STREET_ADDRESS), ' ', ''), '.', ''), ',', '')
			LIKE REPLACE(REPLACE(REPLACE(UPPER(ADD_LINE_1), ' ', ''), '.', ''), ',', '') || '%')
			THEN 1
		ELSE 0
		END AS ADDRESS
	,UPPER(ADD_LINE_1) AS EPIC_ADDRESS
	,UPPER(STREET_ADDRESS) AS AOU_ADDRESS
	,CASE
		WHEN REPLACE(UPPER(HOME_PHONE), '-', '') = REPLACE(REPLACE(REPLACE(REPLACE(UPPER(AOU_DRIVER_PROD.PHONE), '-', ''), ')', ''), '(', ''), ' ', '')
			THEN 1
		ELSE 0
		END AS "PHONE NUMBER"
	,UPPER(HOME_PHONE) AS EPIC_PHONE
	,UPPER(PHONE) AS AOU_PHONE
	,CASE
		WHEN REPLACE(UPPER(EMAIL_ADDRESS), ',', '') = REPLACE(UPPER(AOU_DRIVER_PROD.EMAIL), ',', '')
			THEN 1
		ELSE 0
		END AS EMAIL
	,UPPER(EMAIL_ADDRESS) AS EPIC_EMAIL
	,UPPER(REPLACE(EMAIL, ',', '')) AS AOU_EMAIL
	,EHR_EXPORT_PT_MATCH_PASS AS "MANUAL VALIDATION"

FROM {{ source('CLARITY','PATIENT')}} AS PATIENT

	INNER JOIN {{ref('AOU_DRIVER_PROD')}} AS AOU_DRIVER_PROD
		ON PATIENT.PAT_ID = AOU_DRIVER_PROD.EPIC_PAT_ID

	INNER JOIN {{ source('CLARITY','ZC_SEX')}} AS ZC_SEX
		ON PATIENT.SEX_C = ZC_SEX.RCPT_MEM_SEX_C
