--PROVIDERS_REFERENCED

        SELECT PROVIDER_ID
        FROM SH_OMOP_DB_PROD.OMOP.PERSON_RAW AS PERSON
        UNION
        SELECT PROVIDER_ID
        FROM SH_OMOP_DB_PROD.OMOP.VISIT_OCCURRENCE_RAW AS VISIT_OCCURRENCE
        UNION
        SELECT PROVIDER_ID
        FROM SH_OMOP_DB_PROD.OMOP.VISIT_DETAIL_RAW AS VISIT_DETAIL
        UNION
        SELECT PROVIDER_ID
        FROM SH_OMOP_DB_PROD.OMOP.CONDITION_OCCURRENCE_RAW AS CONDITION_OCCURRENCE
        UNION
        SELECT PROVIDER_ID
        FROM SH_OMOP_DB_PROD.OMOP.DEVICE_EXPOSURE_RAW AS DEVICE_EXPOSURE
        UNION
        SELECT PROVIDER_ID
        FROM SH_OMOP_DB_PROD.OMOP.DRUG_EXPOSURE_RAW AS DRUG_EXPOSURE
        UNION
        SELECT PROVIDER_ID
        FROM SH_OMOP_DB_PROD.OMOP.MEASUREMENT_RAW AS MEASUREMENT
        UNION
        SELECT PROVIDER_ID
        FROM SH_OMOP_DB_PROD.OMOP.NOTE_RAW AS NOTE
        UNION
        SELECT PROVIDER_ID
        FROM SH_OMOP_DB_PROD.OMOP.OBSERVATION_RAW AS OBSERVATION
        UNION

        SELECT PROVIDER_ID
        FROM SH_OMOP_DB_PROD.OMOP.PROCEDURE_OCCURRENCE_RAW AS PROCEDURE_OCCURRENCE