--Query_Visit_Detail_Errors

SELECT
    QA_ERR_DBT.RUN_DATE
    , QA_ERR_DBT.STANDARD_DATA_TABLE
    , QA_ERR_DBT.QA_METRIC
    , QA_ERR_DBT.METRIC_FIELD
    , QA_ERR_DBT.ERROR_TYPE
    , VISIT_DETAIL.*
FROM
    {{ref('QA_ERR_DBT')}} AS QA_ERR_DBT
INNER JOIN {{ref('VISIT_DETAIL_RAW')}} AS VISIT_DETAIL ON
    QA_ERR_DBT.CDT_ID = VISIT_DETAIL.VISIT_DETAIL_ID
    AND QA_ERR_DBT.CDT_ID = VISIT_DETAIL.VISIT_DETAIL_ID
WHERE
    QA_ERR_DBT.STANDARD_DATA_TABLE = 'VISIT_DETAIL'
