--Query_Location_Errors

SELECT
    QA_ERR_DBT.RUN_DATE
    , QA_ERR_DBT.STANDARD_DATA_TABLE
    , QA_ERR_DBT.QA_METRIC
    , QA_ERR_DBT.METRIC_FIELD
    , QA_ERR_DBT.ERROR_TYPE
    , LOCATION.*
FROM
    {{ref('QA_ERR_DBT')}} AS QA_ERR_DBT
INNER JOIN {{ref('LOCATION')}} AS LOCATION ON
    QA_ERR_DBT.CDT_ID = LOCATION.LOCATION_ID
    AND QA_ERR_DBT.CDT_ID = LOCATION.LOCATION_ID
WHERE
    QA_ERR_DBT.STANDARD_DATA_TABLE = 'LOCATION'
