--Query_Note_Errors

SELECT
    QA_ERR_DBT.RUN_DATE
    , QA_ERR_DBT.STANDARD_DATA_TABLE
    , QA_ERR_DBT.QA_METRIC
    , QA_ERR_DBT.METRIC_FIELD
    , QA_ERR_DBT.ERROR_TYPE
    , NOTE.*
FROM
    {{ref('QA_ERR_DBT')}} AS QA_ERR_DBT
INNER JOIN {{ref('NOTE')}} AS NOTE ON
    QA_ERR_DBT.CDT_ID = NOTE.NOTE_ID
WHERE
    QA_ERR_DBT.STANDARD_DATA_TABLE = 'NOTE'
