--Query_Specimen_Errors

SELECT
    QA_ERR_DBT.RUN_DATE
    , QA_ERR_DBT.STANDARD_DATA_TABLE
    , QA_ERR_DBT.QA_METRIC
    , QA_ERR_DBT.METRIC_FIELD
    , QA_ERR_DBT.ERROR_TYPE
    , SPECIMEN.*
FROM
    {{ref('QA_ERR_DBT')}} AS QA_ERR_DBT
INNER JOIN {{ref('SPECIMEN_RAW')}} AS SPECIMEN ON
    QA_ERR_DBT.CDT_ID = SPECIMEN.SPECIMEN_ID
    AND QA_ERR_DBT.CDT_ID = SPECIMEN.SPECIMEN_ID
WHERE
    QA_ERR_DBT.STANDARD_DATA_TABLE = 'SPECIMEN'
