--Query_Device_Exposure_Errors

SELECT
    QA_ERR_DBT.RUN_DATE
    , QA_ERR_DBT.STANDARD_DATA_TABLE
    , QA_ERR_DBT.QA_METRIC
    , QA_ERR_DBT.METRIC_FIELD
    , QA_ERR_DBT.ERROR_TYPE
    , DEVICE_EXPOSURE.*
FROM
    {{ref('QA_ERR_DBT')}} AS QA_ERR_DBT
INNER JOIN {{ref('DEVICE_EXPOSURE')}} AS DEVICE_EXPOSURE ON
    QA_ERR_DBT.CDT_ID = DEVICE_EXPOSURE.DEVICE_EXPOSURE_ID

WHERE
    QA_ERR_DBT.STANDARD_DATA_TABLE = 'DEVICE_EXPOSURE'
