--Query_Measurement_Errors

SELECT
    QA_ERR_DBT.RUN_DATE
    , QA_ERR_DBT.STANDARD_DATA_TABLE
    , QA_ERR_DBT.QA_METRIC
    , QA_ERR_DBT.METRIC_FIELD
    , QA_ERR_DBT.ERROR_TYPE
    , MEASUREMENT.*
FROM
    {{ref('QA_ERR_DBT')}} AS QA_ERR_DBT
INNER JOIN {{ref('MEASUREMENT')}} AS MEASUREMENT ON
    QA_ERR_DBT.CDT_ID = MEASUREMENT.MEASUREMENT_ID
    AND QA_ERR_DBT.CDT_ID = MEASUREMENT.MEASUREMENT_ID
WHERE
    QA_ERR_DBT.STANDARD_DATA_TABLE = 'MEASUREMENT'
