--Query_Care_Site_Errors


SELECT
    QA_ERR_DBT.RUN_DATE
    , QA_ERR_DBT.STANDARD_DATA_TABLE
    , QA_ERR_DBT.QA_METRIC
    , QA_ERR_DBT.METRIC_FIELD
    , QA_ERR_DBT.ERROR_TYPE
    , CARE_SITE.*
FROM
    {{ref('QA_ERR_DBT')}} AS QA_ERR_DBT
INNER JOIN {{ref('CARE_SITE')}} AS CARE_SITE ON
    QA_ERR_DBT.CDT_ID = CARE_SITE.CARE_SITE_ID
    AND QA_ERR_DBT.CDT_ID = CARE_SITE.CARE_SITE_ID
WHERE
    QA_ERR_DBT.STANDARD_DATA_TABLE = 'CARE_SITE'
