--QA_ERR

{{ config(materialized = 'view') }}

--CARE_SITE
SELECT  RUN_DATE, STANDARD_DATA_TABLE, QA_METRIC, METRIC_FIELD, ERROR_TYPE, CARE_SITE_ID AS CDT_ID
 FROM 
{{ref('QA_CARE_SITE_DUPLICATES_DETAIL')}} AS QA_CARE_SITE_DUPLICATES_DETAIL 
{# UNION SELECT  * FROM
{{ref('xxx')}} AS QA_CARE_SITE_NOMATCH_DETAIL  #}
UNION SELECT  * FROM
{{ref('QA_CARE_SITE_NON_STANDARD_DETAIL')}} AS QA_CARE_SITE_NON_STANDARD_DETAIL 
UNION SELECT  * FROM
{{ref('QA_CARE_SITE_NULLFK_DETAIL')}} AS QA_CARE_SITE_NULLFK_DETAIL 
UNION SELECT  * FROM
{{ref('QA_CARE_SITE_NULL_CONCEPT_DETAIL')}} AS QA_CARE_SITE_NULL_CONCEPT_DETAIL 
UNION SELECT  * FROM
{{ref('QA_CARE_SITE_ZERO_CONCEPT_DETAIL')}} AS QA_CARE_SITE_ZERO_CONCEPT_DETAIL 

--CONDITION
UNION SELECT  * FROM
{{ref('QA_CONDITION_30AFTERDEATH_DETAIL')}} AS QA_CONDITION_30AFTERDEATH_DETAIL
UNION SELECT  * FROM
{{ref('QA_CONDITION_OCCURRENCE_DATEVDATETIME_DETAIL')}} AS QA_CONDITION_OCCURRENCE_DATEVDATETIME_DETAIL
UNION SELECT  * FROM
 {{ref('QA_CONDITION_OCCURRENCE_DUPLICATES_DETAIL')}} AS QA_CONDITION_OCCURRENCE_DUPLICATES_DETAIL
UNION SELECT  * FROM
 {{ref('QA_CONDITION_OCCURRENCE_END_BEFORE_START_DETAIL')}} AS QA_CONDITION_OCCURRENCE_END_BEFORE_START_DETAIL
{# UNION SELECT  * FROM
{{ref('QA_CONDITION_OCCURRENCE_NOMATCH_DETAIL')}} AS QA_CONDITION_OCCURRENCE_NOMATCH_DETAIL #}
UNION SELECT  * FROM
{{ref('QA_CONDITION_OCCURRENCE_NONSTANDARD_DETAIL')}} AS QA_CONDITION_OCCURRENCE_NONSTANDARD_DETAIL
UNION SELECT  * FROM
{{ref('QA_CONDITION_OCCURRENCE_NOVISIT_DETAIL')}} AS QA_CONDITION_OCCURRENCE_NOVISIT_DETAIL
UNION SELECT  * FROM
{{ref('QA_CONDITION_OCCURRENCE_NULLCONCEPT_DETAIL')}} AS QA_CONDITION_OCCURRENCE_NULLCONCEPT_DETAIL
UNION SELECT  * FROM
{{ref('QA_CONDITION_OCCURRENCE_NULLFK_DETAIL')}} AS QA_CONDITION_OCCURRENCE_NULLFK_DETAIL
UNION SELECT  * FROM
{{ref('QA_CONDITION_OCCURRENCE_VISITDATEDISPARITY_DETAIL')}} AS QA_CONDITION_OCCURRENCE_VISITDATEDISPARITY_DETAIL 
UNION SELECT  * FROM
{{ref('QA_CONDITION_OCCURRENCE_ZEROCONCEPT_DETAIL')}} AS QA_CONDITION_OCCURRENCE_ZEROCONCEPT_DETAIL

--DEATH
UNION SELECT  * FROM
{{ref('QA_DEATH_DUPLICATES_DETAIL')}} AS QA_DEATH_DUPLICATES_DETAIL
UNION SELECT  * FROM
{{ref('QA_DEATH_NULL_CONCEPT_DETAIL')}} AS QA_DEATH_NULL_CONCEPT_DETAIL
UNION SELECT  * FROM
{{ref('QA_DEATH_ZERO_CONCEPT_DETAIL')}} AS QA_DEATH_ZERO_CONCEPT_DETAIL

--DEVICE_EXPOSURE
UNION SELECT  * FROM
{{ref('QA_DEVICE_CONCEPT_DUPLICATES_DETAIL')}} AS QA_DEVICE_CONCEPT_DUPLICATES_DETAIL 
UNION SELECT  * FROM
{{ref('QA_DEVICE_EXPOSURE_DATEVDATETIME_DETAIL')}} AS QA_DEVICE_EXPOSURE_DATEVDATETIME_DETAIL 
UNION SELECT  * FROM
{{ref('QA_DEVICE_EXPOSURE_END_BEFORE_START_DETAIL')}} AS QA_DEVICE_EXPOSURE_END_BEFORE_START_DETAIL
{# UNION SELECT  * FROM
{{ref('xxx')}} AS QA_DEVICE_EXPOSURE_NOMATCH_DETAIL  #}
UNION SELECT  * FROM
{{ref('QA_DEVICE_EXPOSURE_NONSTANDARD_DETAIL')}} AS QA_DEVICE_EXPOSURE_NONSTANDARD_DETAIL 
UNION SELECT  * FROM
{{ref('QA_DEVICE_EXPOSURE_NOVISIT_DETAIL')}} AS QA_DEVICE_EXPOSURE_NOVISIT_DETAIL
UNION SELECT  * FROM
{{ref('QA_DEVICE_EXPOSURE_NULLFK_DETAIL')}} AS QA_DEVICE_EXPOSURE_NULLFK_DETAIL 
UNION SELECT  * FROM
{{ref('QA_DEVICE_EXPOSURE_NULL_CONCEPT_DETAIL')}} AS QA_DEVICE_EXPOSURE_NULL_CONCEPT_DETAIL 
UNION SELECT  * FROM
{{ref('QA_DEVICE_EXPOSURE_ZERO_CONCEPT_DETAIL')}} AS QA_DEVICE_EXPOSURE_ZERO_CONCEPT_DETAIL 

--DRUG_EXPOSURE
UNION SELECT  * FROM
{{ref('QA_DRUG_30AFTERDEATH_DETAIL')}} AS QA_DRUG_30AFTERDEATH_DETAIL 
UNION SELECT  * FROM
{{ref('QA_DRUG_EXPOSURE_DATEVDATETIME_DETAIL')}} AS QA_DRUG_EXPOSURE_DATEVDATETIME_DETAIL 
UNION SELECT  * FROM
{{ref('QA_DRUG_EXPOSURE_DUPLICATES_DETAIL')}} AS QA_DRUG_EXPOSURE_DUPLICATES_DETAIL 
UNION SELECT  * FROM
{{ref('QA_DRUG_EXPOSURE_END_BEFORE_START_DETAIL')}} AS QA_DRUG_EXPOSURE_END_BEFORE_START_DETAIL
{# UNION SELECT  * FROM
{{ref('XXX')}} AS QA_DRUG_EXPOSURE_NOMATCH_DETAIL #}
UNION SELECT  * FROM
{{ref('QA_DRUG_EXPOSURE_NONSTANDARD_DETAIL')}} AS QA_DRUG_EXPOSURE_NONSTANDARD_DETAIL 
UNION SELECT  * FROM
{{ref('QA_DRUG_EXPOSURE_NOVISIT_DETAIL')}} AS QA_DRUG_EXPOSURE_NOVISIT_DETAIL 
UNION SELECT  * FROM
{{ref('QA_DRUG_EXPOSURE_NULLCONCEPT_DETAIL')}} AS QA_DRUG_EXPOSURE_NULLCONCEPT_DETAIL
UNION SELECT  * FROM
{{ref('QA_DRUG_EXPOSURE_NULLFK_DETAIL')}} AS QA_DRUG_EXPOSURE_NULLFK_DETAIL
UNION SELECT  * FROM
{{ref('QA_DRUG_EXPOSURE_VISITDATEDISPARITY_DETAIL')}} AS QA_DRUG_EXPOSURE_VISITDATEDISPARITY_DETAIL
UNION SELECT  * FROM
{{ref('QA_DRUG_EXPOSURE_ZEROCONCEPT_DETAIL')}} AS QA_DRUG_EXPOSURE_ZEROCONCEPT_DETAIL

--LOCATION
UNION SELECT  * FROM
{{ref('QA_LOCATION_DUPLICATES_DETAIL')}} AS QA_LOCATION_DUPLICATES_DETAIL

--MEASUREMENT
UNION SELECT  * FROM
{{ref('QA_MEASUREMENT_30AFTERDEATH_DETAIL')}} AS QA_MEASUREMENT_30AFTERDEATH_DETAIL
UNION SELECT  * FROM
{{ref('QA_MEASUREMENT_DATEVDATETIME_DETAIL')}} AS QA_MEASUREMENT_DATEVDATETIME_DETAIL
UNION SELECT  * FROM
{{ref('QA_MEASUREMENT_DUPLICATES_DETAIL')}} AS QA_MEASUREMENT_DUPLICATES_DETAIL
{# UNION SELECT  * FROM
{{ref('xxx')}} AS QA_MEASUREMENT_NOMATCH_DETAIL #}
UNION SELECT  * FROM
{{ref('QA_MEASUREMENT_NONSTANDARD_DETAIL')}} AS QA_MEASUREMENT_NONSTANDARD_DETAIL
UNION SELECT  * FROM
{{ref('QA_MEASUREMENT_NOVISIT_DETAIL')}} AS QA_MEASUREMENT_NOVISIT_DETAIL
UNION SELECT  * FROM
{{ref('QA_MEASUREMENT_NULLCONCEPT_DETAIL')}} AS QA_MEASUREMENT_NULLCONCEPT_DETAIL
UNION SELECT  * FROM
{{ref('QA_MEASUREMENT_NULLFK_DETAIL')}} AS QA_MEASUREMENT_NULLFK_DETAIL
UNION SELECT  * FROM
{{ref('QA_MEASUREMENT_VISITDATEDISPARITY_DETAIL')}} AS QA_MEASUREMENT_VISITDATEDISPARITY_DETAIL
UNION SELECT  * FROM
{{ref('QA_MEASUREMENT_ZEROCONCEPT_DETAIL')}} AS QA_MEASUREMENT_ZEROCONCEPT_DETAIL

--NOTE
UNION SELECT  * FROM
{{ref('QA_NOTE_DATEVDATETIME_DETAIL')}} AS QA_NOTE_DATEVDATETIME_DETAIL
UNION SELECT  * FROM
{{ref('QA_NOTE_DUPLICATES_DETAIL')}} AS QA_NOTE_DUPLICATES_DETAIL
{# UNION SELECT  * FROM
{{ref('xxx')}} AS QA_NOTE_NOMATCH_DETAIL #}
UNION SELECT  * FROM
{{ref('QA_NOTE_NONSTANDARD_DETAIL')}} AS QA_NOTE_NONSTANDARD_DETAIL
UNION SELECT  * FROM
{{ref('QA_NOTE_NOVISIT_DETAIL')}} AS QA_NOTE_NOVISIT_DETAIL
UNION SELECT  * FROM
{{ref('QA_NOTE_NULLCONCEPT_DETAIL')}} AS QA_NOTE_NULLCONCEPT_DETAIL
UNION SELECT  * FROM
{{ref('QA_NOTE_NULLFK_DETAIL')}} AS QA_NOTE_NULLFK_DETAIL
UNION SELECT  * FROM
{{ref('QA_NOTE_ZEROCONCEPT_DETAIL')}} AS QA_NOTE_ZEROCONCEPT_DETAIL

--OBSERVATION
UNION SELECT  * FROM
{{ref('QA_OBSERVATION_30AFTERDEATH_DETAIL')}} AS QA_OBSERVATION_30AFTERDEATH_DETAIL
UNION SELECT  * FROM
{{ref('QA_OBSERVATION_DATEVDATETIME_DETAIL')}} AS QA_OBSERVATION_DATEVDATETIME_DETAIL
UNION SELECT  * FROM
{{ref('QA_OBSERVATION_DUPLICATES_DETAIL')}} AS QA_OBSERVATION_DUPLICATES_DETAIL
{# UNION SELECT  * FROM
{{ref('xxx')}} AS QA_OBSERVATION_NOMATCH_DETAIL #}
UNION SELECT  * FROM
{{ref('QA_OBSERVATION_NONSTANDARD_DETAIL')}} AS QA_OBSERVATION_NONSTANDARD_DETAIL
UNION SELECT  * FROM
{{ref('QA_OBSERVATION_NOVISIT_DETAIL')}} AS QA_OBSERVATION_NOVISIT_DETAIL
UNION SELECT  * FROM
{{ref('QA_OBSERVATION_NULLCONCEPT_DETAIL')}} AS QA_OBSERVATION_NULLCONCEPT_DETAIL
UNION SELECT  * FROM
{{ref('QA_OBSERVATION_NULLFK_DETAIL')}} AS QA_OBSERVATION_NULLFK_DETAIL
UNION SELECT  * FROM
{{ref('QA_OBSERVATION_VISITDATEDISPARITY_DETAIL')}} AS QA_OBSERVATION_VISITDATEDISPARITY_DETAIL
UNION SELECT  * FROM
{{ref('QA_OBSERVATION_ZEROCONCEPT_DETAIL')}} AS QA_OBSERVATION_ZEROCONCEPT_DETAIL

--PERSON
UNION SELECT  * FROM
{{ref('QA_PERSON_AGE_ERR_DETAIL')}} AS QA_PERSON_AGE_ERR_DETAIL
UNION SELECT  * FROM
{{ref('QA_PERSON_DUPLICATES_DETAIL')}} AS QA_PERSON_DUPLICATES_DETAIL
{#UNION SELECT  * FROM
{{ref('xxx')}} AS QA_PERSON_NOMATCH_DETAIL #}
UNION SELECT  * FROM
{{ref('QA_PERSON_NONSTANDARD_DETAIL')}} AS QA_PERSON_NONSTANDARD_DETAIL
UNION SELECT  * FROM
{{ref('QA_PERSON_NULLCONCEPT_DETAIL')}} AS QA_PERSON_NULLCONCEPT_DETAIL
UNION SELECT  * FROM
{{ref('QA_PERSON_NULLFK_DETAIL')}} AS QA_PERSON_NULLFK_DETAIL
UNION SELECT  * FROM
{{ref('QA_PERSON_ZEROCONCEPT_DETAIL')}} AS QA_PERSON_ZEROCONCEPT_DETAIL 

--PROCEDURE_OCCURRENCE
UNION SELECT  * FROM
{{ref('QA_PROCEDURE_30AFTERDEATH_DETAIL')}} AS QA_PROCEDURE_30AFTERDEATH_DETAIL
UNION SELECT  * FROM
{{ref('QA_PROCEDURE_OCCURRENCE_DATEVDATETIME_DETAIL')}} AS QA_PROCEDURE_OCCURRENCE_DATEVDATETIME_DETAIL
UNION SELECT  * FROM
{{ref('QA_PROCEDURE_OCCURRENCE_DUPLICATES_DETAIL')}} AS QA_PROCEDURE_OCCURRENCE_DUPLICATES_DETAIL
{#UNION SELECT  * FROM
{{ref('xxx')}} AS QA_PROCEDURE_OCCURRENCE_NOMATCH_DETAIL #}
UNION SELECT  * FROM
{{ref('QA_PROCEDURE_OCCURRENCE_NONSTANDARD_DETAIL')}} AS QA_PROCEDURE_OCCURRENCE_NONSTANDARD_DETAIL
UNION SELECT  * FROM
{{ref('QA_PROCEDURE_OCCURRENCE_NOVISIT_DETAIL')}} AS QA_PROCEDURE_OCCURRENCE_NOVISIT_DETAIL
UNION SELECT  * FROM
{{ref('QA_PROCEDURE_OCCURRENCE_NULLCONCEPT_DETAIL')}} AS QA_PROCEDURE_OCCURRENCE_NULLCONCEPT_DETAIL
UNION SELECT  * FROM
{{ref('QA_PROCEDURE_OCCURRENCE_NULLFK_DETAIL')}} AS QA_PROCEDURE_OCCURRENCE_NULLFK_DETAIL
UNION SELECT  * FROM
{{ref('QA_PROCEDURE_OCCURRENCE_VISITDATEDISPARITY_DETAIL')}} AS QA_PROCEDURE_OCCURRENCE_VISITDATEDISPARITY_DETAIL
UNION SELECT  * FROM
{{ref('QA_PROCEDURE_OCCURRENCE_ZEROCONCEPT_DETAIL')}} AS QA_PROCEDURE_OCCURRENCE_ZEROCONCEPT_DETAIL

--PROVIDER
UNION SELECT  * FROM
{{ref('QA_PROVIDER_DUPLICATES_DETAIL')}} AS QA_PROVIDER_DUPLICATES_DETAIL
{#UNION SELECT  * FROM
{{ref('xxx')}} AS QA_PROVIDER_NOMATCH_DETAIL #}
UNION SELECT  * FROM
{{ref('QA_PROVIDER_NONSTANDARD_DETAIL')}} AS QA_PROVIDER_NONSTANDARD_DETAIL 
UNION SELECT  * FROM
{{ref('QA_PROVIDER_NULLFK_DETAIL')}} AS QA_PROVIDER_NULLFK_DETAIL
UNION SELECT  * FROM
{{ref('QA_PROVIDER_NULL_CONCEPT_DETAIL')}} AS QA_PROVIDER_NULL_CONCEPT_DETAIL
UNION SELECT  * FROM
{{ref('QA_PROVIDER_ZEROCONCEPT_DETAIL')}} AS QA_PROVIDER_ZEROCONCEPT_DETAIL

--SPECIMEN
UNION SELECT  * FROM
{{ref('QA_SPECIMEN_DATEVDATETIME_DETAIL')}} AS QA_SPECIMEN_DATEVDATETIME_DETAIL
UNION SELECT  * FROM
{{ref('QA_SPECIMEN_DUPLICATES_DETAIL')}} AS QA_SPECIMEN_DUPLICATES_DETAIL
{#UNION SELECT  * FROM
{{ref('xxx')}} AS QA_SPECIMEN_NOMATCH_DETAIL #}
UNION SELECT  * FROM
{{ref('QA_SPECIMEN_NONSTANDARD_DETAIL')}} AS QA_SPECIMEN_NONSTANDARD_DETAIL
UNION SELECT  * FROM
{{ref('QA_SPECIMEN_NULLCONCEPT_DETAIL')}} AS QA_SPECIMEN_NULLCONCEPT_DETAIL
UNION SELECT  * FROM
{{ref('QA_SPECIMEN_ZEROCONCEPT_DETAIL')}} AS QA_SPECIMEN_ZEROCONCEPT_DETAIL

--VISIT_OCCURRENCE
UNION SELECT  * FROM
{{ref('QA_VISIT_30AFTERDEATH_DETAIL')}} AS QA_VISIT_30AFTERDEATH_DETAIL
UNION SELECT  * FROM
{{ref('QA_VISIT_DATEVDATETIME_DETAIL')}} AS QA_VISIT_DATEVDATETIME_DETAIL
UNION SELECT  * FROM
{{ref('QA_VISIT_OCCURRENCE_DUPLICATES_DETAIL')}} AS QA_VISIT_OCCURRENCE_DUPLICATES_DETAIL
UNION SELECT  * FROM
{{ref('QA_VISIT_OCCURRENCE_END_BEFORE_START_DETAIL')}} AS QA_VISIT_OCCURRENCE_END_BEFORE_START_DETAIL
{# UNION SELECT  * FROM
{{ref('xxx')}} AS QA_VISIT_OCCURRENCE_NOMATCH_DETAIL #}
UNION SELECT  * FROM
{{ref('QA_VISIT_OCCURRENCE_NONSTANDARD_DETAIL')}} AS QA_VISIT_OCCURRENCE_NONSTANDARD_DETAIL
UNION SELECT  * FROM
{{ref('QA_VISIT_OCCURRENCE_NULLCONCEPT_DETAIL')}} AS QA_VISIT_OCCURRENCE_NULLCONCEPT_DETAIL
UNION SELECT  * FROM
{{ref('QA_VISIT_OCCURRENCE_NULLFK_DETAIL')}} AS QA_VISIT_OCCURRENCE_NULLFK_DETAIL
UNION SELECT  * FROM
{{ref('QA_VISIT_OCCURRENCE_ZEROCONCEPT_DETAIL')}} AS QA_VISIT_OCCURRENCE_ZEROCONCEPT_DETAIL 

{# -- DUP PAT_IDs
UNION SELECT  * FROM
{{ref('xxx')}} AS QA_AOU_DRIVER_PROD_DUPLICATES_DETAIL #}


