----------------------------------
-- PULL_DRUG_EXPOSURE_HOSP_V_RX_CHARGES
----------------------------------
{#-- {{ config(materialized = 'view', schema = 'OMOP_PULL') }}#}

SELECT DISTINCT
-- ***STAGE ATTRIBUTES***
-- OMOP Standard fields used for the StagePULL_VISIT_OCCURRENCE_HSP.PERSON_ID
	PULL_VISIT_OCCURRENCE_HSP.PERSON_ID 								AS PERSON_ID
	,MAR_ADMIN_INFO.TAKEN_TIME::DATE 									AS DRUG_EXPOSURE_START_DATE
	,MAR_ADMIN_INFO.TAKEN_TIME 											AS DRUG_EXPOSURE_START_DATETIME
	,CAST(CASE
		WHEN (COALESCE(ORDER_END_TIME, TAKEN_TIME)::DATE = TAKEN_TIME::DATE)
			AND (COALESCE(ORDER_END_TIME, TAKEN_TIME) < TAKEN_TIME)
			THEN TAKEN_TIME
			ELSE
			COALESCE(ORDER_END_TIME, TAKEN_TIME)
		END
			AS DATE) 													AS DRUG_EXPOSURE_END_DATE
	,CASE
		WHEN (COALESCE(ORDER_END_TIME, TAKEN_TIME)::DATE = TAKEN_TIME::DATE)
			AND (COALESCE(ORDER_END_TIME, TAKEN_TIME) < TAKEN_TIME)
			THEN TAKEN_TIME
			ELSE
			COALESCE(ORDER_END_TIME, TAKEN_TIME)
		END 															AS DRUG_EXPOSURE_END_DATETIME
	,ORDER_MED.END_DATE 												AS VERBATIM_END_DATE
	,LEFT(ZC_RSN_FOR_DISCON_NAME, 20) 									AS STOP_REASON
    ,CASE
		WHEN TRY_CAST(ORDER_MED.REFILLS AS NUMERIC) IS NULL
			THEN NULL
		ELSE  ORDER_MED.REFILLS
		END 															AS REFILLS
    ,CASE
		WHEN V_RX_CHARGES.CHARGED_QTY_UNIT_NAME IN ('UNITS','MILLIGRAMS')
            THEN V_RX_CHARGES.CHARGED_QTY
		WHEN V_RX_CHARGES.CHARGED_QTY_UNIT_NAME IN ('MILLILITERS', 'ML','GRAMS')
            THEN V_RX_CHARGES.IMPLIED_QTY
	    END                                                             AS QUANTITY
	,NULL 																AS DAYS_SUPPLY
	,ORDER_MED_SIG.SIG_TEXT 											AS SIG
	,NULL 																AS LOT_NUMBER
	,ORDER_MED.AUTHRZING_PROV_ID										AS PROVIDER_SOURCE_VALUE
	,ZC_MED_UNIT_NAME 													AS DOSE_UNIT_SOURCE_VALUE

-- ***ADDITIONAL ATTRIBUTES***
-- Non_OMOP fields used for the Stage
	,PULL_VISIT_OCCURRENCE_HSP.PULL_CSN_ID 								AS PULL_CSN_ID
	,CLARITY_MEDICATION.MEDICATION_ID									AS PULL_MEDICATION_ID
	,CLARITY_MEDICATION.NAME 											AS PULL_MEDICATION_NAME
	,ORDER_MED.MED_ROUTE_C												AS PULL_MED_ROUTE_C
	,ZC_ADMIN_ROUTE.ZC_ADMIN_ROUTE_NAME									AS PULL_ZC_ADMIN_ROUTE_NAME
	,RXNORM_CODES.RXNORM_CODE 											AS PULL_RXNORM_CODE
	,RXNORM_CODES.LINE 													AS PULL_RXNORM_CODES_LINE


-- ***SOURCE ATTRIBUTES***
-- field names pulled from the source for verification purposes.
	-- ,ORDER_MED.AUTHRZING_PROV_ID
	-- ,MAR_ADMIN_INFO.TAKEN_TIME
	-- ,ORDER_MED.ORDER_END_TIME
	-- ,ORDER_MED.ORDER_START_TIME
	-- ,RXNORM_CODES.RXNORM_CODE
	-- ,RXNORM_CODES.RXNORM_TERM_TYPE_C
	-- ,ZC_RXNORM_TERM_TYPE.NAME AS ZC_RXNORM_TERM_TYPE_name
	-- ,END_DATE
	-- ,ORDER_MED.RSN_FOR_DISCON_C
	-- ,ZC_RSN_FOR_DISCON.NAME AS ZC_RSN_FOR_DISCON_name
	-- ,REFILLS

	-- ,ZC_MED_UNIT.NAME AS ZC_MED_UNIT_NAME
	-- ,MAR_ADMIN_INFO.SIG
	-- ,MAR_ADMIN_INFO.LINE AS MAR_ADMIN_INFO_LINE
	-- ,EDITED_LINE
	-- ,MAR_ACTION_C
	-- ,REASON_C
	-- ,MAR_ENC_CSN
	-- ,RXNORM_CODES.LINE AS RXNORM_CODES_LINE
	-- ,MAR_ADMIN_INFO.ORDER_MED_ID
	-- ,CLARITY_MEDICATION.medication_ID
	-- ,CLARITY_MEDICATION.NAME AS CLARITY_MEDICATION_NAME
	-- ,ORDER_MED.MED_ROUTE_C
	-- ,ZC_ADMIN_ROUTE.NAME AS ZC_ADMIN_ROUTE_NAME
	-- ,ORDER_STATUS_C
    -- ,V_RX_CHARGES.UCL_ID 								--included for troubleshooting and to maintain granularity, if exclude and pt has multiple admins on same date of service the granularity can get messed up
	-- , V_RX_CHARGES.SERVICE_DATE
	-- , V_RX_CHARGES.ORDER_ID
	-- , V_RX_CHARGES.ORDER_NAME
	-- , V_RX_CHARGES.BILLING_QUANTITY 					-- this is hcpcs billing quantity, so for the bevacizumab order id below a billing unit is 10mg, 10mg*35 units = total of 350mg
	-- , V_RX_CHARGES.IMPLIED_QTY 						-- quantity of dosage forms - tabs, vials, etc.
	-- , V_RX_CHARGES.IMPLIED_QTY_UNIT_NAME
	-- , V_RX_CHARGES.IMPLIED_QTY_DESC 					-- combined field of previous two, also exist independently in RX_NDC table
	-- , V_RX_CHARGES.CHARGED_QTY 						-- RX_NDC charged quantity, found in CLARITY_UCL item 259
	-- , V_RX_CHARGES.CHARGED_QTY_UNIT_NAME
	-- , V_RX_CHARGES.MEDICATION_ID as V_RX_CHARGES_MEDICATION_ID
	-- , V_RX_CHARGES.NDC_CODE
	-- , RX_NDC.RAW_11_DIGIT_NDC
	-- , V_RX_CHARGES.NDC_CODE_PACKAGE_SIZE
	-- , CLARITY_UCL.EPT_CSN 							-- link to any encounter details
	-- , CLARITY_UCL.HOSPITAL_ACCOUNT_ID 				-- link to har and any billing/coverage details if desired
	-- ,'PULL_DRUG_EXPOSURE--CLARITYHOSP--V_RX_CHARGES' AS ETL_Module

FROM {{ref('PULL_VISIT_OCCURRENCE_HSP')}} AS PULL_VISIT_OCCURRENCE_HSP

INNER JOIN {{ ref('ORDER_MED_stg')}} AS ORDER_MED
	ON ORDER_MED.PAT_ENC_CSN_ID =  PULL_VISIT_OCCURRENCE_HSP.PULL_CSN_ID

LEFT JOIN {{ ref('ORDER_MED_SIG_stg')}} AS ORDER_MED_SIG
	ON ORDER_MED.ORDER_MED_ID = ORDER_MED_SIG.ORDER_ID

INNER JOIN {{ ref('V_RX_CHARGES_stg')}} AS V_RX_CHARGES
			ON ORDER_MED.ORDER_MED_ID = V_RX_CHARGES.ORDER_ID

INNER JOIN {{ ref('CLARITY_MEDICATION_stg')}} AS CLARITY_MEDICATION
	ON ORDER_MED.MEDICATION_ID = CLARITY_MEDICATION.MEDICATION_ID

INNER JOIN {{ ref('MAR_ADMIN_INFO_stg')}} AS MAR_ADMIN_INFO
	ON ORDER_MED.ORDER_MED_ID = MAR_ADMIN_INFO.ORDER_MED_ID

INNER JOIN {{ ref('ZC_MED_UNIT_stg')}} AS ZC_MED_UNIT
	ON ORDER_MED.HV_DOSE_UNIT_C = ZC_MED_UNIT.DISP_QTYUNIT_C

LEFT JOIN {{ ref('ZC_RSN_FOR_DISCON_stg')}} AS ZC_RSN_FOR_DISCON
	ON ORDER_MED.RSN_FOR_DISCON_C = ZC_RSN_FOR_DISCON.RSN_FOR_DISCON_C

LEFT JOIN {{ref('ZC_ADMIN_ROUTE_stg')}} AS ZC_ADMIN_ROUTE
	ON ORDER_MED.MED_ROUTE_C = ZC_ADMIN_ROUTE.MED_ROUTE_C

INNER JOIN {{ ref('RXNORM_CODES_stg')}} AS RXNORM_CODES
	ON ORDER_MED.MEDICATION_ID = RXNORM_CODES.MEDICATION_ID

INNER JOIN {{ ref('ZC_RXNORM_TERM_TYPE_stg')}} AS ZC_RXNORM_TERM_TYPE
	ON RXNORM_CODES.RXNORM_TERM_TYPE_C = ZC_RXNORM_TERM_TYPE.RXNORM_TERM_TYPE_C

-------New Quantity Data---------------------------
	LEFT JOIN {{ ref('CLARITY_UCL_stg')}} AS CLARITY_UCL
            ON V_RX_CHARGES.UCL_ID =CLARITY_UCL.UCL_ID

	LEFT JOIN {{ ref('RX_NDC_STATUS_stg')}} AS 	RX_NDC_STATUS
            ON V_RX_CHARGES.DISP_NDC_CSN = RX_NDC_STATUS.CNCT_SERIAL_NUM

	LEFT JOIN {{ ref('RX_NDC_stg')}} AS	RX_NDC
            ON RX_NDC_STATUS.NDC_ID = RX_NDC.NDC_ID
-------------------------------------------------

WHERE TAKEN_TIME IS NOT NULL

	AND ORDER_STATUS_C NOT IN (
		4 --4 - CANCELED
		,6 --6 - HOLDING
		,7 --7 - DENIED
		,8 --8 - SUSPEND
		,9 --9 - DISCONTINUED
		)
	AND MAR_ACTION_C NOT IN (
		2 --2 - Missed
		,4 --4 - Canceled Entry
		,8 --8 - Stopped
		,15 --15 - See Alternative
		)
