
-------------------------------
--PULL_DRUG_EXPOSURE_AMB_RXNORM
-------------------------------
{#-- {{ config(materialized = 'view', schema = 'OMOP_PULL') }}#}
SELECT DISTINCT
-- ***STAGE ATTRIBUTES***
-- OMOP Standard fields used for the Stage
	PULL_VISIT_OCCURRENCE_AMB.PERSON_ID 							    AS PERSON_ID
	,ORDER_START_TIME::DATE                                             AS DRUG_EXPOSURE_START_DATE
	,ORDER_START_TIME                                           		AS DRUG_EXPOSURE_START_DATETIME
	,CAST(CASE
		WHEN (COALESCE(ORDER_END_TIME, ORDER_START_TIME)::DATE = ORDER_START_TIME::DATE)
			AND (COALESCE(ORDER_END_TIME, ORDER_START_TIME) < ORDER_START_TIME)
			THEN ORDER_START_TIME
			ELSE
			COALESCE(ORDER_END_TIME, ORDER_START_TIME)
		END
			AS DATE)													AS DRUG_EXPOSURE_END_DATE
	,CASE
		WHEN (COALESCE(ORDER_END_TIME, ORDER_START_TIME)::DATE = ORDER_START_TIME::DATE)
			AND (COALESCE(ORDER_END_TIME, ORDER_START_TIME) < ORDER_START_TIME)
			THEN ORDER_START_TIME
			ELSE
			COALESCE(ORDER_END_TIME, ORDER_START_TIME)
		END 															AS DRUG_EXPOSURE_END_DATETIME
	,END_DATE 															AS VERBATIM_END_DATE
	,LEFT(ZC_RSN_FOR_DISCON_NAME, 20) 									AS STOP_REASON
      ,	CASE
		WHEN TRY_CAST(REFILLS AS NUMERIC) IS NULL
			THEN NULL
		ELSE  REFILLS
		END 															AS REFILLS
	,CASE
		WHEN TRY_TO_NUMERIC(LEFT(QUANTITY, CHARINDEX(' ', QUANTITY))) IS  NULL
			OR UPPER(ZC_MED_UNIT_NAME) = 'APPLICATION'
			THEN 1
		ELSE LEFT(QUANTITY, CHARINDEX(' ', QUANTITY))::FLOAT
		END 															AS QUANTITY
	,NULL 																AS DAYS_SUPPLY
	,SIG 																AS SIG
	,NULL 																AS LOT_NUMBER
	,ORDER_MED.AUTHRZING_PROV_ID										AS PROVIDER_SOURCE_VALUE
	,ZC_MED_UNIT_NAME 													AS DOSE_UNIT_SOURCE_VALUE

-- ***ADDITIONAL ATTRIBUTES***
-- Non_OMOP fields used for the Stage
	,PULL_VISIT_OCCURRENCE_AMB.PULL_CSN_ID 								AS PULL_CSN_ID
	,CLARITY_MEDICATION.MEDICATION_ID 									AS PULL_MEDICATION_ID
	,CLARITY_MEDICATION.NAME 											AS PULL_MEDICATION_NAME
	,ORDER_MED.MED_ROUTE_C												AS PULL_MED_ROUTE_C
	,ZC_ADMIN_ROUTE.ZC_ADMIN_ROUTE_NAME									AS PULL_ZC_ADMIN_ROUTE_NAME
    ,RXNORM_CODES.RXNORM_CODE 											AS PULL_RXNORM_CODE
    ,RXNORM_CODES.LINE 													AS PULL_RXNORM_CODES_LINE


-- ***SOURCE ATTRIBUTES***
-- field names pulled from the source for verification purposes. May be duplicated above.

-- --    ,PULL_VISIT_OCCURRENCE_AMB.EHR_PATIENT_ID
-- --    ,PULL_VISIT_OCCURRENCE_AMB.PAT_ID
--     ,PULL_VISIT_OCCURRENCE_AMB.PAT_ENC_CSN_ID
-- --    ,PULL_VISIT_OCCURRENCE_AMB.HSP_ACCOUNT_ID
-- --    ,PULL_VISIT_OCCURRENCE_AMB.IP_DOC_CONTACT_CSN
--     ,PULL_VISIT_OCCURRENCE_AMB.ENC_TYPE_C
--     ,PULL_VISIT_OCCURRENCE_AMB.ZC_DISP_ENC_TYPE_NAME
-- --    ,PULL_VISIT_OCCURRENCE_AMB.PAT_OR_ADM_LINK_CSN AS PAT_OR_ADM_LINK_PAT_ENC_CSN_ID
--     ,ORDER_MED.ORDER_END_TIME
--     ,ORDER_MED.ORDER_START_TIME
--     ,ORDER_MED.END_DATE
--     ,ORDER_MED.RSN_FOR_DISCON_C
--     ,ORDER_MED.REFILLS
--     ,ORDER_MED.QUANTITY
--     ,ORDER_MED.AUTHRZING_PROV_ID
--     ,ORDER_MED.MED_ROUTE_C
--     ,ORDER_MED.ORDER_STATUS_C
--     ,REPLACE(ORDER_MED.SIG,'\\',' ') AS SIG
--     ,CLARITY_MEDICATION.MEDICATION_ID
--     ,CLARITY_MEDICATION.CLARITY_MEDICATION_NAME
--     , ZC_RXNORM_TERM_TYPE_NAME
--     ,ZC_RSN_FOR_DISCON_NAME
--     ,ZC_MED_UNIT_NAME AS ZC_MED_UNIT_NAME
--     ,ZC_ADMIN_ROUTE_NAME AS ZC_ADMIN_ROUTE_NAME
--     ,'PULL_DRUG_EXPOSURE--CLARITYAMB--RXNORM' AS ETL_MODULE

FROM {{ref('PULL_VISIT_OCCURRENCE_AMB')}} AS PULL_VISIT_OCCURRENCE_AMB

INNER JOIN {{ ref('ORDER_MED_stg')}} AS ORDER_MED
    ON ORDER_MED.PAT_ENC_CSN_ID =  PULL_VISIT_OCCURRENCE_AMB.PULL_CSN_ID

INNER JOIN {{ ref('CLARITY_MEDICATION_stg')}} AS CLARITY_MEDICATION
    ON ORDER_MED.MEDICATION_ID = CLARITY_MEDICATION.MEDICATION_ID

INNER JOIN {{ ref('RXNORM_CODES_stg')}} AS RXNORM_CODES
    ON ORDER_MED.MEDICATION_ID = RXNORM_CODES.MEDICATION_ID

INNER JOIN {{ ref('ZC_MED_UNIT_stg')}} AS ZC_MED_UNIT
    ON ORDER_MED.HV_DOSE_UNIT_C = ZC_MED_UNIT.DISP_QTYUNIT_C

LEFT JOIN {{ ref('ZC_RSN_FOR_DISCON_stg')}} AS ZC_RSN_FOR_DISCON
    ON ORDER_MED.RSN_FOR_DISCON_C = ZC_RSN_FOR_DISCON.RSN_FOR_DISCON_C

LEFT JOIN {{ref('ZC_ADMIN_ROUTE_stg')}} AS ZC_ADMIN_ROUTE
    ON ORDER_MED.MED_ROUTE_C = ZC_ADMIN_ROUTE.MED_ROUTE_C

INNER JOIN {{ ref('ZC_RXNORM_TERM_TYPE_stg')}} AS ZC_RXNORM_TERM_TYPE
    ON RXNORM_CODES.RXNORM_TERM_TYPE_C = ZC_RXNORM_TERM_TYPE.RXNORM_TERM_TYPE_C

WHERE ORDER_MED.ORDER_START_TIME IS NOT NULL
    AND PULL_VISIT_OCCURRENCE_AMB.PULL_ENC_TYPE_C <> 3
    AND ORDER_STATUS_C NOT IN (
        4 --4 - CANCELED
        ,6 --6 - HOLDING
        ,7 --7 - DENIED
        ,8 --8 - SUSPEND
        ,9 --9 - DISCONTINUED
        )
	AND  RXNORM_CODES.RXNORM_TERM_TYPE_C <> 2 --2 - PRECISE INGREDIENT



