--------------------------------
--PULL_DRUG_EXPOSURE_ANES_RXNORM
--------------------------------
--  {{ config(materialized = 'view', schema = 'OMOP_PULL') }}
SELECT DISTINCT 
-- ***STAGE ATTRIBUTES***
-- OMOP Standard fields used for the Stage
	 PULL_VISIT_OCCURRENCE_HSP.PERSON_ID						AS PERSON_ID
	,MAR_ADMIN_INFO.TAKEN_TIME::DATE 							AS DRUG_EXPOSURE_START_DATE
	,MAR_ADMIN_INFO.TAKEN_TIME 									AS DRUG_EXPOSURE_START_DATETIME
	,CAST(CASE
		WHEN (COALESCE(AN_STOP_DATETIME, TAKEN_TIME)::DATE = TAKEN_TIME::DATE)
			AND (COALESCE(AN_STOP_DATETIME, TAKEN_TIME) < TAKEN_TIME)
			THEN TAKEN_TIME
			ELSE
			COALESCE(AN_STOP_DATETIME, TAKEN_TIME)
		END 
		AS DATE)												AS DRUG_EXPOSURE_END_DATE
	,CASE
		WHEN (COALESCE(AN_STOP_DATETIME, TAKEN_TIME)::DATE = TAKEN_TIME::DATE)
			AND (COALESCE(AN_STOP_DATETIME, TAKEN_TIME) < TAKEN_TIME)
			THEN TAKEN_TIME
			ELSE
			COALESCE(AN_STOP_DATETIME, TAKEN_TIME)
		END 													AS DRUG_EXPOSURE_END_DATETIME
	,F_AN_RECORD_SUMMARY.AN_STOP_DATETIME 						AS VERBATIM_END_DATE

	,LEFT(ZC_RSN_FOR_DISCON_NAME, 20) 							AS STOP_REASON
	,NULL 														AS REFILLS
	,CASE
		WHEN TRY_TO_NUMERIC(LEFT(QUANTITY, CHARINDEX(' ', QUANTITY))) IS NULL
			THEN 1
		ELSE LEFT(QUANTITY, CHARINDEX(' ', QUANTITY))::FLOAT
		END 													AS QUANTITY
	,NULL 														AS DAYS_SUPPLY
	,MAR_ADMIN_INFO.SIG 										AS SIG
	,NULL 														AS LOT_NUMBER
	,COALESCE(
			F_AN_RECORD_SUMMARY.AN_RESP_PROV_ID
			,ORDER_MED.AUTHRZING_PROV_ID) 						AS PROVIDER_SOURCE_VALUE
--    ,VISIT_DETAIL.VISIT_DETAIL_ID AS VISIT_DETAIL_ID
    ,0 															AS VISIT_DETAIL_ID
	,DOSE_UNIT.ZC_MED_UNIT_NAME									AS DOSE_UNIT_SOURCE_VALUE
	,'DRUG_EXPOSURE--CLARITYANES--RXNORM' 						AS ETL_MODULE

-- ***ADDITIONAL ATTRIBUTES***
-- Non_OMOP fields used for the Stage
	, PULL_VISIT_OCCURRENCE_HSP.PULL_CSN_ID 					AS PULL_CSN_ID
	,CLARITY_MEDICATION.MEDICATION_ID 							AS PULL_MEDICATION_ID
	,CLARITY_MEDICATION.NAME 									AS PULL_MEDICATION_NAME
	,MAR_ADMIN_INFO.ROUTE_C										AS PULL_MED_ROUTE_C	
	,ZC_ADMIN_ROUTE.ZC_ADMIN_ROUTE_NAME 						AS PULL_ZC_ADMIN_ROUTE_NAME
	,RXNORM_CODES.RXNORM_CODE									AS PULL_RXNORM_CODE
	,RXNORM_CODES.LINE 											AS PULL_RXNORM_CODES_LINE


-- ***PULL attributes***
-- field names pulled from the source for verification purposes. May be duplicated above.

	-----HOSPITAL ENCOUNTER---------
	-- ,PULL_VISIT_OCCURRENCE_HSP.PAT_ENC_CSN_ID
	-- ,AN_PAT_ID
	-- ,AN_53_ENC_CSN_ID
	-- ,AN_INPATIENT_DATA_ID
	-- ,AN_LOG_ID
	-- ,F_AN_RECORD_SUMMARY.AN_52_ENC_CSN_ID
	-- ,F_AN_RECORD_SUMMARY.AN_RESP_PROV_ID
	-- ,F_AN_RECORD_SUMMARY.AN_START_DATETIME
	-- ,F_AN_RECORD_SUMMARY.AN_STOP_DATETIME
	-- ,F_AN_RECORD_SUMMARY.AN_PROC_NAME
	-- ,ORDER_MED.AUTHRZING_PROV_ID
	-- ,ORDER_MED.RSN_FOR_DISCON_C
	-- ,ORDER_MED.QUANTITY
	-- ,ORDER_MED.ORDER_STATUS_C
	-- ,MAR_ADMIN_INFO.TAKEN_TIME
	-- ,MAR_ADMIN_INFO.INFUSION_RATE
	-- ,MAR_ADMIN_INFO.MAR_INF_RATE_UNIT_C
	-- ,MAR_ADMIN_INFO.SIG
	-- ,MAR_ADMIN_INFO.LINE AS MAR_ADMIN_INFO_LINE
	-- ,MAR_ADMIN_INFO.MAR_ACTION_C
	-- ,MAR_ADMIN_INFO.REASON_C
	-- ,MAR_ADMIN_INFO.DOSE_UNIT_C
	-- ,MAR_ADMIN_INFO.MAR_ENC_CSN
	-- ,MAR_ADMIN_INFO.ROUTE_C
	-- ,MAR_ADMIN_INFO.ORDER_MED_ID
	-- ,CLARITY_MEDICATION.MEDICATION_ID
	-- ,CLARITY_MEDICATION_NAME AS CLARITY_MEDICATION_NAME
	-- ,RXNORM_CODES.RXNORM_TERM_TYPE_C
	-- ,ZC_MAR_RSLT_NAME AS MAR_ACTION_NAME
	-- ,ZC_RXNORM_TERM_TYPE_NAME
	-- ,ZC_RSN_FOR_DISCON_NAME
	-- ,INF_RATE.ZC_MED_UNIT_NAME AS INFUSION_RATE_UNIT_NAME
	-- ,DOSE_UNIT.ZC_MED_UNIT_NAME AS DOSE_UNIT_NAME
	-- ,ZC_MAR_RSN_NAME AS MAR_REASON_NAME
	-- ,ZC_ADMIN_ROUTE_NAME AS ZC_ADMIN_ROUTE_NAME

	-- ,'PULL_DRUG_EXPOSURE--CLARITYANES--RXNORM' AS ETL_MODULE

FROM {{ref('PULL_VISIT_OCCURRENCE_HSP')}} AS PULL_VISIT_OCCURRENCE_HSP

-- ASSOCIATES ANETHESIA RECORD TO HOSPITAL ENCOUNTER
INNER JOIN {{ ref('AN_HSB_LINK_INFO_stg')}} AS AN_HSB_LINK_INFO
	ON AN_HSB_LINK_INFO.AN_BILLING_CSN_ID = PULL_VISIT_OCCURRENCE_HSP.PULL_CSN_ID

INNER JOIN {{ ref('F_AN_RECORD_SUMMARY_stg')}} AS F_AN_RECORD_SUMMARY
	ON F_AN_RECORD_SUMMARY.AN_EPISODE_ID = AN_HSB_LINK_INFO.SUMMARY_BLOCK_ID

INNER JOIN {{ ref('MAR_ADMIN_INFO_stg')}} AS MAR_ADMIN_INFO
	ON F_AN_RECORD_SUMMARY.AN_52_ENC_CSN_ID = MAR_ADMIN_INFO.MAR_ENC_CSN

INNER JOIN {{ ref('ORDER_MED_stg')}} AS ORDER_MED
	ON ORDER_MED.ORDER_MED_ID = MAR_ADMIN_INFO.ORDER_MED_ID

INNER JOIN {{ ref('CLARITY_MEDICATION_stg')}} AS CLARITY_MEDICATION
	ON ORDER_MED.MEDICATION_ID = CLARITY_MEDICATION.MEDICATION_ID

LEFT JOIN {{ ref('ZC_RSN_FOR_DISCON_stg')}} AS ZC_RSN_FOR_DISCON
	ON ORDER_MED.RSN_FOR_DISCON_C = ZC_RSN_FOR_DISCON.RSN_FOR_DISCON_C

LEFT JOIN {{ref('ZC_ADMIN_ROUTE_stg')}} AS ZC_ADMIN_ROUTE
	ON MAR_ADMIN_INFO.ROUTE_C = ZC_ADMIN_ROUTE.MED_ROUTE_C

LEFT JOIN {{ ref('ZC_MED_UNIT_stg')}} AS INF_RATE
	ON MAR_ADMIN_INFO.MAR_INF_RATE_UNIT_C = INF_RATE.DISP_QTYUNIT_C

LEFT JOIN {{ ref('ZC_MED_UNIT_stg')}} AS DOSE_UNIT
	ON MAR_ADMIN_INFO.DOSE_UNIT_C = DOSE_UNIT.DISP_QTYUNIT_C

LEFT JOIN {{ ref('ZC_MAR_RSLT_stg')}} AS ZC_MAR_RSLT
	ON MAR_ADMIN_INFO.MAR_ACTION_C = ZC_MAR_RSLT.RESULT_C

LEFT JOIN {{ ref('ZC_MAR_RSN_stg')}} AS ZC_MAR_RSN
	ON MAR_ADMIN_INFO.REASON_C = ZC_MAR_RSN.REASON_C

INNER JOIN {{ ref('RXNORM_CODES_stg')}} AS RXNORM_CODES
	ON ORDER_MED.MEDICATION_ID = RXNORM_CODES.MEDICATION_ID

INNER JOIN {{ ref('ZC_RXNORM_TERM_TYPE_stg')}} AS ZC_RXNORM_TERM_TYPE
	ON RXNORM_CODES.RXNORM_TERM_TYPE_C = ZC_RXNORM_TERM_TYPE.RXNORM_TERM_TYPE_C

WHERE MAR_ACTION_C = 1
	AND  RXNORM_CODES.RXNORM_TERM_TYPE_C <> 2 --2 - PRECISE INGREDIENT
