
--PULL_DRUG_EXPOSURE_ALL_IMM
{#-- {{ config(materialized = 'view', schema = 'OMOP_PULL') }}#}
--
SELECT
-- ***STAGE ATTRIBUTES***
-- OMOP Standard fields used for the Stage
    PATIENT_DRIVER.PERSON_ID 						        AS PERSON_ID
    , IMMUNE.IMMUNE_DATE::DATE 				                AS DRUG_EXPOSURE_START_DATE
	, COALESCE(IMMUNE.IMMUNIZATION_TIME
            , IMMUNE.IMMUNE_DATE)::DATETIME    		        AS DRUG_EXPOSURE_START_DATETIME
	-- , IMMUNE.MED_ADMIN_COMMENT						        AS COMMENT
	, ZC_MED_UNIT.ZC_MED_UNIT_NAME						    AS DOSE_UNIT_SOURCE_VALUE
	, LTRIM(RTRIM(LOT))					                    AS LOT_NUMBER
	,ORDER_MED.AUTHRZING_PROV_ID							AS PROVIDER_SOURCE_VALUE

-- ***ADDITIONAL ATTRIBUTES***
-- Non_OMOP fields used for the Stage
	, PAT_ENC.PAT_ENC_CSN_ID 						        AS PULL_CSN_ID
    , IMMUNE.IMMUNE_ID                                      AS PULL_IMMUNE_ID
    , IMMUNE.IMMUNZATN_ID                                   AS PULL_IMMUNZATN_ID
	, CLARITY_IMMUNZATN.IMMUNZATN_ID_NAME				    AS PULL_CLARITY_IMMUNZATN_NAME
	, COALESCE(IMMUNE.ROUTE_C, CLARITY_IMMUNZATN.ROUTE_C)   AS PULL_ROUTE_C
	, ZC_ROUTE.ZC_ROUTE_NAME				                AS PULL_ZC_ROUTE_NAME
	, CLARITY_IMMUNZATN.CVX_CODE				            AS PULL_CLARITY_CVX_CODE
	, RX_NDC.RAW_11_DIGIT_NDC				                AS PULL_RX_NDC_RAW_11_DIGIT_NDC

	FROM {{ref('IMMUNE_stg')}}  AS  IMMUNE
	INNER JOIN {{ref('CLARITY_IMMUNZATN_stg')}} AS  CLARITY_IMMUNZATN  ON IMMUNE.IMMUNZATN_ID = CLARITY_IMMUNZATN.IMMUNZATN_ID
	INNER JOIN {{ref('PAT_ENC_stg')}} AS  PAT_ENC  ON PAT_ENC.PAT_ENC_CSN_ID = IMMUNE.IMM_CSN
	LEFT JOIN {{ref('PAT_ENC_HSP_stg')}} AS  PAT_ENC_HSP  ON PAT_ENC_HSP.PAT_ENC_CSN_ID = IMMUNE.IMM_CSN
	LEFT JOIN {{ref('ZC_MED_UNIT_stg')}} AS  ZC_MED_UNIT  ON IMMUNE.IMMNZTN_DOSE_UNIT_C = ZC_MED_UNIT.DISP_QTYUNIT_C
	LEFT JOIN {{ref('RX_NDC_stg')}} AS  RX_NDC  ON IMMUNE.NDC_NUM_ID = RX_NDC.NDC_ID
	LEFT JOIN {{ref('ORDER_MED_stg')}} AS  ORDER_MED  ON IMMUNE.ORDER_ID = ORDER_MED.ORDER_MED_ID
    LEFT JOIN {{ref('ZC_ROUTE_stg')}} AS ZC_ROUTE  ON COALESCE(IMMUNE.ROUTE_C, CLARITY_IMMUNZATN.ROUTE_C) = ZC_ROUTE.ROUTE_C


	INNER JOIN {{ref('PATIENT_DRIVER')}} AS PATIENT_DRIVER
		ON (PATIENT_DRIVER.EHR_PATIENT_ID = IMMUNE.PAT_ID)

	WHERE IMMUNE.IMMNZTN_STATUS_C = 1 AND ORDER_MED.ORDER_MED_ID IS NULL

