--STAGE_DEVICE_EXPOSURE_HSP_BLOOD
{#-- {{ config(materialized = 'view', schema = 'OMOP_STAGE') }}#}
SELECT DISTINCT

	PULL_DEVICE_EXPOSURE_HOSP_BLOOD.PERSON_ID
	,T_SOURCE_TO_CONCEPT_MAP_DEVICE_BLOOD.TARGET_CONCEPT_ID AS DEVICE_CONCEPT_ID
	,DEVICE_EXPOSURE_START_DATE 							AS DEVICE_EXPOSURE_START_DATE
	,DEVICE_EXPOSURE_START_DATETIME 						AS DEVICE_EXPOSURE_START_DATETIME
	,DEVICE_EXPOSURE_END_DATE 								AS DEVICE_EXPOSURE_END_DATE
	,DEVICE_EXPOSURE_END_DATETIME 							AS DEVICE_EXPOSURE_END_DATETIME
	,32817 													AS DEVICE_TYPE_CONCEPT_ID --INFERRED FROM PROCEDURE CLAIM
	,UNIQUE_DEVICE_ID 										AS UNIQUE_DEVICE_ID
    ,NULL 													AS PRODUCTION_ID --NEW 5.4
	,PULL_DEVICE_EXPOSURE_HOSP_BLOOD.QUANTITY 				AS QUANTITY
	,PROVIDER.PROVIDER_ID 									AS PROVIDER_ID
	,VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID 					AS VISIT_OCCURRENCE_ID
--    ,VISIT_DETAIL.VISIT_DETAIL_ID AS VISIT_DETAIL_ID
    ,0 														AS VISIT_DETAIL_ID
	,DEVICE_SOURCE_VALUE 									AS DEVICE_SOURCE_VALUE
	,0 														AS DEVICE_SOURCE_CONCEPT_ID
    ,0 														AS UNIT_CONCEPT_ID --NEW 5.4
    ,NULL 													AS UNIT_SOURCE_VALUE --NEW 5.4
    ,0 														AS UNIT_SOURCE_CONCEPT_ID --NEW 5.4
	-------- Non-OMOP Fields ------------
	,'DEVICE_EXPOSURE_HSP_BLOODD' 							AS ETL_MODULE
    ,PULL_DEVICE_EXPOSURE_HOSP_BLOOD.PULL_PROC_ID           AS STAGE_PROC_ID
	,VISIT_OCCURRENCE.phi_PAT_ID							AS STAGE_PAT_ID
    ,VISIT_OCCURRENCE.phi_MRN_CPI							AS STAGE_MRN_CPI
	,VISIT_OCCURRENCE.phi_CSN_ID							AS STAGE_CSN_ID

FROM {{ref('PULL_DEVICE_EXPOSURE_HOSP_BLOOD')}} AS PULL_DEVICE_EXPOSURE_HOSP_BLOOD

INNER JOIN {{ ref('SOURCE_TO_CONCEPT_MAP_DEVICE_BLOOD')}} AS T_SOURCE_TO_CONCEPT_MAP_DEVICE_BLOOD
  ON PULL_DEVICE_EXPOSURE_HOSP_BLOOD.PULL_PROC_ID = T_SOURCE_TO_CONCEPT_MAP_DEVICE_BLOOD.SOURCE_CODE

INNER JOIN {{ref('VISIT_OCCURRENCE_RAW')}} AS VISIT_OCCURRENCE
	ON PULL_DEVICE_EXPOSURE_HOSP_BLOOD.PULL_CSN_ID = VISIT_OCCURRENCE.phi_CSN_ID

INNER JOIN {{ref('PROVIDER_RAW')}} AS PROVIDER
	ON PULL_DEVICE_EXPOSURE_HOSP_BLOOD.PROVIDER_SOURCE_VALUE = PROVIDER.PROVIDER_SOURCE_VALUE
