{{ config(materialized='ephemeral') }}
--BEGIN cte__T_PROCEDURE_CONCEPT
    SELECT C2.CONCEPT_ID AS CONCEPT_ID
        ,C1.CONCEPT_ID AS SOURCE_CONCEPT_ID

    FROM {{ref('CONCEPT_stg')}} AS  C1
    INNER JOIN {{ref('CONCEPT_RELATIONSHIP_stg')}} AS  CR
        ON C1.CONCEPT_ID = CR.CONCEPT_ID_1
            AND UPPER(CR.RELATIONSHIP_ID) = 'MAPS TO'
    INNER JOIN {{ref('CONCEPT_stg')}} AS  C2
        ON C2.CONCEPT_ID = CR.CONCEPT_ID_2
    WHERE C2.STANDARD_CONCEPT = 'S'
        AND UPPER(C2.DOMAIN_ID) = 'PROCEDURE'
--END cte__T_PROCEDURE_CONCEPT
--
