{{ config(materialized='ephemeral') }}
--BEGIN cte__SOURCE_TO_CONCEPT_MAP_AMB_VISIT
    SELECT *
    FROM {{ref('SOURCE_TO_CONCEPT_MAP_stg')}}
    WHERE SOURCE_VOCABULARY_ID = 'SH_AMB_F2F'
--END cte__SOURCE_TO_CONCEPT_MAP_AMB_VISIT
--
