
--DEVICE_EXPOSURE
 {{ config(materialized = 'view', schema = 'OMOP') }}

SELECT DISTINCT
      DEVICE_EXPOSURE_ID
    , PERSON_ID
    , DEVICE_CONCEPT_ID
    , DEVICE_EXPOSURE_START_DATE
    , DEVICE_EXPOSURE_START_DATETIME
    , DEVICE_EXPOSURE_END_DATE
    , DEVICE_EXPOSURE_END_DATETIME
    , DEVICE_TYPE_CONCEPT_ID
    , UNIQUE_DEVICE_ID
    , PRODUCTION_ID --NEW 5.4
    , QUANTITY
    , PROVIDER_ID
    , VISIT_OCCURRENCE_ID
    , VISIT_DETAIL_ID
    , DEVICE_SOURCE_VALUE --Human readable Source Value use src_VALUE_ID below to link
    , DEVICE_SOURCE_CONCEPT_ID
    , UNIT_CONCEPT_ID --NEW 5.4
    , UNIT_SOURCE_VALUE --NEW 5.4
    , UNIT_SOURCE_CONCEPT_ID --NEW 5.4

 ------Non OMOP fields -----------
    , ETL_MODULE
    , phi_PAT_ID
    , phi_MRN_CPI
    , phi_CSN_ID
----- Link to source
    , src_TABLE
    , src_FIELD
    , src_VALUE_ID

FROM
     {{ref('DEVICE_EXPOSURE_RAW')}} AS DEVICE_EXPOSURE

LEFT JOIN (
    SELECT CDT_ID
    FROM {{ref('QA_ERR_DBT')}}
    WHERE (STANDARD_DATA_TABLE = 'DEVICE_EXPOSURE')
        AND (ERROR_TYPE IN ('FATAL', 'INVALID DATA'))
    ) AS EXCLUSION_RECORDS
    ON DEVICE_EXPOSURE.DEVICE_EXPOSURE_ID = EXCLUSION_RECORDS.CDT_ID
WHERE (EXCLUSION_RECORDS.CDT_ID IS NULL)
