

{{ config(materialized='table', schema = 'OMOP_PULL',
        cluster_by = ['PULL_CSN_ID']) }}
--PULL_VISIT_OCCURRENCE_HSP  
SELECT DISTINCT
-- ***STAGE ATTRIBUTES***
-- fields used for the Stage
	PATIENT_DRIVER.PERSON_ID::NUMBER(28,0) 						AS PERSON_ID
	,CAST(PAT_ENC_HSP.HOSP_ADMSN_TIME AS DATE) 					AS VISIT_START_DATE
	,PAT_ENC_HSP.HOSP_ADMSN_TIME 								AS VISIT_START_DATETIME
	,CAST(PAT_ENC_HSP.HOSP_DISCH_TIME AS DATE)					AS VISIT_END_DATE
	,PAT_ENC_HSP.HOSP_DISCH_TIME 								AS VISIT_END_DATETIME
	,ZC_PAT_CLASS_NAME											AS VISIT_SOURCE_VALUE	
	,CAST(PAT_ENC_HSP.ADMIT_SOURCE_C AS VARCHAR(10)) || ':' || LEFT(ZC_ADM_SOURCE_NAME, 45) 	AS ADMITTED_FROM_SOURCE_VALUE
	,CAST(PAT_ENC_HSP.DISCH_DISP_C AS VARCHAR(10)) || ':' || LEFT(ZC_DISCH_DISP_NAME, 45) 		AS DISCHARGED_TO_SOURCE_VALUE

-- ***ADDITIONAL ATTRIBUTES***
-- Non-OMOP fields used for the Stage
	,COALESCE(HSP_ACCOUNT.ATTENDING_PROV_ID, HSP_ACCOUNT.REFERRING_PROV_ID)  AS PULL_PROVIDER_SOURCE_VALUE
	,PAT_ENC_HSP.HOSPITAL_AREA_ID								AS PULL_CARE_SITE_ID
	,PAT_ENC_HSP.ADT_PAT_CLASS_C								AS PULL_VISIT_SOURCE_CODE
	,PAT_ENC_HSP.ADMIT_SOURCE_C									AS PULL_ADMIT_SOURCE_CODE
	,PAT_ENC_HSP.DISCH_DISP_C									AS PULL_DISCHARGE_SOURCE_CODE
	,PAT_ENC_HSP.HSP_ACCOUNT_ID									AS PULL_HSP_ACCOUNT_ID

-- ***PULL attributes***
-- field names pulled from the source for verification purposes. May be duplicated above.
    ,PATIENT_DRIVER.EHR_PATIENT_ID                      		AS PULL_PAT_ID
    ,PATIENT_DRIVER.MRN_CPI                            			AS PULL_MRN_CPI
	,PAT_ENC_HSP.PAT_ENC_CSN_ID									AS PULL_CSN_ID


/*
	,PATIENT_DRIVER.EHR_PATIENT_ID
	,PAT_ENC_HSP.PAT_ID	
	,PAT_ENC_HSP.ADT_PAT_CLASS_C
	,ZC_PAT_CLASS_NAME AS ADT_PAT_CLASS_NAME
	,PAT_ENC_HSP.HOSP_ADMSN_TIME
	,PAT_ENC_HSP.INP_ADM_DATE
	,PAT_ENC_HSP.EXP_ADMISSION_TIME
	,PAT_ENC_HSP.OP_ADM_DATE
	,PAT_ENC_HSP.EMER_ADM_DATE
	,PAT_ENC_HSP.INSTANT_OF_ENTRY_TM
	,PAT_ENC_HSP.HOSP_DISCH_TIME
	,PAT_ENC_HSP.ED_DISP_TIME
	,PAT_ENC_HSP.HOSPITAL_AREA_ID
	,PAT_ENC_HSP.HSP_ACCOUNT_ID
	,PAT_ENC_HSP.INPATIENT_DATA_ID
	,PAT_ENC_HSP.IP_EPISODE_ID
	,PAT_ENC_HSP.ED_EPISODE_ID
	,PAT_ENC_HSP.ED_DISPOSITION_C
	, ZC_ED_DISPOSITION_NAME AS ED_DISPOSITION_NAME
	,PAT_ENC_HSP.ADMIT_SOURCE_C
	,ZC_ADM_SOURCE_NAME AS ADMIT_SOURCE_NAME
	,PAT_ENC_HSP.DISCH_DISP_C
	,ZC_DISCH_DISP_NAME  AS DISCH_DISP_NAME
	,PAT_ENC_HSP.BILL_ATTEND_PROV_ID
	,PAT_ENC_HSP.ADT_PATIENT_STAT_C
	, ZC_PAT_STATUS_NAME AS ADT_PATIENT_STAT_NAME
	, HSP_ACCOUNT.ATTENDING_PROV_ID
	, HSP_ACCOUNT.REFERRING_PROV_ID
	, HSP_ACCOUNT.ADM_DATE_TIME
	, HSP_ACCOUNT.DISCH_DATE_TIME
*/
FROM  {{ ref('PAT_ENC_HSP_stg')}} AS PAT_ENC_HSP

	LEFT JOIN  {{ ref('ZC_PAT_CLASS_stg')}} AS ZC_PAT_CLASS
		ON PAT_ENC_HSP.ADT_PAT_CLASS_C = ZC_PAT_CLASS.ADT_PAT_CLASS_C

	LEFT JOIN  {{ ref('ZC_PAT_STATUS_stg')}} AS ZC_PAT_STATUS
		ON PAT_ENC_HSP.ADT_PATIENT_STAT_C = ZC_PAT_STATUS.ADT_PATIENT_STAT_C

	LEFT JOIN  {{ref('ZC_ADM_SOURCE_stg')}} AS ZC_ADM_SOURCE
		ON PAT_ENC_HSP.ADMIT_SOURCE_C = ZC_ADM_SOURCE.ADMIT_SOURCE_C

	LEFT JOIN  {{ ref('ZC_DISCH_DISP_stg')}} AS ZC_DISCH_DISP
		ON PAT_ENC_HSP.DISCH_DISP_C = ZC_DISCH_DISP.DISCH_DISP_C

	LEFT JOIN 	 {{ ref('ZC_ED_DISPOSITION_stg')}} AS ZC_ED_DISPOSITION
		ON PAT_ENC_HSP.ED_DISPOSITION_C	= ZC_ED_DISPOSITION.ED_DISPOSITION_C

	LEFT JOIN  {{ ref('HSP_ACCOUNT_stg')}} AS HSP_ACCOUNT
		ON PAT_ENC_HSP.HSP_ACCOUNT_ID = HSP_ACCOUNT.HSP_ACCOUNT_ID

	INNER JOIN {{ref('PATIENT_DRIVER')}} AS PATIENT_DRIVER
		ON PAT_ENC_HSP.PAT_ID = PATIENT_DRIVER.EHR_PATIENT_ID
WHERE HOSP_DISCH_TIME IS NOT NULL
