------ QA_VISIT_OCCURRENCE_NULLCONCEPT_COUNT
---------------------------------------------------------------------
WITH NULLCONCEPT_COUNT AS (
	SELECT 'VISIT_CONCEPT_ID' AS METRIC_FIELD,'NULL CONCEPT' AS QA_METRIC,'FATAL' AS ERROR_TYPE
		,COUNT(*) AS CNT
	FROM {{ref('VISIT_OCCURRENCE_RAW')}} AS T1
	WHERE (VISIT_CONCEPT_ID IS NULL)
-- UNION ALL
-- 	SELECT 'VISIT_TYPE_CONCEPT_ID' AS METRIC_FIELD,'NULL CONCEPT' AS QA_METRIC,'FATAL' AS ERROR_TYPE
-- 		,COUNT(*) AS CNT
-- 	FROM {{ref('VISIT_OCCURRENCE_RAW')}} AS T1
-- 	WHERE (VISIT_TYPE_CONCEPT_ID IS NULL)
-- UNION ALL
-- 	SELECT 'VISIT_SOURCE_CONCEPT_ID' AS METRIC_FIELD,'NULL CONCEPT' AS QA_METRIC,'FATAL' AS ERROR_TYPE
-- 		,COUNT(*) AS CNT
-- 	FROM {{ref('VISIT_OCCURRENCE_RAW')}} AS T1
-- 	WHERE (VISIT_SOURCE_CONCEPT_ID IS NULL)
-- UNION ALL
-- 	SELECT 'ADMITTED_FROM_CONCEPT_ID' AS METRIC_FIELD,'NULL CONCEPT' AS QA_METRIC,'FATAL' AS ERROR_TYPE
-- 		,COUNT(*) AS CNT
-- 	FROM {{ref('VISIT_OCCURRENCE_RAW')}} AS T1
-- 	WHERE (ADMITTED_FROM_CONCEPT_ID IS NULL)
-- UNION ALL
-- 	SELECT 'DISCHARGED_TO_CONCEPT_ID' AS METRIC_FIELD,'NULL CONCEPT' AS QA_METRIC,'FATAL' AS ERROR_TYPE
-- 		,COUNT(*) AS CNT
-- 	FROM {{ref('VISIT_OCCURRENCE_RAW')}} AS T1
-- 	WHERE (DISCHARGED_TO_CONCEPT_ID IS NULL)
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'VISIT_OCCURRENCE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) <> 0 THEN ERROR_TYPE ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('VISIT_OCCURRENCE_RAW')}}) AS TOTAL_RECORDS
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('VISIT_OCCURRENCE')}}) AS TOTAL_RECORDS_CLEAN
FROM NULLCONCEPT_COUNT
GROUP BY   METRIC_FIELD, QA_METRIC, ERROR_TYPE

