--QA_VISIT_OCCURRENCE_DUPLICATES_COUNT
---------------------------------------------------------------------
WITH TMP_DUPES AS (
SELECT PERSON_ID
	,VISIT_CONCEPT_ID
	,VISIT_START_DATE
	,VISIT_START_DATETIME
	,VISIT_END_DATE
	,VISIT_END_DATETIME
	,VISIT_TYPE_CONCEPT_ID
	,PROVIDER_ID
	,CARE_SITE_ID
	,phi_CSN_ID
	,VISIT_SOURCE_CONCEPT_ID
	,ADMITTED_FROM_CONCEPT_ID
	,ADMITTED_FROM_SOURCE_VALUE
	,DISCHARGED_TO_CONCEPT_ID
	,DISCHARGED_TO_SOURCE_VALUE
	,PRECEDING_VISIT_OCCURRENCE_ID
	,COUNT(*) AS CNT
--INTO #TMP_DUPES
FROM {{ref('VISIT_OCCURRENCE_RAW')}} AS T1
GROUP BY PERSON_ID
	,VISIT_CONCEPT_ID
	,VISIT_START_DATE
	,VISIT_START_DATETIME
	,VISIT_END_DATE
	,VISIT_END_DATETIME
	,VISIT_TYPE_CONCEPT_ID
	,PROVIDER_ID
	,CARE_SITE_ID
	,phi_CSN_ID
	,VISIT_SOURCE_CONCEPT_ID
	,ADMITTED_FROM_CONCEPT_ID
	,ADMITTED_FROM_SOURCE_VALUE
	,DISCHARGED_TO_CONCEPT_ID
	,DISCHARGED_TO_SOURCE_VALUE
	,PRECEDING_VISIT_OCCURRENCE_ID
HAVING COUNT(*) > 1
)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	, 'VISIT_OCCURRENCE' AS STANDARD_DATA_TABLE
	, 'DUPLICATE' AS QA_METRIC
	, 'RECORDS'  AS METRIC_FIELD
	, COALESCE(SUM(CNT),0) AS QA_ERRORS
	, CASE WHEN SUM(CNT) IS NOT NULL THEN 'FATAL' ELSE NULL END   AS ERROR_TYPE
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('VISIT_OCCURRENCE_RAW')}}) AS TOTAL_RECORDS
	, (SELECT COUNT(*) AS NUM_ROWS FROM {{ref('VISIT_OCCURRENCE')}}) AS TOTAL_RECORDS_CLEAN
FROM TMP_DUPES

