--QA_VISIT_OCCURRENCE_NULLFK_DETAIL
---------------------------------------------------------------------
WITH NULLFK_DETAIL AS (
	SELECT 'PERSON_ID' AS METRIC_FIELD	,'NULL FK' AS QA_METRIC	,'WARNING' AS ERROR_TYPE
		,VISIT_OCCURRENCE_ID AS CDT_ID
	FROM {{ref('VISIT_OCCURRENCE_RAW')}} AS T1
	WHERE (PERSON_ID IS NULL)
-- UNION ALL
-- 	SELECT 'PROVIDER_ID' AS METRIC_FIELD,'NULL FK' AS QA_METRIC,'WARNING' AS ERROR_TYPE
-- 		,VISIT_OCCURRENCE_ID AS CDT_ID
-- 	FROM {{ref('VISIT_OCCURRENCE_RAW')}} AS T1
-- 	WHERE (PROVIDER_ID IS NULL)
-- UNION ALL
-- 	SELECT 'CARE_SITE_ID' AS METRIC_FIELD,'NULL FK' AS QA_METRIC,'WARNING' AS ERROR_TYPE
-- 		,VISIT_OCCURRENCE_ID AS CDT_ID
-- 	FROM {{ref('VISIT_OCCURRENCE_RAW')}} AS T1
-- 	WHERE (CARE_SITE_ID IS NULL)
-- UNION ALL
-- 	SELECT 'PRECEDING_VISIT_OCCURRENCE_ID' AS METRIC_FIELD,'NULL FK' AS QA_METRIC,'EXPECTED' AS ERROR_TYPE
-- 		,VISIT_OCCURRENCE_ID AS CDT_ID
-- 	FROM {{ref('VISIT_OCCURRENCE_RAW')}} AS T1
-- 	WHERE (PRECEDING_VISIT_OCCURRENCE_ID IS NULL)

)

SELECT CAST(GETDATE() AS DATE) AS RUN_DATE
	,'VISIT_OCCURRENCE' AS STANDARD_DATA_TABLE
	, QA_METRIC AS QA_METRIC
	, METRIC_FIELD  AS METRIC_FIELD
	, ERROR_TYPE
	, CDT_ID
FROM NULLFK_DETAIL
  WHERE ERROR_TYPE <>'EXPECTED'

