/*
Purpose: Transform and map blood-related device exposure data to OMOP CDM format
Source: Hospital blood device data
Target: OMOP Device_Exposure table
*/

-- CTE to get blood device concept mappings
WITH __dbt__cte__SOURCE_TO_CONCEPT_MAP_DEVICE_BLOOD AS (
    SELECT *
    FROM CARE_RES_OMOP_GEN_WKSP.OMOP.SOURCE_TO_CONCEPT_MAP
    WHERE SOURCE_VOCABULARY_ID = 'SH_DEVICE_BLOOD'
)

-- Main query to transform device exposure data
SELECT DISTINCT
    -- Standard OMOP CDM fields
    PULL_DEVICE_EXPOSURE_HOSP_BLOOD.PERSON_ID,
    T_SOURCE_TO_CONCEPT_MAP_DEVICE_BLOOD.TARGET_CONCEPT_ID AS DEVICE_CONCEPT_ID,
    DEVICE_EXPOSURE_START_DATE AS DEVICE_EXPOSURE_START_DATE,
    DEVICE_EXPOSURE_START_DATETIME AS DEVICE_EXPOSURE_START_DATETIME,
    DEVICE_EXPOSURE_END_DATE AS DEVICE_EXPOSURE_END_DATE,
    DEVICE_EXPOSURE_END_DATETIME AS DEVICE_EXPOSURE_END_DATETIME,
    32817 AS DEVICE_TYPE_CONCEPT_ID,  -- INFERRED FROM PROCEDURE CLAIM
    UNIQUE_DEVICE_ID AS UNIQUE_DEVICE_ID,
    NULL AS PRODUCTION_ID,  -- NEW 5.4
    PULL_DEVICE_EXPOSURE_HOSP_BLOOD.QUANTITY AS QUANTITY,
    PROVIDER.PROVIDER_ID AS PROVIDER_ID,
    VISIT_OCCURRENCE.VISIT_OCCURRENCE_ID AS VISIT_OCCURRENCE_ID,
    0 AS VISIT_DETAIL_ID,
    DEVICE_SOURCE_VALUE AS DEVICE_SOURCE_VALUE,
    0 AS DEVICE_SOURCE_CONCEPT_ID,
    0 AS UNIT_CONCEPT_ID,  -- NEW 5.4
    NULL AS UNIT_SOURCE_VALUE,  -- NEW 5.4
    0 AS UNIT_SOURCE_CONCEPT_ID,  -- NEW 5.4

    -- Custom fields for tracking and debugging
    'DEVICE_EXPOSURE_HSP_BLOODD' AS ETL_MODULE,
    PULL_DEVICE_EXPOSURE_HOSP_BLOOD.PULL_PROC_ID AS STAGE_PROC_ID,
    VISIT_OCCURRENCE.phi_PAT_ID AS STAGE_PAT_ID,
    VISIT_OCCURRENCE.phi_MRN_CPI AS STAGE_MRN_CPI,
    VISIT_OCCURRENCE.phi_CSN_ID AS STAGE_CSN_ID

FROM CARE_RES_OMOP_DEV2_WKSP.OMOP_PULL.PULL_DEVICE_EXPOSURE_HOSP_BLOOD AS PULL_DEVICE_EXPOSURE_HOSP_BLOOD

-- Join to get concept mappings
INNER JOIN __dbt__cte__SOURCE_TO_CONCEPT_MAP_DEVICE_BLOOD AS T_SOURCE_TO_CONCEPT_MAP_DEVICE_BLOOD
    ON PULL_DEVICE_EXPOSURE_HOSP_BLOOD.PULL_PROC_ID = T_SOURCE_TO_CONCEPT_MAP_DEVICE_BLOOD.SOURCE_CODE

-- Join to get visit information
INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP.VISIT_OCCURRENCE_RAW AS VISIT_OCCURRENCE
    ON PULL_DEVICE_EXPOSURE_HOSP_BLOOD.PULL_CSN_ID = VISIT_OCCURRENCE.phi_CSN_ID

-- Join to get provider information
INNER JOIN CARE_RES_OMOP_DEV2_WKSP.OMOP.PROVIDER_RAW AS PROVIDER
    ON PULL_DEVICE_EXPOSURE_HOSP_BLOOD.PROVIDER_SOURCE_VALUE = PROVIDER.PROVIDER_SOURCE_VALUE